// GENERATED by scripts/build_forest_context.py -- do not hand-edit.
// Per-study rows are parsed from the Stata log, verified against the expected study set and weight sum before being written.
window.FOREST_CONTEXT = {
  "generated_by": "scripts/build_forest_context.py",
  "disclaimer": "Per-study effect, 95% CI and pooling weight, parsed from the Stata log that produced the adjacent forest plot image. Modality, comparator, risk of bias and derivability tier are read client-side from the review's existing study data, not duplicated here.",
  "figures": [
    {
      "figure": "forest_opioid24_primary_mme.png",
      "analysis_id": "AN-01-COMB",
      "source": "06_FINAL_ANALYSIS_V26/02_STATA/logs/01_opioid24_primary.log",
      "rows": [
        {
          "study": "Chen 1998",
          "estimate": -21.0,
          "ci_low": -32.962,
          "ci_high": -9.038,
          "weight_pct": 11.69
        },
        {
          "study": "Chen 2020",
          "estimate": -28.19,
          "ci_low": -31.681,
          "ci_high": -24.699,
          "weight_pct": 15.09
        },
        {
          "study": "El-Rakshy 2009",
          "estimate": -1.6,
          "ci_low": -8.888,
          "ci_high": 5.688,
          "weight_pct": 13.83
        },
        {
          "study": "He 2026 (hepatectomy/JIS)",
          "estimate": -0.6,
          "ci_low": -1.733,
          "ci_high": 0.533,
          "weight_pct": 15.47
        },
        {
          "study": "Seevaunnamtum 2016",
          "estimate": -12.56,
          "ci_low": -21.162,
          "ci_high": -3.958,
          "weight_pct": 13.27
        },
        {
          "study": "Szmit 2021",
          "estimate": -7.7,
          "ci_low": -10.623,
          "ci_high": -4.777,
          "weight_pct": 15.21
        },
        {
          "study": "Yang 2024",
          "estimate": -0.3,
          "ci_low": -1.703,
          "ci_high": 1.103,
          "weight_pct": 15.44
        }
      ]
    }
  ]
};
