// GENERATED by scripts/check_stratum_purity.py -- do not hand-edit.
// Contributing studies are read from the Stata logs, not from labels.
window.STRATUM_PURITY = {
  "generated_by": "scripts/check_stratum_purity.py",
  "protocol": [
    {
      "source": "Locked protocol scope, Outcomes and synthesis boundary",
      "quote": "TEAS and EA analyses are stratified by modality. Principal sham-controlled and supportive non-sham comparisons remain separate."
    },
    {
      "source": "Locked protocol scope, Comparators and analytic separation",
      "quote": "Usual perioperative care, standard multimodal analgesia, no stimulation, waiting-list control, and attention control are supportive comparisons and remain separate from sham-controlled evidence."
    },
    {
      "source": "PROSPERO, Strategy for data synthesis",
      "quote": "TEAS and electroacupuncture (EA) will not be combined in a pooled estimate. Analyses will be stratified by modality."
    }
  ],
  "note": "Each analysis's contributing studies are read from the Stata log that produced it, then each contrast's modality and comparator class are resolved. An analysis containing more than one (modality, comparator) combination pools across a boundary the protocol keeps separate.",
  "findings": [
    {
      "analysis_id": "AN-02-TARGET-A",
      "k": 3,
      "stratum": "A_0-48h_cumulative_opioid",
      "contributors": [
        {
          "study": "Chen 2020",
          "modality": "TEAS",
          "comparator": "Sham"
        },
        {
          "study": "Zhang 2023",
          "modality": "TEAS",
          "comparator": "Sham"
        },
        {
          "study": "An 2014",
          "modality": "EA",
          "comparator": "Usual care"
        }
      ],
      "distinct_strata": [
        "EA vs Usual care",
        "TEAS vs Sham"
      ],
      "pure": false
    },
    {
      "analysis_id": "AN-04-TARGET-C",
      "k": 4,
      "stratum": "C_rest_pain_~24h",
      "contributors": [
        {
          "study": "Xing 2022",
          "modality": "TEAS",
          "comparator": "Sham"
        },
        {
          "study": "Liu 2021",
          "modality": "TEAS",
          "comparator": "Sham"
        },
        {
          "study": "Song 2020",
          "modality": "TEAS",
          "comparator": "Sham"
        },
        {
          "study": "Gao 2022",
          "modality": "TEAS",
          "comparator": "Sham"
        }
      ],
      "distinct_strata": [
        "TEAS vs Sham"
      ],
      "pure": true
    },
    {
      "analysis_id": "AN-05-TARGET-D-24",
      "k": 4,
      "stratum": "D_PONV_0-24h",
      "contributors": [
        {
          "study": "Zheng 2025",
          "modality": "TEAS",
          "comparator": "Sham"
        },
        {
          "study": "Lu 2021",
          "modality": "TEAS",
          "comparator": "Sham"
        },
        {
          "study": "Song 2020",
          "modality": "TEAS",
          "comparator": "Sham"
        },
        {
          "study": "Gao 2022",
          "modality": "TEAS",
          "comparator": "Sham"
        }
      ],
      "distinct_strata": [
        "TEAS vs Sham"
      ],
      "pure": true
    },
    {
      "analysis_id": "AN-06-TARGET-D-48",
      "k": 2,
      "stratum": "D_PONV_0-48h",
      "contributors": [
        {
          "study": "Xiong 2021",
          "modality": "TEAS",
          "comparator": "UNCLASSIFIED (Dexamethasone + tropisetron)"
        },
        {
          "study": "Xing 2022",
          "modality": "TEAS",
          "comparator": "Sham"
        }
      ],
      "distinct_strata": [
        "TEAS vs Sham",
        "TEAS vs UNCLASSIFIED (Dexamethasone + tropisetron)"
      ],
      "pure": false
    },
    {
      "analysis_id": "AN-07-TARGET-E",
      "k": 7,
      "stratum": "E_time_to_first_flatus",
      "contributors": [
        {
          "study": "Zhou 2025",
          "modality": "TEAS",
          "comparator": "Sham"
        },
        {
          "study": "Yang 2020",
          "modality": "EA",
          "comparator": "Usual care"
        },
        {
          "study": "Yang 2024",
          "modality": "EA",
          "comparator": "Usual care"
        },
        {
          "study": "Xing 2022",
          "modality": "TEAS",
          "comparator": "Sham"
        },
        {
          "study": "Lu 2022",
          "modality": "TEAS",
          "comparator": "Usual care"
        },
        {
          "study": "Ng 2013",
          "modality": "EA",
          "comparator": "Sham"
        },
        {
          "study": "Zhang 2018",
          "modality": "MODALITY_REVIEW_REQUIRED",
          "comparator": "Sham"
        }
      ],
      "distinct_strata": [
        "EA vs Sham",
        "EA vs Usual care",
        "MODALITY_REVIEW_REQUIRED vs Sham",
        "TEAS vs Sham",
        "TEAS vs Usual care"
      ],
      "pure": false
    }
  ],
  "impure_ids": [
    "AN-02-TARGET-A",
    "AN-06-TARGET-D-48",
    "AN-07-TARGET-E"
  ]
};
