* =============================================================================
* 12_stratum_compliant_refit.do
*
* Re-fit the three reported analyses that pool across the protocol's modality
* and comparator boundaries, WITHIN those boundaries.
*
* WHY
* The locked protocol scope states:
*   "TEAS and EA analyses are stratified by modality. Principal sham-controlled
*    and supportive non-sham comparisons remain separate."
*   "Usual perioperative care ... and attention control are supportive
*    comparisons and remain separate from sham-controlled evidence."
* and PROSPERO's synthesis strategy: "TEAS and electroacupuncture (EA) will not
* be combined in a pooled estimate."
*
* 05_ponv.do pools with `if endpoint_stratum == ...` and 06_flatus.do pools the
* whole dataset, so neither applies a modality or comparator condition.
* 02_targetA_48h.do pools on include_strict, which does not encode either.
* scripts/check_stratum_purity.py identifies the affected analyses by reading
* the contributing studies out of the Stata logs.
*
* WHAT THIS DOES NOT DO
* Replace the published estimates. It writes its results to a separate file so
* the review lead can compare them against the originals and decide what is
* reported. Nothing in 01_DATA or 03_RESULTS is overwritten.
*
* Run from the repository root:
*   stata-se -b do 06_FINAL_ANALYSIS_V26/02_STATA/12_stratum_compliant_refit.do
* =============================================================================

clear all
set more off
capture log close
log using "06_FINAL_ANALYSIS_V26/02_STATA/logs/12_stratum_compliant_refit.log", replace text

* -----------------------------------------------------------------------------
* Stratum assignment, generated by scripts/check_stratum_purity.py from the
* resolved comparator adjudications. Merged rather than hardcoded here so the
* assignment is auditable in one place.
* -----------------------------------------------------------------------------
* One row per (analysis_id, study): Xing 2022 contributes to two of the three
* affected analyses, so the assignment is split per analysis before merging.
* Re-imported per analysis rather than preserved: Stata does not allow a
* nested preserve, and there is no dataset in memory to protect here anyway.
tempfile assignA assignD assignE
local aids "AN-02-TARGET-A AN-06-TARGET-D-48 AN-07-TARGET-E"
local tfs  "assignA assignD assignE"
forvalues i = 1/3 {
    local aid : word `i' of `aids'
    local tf  : word `i' of `tfs'
    import delimited "06_FINAL_ANALYSIS_V26/01_DATA/stratum_assignment.csv", ///
        clear varnames(1) stringcols(_all)
    keep if analysis_id == "`aid'"
    save ``tf'', replace
}

* =============================================================================
* Helper: fit one stratum, or record it as a single study
* =============================================================================
capture program drop fitstratum
program define fitstratum
    args aid mod comp
    quietly count
    local k = r(N)
    if `k' == 0 exit
    di as txt _n "---------------------------------------------------------------"
    di as txt "`aid' | `mod' vs `comp' | k = `k'"
    di as txt "---------------------------------------------------------------"
    list study, clean noobs
    if `k' == 1 {
        di as txt "  Single study: not pooled."
    }
    else {
        meta summarize, random(reml) se(kh)
    }
end

* =============================================================================
* 1. AN-02 TARGET A -- cumulative 0-48 h opioid
* =============================================================================
use "06_FINAL_ANALYSIS_V26/01_DATA/target_A_48h.dta", clear
keep if include_strict == 1
merge m:1 study using `assignA', keep(master match) nogen ///
    keepusing(modality comparator_class)
meta set md_mme se_mme, studylabel(study) eslabel("Mean Difference (mg IV MME)")

levelsof modality, local(mods)
foreach m of local mods {
    levelsof comparator_class if modality == "`m'", local(comps)
    foreach c of local comps {
        preserve
        keep if modality == "`m'" & comparator_class == "`c'"
        fitstratum "AN-02-TARGET-A" "`m'" "`c'"
        restore
    }
}

* =============================================================================
* 2. AN-06 TARGET D -- PONV 0-48 h
* =============================================================================
use "06_FINAL_ANALYSIS_V26/01_DATA/target_D_ponv.dta", clear
keep if endpoint_stratum == "D_PONV_0-48h"
merge m:1 study using `assignD', keep(master match) nogen ///
    keepusing(modality comparator_class)

* Haldane-Anscombe continuity correction, applied UNIVERSALLY (review team
* decision 2026-09-11; implemented in Stata 2026-09-12), matching 05_ponv.do.
* Adding 0.5 to all four cells of a 2x2 table raises each ARM TOTAL by 1.0, not
* by 0.5 -- this file already had that arithmetic right; what changes here is
* that the correction is no longer restricted to zero-cell rows.
gen ei_cc = events_i + 0.5
gen ec_cc = events_c + 0.5
gen ni_cc = n_i + 1.0
gen nc_cc = n_c + 1.0
gen rr_  = (ei_cc / ni_cc) / (ec_cc / nc_cc)
gen lnrr_ = ln(rr_)
gen se_lnrr_ = sqrt((1/ei_cc - 1/ni_cc) + (1/ec_cc - 1/nc_cc))
meta set lnrr_ se_lnrr_, studylabel(study) eslabel("Risk Ratio (log scale)")

levelsof modality, local(mods)
foreach m of local mods {
    levelsof comparator_class if modality == "`m'", local(comps)
    foreach c of local comps {
        preserve
        keep if modality == "`m'" & comparator_class == "`c'"
        fitstratum "AN-06-TARGET-D-48" "`m'" "`c'"
        restore
    }
}

* =============================================================================
* 3. AN-07 TARGET E -- time to first flatus
* =============================================================================
use "06_FINAL_ANALYSIS_V26/01_DATA/target_E_flatus.dta", clear
merge m:1 study using `assignE', keep(master match) nogen ///
    keepusing(modality comparator_class)
meta set md_hours se_hours, studylabel(study) eslabel("Mean Difference (Hours)")

levelsof modality, local(mods)
foreach m of local mods {
    levelsof comparator_class if modality == "`m'", local(comps)
    foreach c of local comps {
        preserve
        keep if modality == "`m'" & comparator_class == "`c'"
        fitstratum "AN-07-TARGET-E" "`m'" "`c'"
        restore
    }
}

di as txt _n "Done. Results are in the log; nothing in 01_DATA or 03_RESULTS was changed."
log close
