"""Generate v37 provenance/reviewer-action artifacts without inventing approval or screening decisions."""
import collections
import csv
import hashlib
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
D = ROOT / '10_FINAL_ADJUDICATION'
R = D / '06_REPORTS'
V = D / '05_REPRODUCTION/v37'
B = V / 'baseline'
Q = D / '02_DECISIONS/v37'
Q.mkdir(exist_ok=True)
STAMP = 'Generated by `code/build_v37_followup.py`, 20 September 2026. Not human approval. Do not edit generated files by hand.'


def read(path):
    with open(ROOT / path, encoding='utf-8-sig', newline='') as f:
        return list(csv.DictReader(f))


def save(path, rows):
    assert rows
    with open(path, 'w', newline='') as f:
        w = csv.DictWriter(f, list(dict.fromkeys(k for r in rows for k in r)))
        w.writeheader(); w.writerows(rows)


def doc(path, text):
    path.write_text(text.rstrip() + '\n')


results = {r['result_id']: r for r in read(D / '03_CANONICAL/results.csv')}
links = {r['result_id']: r for r in read('FINAL_RESULT_ROB2_LINKAGE.csv')}
spec = json.loads((D / '02_DECISIONS/model_specifications.json').read_text())
models = {m['model_id']: m for m in json.loads((D / '04_MODELS/model_outputs.json').read_text())}
grade = read(D / '03_CANONICAL/grade.csv')
members = collections.defaultdict(list)
for s in spec:
    if s['role'] != 'SENSITIVITY':
        for rid in s['result_ids']:
            members[rid].append(s['model_id'])

# Preserve exact historical candidates as versioned records; never silently replace selected assessments.
fields = {'study': 'study', 'outcome': 'outcome', 'timepoint': 'window',
          'intervention': 'intervention', 'comparator': 'comparator'}
domains = ['d1_randomisation', 'd2_deviations', 'd3_missing', 'd4_measurement', 'd5_reporting']
candidate_rows = []
candidate_by = collections.defaultdict(list)
scope = set(members) | {i for i, l in links.items() if l['rob2_assessment_id']}
for name in ['v34_rob2_draft_assessments.csv', 'v34_rob2_priority2_assessments.csv']:
    source = pathlib.Path('09_V34_ANALYSIS/03_ROB2') / name
    with open(ROOT / source, newline='') as f:
        reader = csv.DictReader(f); reader.fieldnames
        while True:
            line = reader.line_num + 1
            try: a = next(reader)
            except StopIteration: break
            for rid in sorted(scope):
                r = results[rid]
                if not all(a[x] == r[y] for x, y in fields.items()): continue
                if any(float(a[x]) != float(r[y]) for x, y in [('analysed_n_i', 'n_i'), ('analysed_n_c', 'n_c')]): continue
                if pathlib.Path(a['source_pdf']).name != pathlib.Path(r['source_pdf']).name: continue
                vec = [a[d] for d in domains] + [a['overall']]
                current = [links[rid]['d'+str(i)] for i in range(1, 6)] + [links[rid]['overall']]
                row = dict(result_id=rid, study=r['study'], assessment_version_key=f'{source}:L{line}',
                           source_sha256=hashlib.sha256((ROOT/source).read_bytes()).hexdigest(),
                           match_basis='Exact study/outcome/window/arms/analyzed Ns/PDF filename; arm statistics absent in this historical register',
                           **{'d'+str(i+1): a[d] for i,d in enumerate(domains)}, overall=a['overall'],
                           recorded_adopted_by=a['adopted_by'], recorded_adopted_date=a['adopted_date'],
                           provenance_note=a['provenance_note'], rationale=a['rationale'],
                           currently_linked=bool(links[rid]['rob2_assessment_id']),
                           same_as_selected_vector=vec == current,
                           status='CANDIDATE ONLY; reconcile version and source rationale; no approval transferred')
                candidate_rows.append(row); candidate_by[rid].append(row)

# One separately inspected corrected-register candidate: Zhu's day-before arm only.
rid = 'V33-OD-0020'
a = json.loads((ROOT/'ASTRA_VERIFICATION_SUPPORT/workbook.json').read_text())['Corrected_RoB2'][6]
assert a['Canonical study'] == 'Zhu 2022'
row = dict(result_id=rid, study='Zhu 2022', assessment_version_key='CORRECTED-V34-007@workbook.json:Corrected_RoB2:7',
           source_sha256=hashlib.sha256((ROOT/'ASTRA_VERIFICATION_SUPPORT/workbook.json').read_bytes()).hexdigest(),
           match_basis='Manually inspected day-before EA/usual-care vomiting 6–24h, 5/101 vs 22/101; not other active arms',
           **{'d'+str(i):a['Domain '+str(i)] for i in range(1,6)}, overall=a['Overall RoB 2'],
           recorded_adopted_by='', recorded_adopted_date='', provenance_note=a['Correction source'],
           rationale='Existing corrected-register candidate; reviewer reconciliation required', currently_linked=False,
           same_as_selected_vector=False, status='CANDIDATE ONLY; no approval transferred')
candidate_rows.append(row); candidate_by[rid].append(row)
save(Q/'rob2_existing_candidates.csv', candidate_rows)

work = []
for rid in sorted(members):
    r, l = results[rid], links[rid]
    work.append(dict(result_id=rid, study=r['study'], outcome=r['outcome'], window=r['window'],
        intervention=r['intervention'], comparator=r['comparator'], n_i=r['n_i'], n_c=r['n_c'],
        models=';'.join(members[rid]), source_pdf=r['source_pdf'], source_location=r['source_location'],
        current_assessment=l['rob2_assessment_id'], current_overall=l['overall'],
        candidate_versions=';'.join(a['assessment_version_key'] for a in candidate_by[rid]),
        action='RECONCILE SELECTED VERSION / SIGNOFF' if l['rob2_assessment_id'] else ('REVIEW EXISTING CANDIDATE' if candidate_by[rid] else 'RESULT-SPECIFIC ASSESSMENT NEEDED'),
        reviewer='', review_date='', final_decision='', evidence_locator=''))
save(Q/'rob2_non_sensitivity_worklist.csv', work)
save(Q/'grade_review_ledger.csv', [dict(**g, review_priority=('EXPLICIT REVIEW: v36 bowel-sounds downgrade' if g['model_id']=='bowelsounds_TEAS_sham' else 'EXPLICIT REVIEW: conflicting nausea RoB versions and serious vs very-serious downgrade' if g['model_id']=='nausea48_TEAS_sham' else 'Reviewer approval/revision required'), reviewer='', date='', decision='', rationale='') for g in grade])

reg = read(D/'02_DECISIONS/existing_rob2_assessments.csv')
counts = collections.Counter(a['assessment_id'] for a in reg)
save(Q/'rob2_id_collisions.csv', [dict(register_row=i+2, original_id=a['assessment_id'], version_key=f"{a['assessment_id']}@register-row-{i+2}", source=a['source'], study=a['study'], outcome=a['outcome'], window=a['window'], comparison=a['comparison'], overall=a['overall']) for i,a in enumerate(reg) if counts[a['assessment_id']]>1])
linked = sum(bool(links[i]['rob2_assessment_id']) for i in members)
new_candidates = {i for i in members if not links[i]['rob2_assessment_id'] and candidate_by[i]}
doc(R/'ROB2_PROVENANCE_RECONCILIATION_v37.md', f'''# RoB 2 provenance reconciliation — v37

{STAMP}

Non-sensitivity bodies: {len(grade)}; unique component results: {len(members)}; currently linked: {linked}; unlinked: {len(members)-linked}. Existing candidates found for {len(new_candidates)} of the unlinked results; {len(members)-linked-len(new_candidates)} lack such a candidate. These counts describe applicability work, not approval. Current canonical linkage remains 97/761. No GRADE certainty category or RoB vector was changed.

`02_DECISIONS/v37/rob2_non_sensitivity_worklist.csv` has one row per component result, including separate active arms before combination. `rob2_existing_candidates.csv` preserves historical assessment vectors, source row/version identities, recorded adopters/dates and rationale. Historical v34 source registers contain textual claims of review-lead adoption; these are evidence of recorded adoption, not independently verified dual review. The linker's hard-coded date placeholders cannot establish absence of upstream adoption.

## Version conflicts requiring decisions

- Luo nausea48: selected AF26-D-008 is High (D4 High); corrected record CORRECTED-V34-031 is Some concerns; historical priority-2 record is Low and assumes effective masking. Source allocation guesses were 77.5% and 66.2% (`ASTRA_VERIFICATION_SUPPORT/source_text/covidence_35_verified.txt:370`). Do not transfer the historical approval to the selected High vector or automatically revise GRADE. Nausea rationale now references 77 nausea events, not vomiting events; inherited Low certainty remains pending review.
- Xiong PONV48: source has no-current electrodes (`ASTRA_VERIFICATION_SUPPORT/source_text/covidence_431_full_article.txt:142`); sham classification stays. Current corrected RoB record says antiemetics alone; reconcile D2/comparator wording and the alternative AF26-D-003 High assessment.
- El-Rakshy: `07_risk_of_bias/RoB2_ElRakshy_2009_MorphineConsumption_24h.md` records Mendoza adoption 9 Sep, but D2 Some concerns differs from selected D2 Low. The dated adoption cannot be copied to that selected vector.
- Ng flatus V33-OD-0117: historical priority-2 adoption 8 Sep matches the selected domain vector. Retain as provenance, not independent final sign-off.
- Pan vomiting AUDIT-0100: historical candidate says 105 randomized/analyzed; source describes 120 enrolled and subsequent exclusions. Revisit D3 before accepting it.
- Zheng flatus AUDIT-0347: source endpoint definition refers to first stools (`01_SOURCE_EVIDENCE/Zheng_2025.txt:200`); clarify gas versus defecation as well as SD/P inconsistency. Source values and model membership remain unchanged; leave-out diagnostic retained.

## Linker limitations — explicitly not certified

The inherited register contains {len(reg)} rows and {len(counts)} distinct assessment IDs; {sum(n>1 for n in counts.values())} IDs are reused. `rob2_id_collisions.csv` gives row-specific identities. Automatic AF selection tests study, comparison ID and statistics but lacks an explicit semantic outcome/window gate; equal counts alone are not sufficient. These limitations require version-specific reconciliation before final lock. Candidate records are deliberately not imported into canonical selections as if approved.

Do not extend assessments across Zhu active arms, Lu PC6/combined-site arms, Sun timing arms, Huang ipsilateral/contralateral arms, Ng sham/no-acupuncture controls, or Oztas usual-care/active-TENS controls. Szmit's usual-care primary opioid result remains unassessed. The current vomiting24 TEAS/sham model has 4 trial contrasts, not the obsolete 5.
''')

# Record provenance is separate from deferred eligibility re-screening.
cross = read(D/'02_DECISIONS/covidence_record_crosswalk.csv')
provenance = read(D/'02_DECISIONS/registry_report_provenance.csv')
history = {
    'Gao 2022':'4f9aa4a (12 Sep): review-team admission claim; underlying attributable approval not located',
    'Song 2020':'4f9aa4a (12 Sep): review-team admission claim; underlying attributable approval not located',
    'Zhang 2018':'4f9aa4a (12 Sep): admission claim; two excluded Covidence records require report-level resolution',
    'Szmit 2021':'1e89751 (7 Sep): implemented admission/project-decision wording; contemporaneous Tan audit still requests human adjudication',
    'Liu 2015':'Integration history including 1e89751; no attributable re-inclusion approval located',
    'Oztas 2019':'Integration history including 1e89751; no attributable re-inclusion approval located',
    'Wu 2016':'1976ec0 (10 Sep): citation label automatically assigned to unmatched records; Tan-reference presence is not a dated discovery/acceptance event'}
save(Q/'prisma_report_provenance_ledger.csv', [dict(**r,
    evidence=history.get(r['report_id'],'Saved Covidence included disposition; individual decision dates/assessors not supplied in this export'),
    status='HOLD: dated admission/source-path confirmation required' if r['report_id'] in history else 'INCLUDED export path established; dated reviewer trail incomplete',
    decision_by='', decision_date='', reason_code='', decision_evidence='') for r in provenance])
reasons = collections.Counter(r['exclusion_reason'] for r in cross if r['covidence_decision']=='EXCLUDED')
save(Q/'prisma_export_reason_counts.csv', [dict(reason=k, records=v, basis='Saved 161-record excluded export; not a final adjudicated PRISMA flow') for k,v in sorted(reasons.items())])
exlinks = [r for r in cross if r['covidence_decision']=='EXCLUDED' and r['registry_report']]
reason_table = '\n'.join(f'| {k} | {v} |' for k,v in sorted(reasons.items()))
exception_table = '\n'.join(f"| {r['registry_report']} | {r['covidence_id']} | {r['exclusion_reason']} | {r['excluded_on']} |" for r in exlinks)
doc(R/'PRISMA_REPORT_TRIAL_ACCOUNTING.md', f'''# PRISMA record/report/trial accounting — v37

{STAMP}

**HOLD: no approved final flow figure.** A1 reviewer screening package is deferred by the user; no eligibility decisions or screening forms were produced in this continuation.

Saved exports contain {len(cross)} unique records: 63 included, 161 excluded. The registry contains 70 reports: 63 with included-export paths, six reports mapping to {len(exlinks)} excluded records, plus Wu 2016 with no match. Zhang 2018 maps to two excluded records (wrong outcomes and abstract only). Six report reinstatements must not automatically be treated as six record reversals. A conditional 69-included/155-excluded arithmetic shortcut is not a reconciled flow.

| Registry report | Excluded record | Saved reason | Saved date |
|---|---|---|---|
{exception_table}

| Exclusion reason | Saved records |
|---|---:|
{reason_table}

The published/displayed flow's language=0, not-retrieved=14 and wrong-outcomes=117 do not match these saved records (12, 2 and 122 respectively). Earlier 5,100 references to 5,088 study records to 2,928 screened still lack a complete record-level collapse/deduplication path. Records, reports and trials are different units; the current 70 reports / 69 operational trial units are not a validated selection flow.

## Provenance findings

12 Sep commit 4f9aa4a and `06_FINAL_ANALYSIS_V26/02_STATA/00_prep_data.do:239` claim review-team admission for Gao/Song/Zhang. 7 Sep commit 1e89751 implements Szmit admission, while `TAN_2024_COVIDENCE_RECONCILIATION_AUDIT.md:208` still requests human adjudication. These are implementation/adoption claims, not an attributable underlying approval or Covidence reversal. Earlier automated INCLUDE votes do not substitute for reviewer decisions.

Wu's citation-search label in 10 Sep commit 1976ec0 comes from `scripts/derive_study_provenance.py:70`, which labels unmatched records automatically. Its presence in Tan's reference list establishes a possible route, not the actual dated discovery/acceptance event.

`02_DECISIONS/v37/prisma_report_provenance_ledger.csv` retains all 70 paths and leaves missing names/dates blank. To close A2: provide dated admission decisions for the six reports, resolve both Zhang records at record/report level, confirm Wu's route/date, supply the earlier reference-collapse trail, then regenerate the final figure from reconciled records. No inference here changes Covidence or silently screens excluded reports.
''')

# Operational B/C/D decisions remain explicit; fields intentionally blank until actual human action.
policies = [
 ('C1','Pan 2023 → usual care','Retain v36 source-verified comparator; reviewer confirmation pending'),
 ('C2','Liang 2021 → usual care','Retain v36 source-verified comparator; reviewer confirmation pending'),
 ('C3','Xiong 2021 → sham','Retain source-verified no-current electrodes; reconcile RoB D2/comparator wording'),
 ('C4','Seven registry comparator corrections','Retain source quotes in studies.json; 63 study labels remain LEGACY; result class governs'),
 ('C5','Three v36 added RoB links','Retain existing selections; no new human approval asserted'),
 ('C6','Huang 2017 → TEAS','Retain source-verified surface-electrode classification; no model contribution'),
 ('D1','Sufentanil factor 0.5','Retain 0.25/1.0 sensitivities; explicit policy approval needed'),
 ('D2','Song active electrical comparator','Retain separate body and broad-sham sensitivity'),
 ('D3','Flatus hours MD, SMD diagnostic','Retain; disclose posthoc policy'),
 ('D4','El-Rakshy supportive inclusion','Retain printed data/High RoB/leave-out diagnostic; reviewer retention decision needed'),
 ('D5','Chen 1998/Yang 2024/Lin 2002','Retain sensitivity-only for unquantified rescue')]
save(Q/'source_corrections_and_policy_review.csv', [dict(item=i, decision=d, interim_rule=h, status='HUMAN CONFIRMATION PENDING', reviewer='', date='', disposition='', evidence='') for i,d,h in policies])
save(Q/'author_query_log.csv', [dict(item='B'+str(i), study=s, status='UNSENT — APPROVAL REQUIRED', prepared_date='2026-09-20', sent_date='', reply_date='', nonresponse_as_of='', reply_evidence='', draft='10_FINAL_ADJUDICATION/02_DECISIONS/v37_author_queries.md#b'+str(i)) for i,s in enumerate(['Chen 2020','He 2026 hepatectomy','El-Rakshy 2009','Zheng 2025','He 2026 breast','Yeh 2010/2011','Jin 2023','Long 2025'],1)])

old = {m['model_id']:m for m in json.loads((B/'10_FINAL_ADJUDICATION/04_MODELS/model_outputs.json').read_text())}
comparison = []
for mid in sorted(set(old)|set(models)):
    x,y = old.get(mid,{}),models.get(mid,{})
    changed = [k for k in sorted(set(x)|set(y)) if x.get(k)!=y.get(k)]
    comparison.append(dict(model_id=mid, old_k=x.get('k'), new_k=y.get('k'), old_N=x.get('N'), new_N=y.get('N'),
         old_effect=x.get('display_effect'), new_effect=y.get('display_effect'),
         old_ci_low=x.get('display_ci_low'), new_ci_low=y.get('display_ci_low'),
         old_ci_high=x.get('display_ci_high'), new_ci_high=y.get('display_ci_high'),
         changed_fields=';'.join(changed), status='UNCHANGED' if not changed else 'CHANGED'))
save(R/'model_comparison_v37.csv', comparison)
assert not any(c['changed_fields'] for c in comparison), 'Unexpected model drift: inspect before handoff'

# Regenerate current summaries from the immutable captured v36 baseline; preserve its detailed dispositions.
current = (B/'FINAL_CURRENT_STATE_REPORT.md').read_text()
current = current.replace('adjudication v36','adjudication v37',1).replace('16 September 2026 · branch `astra-final-resolution` · base `035ed97`; v36 committed as `dbb15df`–`3e56991` and merged into `main` via PR #23', '20 September 2026 · branch `astra-final-resolution` · inherited HEAD `253a8b9`; v36 numerical evidence retained, v37 provenance/metadata follow-up')
current = current.replace('No human sign-off exists for GRADE or RoB 2 linkage, most secondary-body results lack exact RoB 2 assessments, and the registration identifier is unconfirmed.', 'Current GRADE recommendations and selected RoB versions lack reconciled final approval. Historical lead-adoption records exist but often concern different assessment vectors. Of 94 unique non-sensitivity results, 36 are linked and 58 unlinked; 38 of the latter have historical candidates awaiting reconciliation. Registration identity is now verified: CRD420261452908.')
current = current.replace('Mechanical triage flags 84 of them for priority re-screening.', 'Mechanical triage flags 84 priority and 29 secondary records. The user explicitly deferred the reviewer screening package; this blocker remains open.')
current = current.replace('The dashboard is stale and must not be rebuilt from v36 data yet; since 17 Sep 2026 it carries a provisional banner (`dcd8f23`) warning readers not to cite it.', 'The dashboard remains stale and untouched. The provisional banner was added and then removed at the user’s request on 17 Sep 2026 (removal merged as `9b70766`); it has not been re-added. No rebuild/deployment is authorized while evidence/sign-off blockers remain.')
current = current.replace('**Current (v36)**','**Current (v37)**').replace('Committed HEAD registry labels Huang 2017 EA; HEAD results label it TEAS','Historical pre-v36 `035ed97` registry labels Huang 2017 EA; its results label it TEAS')
current = current.replace('It fails on committed HEAD and on injected', 'The historical v36 negative test failed on pre-v36 `035ed97` (not current HEAD) and on injected')
current = current.replace('Disclose that the protocol identifier is unconfirmed and that CRD420251090635 belongs to a similar review;', 'Use verified [CRD420261452908](https://www.crd.york.ac.uk/PROSPERO/view/CRD420261452908); CRD420251090635 belongs to a similar review. Disclose that')
current += '''\n## v37 completed work and remaining limits\n\nA3 closed by direct official-record verification (exact title, authors, submission/registration dates and version history). A2 record ledger rebuilt without manufacturing reversals; six reports map to seven excluded records. RoB/GRADE review ledgers prepared with version conflicts and recorded adoption provenance. Eight source-clarification drafts prepared, none sent. Jin's official trial registry checked; anaesthesia/concentration HOLD remains. C/D review ledger retains standing corrections/policies without claiming approval. The screening package is deferred.\n\nModel-input export metadata corrected so every input states its own inclusion/sensitivity decision and model rather than a stale pre-admission snapshot. No source value, model membership, effect, CI or certainty category changed. Nausea48 GRADE rationale corrected to its own event counts. The full 73-estimand before/after table is `06_REPORTS/model_comparison_v37.csv`. Fresh numerical and integrity results are in `06_REPORTS/REPRODUCIBILITY_REPORT.md` and `05_REPRODUCTION/v37/`.\n\n**Data lock: NO.** A1, A2, A4/A5 remain open; A6 remains intentionally deferred. No outward messages, dashboard edits, commits, pushes or deployments were performed.\n'''
doc(ROOT/'FINAL_CURRENT_STATE_REPORT.md', current)
backlog = (B/'10_FINAL_ADJUDICATION/06_REPORTS/UNRESOLVED_HUMAN_DECISIONS.md').read_text()
backlog = backlog.replace('(v36, 16 September 2026)','(v37, 20 September 2026)',1)
backlog = backlog.replace('Current 70-report base used as-is; GRADE', 'USER DEFERRED reviewer screening package; current 70-report base used as-is; GRADE',1)
backlog = backlog.replace('No identifier assigned. The dashboard still displays CRD420251090635 (19 `_site` files), which is stale.', 'CLOSED 20 Sep: official record CRD420261452908 matches exact title, authors, dates and version. Dashboard remains unchanged/stale.')
backlog = backlog.replace('External confirmation from PROSPERO of this record\'s CRD number', 'Evidence: `02_DECISIONS/v37_external_verification.md`; chronology disclosure still required')
backlog = backlog.replace('all 5 vomiting24_TEAS_sham contrasts','all 4 current vomiting24_TEAS_sham contrasts')
backlog = backlog.replace('No linked record carries a sign-off date.', 'Linker placeholders do not capture historical adoption records; version-specific conflicts remain.')
backlog = backlog.replace('Not rebuilt; provisional banner deployed 17 Sep 2026 (`dcd8f23`)', 'Not rebuilt; banner removed at user request 17 Sep (merge `9b70766`); do not re-add')
backlog += '''\n## v37 action files and evidence\n\n- A2: `02_DECISIONS/v37/prisma_report_provenance_ledger.csv`; six reports map to seven excluded records, including two Zhang records. Dated admission evidence still missing. See updated PRISMA report.\n- A4/A5: 94 unique non-sensitivity component results, 36 linked and 58 unlinked. Historical candidates exist for 38 unlinked results but are not newly approved. See `ROB2_PROVENANCE_RECONCILIATION_v37.md`, candidate/worklist CSVs and 38-row GRADE ledger. Do not copy adoption dates onto conflicting vectors.\n- B1–B8: eight UNSENT drafts in `02_DECISIONS/v37_author_queries.md`, log in `02_DECISIONS/v37/author_query_log.csv`. Sending requires user approval. B7 official registry check did not resolve GA/concentration. B4 now explicitly includes gas-versus-stool endpoint ambiguity.\n- C/D: `02_DECISIONS/v37/source_corrections_and_policy_review.csv`; existing dispositions retained, approval fields blank. No certainty or model changes.\n- A1 remains deferred, not resolved. A3 identity is resolved; actual prospective conduct is not established. No data lock.\n'''
doc(R/'UNRESOLVED_HUMAN_DECISIONS.md', backlog)
summary = dict(non_sensitivity_results=len(members), linked=linked, unlinked=len(members)-linked,
               unlinked_with_existing_candidates=len(new_candidates), models_unchanged=len(comparison),
               source_contradiction_queries=8, grade_recommendations=len(grade), screening_package='DEFERRED BY USER', registration='CRD420261452908')
doc(V/'followup_counts.json', json.dumps(summary, indent=2))
print(json.dumps(summary, indent=2))
