"""Write verification-backed handoff reports and a file-by-file change inventory."""
import csv
import hashlib
import json
import pathlib
import subprocess
import sys
import numpy
import scipy

ROOT=pathlib.Path(__file__).resolve().parents[2]
D=ROOT/'10_FINAL_ADJUDICATION'
R=D/'06_REPORTS'
V=D/'05_REPRODUCTION/v37'
verified=json.loads((V/'verification.json').read_text())
integrity=json.loads((V/'integrity.json').read_text())
start=json.loads((V/'starting_state.json').read_text())
assert verified['status']==integrity['status']=='PASS'
for name,digest in verified['output_sha256'].items():
    assert hashlib.sha256((ROOT/name).read_bytes()).hexdigest()==digest, name

text=f'''# Reproducibility report — v37, 20 September 2026

Generated by `code/finalize_v37.py` from completed verification records. These checks establish numerical reproducibility and bounded internal consistency, not source truth, complete selection, assessment-version approval or prospective conduct.

| Check | Result |
|---|---|
| Before/after all model fields | 73/73 defined estimands unchanged versus inherited HEAD {start['base_commit'][:7]}; 68 fitted, 5 empty |
| Deterministic regeneration | {verified['deterministic_outputs']}/{verified['deterministic_outputs']} outputs byte-identical across two complete in-scope runs |
| Independent validator | {verified['validator_groups']}/{verified['validator_groups']} groups PASS; new input-metadata check covers 179 contrasts |
| R metafor cross-check | 68 fitted models; {verified['metafor_fields']} compared fields; 0 failures |
| Metadata negative control | One in-memory decision changed to EXCLUDE; validator detected it, exited 1; restored run PASS |
| Protected evidence and existing user work | {integrity['protected_files_checked']}/{integrity['protected_files_checked']} SHA-256 identities preserved |
| Primary source-token check | 22/22 rows' means/SDs found in source text or supplement; token presence alone is not a full extraction audit |
| Deferred screening | No triage or screening-package generation; existing triage unchanged |

## Environment and commands

Python {sys.version.split()[0]}, numpy {numpy.__version__}, scipy {scipy.__version__}; R 4.5.2 and metafor 5.2-1. Exact R session is `05_REPRODUCTION/R_session.txt`. Dependencies were installed in `/tmp/teas-v37.a6vDCB/`, outside the project; no global package installation was performed.

```sh
ASTRA_R_LIBRARY=/tmp/teas-v37.a6vDCB/rlib /tmp/teas-v37.a6vDCB/venv/bin/python 10_FINAL_ADJUDICATION/code/verify_v37.py
/tmp/teas-v37.a6vDCB/venv/bin/python 10_FINAL_ADJUDICATION/code/finalize_v37.py
```

The scratch environment may disappear. Recreate a virtual environment with the listed numpy/scipy versions and install metafor 5.2-1 into a chosen scratch R library before rerunning. `verify_v37.py` uses its invoking Python and `/usr/local/bin/Rscript`; `ASTRA_R_LIBRARY` supplies the R package location.

The runner executes registry, canonical result/model input, fitting, existing RoB linkage, GRADE recommendations, Covidence crosswalk, table reports, independent validation and v37 follow-up generation; then R reproduction/comparison. It repeats the same chain and hashes 38 declared outputs. It deliberately does not invoke `triage_exclusions.py` or any dashboard builder. The source-preservation snapshot is immutable and must not be recreated over the original.

## Tolerances and records

- Metafor comparisons use absolute difference ≤ 1e-5 + 1e-5 × absolute R value; escalc input differences ≤ 1e-10.
- Independent input re-derivation: MD/RR relative 1e-9; SMD uses a large-sample J approximation with relative 5e-4. Independent refit comparison uses the documented validator tolerances (MD/RR relative 1e-6, tau² additional absolute 1e-6; SMD relative 5e-4).
- `05_REPRODUCTION/v37/verification.json`: output names/SHA-256 and test summary; run1/run2 logs alongside it.
- `05_REPRODUCTION/v37/negative_metadata_test.json` and `.log`: deliberately failed negative control, not the current validation result.
- `05_REPRODUCTION/validation_report.json`: restored current 9-group PASS.
- `05_REPRODUCTION/v37/starting_state.json`, `baseline/`, `integrity.json`: inherited commit/worktree, 19 baseline artifacts and 647 protected paths.
- `06_REPORTS/model_comparison_v37.csv`: full 73-row before/after table, including k, N, effect and CI, with all-field comparison.

Historical v36 claims that a validator failed on HEAD refer to pre-v36 commit 035ed97, not current HEAD 253a8b9. The original v36 report is retained in the baseline snapshot. V37 additionally ensures validator failures return a nonzero process exit code; the inherited validator printed FAIL without exiting nonzero.

Remaining limitations: the RoB linker has reused assessment IDs and lacks explicit automatic outcome/window semantic matching; v37 exposes these rather than claiming the numeric validator certifies them. Historical adoption records conflict with selected vectors. A1 completeness is deferred; A2 provenance and A4/A5 review remain open. No data lock.
'''
(R/'REPRODUCIBILITY_REPORT.md').write_text(text)

model_rows=list(csv.DictReader(open(R/'model_comparison_v37.csv')))
primary=[r for r in model_rows if r['model_id'] in ['opioid24_TEAS_sham','opioid24_EA_sham','opioid24_TEAS_usual','opioid24_EA_usual']]
table='\n'.join(f"| {r['model_id']} | {r['old_k']} → {r['new_k']} | {r['old_N']} → {r['new_N']} | {r['status']} |" for r in primary)
changelog=f'''# Changelog v37 — 20 September 2026

Generated by `code/finalize_v37.py`. Inherited HEAD: `{start['base_commit']}`. No commit, push, PR, merge or deployment performed. User's existing dashboard/article-figure work preserved. No third-party full texts added by this continuation.

## Resolved or corrected

1. **A3 CLOSED.** Official PROSPERO record CRD420261452908 matches exact title, four authors, dates and v1.0. Current protocol matrix/reconciliation and status/backlog corrected. Does not establish prospective conduct. Dashboard not edited.
2. **A2 investigated, still HOLD.** Rebuilt 70-report provenance ledger and export reason counts. Six reports correspond to seven excluded records (two for Zhang). Existing Git admission claims and Wu's inferred citation label are not a dated human admission trail. No final PRISMA figure fabricated.
3. **A4/A5 advanced, not signed off.** 94 unique non-sensitivity component results, 36 linked, 58 unlinked. Historical candidates exist for 38 unlinked results; remaining 20 require result-specific assessment. Candidate/version ledger preserves adoption names/dates, conflicting vectors and source rationale. 184 inherited register rows have 163 distinct IDs and 14 reused IDs. Canonical 97/761 linkage unchanged. The old blanket absence-of-adoption claim is corrected.
4. **B1–B8 drafts prepared, UNSENT.** Eight source queries and blank sent/reply log; no non-response invented. Jin's official registry checked without resolving GA/concentration. Zheng gas-versus-stool endpoint ambiguity added to the source query.
5. **C/D preserved with explicit review ledger.** Six source-correction groups and five standing-policy groups retained pending reviewer confirmation; no fabricated approvals.
6. **Input export metadata bug fixed.** `build_results.py` copied each row before updating canonical inclusion, causing exported model inputs to show stale decisions/models/rationale. Input metadata now states its specific model's decision, model ID and rationale. All 179 numerical input contrasts and all 73 output estimands remain unchanged.
7. **GRADE wording corrected.** Nausea48 rationale now refers to 77 nausea events, not the vomiting count. No certainty category changed; conflicting nausea assessments and downgrade severity remain for reviewer decision.
8. **Verification improved.** Independent validator checks input metadata and exits 1 on FAIL. Negative-control mutation confirms detection and restoration. Updated generated reports identify v37 and correct obsolete banner/HEAD claims.

## Inherited HEAD → v37 model comparison

| Primary model | k | N | Every output field |
|---|---:|---:|---|
{table}

All 73/73 estimands are unchanged, including membership, effects, CIs, heterogeneity and diagnostic outputs. See `model_comparison_v37.csv` for the full table. No raw source value or canonical result changed.

## Files and downstream effects

`v37_file_inventory.csv` lists every file created or modified by this continuation, with action and role, including baseline copies and verification logs. Pre-existing user changes are excluded from that inventory and remain protected by the 647-file hash check.

| File/group | Purpose and effect |
|---|---|
| `code/build_results.py`, `04_MODELS/model_inputs.csv` | Correct per-model metadata only; numeric inputs unchanged |
| `code/grade_recommendations.py`, `03_CANONICAL/grade.csv`, root `FINAL_GRADE_RECOMMENDATIONS.md` | Symptom-specific rationale correction; certainty unchanged |
| `code/validate_adjudication.py`, `05_REPRODUCTION/validation_report.json` | Ninth check group and failure exit status |
| `code/build_reports.py`, primary/GRADE/model-manifest reports | Current version/provenance descriptions; numbers unchanged |
| `code/build_v37_followup.py`, `02_DECISIONS/v37/*.csv`, provenance/current-state/backlog reports | Deterministic ledgers, comparison, reconciled limits; missing human fields blank |
| `02_DECISIONS/v37_external_verification.md`, `v37_author_queries.md` | Dated official-record verification and eight unsent drafts |
| `FINAL_PROSPERO_CURRENT_REVIEW_MATRIX.md`, `ASTRA_FINAL_PROTOCOL_RECONCILIATION.md` | Verified identity, no prospective claim |
| `code/v37_integrity.py`, `verify_v37.py`, `finalize_v37.py`, `05_REPRODUCTION/v37/` | Baseline protection, repeated verification, negative control, logs/hashes and reproducible handoff |
| `05_REPRODUCTION/R_session.txt`, reproduction/changelog reports | Actual fresh environment and bounded verification claims |

## Verification and remaining work

38/38 deterministic outputs; 9/9 validator groups; 68 fitted models/731 R comparisons/0 failures; 647/647 protected file hashes; 73/73 estimands unchanged; 22/22 primary literal checks. See `REPRODUCIBILITY_REPORT.md` for tolerances and limits.

**Reviewer screening package A1 is deferred by the user, not complete.** A2 still requires record-level admission/discovery evidence and prior deduplication trail. A4/A5 require version reconciliation, missing result assessments and actual review of all 38 GRADE rows. B queries require approval to send and genuine replies; C/D need reviewer confirmation. Dashboard A6 is untouched and must not be rebuilt from this layer while those blockers remain. **Data lock: NO.**

Spreadsheet provenance guidance informed the row-level identifiers, source locators and separation of observed data, historical adoption claims and blank approval fields. No eligibility screening package was generated.
'''
(R/'CHANGELOG_v37.md').write_text(changelog)

# Every task-owned path, not unrelated dirty/untracked files.
changed=subprocess.check_output(['git','diff','--name-only'],cwd=ROOT,text=True).splitlines()
paths={ROOT/p for p in changed if p not in start['protected_sha256']}
paths.update(V.rglob('*'))
paths.update((D/'02_DECISIONS/v37').glob('*.csv'))
paths.update([D/'02_DECISIONS/v37_external_verification.md',D/'02_DECISIONS/v37_author_queries.md'])
paths.update(D/'code'/n for n in ['v37_integrity.py','build_v37_followup.py','verify_v37.py','finalize_v37.py'])
paths.update(R/n for n in ['ROB2_PROVENANCE_RECONCILIATION_v37.md','model_comparison_v37.csv','CHANGELOG_v37.md','v37_file_inventory.csv'])
rows=[]
tracked=set(subprocess.check_output(['git','ls-files'],cwd=ROOT,text=True).splitlines())
for p in sorted(paths):
    if not p.is_file() and p.name!='v37_file_inventory.csv':continue
    name=str(p.relative_to(ROOT))
    role='Preserved baseline copy' if '/baseline/' in name else 'Verification record/log' if '/05_REPRODUCTION/v37/' in name else 'Generator/validator' if '/code/' in name else 'Decision evidence/draft' if '/02_DECISIONS/' in name else 'Report/derived artifact'
    rows.append(dict(path=name,action='MODIFIED' if name in tracked else 'CREATED',role=role))
with open(R/'v37_file_inventory.csv','w',newline='') as f:
    w=csv.DictWriter(f,['path','action','role']);w.writeheader();w.writerows(rows)
print('Final reports written; task-owned files inventoried:',len(rows))
