"""Render explicitly authored GRADE judgments; no I²/P-value grading thresholds."""
import json,pathlib,csv
ROOT=pathlib.Path(__file__).resolve().parents[2];D=ROOT/'10_FINAL_ADJUDICATION';models=json.load(open(D/'04_MODELS/model_outputs.json'))
# Each entry is a considered evidence-body judgment, not an algorithm that assigns domains from k or P.
J={}
def setj(names,certainty,rob,inc,ind,imp,pub):
 for n in names.split('|'):J[n]=dict(certainty=certainty,risk_of_bias=rob,inconsistency=inc,indirectness=ind,imprecision=imp,publication_bias=pub)
setj('opioid24_TEAS_sham','Low','Serious: only trial has selective-reporting concerns and no full prespecified analysis plan; exact existing assessment Some concerns.','Not downgraded: single study; consistency cannot be evaluated.','Not downgraded for the hernia population itself; extrapolation across surgery remains limited.','Serious: CI crosses the registered10mg benefit threshold;48 analyzed participants cannot establish its magnitude reliably.','Not downgraded again: small evidence body; no informative funnel test. Review-level selection problem reported separately.')
setj('opioid24_TEAS_usual','Very low','Serious: no-stimulation comparison is unblinded; exact comparator-specific RoB linkage unavailable.','Not assessable in one trial.','Not downgraded for the supportive usual-care question; not evidence for sham-specific efficacy.','Very serious:47 participants and CI crosses both8/10mg interpretation thresholds.','No separate downgrade; selective inclusion remains a review-level qualification.')
setj('opioid24_EA_usual','Very low','Serious: El-Rakshy High RoB with internally conflicting arm and population descriptions; Seeva Some concerns.','Serious: clinically divergent morphine effects under different perioperative regimens; two studies cannot characterize distribution reliably.','Not downgraded for supportive question; usual-care effects cannot substitute for principal EA/sham.','Very serious: safeguarded HK CI includes substantial benefit and harm;159 analyzed participants.','No additional downgrade beyond floor; small evidence body cannot exclude missing unfavorable results.')
setj('ponv24_TEAS_sham','Low','Serious: subjective nausea component, variable sensory masking, postrandomization exclusions and incomplete exact RoB linkage.','Serious: variation in effects, surgery and prophylaxis; prediction interval permits null/slightly unfavorable effects despite average benefit.','Not downgraded: clinically relevant cumulative composite; POD1 reports carry modest timing uncertainty.','Not downgraded:3447 participants; average RR interval supports a reduction, although magnitude across settings is uncertain.','Not downgraded separately: funnel asymmetry cannot distinguish heterogeneity from missing reports. Selection completeness problem is separate and blocks a final review-wide claim.')
setj('nausea24_TEAS_sham|vomiting24_TEAS_sham','Very low','Serious: incomplete exact outcome-specific assessments, subjective nausea ascertainment and variable masking.','Serious: clinically heterogeneous surgeries and background prophylaxis; effect-size variation matters to absolute benefit.','No additional downgrade for specific symptom construct.','Serious: intervals cross no effect and permit materially different clinical effects; event evidence is less decisive than composite PONV.','No separate downgrade; missing-result bias cannot be excluded.')
setj('nausea24_EA_usual|vomiting24_EA_usual','Very low','Serious: open-label thoracic trials and incomplete exact symptom-specific RoB linkage.','Not downgraded: broadly compatible direction in two studies; uncertainty is captured in imprecision.','Not downgraded for thoracic supportive question; do not generalize to all surgery/sham efficacy.','Very serious: k2 safeguarded intervals permit major benefit and harm.','No separate downgrade; sparse evidence cannot assess small-study effects.')
setj('nausea6to24_EA_usual|vomiting6to24_EA_usual','Low','Serious: unblinded active-vs-usual-care trial; exact assessment only available for selected vomiting contrast, not every combined arm/outcome.','Not assessable in a single trial.','Not downgraded for6–24h symptom question; indirect for cumulative0–24h and explicitly kept separate.','Serious: one multiarm trial provides limited replication and a range of potentially important effects; no registered symptom MCID.','No separate downgrade; registry/report comparability and publication bias unresolved.')
setj('persistent_nausea24_TEAS_sham','Low','Serious: exact persistent-nausea RoB assessment not established and subjective duration reporting can be affected by masking.','Not assessable in one trial.','Not downgraded for persistent-nausea question; not a substitute for any nausea.','Serious: relatively few persistent-nausea events and broad effect interval despite large trial N.','No additional downgrade; report availability limits publication-bias assessment.')
setj('nausea48_TEAS_sham|vomiting48_TEAS_sham','Low','Serious: single-blind design with blinded patients/assessors; exact assessments High for nausea (outcome measurement) and Some concerns for vomiting. Reviewer to confirm whether High nausea RoB warrants very serious.','Not assessable in one trial.','Not downgraded for48h tympanoplasty question; generalization beyond this setting limited.','Serious:277 participants, few vomiting events and material uncertainty in absolute reduction.','No separate downgrade; absence of replication limits missing-results assessment.')
setj('ponv48_TEAS_sham','Very low','Serious: exact existing assessment Some concerns (outcome measurement and selection domains); anaesthetists unblinded and postoperative tingling could reveal allocation despite no-current electrode sham.','Not assessable in one trial.','Not downgraded for 48h composite PONV after sleeve gastrectomy with dual antiemetic prophylaxis; transportability to other surgery limited.','Very serious: 62 participants and 37 events in one trial; CI excludes no effect but spans small to large reductions.','No separate downgrade beyond floor.')  # v36: Xiong reclassified sham
setj('ponv24_TEAS_active','Very low','Serious: exact existing assessment Some concerns; active non-acupoint stimulation preserves masking but is not an inert comparator.','Not assessable in one trial.','Serious if read as sham efficacy; not downgraded for the separate active-control question.','Very serious: 85 participants in one trial; CI crosses no effect.','No separate downgrade beyond floor.')  # v36: split from former joint row
setj('vomiting24_TEAS_usual','Very low','Serious: no sham procedure described; 15 of 120 enrolled excluded after randomization; exact vomiting-specific RoB assessment not established.','Not assessable in one trial.','Not downgraded for supportive no-stimulation question after laparoscopic myomectomy; not evidence for sham-specific efficacy.','Very serious: 105 participants and 28 events in one trial; upper CI bound close to no effect.','No separate downgrade beyond floor.')  # v36: Pan moved from sham body
setj('intraop_remifentanil_TEAS_usual','Very low','Serious: exact existing assessments High (Pan) and Some concerns (Liang); no sham procedure and anaesthetist-titrated dose.','Serious: opposite effect directions in two trials (Pan reduction, Liang increase); two studies cannot characterize heterogeneity.','Serious: intraoperative dose reduction does not establish postoperative opioid sparing or patient benefit.','Very serious: safeguarded HK CI spans very large reductions and increases.','No separate downgrade beyond floor.')  # v36: Pan and Liang moved from sham body
setj('pain24_rest_TEAS_sham','Low','Serious: Liu and Xing resting-pain exact assessments High; Yu exact assessment not established.','Not downgraded: observed study differences do not overturn the pain-worsening-margin conclusion; statistical homogeneity alone is not proof of consistency.','Not downgraded for24h rest pain; separate trials from the opioid contributor create indirect pairing.','Serious: only218 participants and limited surgery representation; CI excludes+1 average worsening but is not a formal noninferiority trial.','No separate downgrade; missing unfavorable pain results remain possible.')
setj('pain24_movement_TEAS_sham','Low','Serious: subjective cough pain with uncertain sensory masking and no independently established exact cough-pain RoB record.','Not assessable in one trial.','Not downgraded for coughing-pain question; not equivalent to every movement task.','Serious:100 participants, one trial; upperCI below+1 does not establish paired clinical benefit in Szmit.','No separate downgrade; selective availability of movement pain remains possible.')
setj('pain24_movement_EA_sham','Low','Serious: one three-arm trial; result assessment applies to contralateral comparison only and does not fully cover combined active arms.','Not assessable across independent trials.','Not downgraded for knee-movement question; not evidence across all surgeries.','Serious:114 participants, single trial; modest effect and imprecise generalization.','No separate downgrade; He source-dispersion contradiction addressed by sensitivity, not invented data.')
setj('flatus_TEAS_sham','Very low','Serious: varying ascertainment of patient-reported flatus, sensory masking, incomplete exact-result RoB linkage and Zheng2025 SD/P inconsistency (leave-out diagnostic direction and CI unchanged).','Very serious: large clinically disparate time effects including little/no effect; prediction interval crosses no benefit and delay.','Not downgraded for time-to-flatus itself. It does not establish overall GI or functional recovery.','Not separately downgraded: mean CI favors earlier flatus, while major uncertainty across settings is counted in inconsistency.','No extra downgrade; review-level omissions prevent a definitive comprehensive synthesis.')
setj('flatus_EA_usual','Low','Serious: unblinded usual-care comparisons, Huang 2025 and Yang 2024 exact assessments High, and no exact assessment of combined Zhu arms.','Serious: effects vary with surgical setting/protocol and baseline recovery time; same direction is insufficient to establish stable magnitude.','Not downgraded for flatus-hours question; no broad faster-recovery claim.','No extra downgrade: CI supports earlier mean flatus within this body; no registered flatus MCID to imply clinical importance.','No separate downgrade; selection completeness remains a separate blocker.')
setj('flatus_EA_sham','Very low','Serious: patient-reported event and exact flatus-specific assessment not established.','Not assessable in one trial.','Not downgraded for flatus question; postoperative timing/adherence limits transportability.','Very serious:110 participants and CI includes potentially important earlier passage and no benefit/delay.','No additional downgrade.')
setj('bowelsounds_TEAS_sham','Very low','Serious: observer/time-origin ascertainment varies; no exact bowel-sounds RoB record is linked for any trial; Zheng2025 printed mean(SD) values are inconsistent with its printed P value.','Serious: different measurement schedules and control recovery times make a stable magnitude uncertain.','Not downgraded for audible bowel sounds; indirectness would be serious if interpreted as global recovery, which is not claimed.','Serious (v36): pooled CI excludes no effect only with Zheng2025; the leave-out diagnostic (k=2) CI includes no effect and delay. Reviewer to confirm.','No separate downgrade; evidence-selection limitation applies.')
setj('defecation_TEAS_sham|defecation_EA_usual','Very low','Serious: ascertainment, masking and incomplete exact-outcome assessments; open-label EA/usual-care studies add concerns.','Serious: effect sizes vary materially with surgery and bowel-management protocols; EA/usual-care especially disparate.','Not downgraded for first-defecation timing; laxative/co-intervention context must remain explicit.','Serious: intervals include substantial earlier defecation and no benefit/delay.','No further downgrade; selective availability unresolved.')
setj('defecation_EA_sham','Low','Serious: existing selected-result assessment Some concerns; patient-reported event and prespecification concerns.','Not assessable in one trial.','Not downgraded for this colorectal-surgery defecation question.','Serious: single110-participant trial; uncertain magnitude/generalizability despite CI excluding null.','No separate downgrade; absence of independent replication.')
setj('opioid48_EA_usual_PCA|opioid72_EA_sham_PCA','Very low','Serious: existing exact assessments High, postrandomization missingness/attrition.','Not assessable across independent studies.','Serious: PCA exposure may omit other systemic analgesia; these are additional device outcomes, not24h primary exposure.','Serious: small single studies;72h CI includes no benefit/harm,48h effect magnitude remains uncertain.','No further downgrade.')
setj('intraop_remifentanil_TEAS_sham','Very low','Serious: clinician titration/masking varies, exact assessments are incomplete and Zheng2025 SD/P inconsistency (leave-out diagnostic CI still excludes no effect).','Serious: highly different surgery durations, baseline requirements and effects; PI permits increased dose.','Serious: intraoperative dose reduction does not establish postoperative opioid sparing or improved patient outcomes.','Not separately downgraded: average CI excludes null but transportability uncertainty counted above.','No extra downgrade; omissions in selection affect this secondary body directly.')
setj('intraop_remifentanil_EA_usual|intraop_remifentanil_EA_sham','Very low','Serious: exact outcome/combined-arm linkage incomplete and unblinded titration possible.','Not assessable in a single independent trial per stratum.','Serious: anaesthetic dose is indirect for postoperative clinical benefit.','Serious: CI permits reductions and increases.','No additional downgrade.')
setj('pethidine24_TEAS_usual_rescue|pethidine24_TEAS_active_rescue','Very low','Serious: one small trial, exact rescue-result assessment unavailable, co-intervention/measurement concerns.','Not assessable in one trial.','Not downgraded for rescue pethidine; not total systemic consumption.','Very serious:31 participants and CI allows meaningful benefit and harm.','No separate downgrade.')
# v37: keep the inherited judgment pending review but make its symptom-specific rationale accurate.
# Nausea has 77 events (24/138 versus 53/139), not the 36 vomiting events.
J['nausea48_TEAS_sham']['imprecision']='Serious (inherited recommendation; reviewer confirmation pending): 277 participants and 77 nausea events in one trial (24/138 versus 53/139); the relative and absolute benefit magnitudes remain uncertain and no symptom-specific clinical-importance threshold was registered. The previous reference to few vomiting events did not apply to nausea.'
rows=[];text=['# FINAL GRADE RECOMMENDATIONS','', '**ASTRA FINAL GRADE RECOMMENDATION — for the adjudicated 70-report dataset. These recommendations do not certify review-wide completeness or human signoff.**','', 'Randomized evidence starts at high certainty. The following domain judgments were authored for each evidence body; no p-value or I² cutoff assigns certainty. The newly documented outcome-focused exclusions are a review-level selection problem, not automatically relabeled publication bias. They prevent submission-ready review-wide conclusions until the evidence base is reconciled. Diagnostic sensitivities do not receive independent efficacy grades. Existing RoB2 assessments are linked where applicable; unlinked results are explicit and are not silently called Low risk.','', 'Basis: [Cochrane GRADE guidance](https://training.cochrane.org/handbook/current/chapter-14). The opioid10mg and pain+1 margins are registered; secondary GI/symptom clinical-importance thresholds were not registered and are not invented.','']
for m in models:
 if m['role']=='SENSITIVITY':continue
 id=m['model_id']
 if not m['k']:j=dict(certainty='Not rated — insufficient evidence',risk_of_bias='No eligible quantitative body.',inconsistency='Not applicable.',indirectness='Not applicable.',imprecision='No estimate.',publication_bias='Cannot assess.')
 else:assert id in J,id;j=J[id]
 row=dict(model_id=id,label='ASTRA FINAL GRADE RECOMMENDATION',**j);rows.append(row)
 text+=['## '+id,'',f"**{j['certainty']}**; k={m['k']}, N={m['N']}.",'']
 if m['k']:text += [f"{m['measure']} {m['display_effect']:.3f} (95% CI {m['display_ci_low']:.3f} to {m['display_ci_high']:.3f}) {m['unit']}.",'']
 for label,key in [('Risk of bias','risk_of_bias'),('Inconsistency','inconsistency'),('Indirectness','indirectness'),('Imprecision','imprecision'),('Publication bias','publication_bias')]:text+=[f'- **{label}:** '+j[key]]
 text+=['']
(ROOT/'FINAL_GRADE_RECOMMENDATIONS.md').write_text('\n'.join(text))
with open(D/'03_CANONICAL/grade.csv','w',newline='') as f:w=csv.DictWriter(f,list(rows[0]));w.writeheader();w.writerows(rows)
print('Authored GRADE bodies',len(rows))
