/* generated by scripts/extract_article_figures.py; do not hand-edit */
window.ARTICLE_FIGURES = {
  "Zhou 2025": [
    {
      "src": "article_figures/Zhou_2025/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 779,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Zhou_2025/fig_2_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 1063,
      "caption": "Figure / Photo from PDF p. 6"
    }
  ],
  "An 2014": [
    {
      "src": "article_figures/An_2014/fig_1_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 600,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/An_2014/fig_2_p7.jpg",
      "page": 7,
      "width": 776,
      "height": 530,
      "caption": "Figure / Photo from PDF p. 7"
    },
    {
      "src": "article_figures/An_2014/fig_3_p7.jpg",
      "page": 7,
      "width": 795,
      "height": 492,
      "caption": "Figure / Photo from PDF p. 7"
    }
  ],
  "Ao 2021": [
    {
      "src": "article_figures/Ao_2021/fig_1_p3.jpg",
      "page": 3,
      "width": 517,
      "height": 247,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Ao_2021/fig_2_p4.jpg",
      "page": 4,
      "width": 736,
      "height": 811,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Ao_2021/fig_3_p5.jpg",
      "page": 5,
      "width": 516,
      "height": 263,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Ao_2021/fig_4_p6.jpg",
      "page": 6,
      "width": 943,
      "height": 527,
      "caption": "Figure / Photo from PDF p. 6"
    }
  ],
  "Chen 1998": [
    {
      "src": "article_figures/Chen_1998/fig_1_p3.jpg",
      "page": 3,
      "width": 1190,
      "height": 1642,
      "caption": "Figure / Photo from PDF p. 3"
    }
  ],
  "Chen 2015": [
    {
      "src": "article_figures/Chen_2015/fig_1_p2.jpg",
      "page": 2,
      "width": 900,
      "height": 296,
      "caption": "Figure / Photo from PDF p. 2"
    },
    {
      "src": "article_figures/Chen_2015/fig_2_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 1060,
      "caption": "Figure / Photo from PDF p. 3"
    }
  ],
  "Chen 2015 (Hyperalgesia)": [
    {
      "src": "article_figures/Chen_2015__Hyperalgesia_/fig_1_p2.jpg",
      "page": 2,
      "width": 1200,
      "height": 390,
      "caption": "Figure / Photo from PDF p. 2"
    },
    {
      "src": "article_figures/Chen_2015__Hyperalgesia_/fig_2_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 1172,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Chen_2015__Hyperalgesia_/fig_3_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 434,
      "caption": "Figure / Photo from PDF p. 5"
    }
  ],
  "Chen 2020": [
    {
      "src": "article_figures/Chen_2020/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1023,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Chen_2020/fig_2_p5.jpg",
      "page": 5,
      "width": 941,
      "height": 665,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Chen_2020/fig_3_p5.jpg",
      "page": 5,
      "width": 938,
      "height": 660,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Chen_2020/fig_4_p5.jpg",
      "page": 5,
      "width": 940,
      "height": 667,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Chen_2020/fig_5_p5.jpg",
      "page": 5,
      "width": 941,
      "height": 663,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Chen_2020/fig_6_p6.jpg",
      "page": 6,
      "width": 939,
      "height": 664,
      "caption": "Figure / Photo from PDF p. 6"
    }
  ],
  "Coura 2011": [
    {
      "src": "article_figures/Coura_2011/fig_1_p1.jpg",
      "page": 1,
      "width": 1200,
      "height": 1673,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Coura_2011/fig_2_p2.jpg",
      "page": 2,
      "width": 1200,
      "height": 1662,
      "caption": "Figure / Photo from PDF p. 2"
    },
    {
      "src": "article_figures/Coura_2011/fig_3_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 1678,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Coura_2011/fig_4_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1666,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Coura_2011/fig_5_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 1671,
      "caption": "Figure / Photo from PDF p. 5"
    }
  ],
  "El-Rakshy 2009": [],
  "Gao 2021": [
    {
      "src": "article_figures/Gao_2021/fig_1_p1.jpg",
      "page": 1,
      "width": 254,
      "height": 278,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Gao_2021/fig_2_p1.jpg",
      "page": 1,
      "width": 237,
      "height": 299,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Gao_2021/fig_3_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1175,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Gao_2021/fig_4_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 650,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Gao_2021/fig_5_p7.jpg",
      "page": 7,
      "width": 1200,
      "height": 883,
      "caption": "Figure / Photo from PDF p. 7"
    },
    {
      "src": "article_figures/Gao_2021/fig_6_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 685,
      "caption": "Figure / Photo from PDF p. 8"
    }
  ],
  "Gao 2022": [
    {
      "src": "article_figures/Gao_2022/fig_1_p1.jpg",
      "page": 1,
      "width": 279,
      "height": 279,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Gao_2022/fig_2_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1312,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Gao_2022/fig_3_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 949,
      "caption": "Figure / Photo from PDF p. 8"
    }
  ],
  "Grech 2016": [
    {
      "src": "article_figures/Grech_2016/fig_1_p1.jpg",
      "page": 1,
      "width": 201,
      "height": 267,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Grech_2016/fig_2_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 819,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Grech_2016/fig_3_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 1912,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Grech_2016/fig_4_p7.jpg",
      "page": 7,
      "width": 1200,
      "height": 1540,
      "caption": "Figure / Photo from PDF p. 7"
    }
  ],
  "Gu 2019": [
    {
      "src": "article_figures/Gu_2019/fig_1_p1.jpg",
      "page": 1,
      "width": 248,
      "height": 272,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Gu_2019/fig_2_p1.jpg",
      "page": 1,
      "width": 236,
      "height": 298,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Gu_2019/fig_3_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 780,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Gu_2019/fig_4_p4.jpg",
      "page": 4,
      "width": 1001,
      "height": 459,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Gu_2019/fig_5_p4.jpg",
      "page": 4,
      "width": 999,
      "height": 527,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Gu_2019/fig_6_p5.jpg",
      "page": 5,
      "width": 901,
      "height": 542,
      "caption": "Figure / Photo from PDF p. 5"
    }
  ],
  "Guo 2023": [
    {
      "src": "article_figures/Guo_2023/fig_1_p1.jpg",
      "page": 1,
      "width": 236,
      "height": 298,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Guo_2023/fig_2_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1004,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Guo_2023/fig_3_p5.jpg",
      "page": 5,
      "width": 914,
      "height": 609,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Guo_2023/fig_4_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 267,
      "caption": "Figure / Photo from PDF p. 6"
    }
  ],
  "He 2026 (breast/WJCO)": [
    {
      "src": "article_figures/He_2026__breast_WJCO_/fig_1_p1.jpg",
      "page": 1,
      "width": 563,
      "height": 367,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__breast_WJCO_/fig_2_p1.jpg",
      "page": 1,
      "width": 675,
      "height": 675,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__breast_WJCO_/fig_3_p2.jpg",
      "page": 2,
      "width": 563,
      "height": 367,
      "caption": "Figure / Photo from PDF p. 2"
    },
    {
      "src": "article_figures/He_2026__breast_WJCO_/fig_4_p3.jpg",
      "page": 3,
      "width": 563,
      "height": 367,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/He_2026__breast_WJCO_/fig_5_p4.jpg",
      "page": 4,
      "width": 563,
      "height": 367,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/He_2026__breast_WJCO_/fig_6_p5.jpg",
      "page": 5,
      "width": 563,
      "height": 367,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/He_2026__breast_WJCO_/fig_7_p6.jpg",
      "page": 6,
      "width": 563,
      "height": 367,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/He_2026__breast_WJCO_/fig_8_p7.jpg",
      "page": 7,
      "width": 563,
      "height": 367,
      "caption": "Figure / Photo from PDF p. 7"
    },
    {
      "src": "article_figures/He_2026__breast_WJCO_/fig_9_p8.jpg",
      "page": 8,
      "width": 563,
      "height": 367,
      "caption": "Figure / Photo from PDF p. 8"
    },
    {
      "src": "article_figures/He_2026__breast_WJCO_/fig_10_p9.jpg",
      "page": 9,
      "width": 563,
      "height": 367,
      "caption": "Figure / Photo from PDF p. 9"
    },
    {
      "src": "article_figures/He_2026__breast_WJCO_/fig_11_p9.jpg",
      "page": 9,
      "width": 555,
      "height": 555,
      "caption": "Figure / Photo from PDF p. 9"
    }
  ],
  "He 2026 (hepatectomy/JIS)": [
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_1_p1.jpg",
      "page": 1,
      "width": 200,
      "height": 266,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_2_p1.jpg",
      "page": 1,
      "width": 1200,
      "height": 284,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_3_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 1010,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_4_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 1010,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_5_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 703,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_6_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 703,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_7_p1.jpg",
      "page": 1,
      "width": 512,
      "height": 346,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_8_p1.jpg",
      "page": 1,
      "width": 512,
      "height": 346,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_9_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 641,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_10_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 641,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_11_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 470,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_12_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 470,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_13_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 448,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_14_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 448,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_15_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 694,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_16_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 694,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_17_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 674,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_18_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 674,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_19_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 600,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_20_p1.jpg",
      "page": 1,
      "width": 600,
      "height": 600,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_21_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 1478,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_22_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 853,
      "caption": "Figure / Photo from PDF p. 8"
    },
    {
      "src": "article_figures/He_2026__hepatectomy_JIS_/fig_23_p9.jpg",
      "page": 9,
      "width": 1200,
      "height": 916,
      "caption": "Figure / Photo from PDF p. 9"
    }
  ],
  "Hou 2023": [
    {
      "src": "article_figures/Hou_2023/fig_1_p1.jpg",
      "page": 1,
      "width": 236,
      "height": 298,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Hou_2023/fig_2_p7.jpg",
      "page": 7,
      "width": 1200,
      "height": 975,
      "caption": "Figure / Photo from PDF p. 7"
    }
  ],
  "Huang 2017": [],
  "Huang 2024": [
    {
      "src": "article_figures/Huang_2024/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1215,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Huang_2024/fig_2_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 605,
      "caption": "Figure / Photo from PDF p. 8"
    }
  ],
  "Huang 2025": [
    {
      "src": "article_figures/Huang_2025/fig_1_p3.jpg",
      "page": 3,
      "width": 573,
      "height": 553,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Huang_2025/fig_2_p5.jpg",
      "page": 5,
      "width": 1192,
      "height": 1172,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Huang_2025/fig_3_p7.jpg",
      "page": 7,
      "width": 1200,
      "height": 495,
      "caption": "Figure / Photo from PDF p. 7"
    }
  ],
  "Jiang 2026": [
    {
      "src": "article_figures/Jiang_2026/fig_1_p1.jpg",
      "page": 1,
      "width": 248,
      "height": 271,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Jiang_2026/fig_2_p1.jpg",
      "page": 1,
      "width": 236,
      "height": 298,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Jiang_2026/fig_3_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 999,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Jiang_2026/fig_4_p5.jpg",
      "page": 5,
      "width": 1033,
      "height": 725,
      "caption": "Figure / Photo from PDF p. 5"
    }
  ],
  "Jin 2023": [
    {
      "src": "article_figures/Jin_2023/fig_1_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 507,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Jin_2023/fig_2_p7.jpg",
      "page": 7,
      "width": 1001,
      "height": 430,
      "caption": "Figure / Photo from PDF p. 7"
    }
  ],
  "Lee 2011": [],
  "Li 2021": [
    {
      "src": "article_figures/Li_2021/fig_1_p1.jpg",
      "page": 1,
      "width": 272,
      "height": 272,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Li_2021/fig_2_p1.jpg",
      "page": 1,
      "width": 236,
      "height": 298,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Li_2021/fig_3_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 1085,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Li_2021/fig_4_p4.jpg",
      "page": 4,
      "width": 1004,
      "height": 1381,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Li_2021/fig_5_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 845,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Li_2021/fig_6_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 605,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Li_2021/fig_7_p7.jpg",
      "page": 7,
      "width": 1004,
      "height": 1574,
      "caption": "Figure / Photo from PDF p. 7"
    }
  ],
  "Li 2022": [
    {
      "src": "article_figures/Li_2022/fig_1_p4.jpg",
      "page": 4,
      "width": 980,
      "height": 1307,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Li_2022/fig_2_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 812,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Li_2022/fig_3_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 994,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Li_2022/fig_4_p7.jpg",
      "page": 7,
      "width": 1200,
      "height": 994,
      "caption": "Figure / Photo from PDF p. 7"
    }
  ],
  "Liang 2021": [
    {
      "src": "article_figures/Liang_2021/fig_1_p3.jpg",
      "page": 3,
      "width": 510,
      "height": 526,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Liang_2021/fig_2_p3.jpg",
      "page": 3,
      "width": 511,
      "height": 526,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Liang_2021/fig_3_p3.jpg",
      "page": 3,
      "width": 511,
      "height": 526,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Liang_2021/fig_4_p3.jpg",
      "page": 3,
      "width": 511,
      "height": 526,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Liang_2021/fig_5_p3.jpg",
      "page": 3,
      "width": 511,
      "height": 526,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Liang_2021/fig_6_p3.jpg",
      "page": 3,
      "width": 172,
      "height": 1050,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Liang_2021/fig_7_p3.jpg",
      "page": 3,
      "width": 511,
      "height": 526,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Liang_2021/fig_8_p3.jpg",
      "page": 3,
      "width": 510,
      "height": 526,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Liang_2021/fig_9_p3.jpg",
      "page": 3,
      "width": 511,
      "height": 526,
      "caption": "Figure / Photo from PDF p. 3"
    }
  ],
  "Lin 2002": [
    {
      "src": "article_figures/Lin_2002/fig_1_p1.jpg",
      "page": 1,
      "width": 813,
      "height": 499,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Lin_2002/fig_2_p1.jpg",
      "page": 1,
      "width": 638,
      "height": 499,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Lin_2002/fig_3_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 575,
      "caption": "Figure / Photo from PDF p. 4"
    }
  ],
  "Liu 2015": [
    {
      "src": "article_figures/Liu_2015/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 464,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Liu_2015/fig_2_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 785,
      "caption": "Figure / Photo from PDF p. 5"
    }
  ],
  "Liu 2021": [
    {
      "src": "article_figures/Liu_2021/fig_1_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 649,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Liu_2021/fig_2_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 855,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Liu_2021/fig_3_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 278,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Liu_2021/fig_4_p7.jpg",
      "page": 7,
      "width": 1200,
      "height": 1093,
      "caption": "Figure / Photo from PDF p. 7"
    }
  ],
  "Liu 2025": [
    {
      "src": "article_figures/Liu_2025/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1125,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Liu_2025/fig_2_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 704,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Liu_2025/fig_3_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 917,
      "caption": "Figure / Photo from PDF p. 8"
    }
  ],
  "Liu 2026 (ESD)": [],
  "Liu 2026 (burn)": [
    {
      "src": "article_figures/Liu_2026__burn_/fig_1_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 1122,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Liu_2026__burn_/fig_2_p6.jpg",
      "page": 6,
      "width": 1181,
      "height": 893,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Liu_2026__burn_/fig_3_p7.jpg",
      "page": 7,
      "width": 897,
      "height": 946,
      "caption": "Figure / Photo from PDF p. 7"
    },
    {
      "src": "article_figures/Liu_2026__burn_/fig_4_p7.jpg",
      "page": 7,
      "width": 1181,
      "height": 898,
      "caption": "Figure / Photo from PDF p. 7"
    },
    {
      "src": "article_figures/Liu_2026__burn_/fig_5_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 709,
      "caption": "Figure / Photo from PDF p. 8"
    }
  ],
  "Long 2025": [
    {
      "src": "article_figures/Long_2025/fig_1_p1.jpg",
      "page": 1,
      "width": 248,
      "height": 271,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Long_2025/fig_2_p1.jpg",
      "page": 1,
      "width": 236,
      "height": 298,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Long_2025/fig_3_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 940,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Long_2025/fig_4_p4.jpg",
      "page": 4,
      "width": 1000,
      "height": 961,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Long_2025/fig_5_p5.jpg",
      "page": 5,
      "width": 750,
      "height": 583,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Long_2025/fig_6_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 401,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Long_2025/fig_7_p9.jpg",
      "page": 9,
      "width": 1200,
      "height": 988,
      "caption": "Figure / Photo from PDF p. 9"
    }
  ],
  "Lu 2021": [
    {
      "src": "article_figures/Lu_2021/fig_1_p1.jpg",
      "page": 1,
      "width": 236,
      "height": 298,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Lu_2021/fig_2_p1.jpg",
      "page": 1,
      "width": 248,
      "height": 271,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Lu_2021/fig_3_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 853,
      "caption": "Figure / Photo from PDF p. 3"
    }
  ],
  "Lu 2022": [
    {
      "src": "article_figures/Lu_2022/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1006,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Lu_2022/fig_2_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 738,
      "caption": "Figure / Photo from PDF p. 6"
    }
  ],
  "Luo 2026": [
    {
      "src": "article_figures/Luo_2026/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1044,
      "caption": "Figure / Photo from PDF p. 4"
    }
  ],
  "Ma 2026": [
    {
      "src": "article_figures/Ma_2026/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 448,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Ma_2026/fig_2_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 716,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Ma_2026/fig_3_p7.jpg",
      "page": 7,
      "width": 1200,
      "height": 609,
      "caption": "Figure / Photo from PDF p. 7"
    },
    {
      "src": "article_figures/Ma_2026/fig_4_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 352,
      "caption": "Figure / Photo from PDF p. 8"
    },
    {
      "src": "article_figures/Ma_2026/fig_5_p9.jpg",
      "page": 9,
      "width": 1200,
      "height": 422,
      "caption": "Figure / Photo from PDF p. 9"
    },
    {
      "src": "article_figures/Ma_2026/fig_6_p9.jpg",
      "page": 9,
      "width": 1200,
      "height": 684,
      "caption": "Figure / Photo from PDF p. 9"
    },
    {
      "src": "article_figures/Ma_2026/fig_7_p10.jpg",
      "page": 10,
      "width": 1200,
      "height": 672,
      "caption": "Figure / Photo from PDF p. 10"
    }
  ],
  "Ng 2013": [
    {
      "src": "article_figures/Ng_2013/fig_1_p3.jpg",
      "page": 3,
      "width": 1050,
      "height": 1302,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Ng_2013/fig_2_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 890,
      "caption": "Figure / Photo from PDF p. 8"
    }
  ],
  "Ntritsou 2014": [
    {
      "src": "article_figures/Ntritsou_2014/fig_1_p1.jpg",
      "page": 1,
      "width": 458,
      "height": 458,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Ntritsou_2014/fig_2_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 893,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Ntritsou_2014/fig_3_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 639,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Ntritsou_2014/fig_4_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 699,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Ntritsou_2014/fig_5_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 587,
      "caption": "Figure / Photo from PDF p. 5"
    }
  ],
  "Oztas 2019": [
    {
      "src": "article_figures/Oztas_2019/fig_1_p5.jpg",
      "page": 5,
      "width": 1000,
      "height": 824,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Oztas_2019/fig_2_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 388,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Oztas_2019/fig_3_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 1565,
      "caption": "Figure / Photo from PDF p. 6"
    }
  ],
  "Pan 2023": [
    {
      "src": "article_figures/Pan_2023/fig_1_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 1909,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Pan_2023/fig_2_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1217,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Pan_2023/fig_3_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 1078,
      "caption": "Figure / Photo from PDF p. 5"
    }
  ],
  "Seevaunnamtum 2016": [
    {
      "src": "article_figures/Seevaunnamtum_2016/fig_1_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 1144,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Seevaunnamtum_2016/fig_2_p6.jpg",
      "page": 6,
      "width": 279,
      "height": 543,
      "caption": "Figure / Photo from PDF p. 6"
    }
  ],
  "Sim 2002": [],
  "Song 2020": [
    {
      "src": "article_figures/Song_2020/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 919,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Song_2020/fig_2_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 688,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Song_2020/fig_3_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 1297,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Song_2020/fig_4_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 365,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Song_2020/fig_5_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 769,
      "caption": "Figure / Photo from PDF p. 8"
    }
  ],
  "Sun 2017": [
    {
      "src": "article_figures/Sun_2017/fig_1_p4.jpg",
      "page": 4,
      "width": 924,
      "height": 750,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Sun_2017/fig_2_p5.jpg",
      "page": 5,
      "width": 923,
      "height": 753,
      "caption": "Figure / Photo from PDF p. 5"
    }
  ],
  "Szmit 2021": [
    {
      "src": "article_figures/Szmit_2021/fig_1_p1.jpg",
      "page": 1,
      "width": 355,
      "height": 234,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Szmit_2021/fig_2_p1.jpg",
      "page": 1,
      "width": 355,
      "height": 234,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Szmit_2021/fig_3_p1.jpg",
      "page": 1,
      "width": 355,
      "height": 234,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Szmit_2021/fig_4_p1.jpg",
      "page": 1,
      "width": 500,
      "height": 175,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Szmit_2021/fig_5_p4.jpg",
      "page": 4,
      "width": 905,
      "height": 1104,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Szmit_2021/fig_6_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 1697,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Szmit_2021/fig_7_p10.jpg",
      "page": 10,
      "width": 894,
      "height": 709,
      "caption": "Figure / Photo from PDF p. 10"
    },
    {
      "src": "article_figures/Szmit_2021/fig_8_p10.jpg",
      "page": 10,
      "width": 944,
      "height": 722,
      "caption": "Figure / Photo from PDF p. 10"
    }
  ],
  "Tu 2024": [
    {
      "src": "article_figures/Tu_2024/fig_1_p1.jpg",
      "page": 1,
      "width": 236,
      "height": 298,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Tu_2024/fig_2_p1.jpg",
      "page": 1,
      "width": 248,
      "height": 271,
      "caption": "Figure / Photo from PDF p. 1"
    }
  ],
  "Wang 2023": [
    {
      "src": "article_figures/Wang_2023/fig_1_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 800,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Wang_2023/fig_2_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 898,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Wang_2023/fig_3_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 461,
      "caption": "Figure / Photo from PDF p. 8"
    },
    {
      "src": "article_figures/Wang_2023/fig_4_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 452,
      "caption": "Figure / Photo from PDF p. 8"
    }
  ],
  "Wang 2024": [
    {
      "src": "article_figures/Wang_2024/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 689,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Wang_2024/fig_2_p6.jpg",
      "page": 6,
      "width": 827,
      "height": 999,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Wang_2024/fig_3_p7.jpg",
      "page": 7,
      "width": 971,
      "height": 2475,
      "caption": "Figure / Photo from PDF p. 7"
    }
  ],
  "Wong 2006": [
    {
      "src": "article_figures/Wong_2006/fig_1_p3.jpg",
      "page": 3,
      "width": 650,
      "height": 476,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Wong_2006/fig_2_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 1627,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Wong_2006/fig_3_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 1503,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Wong_2006/fig_4_p5.jpg",
      "page": 5,
      "width": 601,
      "height": 414,
      "caption": "Figure / Photo from PDF p. 5"
    }
  ],
  "Wu 2016": [
    {
      "src": "article_figures/Wu_2016/fig_1_p3.jpg",
      "page": 3,
      "width": 392,
      "height": 588,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Wu_2016/fig_2_p5.jpg",
      "page": 5,
      "width": 762,
      "height": 783,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Wu_2016/fig_3_p6.jpg",
      "page": 6,
      "width": 738,
      "height": 724,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Wu_2016/fig_4_p6.jpg",
      "page": 6,
      "width": 661,
      "height": 409,
      "caption": "Figure / Photo from PDF p. 6"
    }
  ],
  "Wu 2022": [
    {
      "src": "article_figures/Wu_2022/fig_1_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 343,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Wu_2022/fig_2_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 886,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Wu_2022/fig_3_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 721,
      "caption": "Figure / Photo from PDF p. 6"
    }
  ],
  "Wu 2025": [
    {
      "src": "article_figures/Wu_2025/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 859,
      "caption": "Figure / Photo from PDF p. 4"
    }
  ],
  "Xie 2014": [
    {
      "src": "article_figures/Xie_2014/fig_1_p2.jpg",
      "page": 2,
      "width": 827,
      "height": 453,
      "caption": "Figure / Photo from PDF p. 2"
    },
    {
      "src": "article_figures/Xie_2014/fig_2_p4.jpg",
      "page": 4,
      "width": 892,
      "height": 497,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Xie_2014/fig_3_p4.jpg",
      "page": 4,
      "width": 939,
      "height": 495,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Xie_2014/fig_4_p4.jpg",
      "page": 4,
      "width": 936,
      "height": 494,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Xie_2014/fig_5_p4.jpg",
      "page": 4,
      "width": 939,
      "height": 492,
      "caption": "Figure / Photo from PDF p. 4"
    }
  ],
  "Xing 2022": [
    {
      "src": "article_figures/Xing_2022/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 450,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Xing_2022/fig_2_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 612,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Xing_2022/fig_3_p7.jpg",
      "page": 7,
      "width": 899,
      "height": 663,
      "caption": "Figure / Photo from PDF p. 7"
    },
    {
      "src": "article_figures/Xing_2022/fig_4_p9.jpg",
      "page": 9,
      "width": 1200,
      "height": 397,
      "caption": "Figure / Photo from PDF p. 9"
    }
  ],
  "Xiong 2021": [],
  "Yang 2020": [
    {
      "src": "article_figures/Yang_2020/fig_1_p1.jpg",
      "page": 1,
      "width": 355,
      "height": 355,
      "caption": "Figure / Photo from PDF p. 1"
    }
  ],
  "Yang 2024": [
    {
      "src": "article_figures/Yang_2024/fig_1_p1.jpg",
      "page": 1,
      "width": 236,
      "height": 298,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Yang_2024/fig_2_p1.jpg",
      "page": 1,
      "width": 248,
      "height": 271,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Yang_2024/fig_3_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 1101,
      "caption": "Figure / Photo from PDF p. 3"
    }
  ],
  "Yao 2015": [],
  "Yeh 2010": [
    {
      "src": "article_figures/Yeh_2010/fig_1_p1.jpg",
      "page": 1,
      "width": 1200,
      "height": 1652,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Yeh_2010/fig_2_p2.jpg",
      "page": 2,
      "width": 1200,
      "height": 1642,
      "caption": "Figure / Photo from PDF p. 2"
    },
    {
      "src": "article_figures/Yeh_2010/fig_3_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 1647,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Yeh_2010/fig_4_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1646,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Yeh_2010/fig_5_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 1649,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Yeh_2010/fig_6_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 1642,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Yeh_2010/fig_7_p7.jpg",
      "page": 7,
      "width": 1200,
      "height": 1653,
      "caption": "Figure / Photo from PDF p. 7"
    },
    {
      "src": "article_figures/Yeh_2010/fig_8_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 1643,
      "caption": "Figure / Photo from PDF p. 8"
    },
    {
      "src": "article_figures/Yeh_2010/fig_9_p9.jpg",
      "page": 9,
      "width": 1200,
      "height": 1647,
      "caption": "Figure / Photo from PDF p. 9"
    }
  ],
  "Yeh 2011": [
    {
      "src": "article_figures/Yeh_2011/fig_1_p3.jpg",
      "page": 3,
      "width": 592,
      "height": 528,
      "caption": "Figure / Photo from PDF p. 3"
    }
  ],
  "Yu 2020": [
    {
      "src": "article_figures/Yu_2020/fig_1_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 713,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Yu_2020/fig_2_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1142,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Yu_2020/fig_3_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 942,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Yu_2020/fig_4_p6.jpg",
      "page": 6,
      "width": 1183,
      "height": 924,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Yu_2020/fig_5_p6.jpg",
      "page": 6,
      "width": 1183,
      "height": 873,
      "caption": "Figure / Photo from PDF p. 6"
    }
  ],
  "Zhan 2020": [
    {
      "src": "article_figures/Zhan_2020/fig_1_p1.jpg",
      "page": 1,
      "width": 247,
      "height": 272,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Zhan_2020/fig_2_p1.jpg",
      "page": 1,
      "width": 236,
      "height": 298,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Zhan_2020/fig_3_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 743,
      "caption": "Figure / Photo from PDF p. 3"
    }
  ],
  "Zhang 2014": [
    {
      "src": "article_figures/Zhang_2014/fig_1_p3.jpg",
      "page": 3,
      "width": 849,
      "height": 380,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Zhang_2014/fig_2_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1364,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Zhang_2014/fig_3_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 422,
      "caption": "Figure / Photo from PDF p. 6"
    }
  ],
  "Zhang 2018": [
    {
      "src": "article_figures/Zhang_2018/fig_1_p3.jpg",
      "page": 3,
      "width": 1000,
      "height": 750,
      "caption": "Figure / Photo from PDF p. 3"
    }
  ],
  "Zhang 2023": [
    {
      "src": "article_figures/Zhang_2023/fig_1_p1.jpg",
      "page": 1,
      "width": 351,
      "height": 149,
      "caption": "Figure / Photo from PDF p. 1"
    },
    {
      "src": "article_figures/Zhang_2023/fig_2_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 653,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Zhang_2023/fig_3_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1234,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Zhang_2023/fig_4_p6.jpg",
      "page": 6,
      "width": 971,
      "height": 599,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Zhang_2023/fig_5_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 1519,
      "caption": "Figure / Photo from PDF p. 8"
    }
  ],
  "Zhang 2025": [
    {
      "src": "article_figures/Zhang_2025/fig_1_p3.jpg",
      "page": 3,
      "width": 1200,
      "height": 882,
      "caption": "Figure / Photo from PDF p. 3"
    },
    {
      "src": "article_figures/Zhang_2025/fig_2_p5.jpg",
      "page": 5,
      "width": 1200,
      "height": 723,
      "caption": "Figure / Photo from PDF p. 5"
    },
    {
      "src": "article_figures/Zhang_2025/fig_3_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 445,
      "caption": "Figure / Photo from PDF p. 8"
    }
  ],
  "Zheng 2025": [
    {
      "src": "article_figures/Zheng_2025/fig_1_p6.jpg",
      "page": 6,
      "width": 1200,
      "height": 1003,
      "caption": "Figure / Photo from PDF p. 6"
    },
    {
      "src": "article_figures/Zheng_2025/fig_2_p8.jpg",
      "page": 8,
      "width": 1200,
      "height": 1624,
      "caption": "Figure / Photo from PDF p. 8"
    },
    {
      "src": "article_figures/Zheng_2025/fig_3_p9.jpg",
      "page": 9,
      "width": 1200,
      "height": 1866,
      "caption": "Figure / Photo from PDF p. 9"
    }
  ],
  "Zhou 2021": [
    {
      "src": "article_figures/Zhou_2021/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 1157,
      "caption": "Figure / Photo from PDF p. 4"
    },
    {
      "src": "article_figures/Zhou_2021/fig_2_p7.jpg",
      "page": 7,
      "width": 1200,
      "height": 820,
      "caption": "Figure / Photo from PDF p. 7"
    }
  ],
  "Zhu 2022": [
    {
      "src": "article_figures/Zhu_2022/fig_1_p4.jpg",
      "page": 4,
      "width": 1200,
      "height": 770,
      "caption": "Figure / Photo from PDF p. 4"
    }
  ]
};
