// Generated by scripts/build_cohort_overlap_scan.py; do not edit.
// Report-to-study reconciliation, the duplicate-cohort scan behind it, and the
// arm-level denominators that disagree with their own source publication.
window.COHORT_OVERLAP = {
  "generated_by": "scripts/build_cohort_overlap_scan.py",
  "reports": 70,
  "studies": 69,
  "declared_links": [
    {
      "study_record": "Yeh 2010",
      "companion_report": "Yeh 2011",
      "note": "Same trial as Yeh 2010. Both papers report one three-arm randomised study of lumbar spinal surgery by the same author team (Yeh, Chung, Chen, Chen): Altern Ther Health Med 2010;16(6):10-18 states “Ninety-nine patients undergoing lumbar spinal surgery were randomly assigned to one of three groups”, and Int J Nurs Stud 2011;48(6):703-709 reports the same cohort, with the sham arm's figures identical between the two papers. Review team decision 2026-09-11: COUNT ONCE. Yeh 2010 (the later, larger report, n=63) is retained as the trial record; this record is its companion publication and must not contribute independently to any synthesis.",
      "linkage_record": "05_study_linkage/cohorts/yeh_lumbar_spinal_surgery.md"
    }
  ],
  "candidates": [
    {
      "studies": [
        "Chen 2015",
        "Chen 2015 (Hyperalgesia)"
      ],
      "status": "flagged_for_review",
      "shared": [
        "country of conduct",
        "surgical specialty",
        "modality",
        "same surgical population",
        "journal",
        "publication year within 1"
      ],
      "analysed_n": {
        "Chen 2015": 83,
        "Chen 2015 (Hyperalgesia)": 59
      },
      "arm_n": {
        "Chen 2015": [
          41,
          42
        ],
        "Chen 2015 (Hyperalgesia)": [
          29,
          30
        ]
      },
      "shared_arm_n": [],
      "citations": {
        "Chen 2015": "Chen Y, et al. *Int J Clin Exp Med*. 2015;8(8):13622-13627. PMCID: PMC4612989",
        "Chen 2015 (Hyperalgesia)": "Chen Y, et al. *Int J Clin Exp Med*. 2015;8(4):5781-5787. PMCID: PMC4483789"
      },
      "procedure": "Elective thyroidectomy"
    },
    {
      "studies": [
        "Yeh 2010",
        "Yeh 2011"
      ],
      "status": "confirmed",
      "shared": [
        "country of conduct",
        "surgical specialty",
        "modality",
        "publication year within 1"
      ],
      "analysed_n": {
        "Yeh 2010": 63,
        "Yeh 2011": 60
      },
      "arm_n": {
        "Yeh 2010": [
          33,
          30
        ],
        "Yeh 2011": [
          30,
          30
        ]
      },
      "shared_arm_n": [
        30
      ],
      "citations": {
        "Yeh 2010": "Yeh ML, et al. *Int J Nurs Stud*. 2011;48(6):703-709. DOI: 10.1016/j.ijnurstu.2010.10.009. PMID: 21084087",
        "Yeh 2011": "Yeh ML, et al. *Altern Ther Health Med*. 2010;16(6):10-18. PMID: 21280458"
      },
      "procedure": "Patients undergoing surgery for nontraumatic lumbar spine injury/disorders"
    }
  ],
  "arm_n_conflicts": {
    "Yeh 2010": {
      "field": "population.arm1_n",
      "register": 33,
      "source_says": 30,
      "source": "TEAS EA Verification/astra_audit/source_text/covidence_828_full_article.txt",
      "quote": "n = 30 in each group; F-test for numerical data or chi-square test for categorical data.",
      "note": "Register key Yeh 2010 is the Int J Nurs Stud 2011 report (covidence_828_full_article.pdf), whose flow diagram randomises 30 / 30 / 30 and whose baseline table footnote states n = 30 in each group. The register's arm1_n of 33 is the EG1 denominator of the companion Altern Ther Health Med report, not this one."
    },
    "Yeh 2011": {
      "field": "population.arm1_n",
      "register": 30,
      "source_says": 33,
      "source": "TEAS EA Verification/astra_audit/source_text/015_PainATHM-2.txt",
      "quote": "Variables EGl(n=33) EG2(n=30) CG(n=31)",
      "note": "Register key Yeh 2011 is the Altern Ther Health Med 2010 report (015_PainATHM-2.pdf), whose Table 2 gives EG1 n = 33. The register's arm1_n of 30 is the companion Int J Nurs Stud figure. The same row's female count (22/33) and ages do come from this paper, so the two reports' arm denominators appear to have been transposed during extraction."
    }
  },
  "cohort_size_disagreements": [
    {
      "studies": [
        "Yeh 2010",
        "Yeh 2011"
      ],
      "summary": "The two reports of this trial state different cohort sizes.",
      "detail": "Int J Nurs Stud 2011 (key Yeh 2010) shows 99 assessed for eligibility, 90 meeting inclusion criteria, and randomisation to 30 / 30 / 30. Altern Ther Health Med 2010 (key Yeh 2011) states \"Ninety-nine patients undergoing lumbar spinal surgery were randomly assigned to one of three groups\" with group sizes 33 / 30 / 31. Whether 90 or 99 were randomised cannot be settled from the two papers, so neither figure is used as the trial's randomised N.",
      "affects": "Descriptive participant totals only. Neither report contributes arm-level data to any synthesis, so no effect estimate depends on this."
    }
  ],
  "participants": {
    "analysed_across_reports": 10678,
    "analysed_across_studies": 10618,
    "deduplicated_by": [
      "Yeh 2011"
    ],
    "randomised_contrast_recorded": [
      "Grech 2016",
      "Gu 2019",
      "He 2026 (hepatectomy/JIS)",
      "Lee 2011"
    ],
    "randomised_whole_trial_recorded": [
      "Chen 2020",
      "Coura 2011",
      "He 2026 (breast/WJCO)",
      "Jin 2023",
      "Lee 2011",
      "Liu 2021",
      "Lu 2021",
      "Ma 2026",
      "Ntritsou 2014",
      "Wu 2025",
      "Yang 2020",
      "Yao 2015",
      "Zheng 2025",
      "Zhu 2022"
    ],
    "randomised_any_channel": [
      "Chen 2020",
      "Coura 2011",
      "Grech 2016",
      "Gu 2019",
      "He 2026 (breast/WJCO)",
      "He 2026 (hepatectomy/JIS)",
      "Jin 2023",
      "Lee 2011",
      "Liu 2021",
      "Lu 2021",
      "Ma 2026",
      "Ntritsou 2014",
      "Wu 2025",
      "Yang 2020",
      "Yao 2015",
      "Zheng 2025",
      "Zhu 2022"
    ],
    "randomised_total_publishable": false,
    "randomised_total_reason": "The register records a randomised denominator for the pairwise contrast in 4 of the 69 studies, and the source-PDF extraction records a whole-trial randomised N in 14. The two are different quantities and are not additive, and neither covers the review. A review-wide randomised participant total is therefore not reported; the analysed total is."
  }
};
