// Generated by scripts/build_cohort_overlap_scan.py; do not edit.
// Report-to-study reconciliation, the duplicate-cohort scan behind it, and the
// arm-level denominators that disagree with their own source publication.
window.COHORT_OVERLAP = {
  "generated_by": "scripts/build_cohort_overlap_scan.py",
  "reports": 70,
  "studies": 69,
  "declared_links": [
    {
      "study_record": "Yeh 2010",
      "companion_report": "Yeh 2011",
      "note": "Same trial as Yeh 2010. This record is the Int J Nurs Stud 2011;48(6):703-709 report (30 per arm); Yeh 2010 is the Altern Ther Health Med 2010;16(6):10-18 report of the same three-arm cohort by the same author team. Review team decision 2026-09-11: COUNT ONCE, with Yeh 2010 retained as the trial record. This record is its companion publication and must not contribute independently to any synthesis. Identity re-assigned 2026-09-12 so that this key names the same publication here as it does in Outcome_Data_AF_LOCK.",
      "linkage_record": "05_study_linkage/cohorts/yeh_lumbar_spinal_surgery.md"
    }
  ],
  "candidates": [
    {
      "studies": [
        "Chen 2015",
        "Chen 2015 (Hyperalgesia)"
      ],
      "status": "adjudicated_separate",
      "adjudication": {
        "verdict": "separate",
        "date": "2026-09-12",
        "record": "05_study_linkage/cohorts/chen_2015_thyroidectomy_pair.md",
        "summary": "Two separate trials by one group at one centre, run back to back.",
        "evidence": [
          "Separate ethics approvals from the same board: Chen 2015 cites “ethical approval from Fujian Provincial Hospital (Ref: K2014-12-003)”; Chen 2015 (Hyperalgesia) cites “the Institutional Review Board of Fujian Provincial Hospital (Ref: K2014-07-003)”.",
          "Non-overlapping recruitment: “from January 2015 to May 2015” versus “from August 2014 to December 2014” — the second trial had finished recruiting before the first began.",
          "Independent screening funnels: 91 assessed → 3 ineligible, 4 declined → 84 enrolled → 83 analysed; versus 73 assessed → 7 ineligible, 6 declined → 60 enrolled → 59 analysed.",
          "Chen 2015 is prospectively registered as ClinicalTrials.gov NCT02333747; Chen 2015 (Hyperalgesia) states no registration.",
          "Different primary outcomes (QoR-40 at 24 h versus mechanical pain threshold), partly different author teams, and separate funding grants (2015J01373 versus 2012Y0012)."
        ],
        "shared_but_not_probative": "Same first author, centre, procedure, sex restriction, ASA and age eligibility, device and stimulation parameters — one group running a consistent protocol across consecutive trials, which is what made this a candidate worth reading."
      },
      "shared": [
        "country of conduct",
        "surgical specialty",
        "modality",
        "same surgical population",
        "journal",
        "publication year within 1"
      ],
      "analysed_n": {
        "Chen 2015": 83,
        "Chen 2015 (Hyperalgesia)": 59
      },
      "arm_n": {
        "Chen 2015": [
          41,
          42
        ],
        "Chen 2015 (Hyperalgesia)": [
          29,
          30
        ]
      },
      "shared_arm_n": [],
      "citations": {
        "Chen 2015": "Chen Y, et al. *Int J Clin Exp Med*. 2015;8(8):13622-13627. PMCID: PMC4612989",
        "Chen 2015 (Hyperalgesia)": "Chen Y, et al. *Int J Clin Exp Med*. 2015;8(4):5781-5787. PMCID: PMC4483789"
      },
      "procedure": "Elective thyroidectomy"
    },
    {
      "studies": [
        "Yeh 2010",
        "Yeh 2011"
      ],
      "status": "confirmed",
      "adjudication": null,
      "shared": [
        "country of conduct",
        "surgical specialty",
        "modality",
        "publication year within 1"
      ],
      "analysed_n": {
        "Yeh 2010": 63,
        "Yeh 2011": 60
      },
      "arm_n": {
        "Yeh 2010": [
          33,
          30
        ],
        "Yeh 2011": [
          30,
          30
        ]
      },
      "shared_arm_n": [
        30
      ],
      "citations": {
        "Yeh 2010": "Yeh ML, et al. *Altern Ther Health Med*. 2010;16(6):10-18. PMID: 21280458",
        "Yeh 2011": "Yeh ML, et al. *Int J Nurs Stud*. 2011;48(6):703-709. DOI: 10.1016/j.ijnurstu.2010.10.009. PMID: 21084087"
      },
      "procedure": "Patients undergoing surgery for nontraumatic lumbar spine injury/disorders"
    }
  ],
  "attribution_conflicts": [],
  "baseline_arm_swaps": [
    {
      "study": "Gu 2019",
      "summary": "Age, BMI and sex are each recorded against the opposite arm.",
      "source": "TEAS EA Verification/Source PDFs/covidence_1471_full_article.pdf",
      "source_location": "Table 1, Characteristics of patients (p4)",
      "quote": "Characteristics C-TEAS(n = 59) L-TEAS(n = 58) | Age (mean ± SD, year) 56.67 ± 6.23  57.59 ± 7.32 | Sex Male 29  31 | Female 30  27 | BMI(mean ± SD, kg/m2) 21.84 ± 2.78  22.71 ± 2.54",
      "arm_assignment_confirmed_by": [
        "The paper: the intervention is the long-duration TEAS group (L-TEAS, n = 58); the comparator is C-TEAS (n = 59), whose stimulator output wires were broken so no current was delivered — a true sham, as the register's comparator_type says.",
        "Outcome_Data_AF_LOCK: all eight Gu 2019 rows record Intervention arm “Long-duration TEAS” with analysed n = 58 against Comparator arm “Sham/no-current TEAS” with analysed n = 59.",
        "The register's own arm_n values (58 for the TEAS group, 59 for the Sham group) already match both."
      ],
      "fields": [
        {
          "field": "arm1_age",
          "register": "56.67 ± 6.23",
          "source_says": "57.59 ± 7.32"
        },
        {
          "field": "arm2_age",
          "register": "57.59 ± 7.32",
          "source_says": "56.67 ± 6.23"
        },
        {
          "field": "arm1_bmi",
          "register": "21.84 ± 2.78",
          "source_says": "22.71 ± 2.54"
        },
        {
          "field": "arm2_bmi",
          "register": "22.71 ± 2.54",
          "source_says": "21.84 ± 2.78"
        },
        {
          "field": "arm1_female",
          "register": "30/59 (50.8%)",
          "source_says": "27/58 (46.6%)"
        },
        {
          "field": "arm2_female",
          "register": "27/58 (46.6%)",
          "source_says": "30/59 (50.8%)"
        }
      ],
      "also": "asa_status reads “ASA I: 20 (33.9%), ASA II: 39 (66.1%)”, which sums to 59 and is the SHAM arm's distribution presented as if it were study-wide. The paper gives ASA I 23 / II 35 for the 58 patients in the TEAS arm.",
      "affects": "Descriptive baseline display only. No analysed denominator, effect estimate, risk-of-bias judgement or GRADE rating reads these fields.",
      "decision_needed": "Straightforward to correct — the paper, the lock and the register's own arm labels all agree on which arm is which, so the six values simply move back to their arms. Left uncorrected pending review-team sign-off, because it edits the register's baseline layer."
    }
  ],
  "resolved_attribution": [
    {
      "studies": [
        "Yeh 2010",
        "Yeh 2011"
      ],
      "resolved": "2026-09-12",
      "verdict": "Yeh 2010 = Altern Ther Health Med 2010;16(6):10-18 (Covidence 823); Yeh 2011 = Int J Nurs Stud 2011;48(6):703-709 (Covidence 828).",
      "why": "Two locked sheets disagreed about which key named which paper. Counted by each file's own numbers, 15 files already used this convention — Outcome_Data_AF_LOCK, every Stata input, all five v34_reconciliation extracts, the mirror of the locked workbook's Outcome_Data sheet and the 07_TIERED_V33 working set. One file, Study_Master, used the other, on the strength of an Identity correction annotation that had been propagated nowhere.",
      "applied_by": "scripts/apply_yeh_identity_correction.py",
      "audited_by": "scripts/audit_yeh_identity_convention.py",
      "record": "05_study_linkage/cohorts/yeh_lumbar_spinal_surgery.md",
      "not_touched": "No arm denominator, mean, SD, effect estimate, RoB 2 judgement or GRADE rating. Both records stay on DUPLICATE-OVERLAP HOLD (include_strict = include_sensitivity = 0 on every row), so no synthesis reads either, and the study count of 69 is unchanged.",
      "superseded_findings": [
        "First reading: transposed arm denominators, naming arm1_n as the defective field.",
        "Second reading: inverted citation, naming the arm denominators as the reliable half.",
        "Both were partial. The lock disagreed with itself, so no single dashboard field was the wrong one."
      ]
    }
  ],
  "denominator_mismatches": [
    {
      "study": "El-Rakshy 2009",
      "arm": "arm1",
      "arm_name": "EA Group",
      "female": "42/44 (95.5%)",
      "female_denominator": 44,
      "analysed_n": 42,
      "randomised_n": null,
      "explained_by_randomised": false
    },
    {
      "study": "El-Rakshy 2009",
      "arm": "arm2",
      "arm_name": "Usual Care Group",
      "female": "50/58 (86.2%)",
      "female_denominator": 58,
      "analysed_n": 53,
      "randomised_n": null,
      "explained_by_randomised": false
    },
    {
      "study": "Lee 2011",
      "arm": "arm1",
      "arm_name": "TEAS Group",
      "female": "20/20 (100%)",
      "female_denominator": 20,
      "analysed_n": 12,
      "randomised_n": 12,
      "explained_by_randomised": false
    },
    {
      "study": "Lee 2011",
      "arm": "arm2",
      "arm_name": "Sham Group",
      "female": "20/20 (100%)",
      "female_denominator": 20,
      "analysed_n": 12,
      "randomised_n": 12,
      "explained_by_randomised": false
    },
    {
      "study": "Grech 2016",
      "arm": "arm1",
      "arm_name": "EA Group",
      "female": "9/20 (45.0%)",
      "female_denominator": 20,
      "analysed_n": 11,
      "randomised_n": 11,
      "explained_by_randomised": false
    },
    {
      "study": "Gu 2019",
      "arm": "arm1",
      "arm_name": "TEAS Group",
      "female": "30/59 (50.8%)",
      "female_denominator": 59,
      "analysed_n": 58,
      "randomised_n": 60,
      "explained_by_randomised": false
    },
    {
      "study": "Gu 2019",
      "arm": "arm2",
      "arm_name": "Sham Group",
      "female": "27/58 (46.6%)",
      "female_denominator": 58,
      "analysed_n": 59,
      "randomised_n": 60,
      "explained_by_randomised": false
    },
    {
      "study": "He 2026 (hepatectomy/JIS)",
      "arm": "arm1",
      "arm_name": "TEAS Group",
      "female": "9/43 (20.9%)",
      "female_denominator": 43,
      "analysed_n": 80,
      "randomised_n": 81,
      "explained_by_randomised": false
    },
    {
      "study": "He 2026 (hepatectomy/JIS)",
      "arm": "arm2",
      "arm_name": "Sham Group",
      "female": "10/43 (23.3%)",
      "female_denominator": 43,
      "analysed_n": 79,
      "randomised_n": 80,
      "explained_by_randomised": false
    }
  ],
  "locked_sheet_disagreements": [
    {
      "study": "Jin 2023",
      "study_master_summary_arms": [
        53,
        53
      ],
      "af_lock_analysed_arms": [
        [
          53,
          52
        ]
      ],
      "exchanged_with": [],
      "kind": "arm_figures_differ"
    },
    {
      "study": "Lu 2021",
      "study_master_summary_arms": [
        190,
        198
      ],
      "af_lock_analysed_arms": [
        [
          190,
          188
        ],
        [
          198,
          188
        ]
      ],
      "exchanged_with": [],
      "kind": "arm_figures_differ"
    },
    {
      "study": "Wang 2024",
      "study_master_summary_arms": [
        68,
        70
      ],
      "af_lock_analysed_arms": [
        [
          33,
          35
        ],
        [
          35,
          35
        ]
      ],
      "exchanged_with": [],
      "kind": "arm_figures_differ"
    },
    {
      "study": "Zhu 2022",
      "study_master_summary_arms": [
        101,
        98
      ],
      "af_lock_analysed_arms": [
        [
          98,
          101
        ],
        [
          100,
          101
        ],
        [
          101,
          101
        ]
      ],
      "exchanged_with": [],
      "kind": "arm_figures_differ"
    }
  ],
  "cohort_size_disagreements": [
    {
      "studies": [
        "Yeh 2010",
        "Yeh 2011"
      ],
      "summary": "The two reports of this trial state different cohort sizes.",
      "detail": "Int J Nurs Stud 2011 shows 99 assessed for eligibility, 90 meeting inclusion criteria, and randomisation to 30 / 30 / 30. Altern Ther Health Med 2010 states \"Ninety-nine patients undergoing lumbar spinal surgery were randomly assigned to one of three groups\" with group sizes 33 / 30 / 31. Whether 90 or 99 were randomised cannot be settled from the two papers, so neither figure is used as the trial's randomised N. Stated by paper rather than by register key, because which key names which paper is itself in question — see the attribution conflict above.",
      "affects": "Descriptive participant totals only. Neither report contributes arm-level data to any synthesis, so no effect estimate depends on this."
    }
  ],
  "participants": {
    "analysed_across_reports": 10678,
    "analysed_across_studies": 10618,
    "deduplicated_by": [
      "Yeh 2011"
    ],
    "randomised_contrast_recorded": [
      "Grech 2016",
      "Gu 2019",
      "He 2026 (hepatectomy/JIS)",
      "Lee 2011"
    ],
    "randomised_whole_trial_recorded": [
      "Chen 2020",
      "Coura 2011",
      "He 2026 (breast/WJCO)",
      "Jin 2023",
      "Lee 2011",
      "Liu 2021",
      "Lu 2021",
      "Ma 2026",
      "Ntritsou 2014",
      "Wu 2025",
      "Yang 2020",
      "Yao 2015",
      "Zheng 2025",
      "Zhu 2022"
    ],
    "randomised_any_channel": [
      "Chen 2020",
      "Coura 2011",
      "Grech 2016",
      "Gu 2019",
      "He 2026 (breast/WJCO)",
      "He 2026 (hepatectomy/JIS)",
      "Jin 2023",
      "Lee 2011",
      "Liu 2021",
      "Lu 2021",
      "Ma 2026",
      "Ntritsou 2014",
      "Wu 2025",
      "Yang 2020",
      "Yao 2015",
      "Zheng 2025",
      "Zhu 2022"
    ],
    "randomised_total_publishable": false,
    "randomised_total_reason": "The register records a randomised denominator for the pairwise contrast in 4 of the 69 studies, and the source-PDF extraction records a whole-trial randomised N in 14. The two are different quantities and are not additive, and neither covers the review. A review-wide randomised participant total is therefore not reported; the analysed total is."
  }
};
