// Generated by scripts/build_cohort_overlap_scan.py; do not edit.
// Report-to-study reconciliation, the duplicate-cohort scan behind it, and the
// arm-level denominators that disagree with their own source publication.
window.COHORT_OVERLAP = {
  "generated_by": "scripts/build_cohort_overlap_scan.py",
  "reports": 70,
  "studies": 69,
  "declared_links": [
    {
      "study_record": "Yeh 2010",
      "companion_report": "Yeh 2011",
      "note": "Same trial as Yeh 2010. Both papers report one three-arm randomised study of lumbar spinal surgery by the same author team (Yeh, Chung, Chen, Chen): Altern Ther Health Med 2010;16(6):10-18 states “Ninety-nine patients undergoing lumbar spinal surgery were randomly assigned to one of three groups”, and Int J Nurs Stud 2011;48(6):703-709 reports the same cohort, with the sham arm's figures identical between the two papers. Review team decision 2026-09-11: COUNT ONCE. Yeh 2010 (the later, larger report, n=63) is retained as the trial record; this record is its companion publication and must not contribute independently to any synthesis.",
      "linkage_record": "05_study_linkage/cohorts/yeh_lumbar_spinal_surgery.md"
    }
  ],
  "candidates": [
    {
      "studies": [
        "Chen 2015",
        "Chen 2015 (Hyperalgesia)"
      ],
      "status": "adjudicated_separate",
      "adjudication": {
        "verdict": "separate",
        "date": "2026-09-12",
        "record": "05_study_linkage/cohorts/chen_2015_thyroidectomy_pair.md",
        "summary": "Two separate trials by one group at one centre, run back to back.",
        "evidence": [
          "Separate ethics approvals from the same board: Chen 2015 cites “ethical approval from Fujian Provincial Hospital (Ref: K2014-12-003)”; Chen 2015 (Hyperalgesia) cites “the Institutional Review Board of Fujian Provincial Hospital (Ref: K2014-07-003)”.",
          "Non-overlapping recruitment: “from January 2015 to May 2015” versus “from August 2014 to December 2014” — the second trial had finished recruiting before the first began.",
          "Independent screening funnels: 91 assessed → 3 ineligible, 4 declined → 84 enrolled → 83 analysed; versus 73 assessed → 7 ineligible, 6 declined → 60 enrolled → 59 analysed.",
          "Chen 2015 is prospectively registered as ClinicalTrials.gov NCT02333747; Chen 2015 (Hyperalgesia) states no registration.",
          "Different primary outcomes (QoR-40 at 24 h versus mechanical pain threshold), partly different author teams, and separate funding grants (2015J01373 versus 2012Y0012)."
        ],
        "shared_but_not_probative": "Same first author, centre, procedure, sex restriction, ASA and age eligibility, device and stimulation parameters — one group running a consistent protocol across consecutive trials, which is what made this a candidate worth reading."
      },
      "shared": [
        "country of conduct",
        "surgical specialty",
        "modality",
        "same surgical population",
        "journal",
        "publication year within 1"
      ],
      "analysed_n": {
        "Chen 2015": 83,
        "Chen 2015 (Hyperalgesia)": 59
      },
      "arm_n": {
        "Chen 2015": [
          41,
          42
        ],
        "Chen 2015 (Hyperalgesia)": [
          29,
          30
        ]
      },
      "shared_arm_n": [],
      "citations": {
        "Chen 2015": "Chen Y, et al. *Int J Clin Exp Med*. 2015;8(8):13622-13627. PMCID: PMC4612989",
        "Chen 2015 (Hyperalgesia)": "Chen Y, et al. *Int J Clin Exp Med*. 2015;8(4):5781-5787. PMCID: PMC4483789"
      },
      "procedure": "Elective thyroidectomy"
    },
    {
      "studies": [
        "Yeh 2010",
        "Yeh 2011"
      ],
      "status": "confirmed",
      "adjudication": null,
      "shared": [
        "country of conduct",
        "surgical specialty",
        "modality",
        "publication year within 1"
      ],
      "analysed_n": {
        "Yeh 2010": 63,
        "Yeh 2011": 60
      },
      "arm_n": {
        "Yeh 2010": [
          33,
          30
        ],
        "Yeh 2011": [
          30,
          30
        ]
      },
      "shared_arm_n": [
        30
      ],
      "citations": {
        "Yeh 2010": "Yeh ML, et al. *Int J Nurs Stud*. 2011;48(6):703-709. DOI: 10.1016/j.ijnurstu.2010.10.009. PMID: 21084087",
        "Yeh 2011": "Yeh ML, et al. *Altern Ther Health Med*. 2010;16(6):10-18. PMID: 21280458"
      },
      "procedure": "Patients undergoing surgery for nontraumatic lumbar spine injury/disorders"
    }
  ],
  "attribution_conflicts": [
    {
      "studies": [
        "Yeh 2010",
        "Yeh 2011"
      ],
      "summary": "Each row carries one paper's arm-level data and the other paper's citation.",
      "papers": [
        {
          "label": "Altern Ther Health Med 2010;16(6):10-18",
          "pdf": "015_PainATHM-2.pdf",
          "pmid": "21280458",
          "authors": "Yeh, Chung, Chen K-M, Tsou M-Y, Chen H-H (five authors, includes Tsou)",
          "setting": "orthopedic departments of a 4000-bed medical center in northern Taiwan",
          "arms": "EG1 33 / EG2 30 / CG 31",
          "female": "EG1 22/33 (66.7%), EG2 21/30 (70.0%), CG 15/31 (48.4%)",
          "cohort_statement": "Ninety-nine patients undergoing lumbar spinal surgery were randomly assigned to one of three groups"
        },
        {
          "label": "Int J Nurs Stud 2011;48(6):703-709",
          "pdf": "covidence_828_full_article.pdf",
          "pmid": "21084087",
          "doi": "10.1016/j.ijnurstu.2010.10.009",
          "authors": "Yeh, Chung, Chen K-M, Chen H-H (four authors, no Tsou)",
          "setting": "3000-bed medical center in northern Taiwan",
          "arms": "AES 30 / Sham 30 / Control 30",
          "female": "AES 20/30 (66.7%), Sham 21/30 (70.0%), Control 15/30 (50.0%)",
          "cohort_statement": "Assessed for eligibility (n=99) ... Meet inclusion criteria (n=90) ... Randomized 30 / 30 / 30"
        }
      ],
      "evidence": [
        "Register row Yeh 2010 holds arm denominators 33 / 30 and cites Int J Nurs Stud 2011 (DOI 10.1016/j.ijnurstu.2010.10.009, PMID 21084087). 33 / 30 are the Altern Ther Health Med figures; Int J Nurs Stud reports 30 in every arm.",
        "Register row Yeh 2011 holds arm denominators 30 / 30 and cites Altern Ther Health Med 2010 (PMID 21280458). 30 / 30 are the Int J Nurs Stud figures; Altern Ther Health Med reports EG1 = 33.",
        "The same inversion shows inside each row without opening either PDF: Yeh 2010 records arm1_n = 33 beside a female count of 20/30, and Yeh 2011 records arm1_n = 30 beside a female count of 22/33. Each female fraction is internally consistent with the OTHER row's arm denominator.",
        "The arm denominators, not the citations, are the values that trace to the lock: Outcome_Data_AF_LOCK holds analysed 33/30 and 33/31 under Yeh 2010, and randomised and analysed 30/30 under Yeh 2011.",
        "The original extraction records agree with the lock and with the publication years: yeh_2010_spinal_aes_full_data_extraction.md is headed “Yeh et al. 2010 ... Alternative Therapies in Health and Medicine 2010;16(6):10-18” from 015_PainATHM-2.pdf, and yeh_2011_covidence_828_full_data_extraction.md is headed “Yeh et al. 2011 (Study #828) ... International Journal of Nursing Studies 2011;48:703-709”.",
        "99_audit/consensus_audit_master_log.md line 127 labels Covidence #828 — the Int J Nurs Stud paper — as “Yeh 2010”, which is the likely origin of the inverted citation and is why it propagated into dashboard/data.js."
      ],
      "affects": "Bibliographic attribution, the source-PDF pointer, the country-of-conduct evidence sentence, and one female count per row. No effect estimate, risk-of-bias judgement or GRADE rating reads any of these, and neither report contributes arm-level data to any synthesis.",
      "not_affected": "The arm denominators themselves. They match the locked workbook and each matches a real paper; nothing here suggests the lock is wrong.",
      "decision_needed": "Two ways to make the rows self-consistent, and they are not equivalent. (a) Move the citations, so each row keeps the arm data it has and gains the matching paper — the register keys then also match the publication years, and the locked workbook is untouched. (b) Move the arm data, which would mean re-cutting Outcome_Data_AF_LOCK. Option (a) leaves the lock alone and is the smaller change, but it contradicts the audit log, so the review team decides.",
      "superseded_finding": "A first pass on 2026-09-12 recorded this as transposed arm denominators and named the arm Ns as the defective field. That reading was wrong: the arm Ns trace to the lock and to real papers. Recorded here so the earlier wording is not mistaken for a separate, still-open issue."
    }
  ],
  "denominator_mismatches": [
    {
      "study": "El-Rakshy 2009",
      "arm": "arm1",
      "arm_name": "EA Group",
      "female": "42/44 (95.5%)",
      "female_denominator": 44,
      "analysed_n": 42,
      "randomised_n": null,
      "explained_by_randomised": false
    },
    {
      "study": "El-Rakshy 2009",
      "arm": "arm2",
      "arm_name": "Usual Care Group",
      "female": "50/58 (86.2%)",
      "female_denominator": 58,
      "analysed_n": 53,
      "randomised_n": null,
      "explained_by_randomised": false
    },
    {
      "study": "Yeh 2010",
      "arm": "arm1",
      "arm_name": "EA Group",
      "female": "20/30 (66.7%)",
      "female_denominator": 30,
      "analysed_n": 33,
      "randomised_n": null,
      "explained_by_randomised": false
    },
    {
      "study": "Lee 2011",
      "arm": "arm1",
      "arm_name": "TEAS Group",
      "female": "20/20 (100%)",
      "female_denominator": 20,
      "analysed_n": 12,
      "randomised_n": 12,
      "explained_by_randomised": false
    },
    {
      "study": "Lee 2011",
      "arm": "arm2",
      "arm_name": "Sham Group",
      "female": "20/20 (100%)",
      "female_denominator": 20,
      "analysed_n": 12,
      "randomised_n": 12,
      "explained_by_randomised": false
    },
    {
      "study": "Yeh 2011",
      "arm": "arm1",
      "arm_name": "EA Group",
      "female": "22/33 (66.7%)",
      "female_denominator": 33,
      "analysed_n": 30,
      "randomised_n": 30,
      "explained_by_randomised": false
    },
    {
      "study": "Grech 2016",
      "arm": "arm1",
      "arm_name": "EA Group",
      "female": "9/20 (45.0%)",
      "female_denominator": 20,
      "analysed_n": 11,
      "randomised_n": 11,
      "explained_by_randomised": false
    },
    {
      "study": "Gu 2019",
      "arm": "arm1",
      "arm_name": "TEAS Group",
      "female": "30/59 (50.8%)",
      "female_denominator": 59,
      "analysed_n": 58,
      "randomised_n": 60,
      "explained_by_randomised": false
    },
    {
      "study": "Gu 2019",
      "arm": "arm2",
      "arm_name": "Sham Group",
      "female": "27/58 (46.6%)",
      "female_denominator": 58,
      "analysed_n": 59,
      "randomised_n": 60,
      "explained_by_randomised": false
    },
    {
      "study": "He 2026 (hepatectomy/JIS)",
      "arm": "arm1",
      "arm_name": "TEAS Group",
      "female": "9/43 (20.9%)",
      "female_denominator": 43,
      "analysed_n": 80,
      "randomised_n": 81,
      "explained_by_randomised": false
    },
    {
      "study": "He 2026 (hepatectomy/JIS)",
      "arm": "arm2",
      "arm_name": "Sham Group",
      "female": "10/43 (23.3%)",
      "female_denominator": 43,
      "analysed_n": 79,
      "randomised_n": 80,
      "explained_by_randomised": false
    }
  ],
  "cohort_size_disagreements": [
    {
      "studies": [
        "Yeh 2010",
        "Yeh 2011"
      ],
      "summary": "The two reports of this trial state different cohort sizes.",
      "detail": "Int J Nurs Stud 2011 shows 99 assessed for eligibility, 90 meeting inclusion criteria, and randomisation to 30 / 30 / 30. Altern Ther Health Med 2010 states \"Ninety-nine patients undergoing lumbar spinal surgery were randomly assigned to one of three groups\" with group sizes 33 / 30 / 31. Whether 90 or 99 were randomised cannot be settled from the two papers, so neither figure is used as the trial's randomised N. Stated by paper rather than by register key, because which key names which paper is itself in question — see the attribution conflict above.",
      "affects": "Descriptive participant totals only. Neither report contributes arm-level data to any synthesis, so no effect estimate depends on this."
    }
  ],
  "participants": {
    "analysed_across_reports": 10678,
    "analysed_across_studies": 10618,
    "deduplicated_by": [
      "Yeh 2011"
    ],
    "randomised_contrast_recorded": [
      "Grech 2016",
      "Gu 2019",
      "He 2026 (hepatectomy/JIS)",
      "Lee 2011"
    ],
    "randomised_whole_trial_recorded": [
      "Chen 2020",
      "Coura 2011",
      "He 2026 (breast/WJCO)",
      "Jin 2023",
      "Lee 2011",
      "Liu 2021",
      "Lu 2021",
      "Ma 2026",
      "Ntritsou 2014",
      "Wu 2025",
      "Yang 2020",
      "Yao 2015",
      "Zheng 2025",
      "Zhu 2022"
    ],
    "randomised_any_channel": [
      "Chen 2020",
      "Coura 2011",
      "Grech 2016",
      "Gu 2019",
      "He 2026 (breast/WJCO)",
      "He 2026 (hepatectomy/JIS)",
      "Jin 2023",
      "Lee 2011",
      "Liu 2021",
      "Lu 2021",
      "Ma 2026",
      "Ntritsou 2014",
      "Wu 2025",
      "Yang 2020",
      "Yao 2015",
      "Zheng 2025",
      "Zhu 2022"
    ],
    "randomised_total_publishable": false,
    "randomised_total_reason": "The register records a randomised denominator for the pairwise contrast in 4 of the 69 studies, and the source-PDF extraction records a whole-trial randomised N in 14. The two are different quantities and are not additive, and neither covers the review. A review-wide randomised participant total is therefore not reported; the analysed total is."
  }
};
