// Generated by scripts/build_eligibility_reconciliation.py; do not edit.
// The dedicated eligibility reconciliation pass for the seven post-lock
// additions. Assigns a disposition per study-outcome; pools nothing.
window.ELIGIBILITY_RECONCILIATION = {
  "generated_by": "scripts/build_eligibility_reconciliation.py",
  "pass_date": "2026-09-12",
  "scope": "the seven studies added to the register after the v26 lock",
  "studies": [
    "Gao 2022",
    "Liu 2015",
    "Oztas 2019",
    "Song 2020",
    "Szmit 2021",
    "Wu 2016",
    "Zhang 2018"
  ],
  "pools_nothing": true,
  "rows": [
    {
      "study": "Szmit 2021",
      "outcome": "opioid_24h",
      "target": "Primary 0-24 h opioid",
      "disposition": "admitted",
      "changed": false,
      "rule": "Admitted before this pass; recorded here so all seven are accounted for.",
      "evidence": "Contributes to the strict primary 24-h opioid analysis and the Target D nausea 0-24 h stratum."
    },
    {
      "study": "Zhang 2018",
      "outcome": "flatus_time",
      "target": "Target E (time to first flatus)",
      "disposition": "admitted",
      "changed": true,
      "admitted_on": "2026-09-12",
      "rule": "Target E takes time-to-event flatus with no clock-window requirement; its six members carry time_window 'Postoperative' or 'From surgery to first ...'.",
      "evidence": "Unblocked 2026-09-12 by formal vector digitisation of Figure 2a: TEA 51.33 +/- 2.78 SE vs sham-TEA 80.05 +/- 4.40 SE hours, n=21 per arm (SD 12.74 vs 20.15). The extraction reproduces all seven percentage reductions the paper reports, this one to 0.02 pp. See 07_TIERED_V33/03_DIGITIZATION/figure_only_values_QC_2026-09-12.md.",
      "unblocks": "ADMITTED 2026-09-12 by review-team decision. Consequence recorded: the Target E mean-difference model moves from -2.00 h [-3.14, -0.87], p=0.006, I2=0.0% (k=6) to -6.79 h [-14.84, +1.27], p=0.085, I2=97.3% (k=7). The standardised model survives at -0.55 [-0.88, -0.22], p=0.007. The heterogeneity is clinically interpretable -- this trial is open abdominal GI-cancer surgery with flatus at 51-80 h against a mostly laparoscopic set at 14-42 h -- but an I2 of 97% makes the pooled MD hard to interpret."
    },
    {
      "study": "Zhang 2018",
      "outcome": "pain_rest_24h",
      "target": "Target C (pain at rest ~24 h)",
      "disposition": "scope_mismatch",
      "changed": true,
      "rule": "Target C takes clock-defined 24-hour endpoints. Both current members carry time_window exactly '24 h'. A day label is not a clock-defined window -- the same rule already excluded Liu 2015's POD 1 PONV from Target D.",
      "evidence": "The value is now digitised and the panel validates at POD 2 (0.10 pp) and POD 3 (0.54 pp), so the data are sound. The timepoint is not: it is POD 1, and the paper states treatment ran 'daily from POD 1 to POD 3', so the POD 1 score falls on the first treatment day with no statement of whether it precedes or follows the sessions. Consistent with that, the digitised POD 1 values show TEA slightly WORSE than sham (3.96 vs 3.77) and the paper reports reductions only from POD 2.",
      "unblocks": "Rescoping Target C to accept day-labelled endpoints -- which would also reopen Liu 2015. Not recommended by this pass."
    },
    {
      "study": "Song 2020",
      "outcome": "pain_rest_24h",
      "target": "Target C (pain at rest ~24 h)",
      "disposition": "admitted",
      "changed": true,
      "admitted_on": "2026-09-12",
      "rule": "A qc_hold is resolved by reading the source. The hold was 'pending resolution of the ITT (85) vs per-protocol (78) denominator inconsistency'.",
      "evidence": "There is no inconsistency. The paper defines both populations and reconciles them exactly: 109 assessed, 15 ineligible, 9 refused, 85 enrolled; 'we included 85 patients in the ITT population and 78 in the PP population (three patients were allergic to TEAS, two patients were transferred to the intensive care unit after surgery, and two patients removal of the drainage tube was delayed)' -- 3+2+2 = 7, and 85-7 = 78. It also names the primary: 'All analyses were based on the intention-to-treat (ITT) population'. The register's 42/43 = 85 is that ITT population. The comparator is a true sham ('The control group also underwent this sham treatment'). The outcome itself is a clean 24-h VAS, 2.76+/-1.1 vs 3.23+/-1.1, P=0.053, directly reported.",
      "unblocks": "ADMITTED 2026-09-12. With Gao 2022, Target C moves from -0.18 VAS [-0.68, +0.33], p=0.141 (k=2) to -0.205 VAS [-0.339, -0.070], p=0.017 (k=4) -- newly significant, though -0.2 on a 0-10 VAS is far below any MCID."
    },
    {
      "study": "Song 2020",
      "outcome": "ponv_24h",
      "target": "Target D (PONV 0-24 h)",
      "disposition": "admitted",
      "changed": true,
      "admitted_on": "2026-09-12",
      "rule": "Same qc_hold, same resolution.",
      "evidence": "24-h PONV 3/42 vs 10/43, P=0.039, directly reported events and totals over the ITT population.",
      "unblocks": "ADMITTED 2026-09-12 to the composite PONV 0-24 h stratum."
    },
    {
      "study": "Song 2020",
      "outcome": "intraop_opioid",
      "target": "Target F (intraoperative)",
      "disposition": "scope_mismatch",
      "changed": false,
      "rule": "Target F's intraoperative stratum is scoped to remifentanil mass.",
      "evidence": "Intraoperative sufentanil 18.54+/-2.3 vs 19.09+/-2.7 ug, P=0.322.",
      "unblocks": "Rescoping the stratum to accept other intraoperative opioids."
    },
    {
      "study": "Gao 2022",
      "outcome": "pain_rest_24h",
      "target": "Target C (pain at rest ~24 h)",
      "disposition": "admitted",
      "changed": true,
      "admitted_on": "2026-09-12",
      "rule": "Held because 'patients could not be fully blinded to real stimulation'.",
      "evidence": "The data are not in question: 24-h pain VAS 2.0+/-1.7 vs 2.2+/-1.8, P=0.006, mean/SD directly reported, clean 24-h window, n=1,655.",
      "unblocks": "RULED AND ADMITTED 2026-09-12. The review team accepted this pass's recommendation. The reasoning was: the blocker is a risk-of-bias concern, and this review already has an architecture for those -- result-specific RoB 2 feeding GRADE. Excluding a trial from pooling instead of rating it down is a different instrument, and it is applied inconsistently here: incomplete patient blinding is a limitation shared by every sham-controlled stimulation trial in the review, and the others are pooled. Either the hold should become a RoB 2 Domain 2 judgement, or the same exclusion should be applied to the other sham-controlled trials. Note the consequence before deciding: at n=1,655 this trial would dominate Target C.",
      "caution": "It did dominate: Target C's pooled N rises from 158 to 1,898, and Gao 2022 alone is 1,655 of that. The point estimate barely moved (-0.18 to -0.205); what changed is the confidence interval, which is now driven by this one trial."
    },
    {
      "study": "Gao 2022",
      "outcome": "ponv_24h",
      "target": "Target D (PONV 0-24 h)",
      "disposition": "admitted",
      "changed": true,
      "admitted_on": "2026-09-12",
      "rule": "Same blinding hold.",
      "evidence": "Composite PONV 243/827 vs 283/828, P=0.036; vomiting 86/827 vs 147/828, P<0.001; nausea 18/827 vs 42/828, P=0.003 -- all directly reported.",
      "unblocks": "RULED AND ADMITTED 2026-09-12, same ruling. With Song 2020, the composite PONV 0-24 h stratum moves from RR 0.565 [0.138, 2.320], p=0.123, I2=0.0% (k=2) to RR 0.648 [0.392, 1.071], p=0.071, I2=66.9% (k=4) -- still not significant, with materially more heterogeneity."
    },
    {
      "study": "Gao 2022",
      "outcome": "opioid_24h",
      "target": "Primary 0-24 h opioid",
      "disposition": "derivation_invalid",
      "changed": true,
      "rule": "A median/IQR may be converted only where the normality the Wan et al. estimators assume is tenable.",
      "evidence": "Settled 2026-09-12: 33 (0-50) vs 30 (0-60) ug, and the paper's own preceding row shows only 597/827 and 588/828 patients received an analgesic pump at all, so ~28% used none. That spike at zero is why Q1 = 0 in both arms. The conversion would give 27.67 +/- 37.13 and 30.00 +/- 44.56, placing ~23% of patients below zero micrograms. See 07_TIERED_V33/03_DIGITIZATION/figure_only_values_QC_2026-09-12.md.",
      "unblocks": "Nothing available. The median, IQR and P value stand as source truth."
    },
    {
      "study": "Wu 2016",
      "outcome": "opioid_24h",
      "target": "Primary 0-24 h opioid",
      "disposition": "data_absent",
      "changed": false,
      "rule": "A pooled contrast needs a reported quantity.",
      "evidence": "Rescue IV tramadol demand was lower with TAES (P<0.05) but exact quantities are not reported.",
      "unblocks": "Author contact."
    },
    {
      "study": "Wu 2016",
      "outcome": "pain_rest_24h",
      "target": "Target C (pain at rest ~24 h)",
      "disposition": "data_absent",
      "changed": true,
      "rule": "A digitisation is admissible only if the source reports something independent of the figure to validate it against (the Gu 2019 standard).",
      "evidence": "Settled 2026-09-12: the paper reports no VAS number anywhere in its text. Checked mechanically -- 27 'mean +/- SD' patterns appear in the paper, none within 200 characters of a pain mention. See 07_TIERED_V33/03_DIGITIZATION/figure_only_values_QC_2026-09-12.md.",
      "unblocks": "Author contact."
    },
    {
      "study": "Wu 2016",
      "outcome": "ponv_24h",
      "target": "Target D (PONV)",
      "disposition": "scope_mismatch",
      "changed": false,
      "rule": "A Target D stratum is defined by its ascertainment window.",
      "evidence": "Nausea/vomiting 3/27 vs 8/27 vs 9/27 are reported, but the postoperative ascertainment window is not stated, so the row cannot be assigned to the 0-24 h or 0-48 h stratum.",
      "unblocks": "Author contact for the window."
    },
    {
      "study": "Liu 2015",
      "outcome": "opioid_24h",
      "target": "Primary 0-24 h opioid",
      "disposition": "data_absent",
      "changed": false,
      "rule": "A pooled contrast needs a reported quantity.",
      "evidence": "PCIA composition and rate are given, but cumulative 0-24 h total/bolus use is not reported.",
      "unblocks": "Author contact."
    },
    {
      "study": "Liu 2015",
      "outcome": "pain_rest_24h",
      "target": "Target C (pain at rest ~24 h)",
      "disposition": "data_absent",
      "changed": true,
      "rule": "Same Gu 2019 standard.",
      "evidence": "Settled 2026-09-12: 34 'mean +/- SD' patterns in the paper, none within 200 characters of a pain mention. See 07_TIERED_V33/03_DIGITIZATION/figure_only_values_QC_2026-09-12.md.",
      "unblocks": "Author contact."
    },
    {
      "study": "Liu 2015",
      "outcome": "ponv_24h",
      "target": "Target D (PONV 0-24 h)",
      "disposition": "scope_mismatch",
      "changed": false,
      "rule": "Target D strata are clock-defined; POD 1 is a day label.",
      "evidence": "POD1 nausea 11/44 vs 9/44; vomiting 9/44 vs 8/44.",
      "unblocks": "Rescoping Target D -- which would also reopen Zhang 2018's POD 1 pain."
    },
    {
      "study": "Liu 2015",
      "outcome": "intraop_opioid",
      "target": "Target F (intraoperative)",
      "disposition": "scope_mismatch",
      "changed": false,
      "rule": "Target F's intraoperative stratum is scoped to remifentanil mass.",
      "evidence": "Total intraoperative sufentanil 95.6+/-21.76 vs 117.7+/-37.95 ug, P=0.02.",
      "unblocks": "Rescoping the stratum."
    },
    {
      "study": "Oztas 2019",
      "outcome": "opioid_24h",
      "target": "Primary 0-24 h opioid",
      "disposition": "derivation_invalid",
      "changed": false,
      "rule": "An MME pool needs a sourced equianalgesic ratio; the review forbids inventing one.",
      "evidence": "0-24 h IV PCA tramadol 228.40+/-87.89 vs 357.81+/-123.70 mg is reported, but no sourced parenteral tramadol:morphine ratio was located (searched 2026-09-07 against this project's equianalgesic reference family).",
      "unblocks": "Locating a citable parenteral tramadol:morphine ratio. This is the one blocker in the set that a literature search rather than an author could lift."
    },
    {
      "study": "Oztas 2019",
      "outcome": "pain_rest_24h",
      "target": "Target C (pain at rest ~24 h)",
      "disposition": "scope_mismatch",
      "changed": false,
      "rule": "Target C takes ~24-hour endpoints.",
      "evidence": "Resting pain 3.00+/-1.30 vs 4.88+/-1.78 was assessed after the 22-h intervention rather than at a clean ~24 h timepoint; overall RoB is High.",
      "unblocks": "Nothing clean; the measurement is tied to the intervention's end, not a clock."
    },
    {
      "study": "Oztas 2019",
      "outcome": "ponv_24h",
      "target": "Target D (PONV)",
      "disposition": "data_absent",
      "changed": false,
      "rule": "A pooled contrast needs reported group values.",
      "evidence": "Exact group values for nausea/vomiting were not reported.",
      "unblocks": "Author contact."
    }
  ],
  "tally": {
    "admitted": 6,
    "data_absent": 5,
    "derivation_invalid": 2,
    "scope_mismatch": 6
  },
  "newly_eligible": [],
  "needs_rule_decision": []
};
