// GENERATED by scripts/build_limitations.py -- do not hand-edit.
// Every entry is derived from a live analysis output; see each item's `where`.
window.LIMITATIONS = {
  "generated_by": "scripts/build_limitations.py",
  "disclaimer": "Assembled from this review's own outputs. Every limitation below is derived from a live analysis file and carries the figures that justify it; none is asserted without evidence, and a category that found nothing is omitted rather than padded.",
  "reported_analyses": 22,
  "limitations": [
    {
      "domain": "Heterogeneity",
      "title": "Considerable between-study heterogeneity in 12 of 22 reported analyses",
      "detail": "Pooled estimates in these analyses describe a distribution of effects rather than one common effect, so a single summary number understates how much the result varies between surgical populations, stimulation protocols and anaesthetic techniques.",
      "evidence": "I² ≥ 75% in 12 analyses; highest is I² = 98.6% in Primary 0–24 h opioid — TEAS vs sham.",
      "where": "Each analysis's forest plot and heterogeneity statistics",
      "affects": [
        "gi_first_flatus_TEAS_Sham",
        "gi_first_flatus_EA_Usual_care",
        "pain_vas_24h_TEAS_Sham",
        "v34_intraop_remifentanil_TEAS_Sham",
        "v34_intraop_sufentanil_TEAS_Sham",
        "v34_qor40_24h_TEAS_Sham",
        "v34_primary_24h_mme_TEAS_Sham",
        "v34_primary_24h_mme_EA_Usual_care",
        "v34_primary_24h_mme_ALL_AUDIT",
        "AN-01-SMD",
        "AN-02-TARGET-A",
        "AN-08-TARGET-F-REMI"
      ],
      "metric": {
        "key": "heterogeneity",
        "count": 12,
        "of": 22
      }
    },
    {
      "domain": "Sparse evidence",
      "title": "12 of 22 reported analyses rest on 3 or fewer trials",
      "detail": "With this few contributing trials, between-study variance is estimated imprecisely, subgroup and moderator analysis is not informative, and a single additional trial could move the estimate materially.",
      "evidence": "k = 1 in 1 analysis; k = 2 in 5 analyses; k = 3 in 6 analyses.",
      "where": "Per-analysis k, and the derivability audit explaining why k is small",
      "affects": [
        "gi_first_flatus_EA_Usual_care",
        "gi_first_bowel_sounds_TEAS_Sham",
        "pain_vas_24h_TEAS_Sham",
        "ponv_24h_TEAS_Sham",
        "v34_intraop_sufentanil_TEAS_Sham",
        "v34_qor40_24h_TEAS_Sham",
        "v34_gi_first_defecation_TEAS_Sham",
        "v34_gi_first_defecation_EA_Usual_care",
        "v34_primary_24h_mme_EA_Usual_care",
        "AN-02-TARGET-A",
        "AN-03-TARGET-B",
        "AN-06-TARGET-D-48"
      ],
      "metric": {
        "key": "sparse",
        "count": 12,
        "of": 22
      }
    },
    {
      "domain": "Imprecision",
      "title": "The confidence interval includes no effect in 15 of 22 reported analyses",
      "detail": "These analyses are compatible with benefit, no difference and — within the interval — harm. They do not establish absence of an effect either; they are inconclusive at the precision this evidence base supports.",
      "evidence": "15 of 22 intervals span the null value for their measure (0 for differences and log-ratios, 1 for ratios).",
      "where": "Each analysis's confidence interval and prediction interval",
      "affects": [
        "gi_first_flatus_EA_Usual_care",
        "pain_vas_24h_TEAS_Sham",
        "ponv_24h_TEAS_Sham",
        "v34_intraop_remifentanil_TEAS_Sham",
        "v34_intraop_sufentanil_TEAS_Sham",
        "v34_qor40_24h_TEAS_Sham",
        "v34_gi_first_defecation_TEAS_Sham",
        "v34_primary_24h_mme_TEAS_Sham",
        "v34_primary_24h_mme_EA_Usual_care",
        "v34_primary_24h_mme_ALL_AUDIT",
        "AN-01-SMD",
        "AN-02-TARGET-A",
        "AN-03-TARGET-B",
        "AN-05-TARGET-D-24",
        "AN-06-TARGET-D-48"
      ],
      "metric": {
        "key": "imprecision",
        "count": 15,
        "of": 22
      }
    },
    {
      "domain": "Risk of bias",
      "title": "12 reported analyses include at least one result at high risk of bias",
      "detail": "Where a high-risk result contributes, the pooled estimate inherits that risk. Leave-one-out results are available for each affected analysis and should be read alongside the main estimate.",
      "evidence": "12 of 22 reported analyses. Most affected: Time to first flatus — EA vs usual care (2 of 2); Pain VAS at 24 h — TEAS vs sham (2 of 3); Time to first defecation — EA vs usual care (2 of 3); and 9 further analyses with at least one.",
      "where": "Result-specific RoB 2 panel and the model rollup",
      "affects": [
        "gi_first_flatus_EA_Usual_care",
        "pain_vas_24h_TEAS_Sham",
        "v34_intraop_remifentanil_TEAS_Sham",
        "v34_qor40_24h_TEAS_Sham",
        "v34_gi_first_defecation_EA_Usual_care",
        "v34_primary_24h_mme_EA_Usual_care",
        "v34_primary_24h_mme_ALL_AUDIT",
        "AN-01-SMD",
        "AN-04-TARGET-C",
        "AN-06-TARGET-D-48",
        "AN-07-TARGET-E",
        "AN-09-TARGET-F-RESCUE"
      ],
      "metric": {
        "key": "rob",
        "count": 12,
        "of": 22
      }
    },
    {
      "domain": "Certainty of evidence",
      "title": "17 of 22 GRADE-rated analyses are Low or Very Low certainty",
      "detail": "The true effect may differ substantially from the estimate in these analyses. Conclusions drawn from them should be phrased as what the evidence is compatible with, not as what it establishes.",
      "evidence": "Very Low: 8, Low: 9, Moderate: 5.",
      "where": "GRADE Summary of Findings, with the downgrade reasons for each rating",
      "affects": [],
      "metric": {
        "key": "low_certainty",
        "count": 17,
        "of": 22
      }
    },
    {
      "domain": "Publication and reporting bias",
      "title": "Small-study effects could not be assessed for any analysis",
      "detail": "Funnel-plot asymmetry tests are uninformative below about 10 contributing studies, so this review cannot exclude publication bias, selective outcome reporting or small-study effects by statistical means for any of its analyses.",
      "evidence": "Every reported analysis has k < 10 (largest k = 7); Cochrane Handbook 13.3.5.4.",
      "where": "Per-analysis k",
      "affects": [],
      "metric": null
    },
    {
      "domain": "Outcome reporting in the source trials",
      "title": "Most trials reporting a 0–24 h opioid outcome cannot contribute to it",
      "detail": "Trials report this outcome in units, distributions and windows that cannot be converted to a common absolute scale — weight-normalised doses, medians without dispersion, graph-only values, drugs with no sourced equivalence factor. This is a limitation of the primary literature, not of the search.",
      "evidence": "Of 93 audited 0–24 h opioid contrasts, 10 are directly poolable in absolute morphine equivalents (Tier A); the remainder fall into Tier B+C (1), Tier C (1), Tier D (1), Tier E (12), Tier F (68).",
      "where": "Derivability audit (Tiers A–F) on the primary-outcome pathway",
      "affects": [],
      "metric": null
    },
    {
      "domain": "Outcome reporting in the source trials",
      "title": "No sham-controlled electroacupuncture trial reports 0–24 h opioid use in absolute morphine equivalents",
      "detail": "For this comparison the review has no estimate on the pre-specified scale at all. A scale-free standardized synthesis is reported instead, as an exploratory secondary result; it answers a different question and carries no certainty rating.",
      "evidence": "k = 0 for the absolute-MME estimand in this stratum; 4 exploratory standardized analyses are reported in its place.",
      "where": "Tier E exploratory scale-free SMD synthesis",
      "affects": [
        "V33_TIERE_EA_SHAM_SMD",
        "V33_TIERE_TEAS_SHAM_SMD_MAIN",
        "V33_TIERE_TEAS_SHAM_SMD_SENS",
        "V33_TIERE_TEAS_USUAL_SMD"
      ],
      "metric": null
    },
    {
      "domain": "Opioid dose conversion",
      "title": "Pooled doses depend on equianalgesic conversion factors",
      "detail": "Converting different opioids to a common morphine-equivalent scale is itself an assumption. One factor in this review was found wrong and corrected during the audit, and the pooled estimate is sensitive to that choice; a prespecified sensitivity analysis quantifies the dependence.",
      "evidence": "3 contrast(s) required a corrected equianalgesic factor (Sufentanil); 4 contrast(s) could not be converted to absolute morphine equivalents at all. Every factor is recorded with its source and status in the conversion audit.",
      "where": "Opioid conversion audit and the conversion sensitivity analysis",
      "affects": [],
      "metric": null
    },
    {
      "domain": "Source data quality",
      "title": "3 analyses contain a result whose source problem only the trial authors or a registry could settle",
      "detail": "These are documented source-level problems — irreconcilable denominators, figure-only values, unreported units — not analytical choices. They are carried as open flags rather than resolved by assumption.",
      "evidence": "Affected trials: El-Rakshy 2009, Zheng 2025. Each is carried as an open source-QC flag on the 3 analyses it contributes to.",
      "where": "Author outreach roster and the per-analysis source-QC flags",
      "affects": [
        "gi_first_flatus_TEAS_Sham",
        "v34_primary_24h_mme_EA_Usual_care",
        "v34_primary_24h_mme_ALL_AUDIT"
      ],
      "metric": null
    },
    {
      "domain": "Selective reporting within this review",
      "title": "8 analyses were computed and are not reported as findings",
      "detail": "Each is listed with the reason it is not carried forward — a component of a reported composite, a single trial, an inclusion variant, or no adopted certainty. They are disclosed so the review cannot be read as having reported only its favourable analyses.",
      "evidence": "8 analyses, none carrying a GRADE certainty rating.",
      "where": "“Analyses computed but not reported as findings — and why”",
      "affects": [],
      "metric": null
    },
    {
      "domain": "Open questions at time of writing",
      "title": "2 post-lock questions remain open",
      "detail": "These are recorded rather than resolved by assumption. None changes a reported estimate; each is a classification or labelling question awaiting a review-team decision.",
      "evidence": "Szmit 2021: Nausea window is 24-h-bounded but not explicitly 0–24 h; Stratum label incomplete in a v26 results file.",
      "where": "Post-lock errata register",
      "affects": [],
      "metric": null
    },
    {
      "domain": "Generalisability",
      "title": "55 of the 69 trials (80%) were conducted in China",
      "detail": "Acupoint-stimulation practice, perioperative opioid prescribing and usual-care comparators all differ between health systems, so an evidence base drawn 80% from one country constrains how far these estimates transfer. 7 of the 11 countries contribute a single trial each, so no second setting is represented strongly enough to test whether the effect holds outside China. This is recorded as a property of the evidence base; whether it warrants a GRADE indirectness downgrade is a review-team judgement and indirectness is currently not downgraded for any rated model.",
      "evidence": "Country of conduct over unique trials: China 55; Taiwan 3; USA 2; Hong Kong 2; Singapore 1; UK 1; Brazil 1; Greece 1; Malaysia 1; Poland 1; Turkey 1. 19 of 69 carry the verbatim source sentence the country was read from; the rest are register values the source-PDF affiliation scan agrees with. Five were corrected on 2026-09-12 (Chen 1998 USA, Lin 2002 Taiwan, El-Rakshy 2009 UK, Ntritsou 2014 Greece, Grech 2016 USA), before which this read 8 countries with China at 87%.",
      "where": "Population Characteristics - Geographic distribution, in the Study Explorer",
      "affects": [],
      "metric": {
        "key": "geographic_concentration",
        "count": 55,
        "share_pct": 79.7,
        "countries": 11
      }
    }
  ],
  "deferred": [
    {
      "title": "Risk-of-bias assessor process",
      "why": "Independent dual assessment of the strict-primary trials is in progress. Recording it here as a settled limitation would contradict work that is still underway; it belongs in this section once that process concludes."
    }
  ]
};
