// Generated by scripts/build_reference_data.py; do not edit.
window.META_OUTCOMES = [
  "flatus_time",
  "intraop_opioid",
  "opioid_24h",
  "opioid_48h",
  "opioid_72h",
  "pain_rest_24h",
  "ponv_24h",
  "rescue_analgesia"
];
