// Generated by scripts/extract_baseline_from_pdfs.py; do not edit.
// Every value carries the source PDF, page and verbatim quote it came from.
window.PDF_EXTRACTED = {
  "#105119 - Zhou 2025": {
    "randomised_n": {
      "value": 100,
      "page": 5,
      "quote": "Consequently, 100 patients were successfully enrolled and subsequently randomized into two distinct groups: the TEAS group (n=50) and the Sham group (n=50).",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "Eligibility screening was conducted for patients scheduled to undergo elective gynecological laparoscopic surgery under general anesthesia.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "Department of Anesthesiology, The Second Affiliated Hospital of Guilin Medical University, Guilin, People’s Republic of China *These authors contributed equally to this work Correspondence: Xu Zhang, Department of Anesthesiology, The Second Affiliated Hospital of Guilin Medical University, No.",
      "hits": 1
    },
    "surgical_population": {
      "value": "laparoscopic gynecological surgery",
      "page": 1,
      "quote": "study investigated the impact of TEAS during the post-anesthesia recovery period on postoperative recovery quality in patients undergoing laparoscopic gynecological surgery. Patients and Methods: In this single-center, randomized, double-blinded, sham-controlled trial, 100 patients undergoing electi",
      "hits": 1
    },
    "source_pdf": "105119.pdf"
  },
  "An 2014": {
    "randomised_n_derived": {
      "value": 88,
      "page": 3,
      "quote": "Patients were randomly allocated into 2 groups using a computer-generated randomized number table; Group C was a control group that did not receive EA during the operation ( n ¼ 43) and Group A was the experimental group that received EA ( n ¼ 45). Acupuncture We collaborated with an acupuncturist f",
      "derivation": "43 + 45",
      "hits": 2
    },
    "arms": {
      "value": 2,
      "page": 3,
      "quote": "Patients were randomly allocated into 2 groups using a computer-generated randomized number table; Group C was a control group that did not receive EA during the operation ( n ¼ 43) and Group A was the experimental group that received EA ( n ¼ 45). Acupuncture We collaborated with an acupuncturist f",
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "*Department of Anesthesia , Beijing Tiantan Hospital Capital Medical University , Beijing 100050 , China †Department of Anesthesia , Beijing Jishuitan Hospital Beijing 100035 , China ‡Department of Acupuncture Beijing University of Traditional Chinese Medicine Beijing 100029 , China §Department of E",
      "hits": 4
    },
    "surgical_population": {
      "value": "a Supratentorial Craniotomy\nLi-Xin A",
      "page": 1,
      "quote": "Pain and Improves Recovery in Patients Undergoing a Supratentorial Craniotomy Li-Xin An, * Xue Chen, † Xiu-Jun Ren ‡ and Hai-Feng Wu § *Department of Anesthesia , Beijing Tiantan Hospital Capital Medical University , Beijing 100050 , China †Department of Anesthesia , Beijing Jishuitan Hospital Beiji",
      "hits": 1
    },
    "source_pdf": "covidence_698_full_article.pdf"
  },
  "Ao 2021": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "General anesthesia was induced using intravenous sufentanil (0.3‑0.5 µg/kg; cat.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "2Department of Anesthesiology, Tangshan People's Hospital and Tangshan Cancer Hospital, North China University of Science and Technology, Tangshan, Hebei 063000; 3Department of Anesthesiology, Second Hospital of Hebei Medical University, Shijiazhuang, Hebei 050000, China Received February 29, 2020; ",
      "hits": 6
    },
    "surgical_population": {
      "value": "radical mastectomy",
      "page": 1,
      "quote": "function in patients undergoing radical mastectomy.",
      "hits": 1
    },
    "source_pdf": "download.pdf"
  },
  "Chen 1998": {
    "surgical_population": {
      "value": "total abdominal hysterectomy or myo- \nmectomy procedures with a standar",
      "page": 1,
      "quote": "women undergoing total abdominal hysterectomy or myo- mectomy procedures with a standardized general anesthe sia were randomly assigned to one of four postoperative an- algesic treatment regimens (n = 25 each): Group I = sham- TENS (no electrical current) at the Zusanli (ST36) acupoints, Group II = ",
      "hits": 1
    },
    "source_pdf": "covidence_969_chen_1998.pdf"
  },
  "Chen 2015": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "General anesthesia was induced with intravenous sufentanil 0.5 μg/kg and propofol 2.0 mg/kg.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Anesthesiology, The Shengli Clinical Medicial College of Fujian Medical University, Fujian Provincial Hospital, Fuzhou 350001, China; 2Department of Anesthesiology, People’s Hospital Affiliated to Fujian University of Traditional Chinese Medicine, Fuzhou 350122, China.",
      "hits": 2
    },
    "surgical_population": {
      "value": "thyroidectomy were randomly allocated to TEAS or control groups",
      "page": 1,
      "quote": "or II patients undergoing thyroidectomy were randomly allocated to TEAS or control groups.",
      "hits": 1
    },
    "source_pdf": "037_chen_2015_thyroidectomy_lund.pdf"
  },
  "Chen 2015 (Hyperalgesia)": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "scheduled for elective thyroidectomy under general anesthesia from August 2014 to December 2014 at Fujian Provincial Hospital.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "Department of Anesthesiology, The Shengli Clinical Medical College of Fujian Medical University & Fujian Provin- cial Hospital, Fuzhou 350001, China.",
      "hits": 1
    },
    "surgical_population": {
      "value": "thyroidectomy: a randomized controlled trial\nYanqing Chen*",
      "page": 1,
      "quote": "alleviates remifentanil-induced hyperalgesia in patients undergoing thyroidectomy: a randomized controlled trial Yanqing Chen*, Yusheng Yao*, Yihuan Wu, Dongsheng Dai, Qiuyan Zhao, Liangcheng Qiu Department of Anesthesiology, The Shengli Clinical Medical College of Fujian Medical University & Fujian",
      "hits": 1
    },
    "source_pdf": "040_chen_2015_hyperalgesia_lund.pdf"
  },
  "Chen 2020": {
    "randomised_n": {
      "value": 80,
      "page": 1,
      "quote": "Methods: A total of 80 patients were randomized into two groups: the TEAS group and the sham TEAS combined with general anesthesia group.",
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1 Key Laboratory of Carcinogenesis and Translational Research (Ministry of Education, Beijing), Department of Anesthesiology, Peking University Cancer Hospital and Institute, Beijing, China 2 Neuroscience Research Institute and Department of Neurobiology, Peking University and Key Laboratory of Neur",
      "hits": 5
    },
    "surgical_population": {
      "value": "thoracoscopic pulmonary resectio",
      "page": 1,
      "quote": "analgesia in lung cancer patients undergoing thoracoscopic pulmonary resection. Methods: A total of 80 patients were randomized into two groups: the TEAS group and the sham TEAS combined with general anesthesia group.",
      "hits": 1
    },
    "source_pdf": "Thoracic Cancer - 2020 - Chen - Efficacy of transcutaneous electrical acupoint stimulation combined with general anesthesia.pdf"
  },
  "Coura 2011": {
    "randomised_n": {
      "value": 32,
      "page": 1,
      "quote": "The day before the surgery, 32 patients undergoing cardiac surgery were randomised into two groups: patients from the treatment group received preoperative EA at bilateral points (LI4-LI11, LR3-ST36, PC6-TE5) for 30 min with altemating frequencies of 3 and 15 Hz.",
      "hits": 2
    },
    "country": {
      "value": "Brazil",
      "page": 1,
      "quote": "'Centro Hospitalar Unimed, Joinville, Brazil 'Centro de Estudos de Acupuntura do Parana, Curitiba, Brazil Correspondence to Dr Luiz Eduardo Fana Coura, Intensivist and Acupuncturist Member of Intensive Care Therapy at Centro Hospitalar Unimed Joinville, Rua Blumenau 314, Joinville-SC 89204-250, Braz",
      "hits": 4
    },
    "surgical_population": {
      "value": "cardiac surgery were randomised\ninto two groups: patients from the tre",
      "page": 1,
      "quote": "patients undergoing cardiac surgery were randomised into two groups: patients from the treatment group received preoperative EA at bilateral points (LI4-LI11, LR3-ST36, PC6-TE5) for 30 min with altemating frequencies of 3 and 15 Hz.",
      "hits": 1
    },
    "source_pdf": "covidence_819_full_article.pdf"
  },
  "El-Rakshy 2009": {
    "randomised_n_derived": {
      "value": 102,
      "page": 1,
      "quote": "randomised to receive either electroacupuncture (n = 56) or no additional treatment (n = 46) during the operative period.",
      "derivation": "56 + 46",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 4,
      "quote": "In conclusion, acupuncture given under general anaesthesia is unlikely to have a clinically useful effect, but research into preoperative acupuncture is likely to lead to improved patient care. Acknowledgements: This study was submitted in partial fulfilment of the Masters degree in pain management ",
      "is_general": true,
      "hits": 1
    },
    "surgical_population": {
      "value": "laparoscopic cho-\nlecystectomy or abdominal hysterectomy",
      "page": 1,
      "quote": "sedation in patients undergoing laparoscopic cho- lecystectomy or abdominal hysterectomy. METHOD Study design A randomised, double-blind, comparative study was conducted in Scunthorpe & Goole Hospitals. Patients all received patient-controlled analgesia (PCA), either with acupuncture (PCA + acupunc-",
      "hits": 1
    },
    "source_pdf": "covidence_868_full_article.pdf"
  },
  "Gao 2021": {
    "arms": {
      "value": 2,
      "page": 3,
      "quote": "and randomly divided into 2 groups: 307 patients allocated to the sham group and 303 patients to the TEAS group.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "(1) surgery under general anesthesia; (2) age /C21 18 years and American Society of Anesthesiologists I eIII; (3) patients ’ ability to understand and sign the written informed consent form; and (4) not involved in other clinical studies.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "a Department of Anesthesiology and Center for Brain Science, the First Af filiated Hospital of Xi ’an Jiaotong University, Xi ’an, China b Department of Anesthesiology, Weinan Central Hospital, Weinan, China c Department of Anesthesiology, Xi ’an Central Hospital, Xi ’an, China d Department of Anest",
      "hits": 13
    },
    "surgical_population": {
      "value": "lapa-\nroscopic surgery showed a reduction in POI risk",
      "page": 4,
      "quote": "multivariate-unadjusted analysis, patients who underwent lapa- roscopic surgery showed a reduction in POI risk (OR, 0.62, 95% CI 0.44e0.89; P ¼ .009).",
      "hits": 1
    },
    "source_pdf": "covidence_400_full_article.pdf"
  },
  "Gao 2022": {
    "arms": {
      "value": 2,
      "page": 6,
      "quote": "of 1,655 patients were enrolled and randomly divided into two groups: 828 patients allocated to the Sham group and 827 patients to the TEAS group.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "non-gastrointestinal surgery under general anesthesia. Interventions: Patients were randomly allocated into the TEAS and Sham grou p with a 1:1 ratio.",
      "is_general": true,
      "hits": 3
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1 Department of Anesthesiology, Center for Brain Science, Th e First Affiliated Hospital of Xi’an Jiaotong University, Xi’an, China, 2 Department of Anesthesiology, Second Hospital of Shanxi Me dical University, Taiyuan, China, 3 Department of Anesthesiology, The First Affiliated Hospital, College o",
      "hits": 12
    },
    "source_pdf": "pdf-2.pdf"
  },
  "Grech 2016": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "Electroacupuncture under General Anesthesia Improves Postoperative Recovery in a Randomized Trial Dennis Grech 1, Zhifeng Li 2, Patrick Morcillo 2, Evelyne Kalyoussef 3, David D.",
      "is_general": true,
      "hits": 5
    },
    "surgical_population": {
      "value": "thyroid and\nparathyroid surgery randomized in two groups: EA",
      "page": 2,
      "quote": "double-blinded study with 20 patients undergoing thyroid and parathyroid surgery randomized in two groups: EA ( n Z 11) group or sham (control, n Z 9) group.",
      "hits": 1
    },
    "source_pdf": "030_grech_2016_lund.pdf"
  },
  "Gu 2019": {
    "country": {
      "value": "China",
      "page": 1,
      "quote": "a Department of Anesthesiology, Tangshan People ’s Hospital, North China University of Science and Technology, No.",
      "hits": 2
    },
    "surgical_population": {
      "value": "laparoscopic radical gastrectomy were randomly\nassigned into the long",
      "page": 1,
      "quote": "Methods: A total of 120 gastric cancer patients undergoing laparoscopic radical gastrectomy were randomly assigned into the long duration TEAS (L-TEAS) group, or the placebo-control (C-TEAS) group.",
      "hits": 1
    },
    "source_pdf": "covidence_1471_full_article.pdf"
  },
  "Guo 2023": {
    "country": {
      "value": "China",
      "page": 1,
      "quote": "Department of Anesthesiology, The Second Affiliated Hospital of Air Force Medical University, Xi’an, People’s Republic of China ARTICLE INFO Keywords: Transcutaneous electrical acupoint stimulation (TEAS) Postoperative cognitive dysfunction(POCD) Quality of life Lung cancer Older patients ABSTRACT O",
      "hits": 3
    },
    "surgical_population": {
      "value": "thoracoscopic pul -\nmonary resectio",
      "page": 1,
      "quote": "(TEAS) on postoperative cognitive function in older patients who underwent thoracoscopic pul - monary resection.",
      "hits": 1
    },
    "source_pdf": "006_guo_2023.pdf"
  },
  "He 2026 (breast/WJCO)": {
    "randomised_n": {
      "value": 130,
      "page": 1,
      "quote": "A total of 130 patients with breast cancer were randomly divided into EA group (n = 65) and control group (n = 65).",
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "Bi-Mei He, Xiao-Lin Sun, Xiao-Yu Huang, Sen-Sen Zhang, Qing-Xiong Hong, Department of Anesthesiology, The Second Affiliated Hospital of Guangzhou University of Chinese Medicine, Guangzhou 510000, Guangdong Province, China ORCID number: Qing-Xiong Hong 0009-0007-0048-1499. Corresponding author: Qing-",
      "hits": 1
    },
    "surgical_population": {
      "value": "peripheral intravenous",
      "page": 3,
      "quote": "Each patient underwent peripheral intravenous (intravenous injection) cannulation to infuse Ringer’s solution at a rate of 8 mL/kg/hour.",
      "hits": 1
    },
    "source_pdf": "covidence_41_verified.pdf"
  },
  "He 2026 (hepatectomy/JIS)": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "Eligible patients were those who were scheduled for elective hepatectomy under general anesthesia.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 2,
      "quote": "laboratory of a nesthesiology of Ministry of e ducation, Xijing Hospital, f ourth Military Medical university, Xi’an, China; bDepartment of a nesthesiology, the f irst a ffiliated Hospital of Henan university of Chinese Medicine, Zhengzhou Henan, China; cDepartment of a nesthesiology, Qinghai Provin",
      "hits": 7
    },
    "surgical_population": {
      "value": "hepatic resectio",
      "page": 2,
      "quote": "In patients undergoing hepatic resection, PONV may exacerbate hemorrhagic complications and extend hospital stays [ 1].",
      "hits": 1
    },
    "source_pdf": "covidence_25_verified.pdf"
  },
  "Hou 2023": {
    "randomised_n_derived": {
      "value": 74,
      "page": 4,
      "quote": "The participants were randomized into either TEAS (n = 37) or control (n = 37) group in a 1:1 ratio based on a randomization number generated by an independent researcher using IBM®SPSS 25.0 (Armonk, New York USA).",
      "derivation": "37 + 37",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "index monitor (BIS) were placed, general anesthesia was induced with IV sufentanil 0.3–0.5 μg kg\u0000 1 and propofol 0.2–0.3 mg kg\u0000 1.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "a Department of Anesthesiology, The First Affiliated Hospital of USTC, Division of Life Sciences and Medicine, University of Science and Technology of China, China b Department of Anesthesiology, University of Connecticut School of Medicine, Farmington, CT, USA c Department of Kidney Transplantation",
      "hits": 3
    },
    "surgical_population": {
      "value": "nephrectomy",
      "page": 2,
      "quote": "All participants underwent nephrectomy, through laparotomy, performed by the same surgical team in the period from September 2020 to December 2020.",
      "hits": 1
    },
    "source_pdf": "007_hou_2023.pdf"
  },
  "Huang 2017": {
    "arms": {
      "value": 4,
      "page": 1,
      "quote": "experience of TEAS or acupuncture were randomly assigned to four groups: control (con), 2/100, 2, and 100 Hz.",
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1 Department of Anesthesiology, Peking University People’s Hospital, Beijing 100044, China 2 Department of Anesthesiology, Ministry of Health Beijing Hospital, Beijing 100730, China 3 Department of Surgery, Beijing Oasis International Hospital, Beijing 100015, China 4 Department of Anesthesiology, R",
      "hits": 3
    },
    "surgical_population": {
      "value": "pneumonectomy [10–12]",
      "page": 2,
      "quote": "on levels of serum components among patients undergoing pneumonectomy [10–12]. As far as we are aware, the effects of different frequen- cies of TEAS on perioperative anesthetic dosage, recovery, complications, and prognosis among patients undergoing V ATS lobectomy have not been investigated.",
      "hits": 1
    },
    "source_pdf": "covidence_666_full_article.pdf"
  },
  "Huang 2024": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "under general anesthesia during hospitalization without surgical and anesthetic contraindications. We excluded patients who: could not participate due to skin lesions at the planned sites of acupuncture needling; had lower extremity sensory disturbance or abnormality; had severe arrhythmias, heart f",
      "is_general": true,
      "hits": 2
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "3 Guanghua Hospital, Shanghai University of Traditional Chinese Medicine, Shanghai, China 4 Longhua Hospital, Shanghai University of Traditional Chinese Medicine, Shanghai, China †Hai Huang and Kangmin Tang contributed equally to this work and should be considered co-first authors. Corresponding aut",
      "hits": 5
    },
    "surgical_population": {
      "value": "unilateral TKA were assigned to \nthe contralateral EA",
      "page": 1,
      "quote": "Methods: In this parallel, single-blind randomized controlled trial, 114 patients undergoing unilateral TKA were assigned to the contralateral EA (EA on the contralateral side + sham EA on the ipsilateral), ipsilateral EA (EA on the ipsilateral + sham EA on the contralateral side), or sham EA (sham ",
      "hits": 1
    },
    "source_pdf": "covidence_245_full_article.pdf"
  },
  "Huang 2025": {
    "randomised_n_derived": {
      "value": 101,
      "page": 4,
      "quote": "The remaining patients were randomly allocated to the EA arm (n = 51) or the Standard care group (n = 50).",
      "derivation": "51 + 50",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "oophorectomy or salpingectomy under general anesthesia; and willing to provide informed consent and participate in the study. Participants were excluded if they met any of the following criteria: severe cardiac, hepatic, or renal insufficiency; skin infection or nerve da- mage near the experimental ",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Gynaecology, The Affiliated Traditional Chinese Medicine Hospital, Southwest Medical University, Luzhou 646000, Sichuan, China; 2Department of Anesthesiology, The Affiliated Traditional Chinese Medicine Hospital, Southwest Medical University, Luzhou 646000, Sichuan, China Received Nov",
      "hits": 4
    },
    "surgical_population": {
      "value": "screening",
      "page": 4,
      "quote": "after 129 patients underwent screening, 28 were deemed ineligible or declined to partici - pate.",
      "hits": 1
    },
    "source_pdf": "covidence_131_verified.pdf"
  },
  "Jiang 2026": {
    "randomised_n": {
      "value": 614,
      "page": 3,
      "quote": "Ultimately, 614 eligible patients were allocated to the TEAS (n = 308) or sham-TEAS (n = 306) group.",
      "hits": 1,
      "randomisation_quote": "Patients were randomized into the TEAS or sham-TEAS groups at a 1:1 ratio using block randomization.",
      "randomisation_page": 2
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "gastrointestinal surgeries were conducted under general anesthesia.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "a Department of Anesthesiology, Shanxi Bethune Hospital, Shanxi Academy of Medical Sciences, Third Hospital of Shanxi Medical University, Tongji Shanxi Hospital, Taiyuan, 030032, China b Department of Anesthesiology and Critical Care Medicine, Tianjin Nankai Hospital, Tianjin, 300100, China ARTICLE ",
      "hits": 2
    },
    "surgical_population": {
      "value": "non-gastrointestinal laparoscopic surgery: a randomized controlled tri",
      "page": 1,
      "quote": "gastrointestinal function recovery in patients undergoing non-gastrointestinal laparoscopic surgery: a randomized controlled trial Xianhong Jiang a,1 , Yuan Zhang b,1, Jiaqi Tan a, Ping Zhuang a, Aili Fang a, Xiaomin Yue a, Jun Pang a, Ying Kong a, Ke Zhang b, Yanfang Zhang b, Jianbo Yu b,* a Depart",
      "hits": 1
    },
    "source_pdf": "study_4_Jiang_2026.pdf"
  },
  "Jin 2023": {
    "randomised_n": {
      "value": 174,
      "page": 3,
      "quote": "The 174 patients were randomized to receive PCIA + 2-Hz EA (n=58), PCIA + 20/ 100−Hz EA (n=58), or PCIA + sham EA (n=58) treatment ( Figure 1 ).",
      "hits": 1,
      "adjudication": "Adjudicated 2026-09-12 by re-reading the source. The paper says \"174 eligible patients were enrolled ... and 29 were not randomized\", which reads as though the randomised total should be 174 - 29 = 145. It cannot be: the three arms are stated as n = 58 each and sum to exactly 174. The paper's own figures reconcile the other way -- 453 planned, 250 excluded leaves 203 eligible, and 203 - 29 not randomised gives 174 randomised. So 174 is the randomised number and \"enrolled\" is the loose word in that sentence; the enrolled figure its arithmetic implies is 203. No value changed as a result of this check."
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "STUDY DESIGN: This single-center, randomized, single-blinded, sham acupuncture controlled clinical trial was conducted at a tertiary uni- versity hospital in China.",
      "hits": 1
    },
    "surgical_population": {
      "value": "cesarean deliv-\nery and received fentanyl as patient-controlled intrave",
      "page": 1,
      "quote": "Female patients who underwent cesarean deliv- ery and received fentanyl as patient-controlled intravenous analgesia for postoperative analgesia were enrolled.",
      "hits": 1
    },
    "source_pdf": "009_jin_2023.pdf"
  },
  "Lee 2011": {
    "randomised_n": {
      "value": 47,
      "page": 1,
      "quote": "on a double-blind, sham and di ﬀerent intervention controlled clinical experimental design, 47 women were randomly allocated to four di ﬀerent groups.",
      "hits": 1
    },
    "country": {
      "value": "Australia",
      "page": 1,
      "quote": "1 School of Biomedical and Health Sciences, Vict oria University, Melbourne, VIC 8001, Australia 2 Department of Anesthesiology, China Medical University Hospital, T aichung 40447, T aiwan Correspondence should be addressed to Hong Xu, hong.xu@vu.edu.au Received 17 January 2011; Accepted 24 March 20",
      "hits": 2,
      "note": "marked as affiliation 1 (lead centre); the paper also lists China"
    },
    "source_pdf": "049_lee_2011.pdf"
  },
  "Li 2021": {
    "pulse_width": {
      "value": "0.6 ms / 0.2 ms",
      "page": 3,
      "quote": "The wave widths were 2 Hz for 0.6 ms and 100 Hz for 0.2 ms, and the waveform was complete symmetric biphasic pulse.",
      "hits": 2
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "tumor resection under general anesthesia (stomach, colon or rec- tum); using postoperative analgesia pump; volunteering to partic- ipate in this study and sign the informed consent. Patients meeting the following criteria were excluded from the study: surgical incision or scar near the acupoints of ",
      "is_general": true,
      "hits": 2
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "a Department of Anesthesiology, Beijing Friendship Hospital, Capital Medical University, Beijing 100050, China b Department of Anesthesiology, Beijing Hui-Min Hospital, Beijing 100053, China c Department of Traditional Chinese Medicine, Beijing Friendship Hospital, Capital Medical University, Beijin",
      "hits": 4
    },
    "surgical_population": {
      "value": "major abdominal surgery",
      "page": 1,
      "quote": "in patients undergoing major abdominal surgery.",
      "hits": 1
    },
    "source_pdf": "covidence_437_full_article.pdf"
  },
  "Li 2022": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "receiving elective thyroidectomy under general anesthesia. Exclusion criteria: (1) history of operative treatment; (2) history of severe pain, including current pain treatment; (3) pregnant or breastfeeding; (4) mental or neurological disorder or intellectual disabilities; (5) implanted cardiac defi",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "Department of Anesthesiology, Affiliated Hospital of Nanjing University of Chinese Medicine, Jiangsu Province Hospital of Chinese Medicine, Nanjing, Jiangsu, People’s Republic of China Correspondence: Weiqian Tian, Department of Anesthesiology, Affiliated Hospital of Nanjing University of Chinese Me",
      "hits": 3
    },
    "surgical_population": {
      "value": "Thyroidectomy:\nA Double-Blind Randomized Controlled T rial\nSha Li",
      "page": 1,
      "quote": "in Patients Undergoing Thyroidectomy: A Double-Blind Randomized Controlled T rial Sha Li, Cheng Hu, Juan Zhu, Y udi Zhou, Y aomei Cui, Qian Xu, Weiqian Tian Department of Anesthesiology, Affiliated Hospital of Nanjing University of Chinese Medicine, Jiangsu Province Hospital of Chinese Medicine, Nan",
      "hits": 1
    },
    "source_pdf": "getfile.php.pdf"
  },
  "Liang 2021": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "undergoing TURP under general anesthesia requiring intraoperative urinary catheterization were enrolled for the trial.",
      "is_general": true,
      "hits": 2
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Anesthesiology, Qilu Hospital, Cheeloo College of Medicine, Shandong University, Jinan, Shandong 250012, China 2Department of Anesthesiology, First Aﬃliated Hospital of Wenzhou Medical University, Wenzhou, Zhejiang 325000, China CorrespondenceshouldbeaddressedtoJinGuiYu;yujingui1109@1",
      "hits": 2
    },
    "surgical_population": {
      "value": "Transurethral Resection of the Prostate\nDongdong Liang",
      "page": 1,
      "quote": "Postoperative Catheter-Related Bladder Discomfort in Patients Undergoing Transurethral Resection of the Prostate Dongdong Liang ,1,2 ShenHui Jin ,2 LeDan Huang ,2 YeLong Ren ,2 ZhongHeng Du ,2 Li Wang ,2 Ying Ren ,2 KeNing Yang ,2 JunLu Wang ,2 and JinGui Yu 1 1Department of Anesthesiology, Qilu Hos",
      "hits": 1
    },
    "source_pdf": "014_liang_2021.pdf"
  },
  "Lin 2002": {
    "randomised_n_derived": {
      "value": 100,
      "page": 2,
      "quote": "hysterectomy were randomly divided into four groups of 25 each by a computer-generated randomization sequence: Group I received neither needle insertion nor electric stimu- lation (control); Group II received needle insertion but with- out electrical stimulation (sham-EA); Group III received needle",
      "derivation": "4 groups x 25 each",
      "hits": 1
    },
    "arms": {
      "value": 4,
      "page": 2,
      "quote": "hysterectomy were randomly divided into four groups of 25 each by a computer-generated randomization sequence: Group I received neither needle insertion nor electric stimu- lation (control); Group II received needle insertion but with- out electrical stimulation (sham-EA); Group III received needle ",
      "hits": 1
    },
    "country": {
      "conflict": [
        "China",
        "Taiwan"
      ],
      "note": "country: several affiliation countries and no affiliation marked as the lead centre; not resolved automatically"
    },
    "surgical_population": {
      "value": "lower\nabdominal surgery were randomly assigned to four treatment regime",
      "page": 1,
      "quote": "One hundred healthy consenting women undergoing lower abdominal surgery were randomly assigned to four treatment regimens: Group I ðn ¼ 25Þ, control; Group II ðn ¼ 25Þ, sham-EA (needle insertion without electrical stimulation); Group III ðn ¼ 25Þ, low-EA (2 Hz of electrical stimulation); and Group I",
      "hits": 1
    },
    "source_pdf": "covidence_951_lin_2002.pdf"
  },
  "Liu 2015": {
    "randomised_n_derived": {
      "value": 92,
      "page": 1,
      "quote": "general anaesthesia were randomly allocated into either a multipoint TEAS (n=46) or a sham TEAS group (n=46).",
      "derivation": "46 + 46",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "scheduled for supratentorial craniotomy under general anaesthesia were randomly allocated into either a multipoint TEAS (n=46) or a sham TEAS group (n=46).",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "Department of Anesthesiology, Beijing 100093 China; baoguowang766@163.com Accepted 10 April 2015 Published Online First 29 April 2015 To cite: Liu X, Li S, Wang B, et al.",
      "hits": 1
    },
    "surgical_population": {
      "value": "supratentorial craniotomy\nXing Liu",
      "page": 1,
      "quote": "with sufentanil anaesthesia in patients undergoing supratentorial craniotomy Xing Liu, 1 Shuqin Li,1 Baoguo Wang,2 Lixin An, 1 Xiujun Ren,3 Haifeng Wu 4 ▸ Additional material is published online only.",
      "hits": 1
    },
    "source_pdf": "covidence_681_full_article.pdf"
  },
  "Liu 2021": {
    "randomised_n": {
      "value": 100,
      "page": 4,
      "quote": "The remaining 100 patients were randomly divided into Group T and Group C (Figure 2). Patient Characteristics The patients included into this final cohort were all Han Chinese, the general characteristics of the entire patients included gender [female, 49 (49%)], age (70.24±5.143 years), BMI (24.78±",
      "hits": 1
    },
    "anaesthesia": {
      "value": "Total intravenous anaesthesia",
      "page": 3,
      "quote": "μg/kg/min) plus propofol (total intravenous anesthesia [TIVA], 4–12 mg/kg/h) at the discretion of the anesthesiol- ogist.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Anesthesiology, The Third Hospital of Hebei Medical University, Shijiazhuang City, Hebei, People’s Republic of China; 2Department of Anesthesiology, Cangzhou Central Hospital, Cangzhou, Hebei, People’s Republic of China Background: Postoperative cognitive decline (POCD) in the old age",
      "hits": 2
    },
    "surgical_population": {
      "value": "laparoscopic radical colon \ncancer surgery",
      "page": 1,
      "quote": "stimulation (TEAS) against POCD in elderly patients undergoing laparoscopic radical colon cancer surgery, as well as the potential mechanism. Methods: A prospective, single-center, parallel-group, randomized trial was designed.",
      "hits": 1
    },
    "source_pdf": "getfile.php-2.pdf"
  },
  "Liu 2025": {
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1 First Clinical Medical College, Guangzhou University of Chinese Medicine, Guangzhou, China, 2 Department of Anesthesiology, The First Affiliated Hospital of Guangzhou University of Chinese Medicine, Guangzhou, China, 3 Guangdong Clinical Research Academy of Chinese Medicine, Guangzhou, China, 4 De",
      "hits": 5
    },
    "surgical_population": {
      "value": "thoracoscopic \nsurgery: a randomized controlled \ntrial\nJie Liu 1",
      "page": 1,
      "quote": "sleep quality in patients undergoing thoracoscopic surgery: a randomized controlled trial Jie Liu 1,2,3, Longfei Ding 1,2, Wuhua Ma 2,3, Jiyong Wang 3,4, Xiuling Song 2,3, Ying Cao 5* and Caineng Wu 2,3* 1 First Clinical Medical College, Guangzhou University of Chinese Medicine, Guangzhou, China, 2 ",
      "hits": 1
    },
    "source_pdf": "pdf.pdf"
  },
  "Liu 2026 (ESD)": {
    "pulse_width": {
      "value": "0.6 ms / 0.2 ms",
      "page": 3,
      "quote": "the current frequency of 2/100 Hz (wave width: 2 Hz, 0.6 ms; 100 Hz, 0.2 ms), alternating frequency for 3 s, and stimulation intensity was set to the patient's maximum tolerance level.",
      "hits": 2
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 6,
      "quote": "undergoing gastroesophageal ESD under general anesthesia, pretreating with TEAS could effectively improve the early postoperative pain of patients, reduce the incidence of moderate-to-severe pain, and decrease the application of morphine after surgery.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "Department of Anesthesiology, Beijing Friendship Hospital, Capital Medical University, Beijing (100050), China; 2.",
      "hits": 4
    },
    "surgical_population": {
      "value": "ESD were assigned : A total of 129 patients undergoing ESD were assigne",
      "page": 1,
      "quote": "MethodsMethods: A total of 129 patients undergoing ESD were assigned : A total of 129 patients undergoing ESD were assigned randomly to the TEAS group (64 cases) or the sham group (65 cases) using computer-generated random randomly to the TEAS group (64 cases) or the sham group (65 cases) using comp",
      "hits": 1
    },
    "source_pdf": "covidence_69_full_article.pdf"
  },
  "Liu 2026 (burn)": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "Methods In this trial, 86 burn patients with wound debridement under general anesthesia were randomized to receive thirty minutes of TEAS (TEAS group, n = 43) at acupoints LI4 (Hegu), PC6 (Neiguan), ST36 (Zusanli), and SP6 (Sanyinjiao) before induction of anesthesia or false stimulation (control gro",
      "is_general": true,
      "hits": 1
    },
    "source_pdf": "covidence_48_verified.pdf"
  },
  "Long 2025": {
    "randomised_n_derived": {
      "value": 53,
      "page": 3,
      "quote": "The patients were randomly assigned to Group C (n = 26) and Group A (n = 27) using a random number table (Fig.",
      "derivation": "26 + 27",
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "a Department of Anesthesiology, The First Hospital of Nanchang, The Third Affiliated Hospital of Nanchang University, Jiangxi Medical College, Nanchang University, Nanchang, China b Department of Anesthesiology, The Second Affiliated Hospital of Zhejiang Chinese Medical University, Hangzhou, China c",
      "hits": 3
    },
    "surgical_population": {
      "value": "elective hip fracture surgery at the Second \nAffiliated Hospital of Zhe",
      "page": 2,
      "quote": "patients who underwent elective hip fracture surgery at the Second Affiliated Hospital of Zhejiang Chinese Medicine University between December 2021 and August 2022 were included in the study. Research grouping Patients who met the inclusion criteria were randomly assigned to either the control grou",
      "hits": 1
    },
    "source_pdf": "1-s2.0-S0020138325005200.pdf"
  },
  "Lu 2021": {
    "randomised_n": {
      "value": 576,
      "page": 3,
      "quote": "A total of 576 patients met the criteria and were randomly assigned into the sham-operated control (n = 188), single acupoint (n = 198), and combined acupoints (n = 190) groups (Fig.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "Participants: Eligible patients were women scheduled for radical mastectomy under general anesthesia.",
      "is_general": true,
      "hits": 5
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "a Department of Anesthesiology and Perioperative Medicine, Xijing Hospital, Fourth Military Medical University, Xi'an, Shaanxi 710032, China b Department of Anesthesiology, First Affiliated Hospital, Xi'an Jiaotong University, Xi'an, Shaanxi 710061, China c Department of Anesthesiology, Tangdu Hospi",
      "hits": 12
    },
    "surgical_population": {
      "value": "mastectomy is associated with a decreased incidence of \nchronic pain at",
      "page": 4,
      "quote": "that TEAS at combined acupoints before anesthesia induction in patients undergoing mastectomy is associated with a decreased incidence of chronic pain at 6 months after surgery compared with the sham inter- vention.",
      "hits": 1
    },
    "source_pdf": "covidence_414_full_article.pdf"
  },
  "Lu 2022": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "Patients scheduled for laparoscopic colon surgery under general anaesthesia were screened.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Anaesthesiology and Perioperative Medicine, Xijing Hospital, Fourth Military Medical University, Xi’an, People’s Republic of China; 2Department of Anaesthesiology, T ongji Hospital, Huazhong University of Science and T echnology, Wuhan, People’s Republic of China; 3Department of Anaes",
      "hits": 8
    },
    "surgical_population": {
      "value": "elective colon surgery were enrolled and 94 \nfinished study",
      "page": 1,
      "quote": "Patients and Methods: From November 2016 to March 2018, 100 patients who underwent elective colon surgery were enrolled and 94 finished study (n = 47 for each) in three university hospitals.",
      "hits": 1
    },
    "source_pdf": "getfile.php-3.pdf"
  },
  "Luo 2026": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 5,
      "quote": "panoplasty under general anesthesia, compared with sham stimulation.",
      "is_general": true,
      "hits": 1
    },
    "surgical_population": {
      "value": "tympanoplasty",
      "page": 1,
      "quote": "patients undergoing tympanoplasty. Methods In this prospective, single-blind, randomized, parallel-group trial, we enrolled 277 patients (aged 18–65 years; ASA physical status I–II) scheduled for tympanoplasty.",
      "hits": 1
    },
    "source_pdf": "covidence_35_verified.pdf"
  },
  "Ma 2026": {
    "randomised_n": {
      "value": 35,
      "page": 5,
      "quote": "< 6 were assigned to the non-randomized control group (Group C), and 35 patients with PSQI ≥ 6 were randomly allocated (1:1) to the sleep disturbance group (Group S, n = 17) or the TEAS intervention group (Group T, n = 18).",
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "2Department of Anesthesiology, Second Affiliated Hospital of Harbin Medical University, Harbin, Heilongjiang, People’s Republic of China; 3The Third People’s Hospital of Chengdu, Chengdu, Sichuan, People’s Republic of China; 4Department of Anesthesiology, The Third Hospital of Hebei Medical Universi",
      "hits": 3
    },
    "source_pdf": "117210.pdf"
  },
  "Ng 2013": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "All laparoscopic surgeries were performed under general anesthesia.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "Hong Kong",
      "page": 1,
      "quote": "Division of Colorectal Surgery, Department of Surgery, The Chinese University of Hong Kong, Prince of Wales Hospital, Shatin, Hong Kong SAR See Covering the Cover synopsis on page 255. BACKGROUND & AIMS: We investigated the efficacy of electroacupuncture in reducing the duration of postoperative ile",
      "hits": 5
    },
    "surgical_population": {
      "value": "elective laparoscopic surgery for colonic\nand upper rectal cancer",
      "page": 1,
      "quote": "patients undergoing elective laparoscopic surgery for colonic and upper rectal cancer, enrolled from October 2008 to Octo- ber 2010.",
      "hits": 1
    },
    "source_pdf": "covidence_1970_ng_2013.pdf"
  },
  "Ntritsou 2014": {
    "randomised_n": {
      "value": 75,
      "page": 1,
      "quote": "observer-blinded trial, 75 patients undergoing radical prostatectomy were randomly assigned to two groups: (1) EA (n=37; tramadol+ketamine +EA) and (2) control (n=38; tramadol+ketamine). EA (100 Hz frequency) was applied at LI4 bilaterally during the closure of the abdominal walls and EA (4 Hz) was ",
      "hits": 1
    },
    "arms": {
      "value": 2,
      "page": 1,
      "quote": "radical prostatectomy were randomly assigned to two groups: (1) EA (n=37; tramadol+ketamine +EA) and (2) control (n=38; tramadol+ketamine). EA (100 Hz frequency) was applied at LI4 bilaterally during the closure of the abdominal walls and EA (4 Hz) was applied at ST36 and LI4 bilaterally immediately",
      "hits": 2
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 6,
      "quote": "ketamine, which contrasts with patients under general anaesthesia who receive benzodiazepines.",
      "is_general": true,
      "hits": 1
    },
    "surgical_population": {
      "value": "radical prostatectomy were randomly assigned to\ntwo groups:",
      "page": 1,
      "quote": "observer-blinded trial, 75 patients undergoing radical prostatectomy were randomly assigned to two groups: (1) EA (n=37; tramadol+ketamine +EA) and (2) control (n=38; tramadol+ketamine). EA (100 Hz frequency) was applied at LI4 bilaterally during the closure of the abdominal walls and EA (4 Hz) was ",
      "hits": 1
    },
    "source_pdf": "covidence_729_full_article.pdf"
  },
  "Oztas 2019": {
    "arms": {
      "value": 3,
      "page": 8,
      "quote": "The patients were randomly divided into three groups. Contemporary Nurse 129",
      "hits": 1
    },
    "country": {
      "value": "Turkey",
      "page": 1,
      "quote": "midline incision: Randomized controlled clinical trial Bediye Oztas a* and Emine Iyigun b aSchool of Nursing, Yuksek Ihtisas University, Ankara, Turkey; bSchool of Nursing, Gulhane Health Science University, Ankara, Turkey (Received 1 December 2018; accepted 31 May 2019 ) Aims-Objectives: The purpos",
      "hits": 2
    },
    "surgical_population": {
      "value": "abdominal surgery",
      "page": 1,
      "quote": "patients undergoing abdominal surgery. Design: This research was conducted as a randomized controlled trial. Methods: This research sample consisted of 48 patients who underwent abdominal surgery with a midline incision.",
      "hits": 1
    },
    "source_pdf": "covidence_505_full_article.pdf"
  },
  "Pan 2023": {
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Anesthesia, The First Affiliated Hospital of Wenzhou Medical University, Wenzhou, People’s Republic of China; 2Department of Anesthesia, Sir Run Run Shaw Hospital, Affiliated with the Zhejiang University School of Medicine, Hangzhou, People’s Republic of China; 3Department of Anesthes",
      "hits": 5
    },
    "surgical_population": {
      "value": "Laparoscopic Myomectomy: A Randomized \nControlled Trial\nYuanyuan Pan\n 1",
      "page": 1,
      "quote": "Accelerates the Recovery of Patients Undergoing Laparoscopic Myomectomy: A Randomized Controlled Trial Yuanyuan Pan 1,*, Yifan Shao 2,*, Zhanghuan Chi 3,*, Shenhui Jin 1, Junlu Wang 1 1Department of Anesthesia, The First Affiliated Hospital of Wenzhou Medical University, Wenzhou, People’s Republic o",
      "hits": 1
    },
    "source_pdf": "getfile.php-4.pdf"
  },
  "Seevaunnamtum 2016": {
    "randomised_n": {
      "value": 64,
      "page": 5,
      "quote": "Praveena Seevaunnamtum S et al. Randomisation n = 64 Allocated to Receive EA (n = 32) Allocated to Control (n =",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "the end of the surgery (mean duration of surgery was 149.06 ± 42.64 minutes) under general anaesthesia.",
      "is_general": true,
      "hits": 3
    },
    "country": {
      "value": "Malaysia",
      "page": 1,
      "quote": "1Department of Anaesthesiology and Critical Care, Universiti Sains Malaysia, Kubang Kerian, Kelantan, Malaysia 2Hospital Raja Permaisuri Bainun Ipoh, Jalan Hospital, 30990 Ipoh, Perak, Malaysia *Corresponding author: S Praveena Seevaunnamtum, Department of Anaesthesiology and Critical Care, School o",
      "hits": 6
    },
    "surgical_population": {
      "value": "gynaecological surgery",
      "page": 1,
      "quote": "gated to determine any opioid-sparing eﬀect and reduction of postoperative nausea and vomiting (PONV) in patients undergoing gynaecological surgery . Patient and Methods: This was a prospective, double blinded randomized study conducted in a tertiary hospital in Malaysia.",
      "hits": 1
    },
    "source_pdf": "covidence_596_verified.pdf"
  },
  "Sim 2002": {
    "randomised_n": {
      "value": 90,
      "page": 1,
      "quote": "Ninety patients were randomly assigned to one of three groups: Group I (control group) – received placebo EA for 45 minutes before induction of general anaesthesia (GA); Group II – preoperative EA instituted 45 minutes before induction of GA; Group III – 45 minutes of postoperative EA.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "was under general anaesthesia, a reliable monitor is required to indicate whether the patient is receiving adequate anaesthesia and/or analgesia. The Bispectral index (BIS) (ASPECT medical system, A-1050, Natick, USA) is a processed parameter derived from multiple features generated by bispectral an",
      "is_general": true,
      "hits": 2
    },
    "country": {
      "value": "Singapore",
      "page": 1,
      "quote": "Department of Anaesthesia, National University Hospital Singapore Correspondence: Tat-Leang Lee analeetl@nus.edu.sg Summary Acupuncture has been shown to be effective in experimental and clinical acute pain settings.",
      "hits": 1
    },
    "source_pdf": "covidence_952_full_article.pdf"
  },
  "Song 2020": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "surgery under general anesthesia.",
      "is_general": true,
      "hits": 2
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Anesthesiology, Shengjing Hospital of China Medical University, Shenyang, Liaoning, People’s Republic of China; 2Department of Anesthesiology, Friendship Hospital of Capital Medical University, Beijing, People’s Republic of China *These authors contributed equally to this work Objecti",
      "hits": 7
    },
    "surgical_population": {
      "value": "selective video-assisted thoracoscopic surgery",
      "page": 1,
      "quote": "stimulation (TEAS) on sleep quality and complications after surgery in patients undergoing selective video-assisted thoracoscopic surgery. Patients and Methods: Eighty-five patients were divided into the TEAS group or the control group randomly.",
      "hits": 1
    },
    "source_pdf": "getfile.php-6.pdf"
  },
  "Sun 2017": {
    "randomised_n_derived": {
      "value": 380,
      "page": 3,
      "quote": "randomized into 4 groups with 95 patients per group.",
      "derivation": "4 groups x 95 each",
      "hits": 1
    },
    "pulse_width": {
      "value": "0.6 ms / 0.2 ms",
      "page": 2,
      "quote": "2 Hz (0.6 ms pulse width) stimulation is alternated with 100 Hz stimulation (0.2 ms pulse width) automatically in every 3 seconds, 9,13,18 at a maximum current tolerated but subnoxious to the patient.",
      "hits": 2
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "for laparoscopic surgery under general anesthesia were randomly assigned to receive sham TEAS (group SSS), preoperative TEAS (group TSS), preoperative TEAS combined with intraoperative TEAS (group TTS) or preoperative TEAS combined with post- operative TEAS (group TST) (n = 95 each group).",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "Medical College, Xuzhou; and zZunyi Medical College, Zunyi, China. This study was carried out in the second aﬃliated hospital of Zhejiang University, School of Medicine and was funded by the Scientific Research Program of Chinese Medicine (2010ZA074) and the department (Department of Anesthesiology,",
      "hits": 4
    },
    "surgical_population": {
      "value": "laparoscopic\nsurgery",
      "page": 1,
      "quote": "during perioperative period in patients undergoing laparoscopic surgery. Methods: From July 2012 to October 2013, 380 patients scheduled for laparoscopic surgery under general anesthesia were randomly assigned to receive sham TEAS (group SSS), preoperative TEAS (group TSS), preoperative TEAS combine",
      "hits": 1
    },
    "source_pdf": "sun2017-2.pdf"
  },
  "Szmit 2021": {
    "randomised_n_derived": {
      "value": 71,
      "page": 1,
      "quote": "a standardized anesthetic technique were randomly assigned to one of three analgesic treatment regimens: PCA + TEAS ( n = 24); PCA + sham-TEAS (no electrical stimulation) ( n = 24), and PCA only (n = 23).",
      "derivation": "24 + 24 + 23",
      "hits": 1
    },
    "country": {
      "value": "Poland",
      "page": 1,
      "quote": "1 Department and Clinic of General, Minimally Invasive and Endocrine Surgery, Wroclaw Medical University, 50-556 Wroclaw, Poland; mateusz.szmit@umed.wroc.pl (M.S.); jerzy.rudnicki@umed.wroc.pl (J.R.) 2 Department and Clinic of Internal Medicine, Occupational Diseases, Hypertension and Clinical Oncol",
      "hits": 9
    },
    "surgical_population": {
      "value": "Inguinal Hernia Repair: A Randomize",
      "page": 1,
      "quote": "Postoperative Analgesic Requirement in Patients Undergoing Inguinal Hernia Repair: A Randomized, Placebo-Controlled Study Mateusz Szmit 1, Siddarth Agrawal 2,3, * , Waldemar Go´ zdzik4,*, Andrzej Kübler 4, Anil Agrawal 5, Piotr Pruchnicki 6 , Marta Wo´ zniak3, Matylda Nowak 7 , Bartłomiej Bartoszewi",
      "hits": 1
    },
    "source_pdf": "pdf-3.pdf"
  },
  "Tu 2024": {
    "country": {
      "value": "China",
      "page": 1,
      "quote": "a Department of Neurosurgery, West China Hospital, Sichuan University, Chengdu, China b Department of Integrated Traditional and Western Medicine, West China Hospital, Sichuan University, Chengdu, China ARTICLE INFO Keywords: Craniotomy Postoperative nausea and vomiting Transcutaneous electrical acu",
      "hits": 5
    },
    "surgical_population": {
      "value": "craniotomy: A randomized \ncontrolled trial \nLiang-dan Tu",
      "page": 1,
      "quote": "and vomiting in patients undergoing craniotomy: A randomized controlled trial Liang-dan Tu a, Peng-cheng Li a, Yu Zhao b, Rui-zhi Feng b, Jian-qin Lv b,* a Department of Neurosurgery, West China Hospital, Sichuan University, Chengdu, China b Department of Integrated Traditional and Western Medicine,",
      "hits": 1
    },
    "source_pdf": "study_244_Tu_2023.pdf"
  },
  "Wang 2023": {
    "country": {
      "value": "China",
      "page": 1,
      "quote": "Nanjing University of Chinese Medicine, Nanjing, China e-mail: surgery34@163.com J.",
      "hits": 3
    },
    "surgical_population": {
      "value": "Laparoscopic Gastrointestinal Tumor\nSurgery: A Prospective",
      "page": 1,
      "quote": "Improves Postoperative Sleep Quality in Patients Undergoing Laparoscopic Gastrointestinal Tumor Surgery: A Prospective, Randomized Controlled Trial Jun Wang .",
      "hits": 1
    },
    "source_pdf": "s40122-023-00493-2.pdf"
  },
  "Wang 2024": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "Standard general anesthesia was induced with propofol 1–2 mg kg−1, sufentanil 0.3–0.6 μg kg−1, and cis-atracurium 0.2–0.4 mg kg−1.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1 Department of Anesthesiology, National Cancer Center/ National Clinical Research Center for Cancer/Cancer Hospital, Chinese Academy of Medical Sciences and Peking Union Medical College, Beijing, China 2 Department of Outcomes Research, Outcomes Research Consortium, Cleveland Clinic, Cleveland, OH,",
      "hits": 2
    },
    "surgical_population": {
      "value": "breast cancer surgery were assigned to either the study group",
      "page": 1,
      "quote": "Methods A total of 140 female patients undergoing breast cancer surgery were assigned to either the study group (70 with SNVP) or the control group (70 with mild to moderate nausea and vomiting during pregnancy (MNVP)).",
      "hits": 1
    },
    "source_pdf": "covidence_212_full_article.pdf"
  },
  "Wong 2006": {
    "country": {
      "value": "Hong Kong",
      "page": 1,
      "quote": "Division of Cardiothoracic Surgery, Department of Surgery, and Departments of Anesthesiology and Physiotherapy, Prince of Wales Hospital, Shatin, Hong Kong, SAR, China Background.",
      "hits": 4
    },
    "surgical_population": {
      "value": "anatomic lung resection with\ncurative intent through a thoracotomy appr",
      "page": 2,
      "quote": "All patients underwent anatomic lung resection with curative intent through a thoracotomy approach by a single thoracic surgeon.",
      "hits": 1
    },
    "source_pdf": "covidence_912_wong_2006.pdf"
  },
  "Wu 2016": {
    "country": {
      "conflict": [
        "China",
        "Germany"
      ],
      "note": "country: several affiliation countries and no affiliation marked as the lead centre; not resolved automatically"
    },
    "surgical_population": {
      "value": "thoracotomy",
      "page": 2,
      "quote": "All of the patients underwent thoracotomy (18) with a rib spreader and wound retractor (tumed -Surgical Instrument & Hospital Supplies GmbH, Tuttlingen, Germany), and without rib excision.",
      "hits": 1
    },
    "source_pdf": "wu2015.pdf"
  },
  "Wu 2022": {
    "randomised_n_derived": {
      "value": 90,
      "page": 1,
      "quote": "fusion surgery were randomized into two groups: pTEAS, (n = 45) and Control (n = 45).",
      "derivation": "45 + 45",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "under general anesthesia were assigned into two groups: patients to receive total intravenous anesthesia (Control group, n = 45), and others to receive pTEAS in addition to total intravenous anesthesia (pTEAS group, n = 45). Inclusion criteria are as follows: (1) ASA I – II; (2) between 40 and 70 ye",
      "is_general": true,
      "hits": 1
    },
    "surgical_population": {
      "value": "lumbar surgery",
      "page": 1,
      "quote": "patients who underwent lumbar surgery, which has a significant impact on patients’ quality of life.",
      "hits": 1
    },
    "source_pdf": "s12871-022-01875-3.pdf"
  },
  "Wu 2025": {
    "randomised_n": {
      "value": 100,
      "page": 4,
      "quote": "Consequently, 100 eligible patients were selected and randomly assigned to two groups: 50 in the TEAS group and 50 in the control group.",
      "hits": 1
    },
    "arms": {
      "value": 2,
      "page": 4,
      "quote": "patients were selected and randomly assigned to two groups: 50 in the TEAS group and 50 in the control group.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "Eligible patients were scheduled for ambulatory video-assisted thoracoscopic pulmonary wedge resection under general anesthesia, aged 18–70 years, and with ASA of Anesthesiologists grade I or II.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Anesthesiology, Shanghai Chest Hospital, Shanghai Jiao T ong University, School of Medicine, Shanghai, People’s Republic of China; 2President’s Office, Shanghai Chest Hospital, Shanghai Jiao T ong University, School of Medicine, Shanghai, People’s Republic of China; 3Department of Sci",
      "hits": 6
    },
    "surgical_population": {
      "value": "surgery for \nlung cancer",
      "page": 2,
      "quote": "efficacy of TEAS in enhancing postoperative recovery and facilitating early discharge of patients undergoing surgery for lung cancer.",
      "hits": 1
    },
    "source_pdf": "103940.pdf"
  },
  "Xie 2014": {
    "randomised_n_derived": {
      "value": 60,
      "page": 2,
      "quote": "patients were randomly divided into 3 groups by com- puter generated randomization number ( n=20 for each group): group A (control) receiving a general anesthesia only; group B (sham) given EA needles at PC4 (Ximen) and PC6 (Neiguan) but no stimulation; group C (EAS) electrically given EAS of the ip",
      "derivation": "3 groups x 20 each",
      "hits": 1
    },
    "arms": {
      "value": 3,
      "page": 2,
      "quote": "patients were randomly divided into 3 groups by com- puter generated randomization number ( n=20 for each group): group A (control) receiving a general anesthesia only; group B (sham) given EA needles at PC4 (Ximen) and PC6 (Neiguan) but no stimulation; group C (EAS) electrically given EAS of the ip",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "The general anesthesia was induced by intravenous anesthesia with remifentanil and propofol by a target controlled infusion (TCI) system (CP600TCI, Slgo Technology Co.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Anesthesiology, Qianfushan Hospital Affiliated to Shandong University, Jinan 250014, China 2Department of Anesthesiology, Anhui Provincial Hospital Affiliated to Anhui Medical University, Hefei 230001, China © Huazhong University of Science and Technology and Springer-Verlag Berlin He",
      "hits": 2
    },
    "surgical_population": {
      "value": "radica l thoracic esophagectomy",
      "page": 1,
      "quote": "through pain induced by remifentan il in patients undergoing radica l thoracic esophagectomy, and the mechanisms were assessed.",
      "hits": 1
    },
    "source_pdf": "covidence_701_full_article.pdf"
  },
  "Xing 2022": {
    "country": {
      "value": "China",
      "page": 1,
      "quote": "Department of Anaesthesiology, The First Affiliated Hospital of USTC, Division of Life Sciences and Medicine, University of Science and Technology of China, Hefei 230001, Anhui, China e-mail: zmynjl@126.com Y.",
      "hits": 1
    },
    "surgical_population": {
      "value": "Laparoscopic Gastric Cancer\nSurgery: A Randomized Controlled Trial\nRuyi",
      "page": 1,
      "quote": "Patients Undergoing Laparoscopic Gastric Cancer Surgery: A Randomized Controlled Trial Ruyi Xing .",
      "hits": 1
    },
    "source_pdf": "s40122-022-00429-2.pdf"
  },
  "Xiong 2021": {
    "randomised_n": {
      "value": 62,
      "page": 1,
      "quote": "Methods Sixty-two female patients undergoing elective LSG were randomly assigned to the TEAS combined with dexameth- asone and tropisetron (TEAS group,n = 31) or dexamethasone and tropisetron (control group,n = 31) groups.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "who underwent elective LSG under general anesthesia be- tween May 2018 and February 2020.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1 Department of Anesthesiology, The First Affiliated Hospital of Chongqing Medical University, Youyi Road 1, Yuzhong District, Chongqing 400016, People’s Republic of China 2 College of Traditional Chinese Medicine, Chongqing Medical University, Chongqing 401331, People’s Republic of China 3 Departme",
      "hits": 3
    },
    "surgical_population": {
      "value": "Laparoscopic Sleeve\nGastrectomy: a Prospective",
      "page": 1,
      "quote": "and Vomiting in Female Patients Undergoing Laparoscopic Sleeve Gastrectomy: a Prospective, Randomized Controlled Trial Qiuju Xiong1 & Su Min 1 & Ke Wei 1 & Yanmei Yang2 & Jingyue Ma1 & Dan Liu 1 & Menghua Zeng3 & Lei Zou 1 Received: 14 November 2020 / Revised: 26 December 2020 / Accepted: 29 Decembe",
      "hits": 1
    },
    "source_pdf": "covidence_431_full_article.pdf"
  },
  "Yang 2020": {
    "randomised_n": {
      "value": 59,
      "page": 3,
      "quote": "The remaining 59 participants were randomized into e920648-3 Indexed in: [Current Contents/Clinical Medicine] [SCI Expanded] [ISI Alerting System] [ISI Journals Master List] [Index Medicus/MEDLINE] [EMBASE/Excerpta Medica] [Chemical Abstracts/CAS] Yang J.",
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1 Department of Anesthesiology, Affiliated Hospital of Nanjing University of Chinese Medicine, Nanjing, Jiangsu, China 2 Department of Acupuncture and Rehabilitation, Affiliated Hospital of Nanjing University of Chinese Medicine, Nanjing, Jiangsu, China 3 School of Health and Biomedical Sciences, Ro",
      "hits": 3,
      "note": "marked as affiliation 1 (lead centre); the paper also lists Australia"
    },
    "surgical_population": {
      "value": "Thoracoscopic Surgery: A Feasibility \nStudy\n ABE 1 Jie Yang*\n AE 1 Libi",
      "page": 1,
      "quote": "Gastrointestinal Recovery in Patients Undergoing Thoracoscopic Surgery: A Feasibility Study ABE 1 Jie Yang* AE 1 Libing Huang* BC 1 Siying Liu A 2 Wenzhong Wu AG 1 Weiqian Tian ADE 3 Zhen Zheng ADE 4 Zhigang Lv AG 1 Fangbing Ji AG 1 Man Zheng * Jie Yang and Libing Huang have contributed equally to t",
      "hits": 1
    },
    "source_pdf": "covidence_464_verified.pdf"
  },
  "Yang 2024": {
    "randomised_n_derived": {
      "value": 180,
      "page": 3,
      "quote": "were randomly assigned to EA group (n = 90) or UC group (n = 90).",
      "derivation": "90 + 90",
      "hits": 1
    },
    "country": {
      "conflict": [
        "Australia",
        "China"
      ],
      "note": "country: several affiliation countries and no affiliation marked as the lead centre; not resolved automatically"
    },
    "surgical_population": {
      "value": "video-assisted thoracoscopic segmentectomy or lobectomy were randomize",
      "page": 1,
      "quote": "180 patients who underwent video-assisted thoracoscopic segmentectomy or lobectomy were randomized to EA group (three sessions, 24 h prior to surgery, postoperative 4 h and 24 h) or usual care group (UC group).",
      "hits": 1
    },
    "source_pdf": "covidence_1930_full_article.pdf"
  },
  "Yao 2015": {
    "randomised_n": {
      "value": 71,
      "page": 3,
      "quote": "A total of 71 patients randomizedtotreatmentallocationcompletedthestudyand theirdatawereincludedintheanalysis.Patientdemographic characteristics, type, and durations of procedures were sim- ilar with no statistically significant differences (𝑃>0.05 ) betweengroups( Table 1). PatientsintheTEASgroupha",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "General anesthesia was induced (Hegu) LI4 (Neiguan) PC6 (Zusanli) ST36 (Sanyinjiao) SP6 Figure 1: Location of Hegu (LI4), Neiguan (PC6), Zusanli (ST36), and Sanyinjiao (SP6) acupoints. withIVsufentanil0.5𝜇g/kgandpropofol2.0mg/kg.Tracheal intubation was facilitated with cisatracurium 0.15mg/kg. After",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Departmentof Anesthesiology,TheShengliClinicalMedicalCollegeof FujianMedicalUniversityand Fujian Provincial Hospital, Fuzhou 350001, China 2Departmentof TraditionalChineseMedicine,Fujian ProvincialHospital,Fuzhou 350001,China CorrespondenceshouldbeaddressedtoYanqingChen;fjslyys@gmail.com Received15",
      "hits": 2
    },
    "surgical_population": {
      "value": "gynecological laparoscopic surgery were randomly allocated to TEAS or c",
      "page": 1,
      "quote": "74 American Society of Anesthesiologists physical status (ASA) I or II patients undergoing gynecological laparoscopic surgery were randomly allocated to TEAS or control groups.",
      "hits": 1
    },
    "source_pdf": "039_yao_2015.pdf"
  },
  "Yeh 2010": {
    "pulse_width": {
      "value": "0.25 ms",
      "page": 3,
      "quote": "for 30 min, bilateral, pulse duration 0.25 ms) • Acupuncture (ipsilateral to the side of surgery, needles remained for 15 min and manually stimulated for 5 s per 5 min and just before needle removal) •PCA+TENS(2Hz) •PCA+TENS(100Hz) • PCA+TENS (altemating 2/100 Hz per 3 s) • True acupressure (no repo",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "spine injuries under general anesthesia and had heen evaluated as American Society of Anesthesiologists grades I to II (I: a nor- mal healthy patient; II: a patient with mild systemic disease that does not limit activity).",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "Taiwan",
      "page": 1,
      "quote": "Mei-Ling Yeh, RN, PhD, is a professor in the School of Nursing, National Taipei College of Nursing, Taiwan.",
      "hits": 1
    },
    "surgical_population": {
      "value": "lumbar spinal surgery were randomly assigned to one of three\ngroups",
      "page": 1,
      "quote": "Ninety-nine patients undergoing lumbar spinal surgery were randomly assigned to one of three groups.",
      "hits": 1
    },
    "randomised_n_quarantined": {
      "reason": "Yeh 2010 prints 99 but its own Table 2 gives 33/30/31 = 94, and the companion report Yeh 2011 gives 90. Three mutually contradictory figures for one cohort; adjudicated 2026-09-12 as unresolvable from the publications.",
      "record": "05_study_linkage/cohorts/yeh_lumbar_spinal_surgery.md"
    },
    "source_pdf": "015_PainATHM-2.pdf"
  },
  "Yeh 2011": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 4,
      "quote": "was general anesthesia with intravenous thiopental (2.1 mg/kg) and fentanyl (4.3 mg/kg), and connected to a PCA device programmed to deliver a patient-triggered 1 mg bolus of morphine with a 10 min lockout interval between doses.",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "Taiwan",
      "page": 2,
      "quote": "spine injuries at a 3000-bed medical center in northern Taiwan.",
      "hits": 1
    },
    "randomised_n_quarantined": {
      "reason": "Companion report of Yeh 2010. Its 30/30/30 is the pairwise contrast the review uses and is not disputed, but the whole-trial randomised total is part of the same unresolvable 90/94/99 dispute.",
      "record": "05_study_linkage/cohorts/yeh_lumbar_spinal_surgery.md"
    },
    "source_pdf": "covidence_828_full_article.pdf"
  },
  "Yu 2020": {
    "surgical_population": {
      "value": "gynecological laparoscopic surgery: a\nprospective",
      "page": 1,
      "quote": "recovery in patients undergoing gynecological laparoscopic surgery: a prospective, randomized, placebo- controlled trial Xiangdi Yu *, Fangxiang Zhang and Bingning Chen Abstract Introduction: In current study we assessed the effect of transcutaneous electrical acupoint stimulation (TEAS) on the qual",
      "hits": 1
    },
    "source_pdf": "s13063-019-3892-4.pdf"
  },
  "Zhan 2020": {
    "country": {
      "value": "China",
      "page": 1,
      "quote": "a Nanjing University of Traditional Chinese Medicine, China bAffiliated Hospital of Nanjing University of Traditional Chinese Medicine, China ARTICLE INFO Keywords: Postoperative analgesic Transverse abdominis plane block Transcutaneous electric acupoint stimulation Abdominal surgery Randomized cont",
      "hits": 2
    },
    "source_pdf": "covidence_1389_full_article.pdf"
  },
  "Zhang 2014": {
    "randomised_n": {
      "value": 72,
      "page": 1,
      "quote": "Seventy-two women scheduled for cosmetic breast surgery were randomly allocated to transcutaneous electric acupoint stimulation or sham groups. Patients in the transcutaneous electric acupoint stimulation group received 30 min of electrical stimulation at three acupoints located on the hand and fore",
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1 Clinical Fellow, 3 Professor, 4 Associate Professor, Department of Anaesthesiology, Xijing Hospital, Fourth Military Medical University, Xi ’an, Shaanxi, China 2 Specialist Registrar, Department of Anaesthesiology, Shaanxi Provincial Maternal and Child Health Hospital, Xi ’an, Shaanxi, China Summa",
      "hits": 2
    },
    "surgical_population": {
      "value": "ambulatory surgery",
      "page": 1,
      "quote": "cantly improve the quality of recovery and decrease the incidence of anaesthesia-related side-effects for patients undergoing ambulatory surgery. ...............................................................................................................................",
      "hits": 1
    },
    "source_pdf": "043_zhang_2014.pdf"
  },
  "Zhang 2018": {
    "randomised_n_derived": {
      "value": 42,
      "page": 1,
      "quote": "of gastrointestinal cancers were randomized to TEA (n = 21) and sham-TEA (n = 21).",
      "derivation": "21 + 21",
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Gastroenterology, Changzheng Hospital affiliated to second Military Medical university, shanghai, 200003, China.",
      "hits": 5
    },
    "surgical_population": {
      "value": "surgical procedures \nstayed in the hospital for a total of 1",
      "page": 1,
      "quote": "data, Medicare patients who underwent surgical procedures stayed in the hospital for a total of 1.82 million days (a mean of 11.3 days per patient), and cost healthcare industries approxi- mately US $1.75 billion during the year of 2000 [4].",
      "hits": 1
    },
    "source_pdf": "Needleless Transcutaneous Electrical Acustimulation_ A Pilot Study Evaluating Improvement in Post-Operative Recovery-2.pdf"
  },
  "Zhang 2023": {
    "randomised_n": {
      "value": 1948,
      "page": 1,
      "quote": "Results A total of 1,948 participants were recruited and randomized to TEAS ( n = 975) or sham ( n = 973) between August 2018 and June 2020.",
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1 Department of Anesthesiology and Critical Care Medicine, Tianjin Nankai Hospital, Tianjin Medical University, 6 Changjiang Road, Tianjin, People’s Republic of China 2 Department of Biomedical Engineering, College of Precision Instruments and Optoelectronics Engineering, Tianjin University, Tianjin",
      "hits": 4
    },
    "surgical_population": {
      "value": "elective laparoscopic cholecystectomy were randomly assigned to either",
      "page": 1,
      "quote": "Methods Participants who underwent elective laparoscopic cholecystectomy were randomly assigned to either the TEAS group or the sham group.",
      "hits": 1
    },
    "source_pdf": "covidence_308_full_article.pdf"
  },
  "Zhang 2025": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 4,
      "quote": "General anesthesia was induced intravenously with sufentanil (0.4 μg/kg), propofol (2 mg/kg), and rocuronium (0.6 mg/kg).",
      "is_general": true,
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Anesthesiology,the Zaoyang First People’s Hospital, Xiangyang, People’s Republic of China; 2Department of Anesthesiology,the First Affiliated Hospital of Wenzhou Medical University, Wenzhou, People’s Republic of China; 3Department of Laboratory Medicine, Clinical Medical College of Sh",
      "hits": 4
    },
    "surgical_population": {
      "value": "Laparoscopic Hysterectomy: \nA Randomized Controlled Trial\nYu Zhang 1",
      "page": 1,
      "quote": "Patients Undergoing Laparoscopic Hysterectomy: A Randomized Controlled Trial Yu Zhang 1, Qinxue Dai 2, Jing Zhang 3, Junlu Wang 2, Xiuxiu Zhuang 2, Anqi Zhang 2, Luping Huang 2, Wenwen Du 2 1Department of Anesthesiology,the Zaoyang First People’s Hospital, Xiangyang, People’s Republic of China; 2Dep",
      "hits": 1
    },
    "source_pdf": "109551.pdf"
  },
  "Zheng 2025": {
    "randomised_n": {
      "value": 88,
      "page": 5,
      "quote": "The remaining 88 patients were randomly assigned to either the TEAS or the control group.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "scopic surgery under general anesthesia at a tertiary hospital in China between April and December 2022 were enrolled.",
      "is_general": true,
      "hits": 2
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Anesthesiology, General Hospital of Northern Theater Command, Shenyang, 110016, People’s Republic of China; 2Department of Anesthesiology, The 964TH Hospital of Chinese People’s Liberation Army Joint Logistics Support Force, Changchun, 130000, People’s Republic of China Correspondence",
      "hits": 5
    },
    "surgical_population": {
      "value": "gynecological laparoscopic surgery",
      "page": 1,
      "quote": "quality of recovery in patients undergoing gynecological laparoscopic surgery. Patients and Methods: In this prospective, randomized, single-blind, controlled trial, patients scheduled for gynecological laparo - scopic surgery under general anesthesia at a tertiary hospital in China between April an",
      "hits": 1
    },
    "source_pdf": "109499.pdf"
  },
  "Zhou 2021": {
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1Department of Gastrointestinal Surgery, The Affiliated Hospital of Qingdao University, Qingdao, Shandong Province, People’s Republic of China; 2Department of Rehabilitation, The Affiliated Hospital of Qingdao University, Qingdao, Shandong Province, People’s Republic of China Purpose: Transcutaneous",
      "hits": 2
    },
    "surgical_population": {
      "value": "gastrectomy is largely \nunknow",
      "page": 1,
      "quote": "Chinese medicine (TCM) therapy for patients who underwent gastrectomy is largely unknown.",
      "hits": 1
    },
    "source_pdf": "getfile.php-5.pdf"
  },
  "Zhu 2022": {
    "randomised_n": {
      "value": 405,
      "page": 7,
      "quote": "POV incidence at 0–6 h and 6–24 h including all 405 patients who were randomized and did not convert to open surgery (Supplemental Table 1).",
      "hits": 1
    },
    "arms": {
      "value": 4,
      "page": 1,
      "quote": "Methods: A total of 413 patients undergoing elective laparoscopic gynecological surgery were randomly allocated into 4 groups receiving EA the day before surgery (Group Pre, n = 103), 30 min before (Group 30, n = 104) or both (Group Comb, n = 103), or usual care alone (Group Usual, n = 103).",
      "hits": 1
    },
    "country": {
      "value": "China",
      "page": 1,
      "quote": "1 Department of Anesthesiology, The Affiliated Hospital of Nanjing University of Chinese Medicine, Nanjing, China 2 Department of Acupuncture, The Affiliated Hospital of Nanjing University of Chinese Medicine, Nanjing, China 3 Key Laboratory of Acupuncture and Medicine Research of Ministry of Educat",
      "hits": 4,
      "note": "marked as affiliation 1 (lead centre); the paper also lists Australia"
    },
    "surgical_population": {
      "value": "laparoscopic surgery",
      "page": 1,
      "quote": "dence of postoperative nausea and vomiting (PONV), and severity of postoperative pain, in gynecological patients undergoing laparoscopic surgery.",
      "hits": 1
    },
    "source_pdf": "covidence_381_full_article.pdf"
  }
};
