// Generated by scripts/extract_baseline_from_pdfs.py; do not edit.
// Every value carries the source PDF, page and verbatim quote it came from.
window.PDF_EXTRACTED = {
  "#105119 - Zhou 2025": {
    "source_pdf": "105119.pdf"
  },
  "An 2014": {
    "arms": {
      "value": 2,
      "page": 3,
      "quote": "Patients were randomly allocated into 2 groups using a computer-generated randomized number table; Group C was a control group that did not receive EA during the operation ( n ¼ 43) and Group A was the experimental group that received EA ( n ¼ 45). Acupuncture We collaborated with an acupuncturist f",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "General anesthesia was initially maintained with sevo flurane, 2% in oxygen at 2 L/min.",
      "hits": 2
    },
    "source_pdf": "covidence_698_full_article.pdf"
  },
  "Ao 2021": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "General anesthesia was induced using intravenous sufentanil (0.3‑0.5 µg/kg; cat.",
      "hits": 1
    },
    "source_pdf": "download.pdf"
  },
  "Chen 1998": {
    "source_pdf": "covidence_969_chen_1998.pdf"
  },
  "Chen 2015": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "General anesthesia was induced with intravenous sufentanil 0.5 μg/kg and propofol 2.0 mg/kg.",
      "hits": 2
    },
    "source_pdf": "037_chen_2015_thyroidectomy_lund.pdf"
  },
  "Chen 2015 (Hyperalgesia)": {
    "source_pdf": "040_chen_2015_hyperalgesia_lund.pdf"
  },
  "Chen 2020": {
    "randomised_n": {
      "value": 80,
      "page": 1,
      "quote": "Methods: A total of 80 patients were randomized into two groups: the TEAS group and the sham TEAS combined with general anesthesia group.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 7,
      "quote": "the stress response during extubation after general anesthesia in elderly patients undergoing elective supratentorial craniotomy: A prospective randomized controlled trial.",
      "hits": 1
    },
    "source_pdf": "Thoracic Cancer - 2020 - Chen - Efficacy of transcutaneous electrical acupoint stimulation combined with general anesthesia.pdf"
  },
  "Coura 2011": {
    "randomised_n": {
      "value": 32,
      "page": 1,
      "quote": "The day before the surgery, 32 patients undergoing cardiac surgery were randomised into two groups: patients from the treatment group received preoperative EA at bilateral points (LI4-LI11, LR3-ST36, PC6-TE5) for 30 min with altemating frequencies of 3 and 15 Hz.",
      "hits": 1
    },
    "source_pdf": "covidence_819_full_article.pdf"
  },
  "El-Rakshy 2009": {
    "source_pdf": "covidence_868_full_article.pdf"
  },
  "Gao 2021": {
    "arms": {
      "value": 2,
      "page": 3,
      "quote": "and randomly divided into 2 groups: 307 patients allocated to the sham group and 303 patients to the TEAS group.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "(1) surgery under general anesthesia; (2) age /C21 18 years and American Society of Anesthesiologists I eIII; (3) patients ’ ability to understand and sign the written informed consent form; and (4) not involved in other clinical studies.",
      "hits": 1
    },
    "source_pdf": "covidence_400_full_article.pdf"
  },
  "Gao 2022": {
    "arms": {
      "value": 2,
      "page": 6,
      "quote": "of 1,655 patients were enrolled and randomly divided into two groups: 828 patients allocated to the Sham group and 827 patients to the TEAS group.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "non-gastrointestinal surgery under general anesthesia. Interventions: Patients were randomly allocated into the TEAS and Sham grou p with a 1:1 ratio.",
      "hits": 3
    },
    "source_pdf": "pdf-2.pdf"
  },
  "Grech 2016": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 6,
      "quote": "tients were under general anesthesia, and therefore blinded to the treatment to avoid any placebo effect. Despite the general anesthesia, EA induced an anti- nociceptive effect; (2) the lower amount of analgesics in the EA group did not cause a higher pain score.",
      "hits": 2
    },
    "source_pdf": "030_grech_2016_lund.pdf"
  },
  "Gu 2019": {
    "source_pdf": "covidence_1471_full_article.pdf"
  },
  "Guo 2023": {
    "source_pdf": "006_guo_2023.pdf"
  },
  "He 2026 (breast/WJCO)": {
    "randomised_n": {
      "value": 130,
      "page": 1,
      "quote": "A total of 130 patients with breast cancer were randomly divided into EA group (n = 65) and control group (n = 65).",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "Patients in both groups were given uniform general anesthesia 30 minutes afterward, induced with propofol (2 mg/kg) and sufentanil (0.5 μg/kg).",
      "hits": 1
    },
    "source_pdf": "covidence_41_verified.pdf"
  },
  "He 2026 (hepatectomy/JIS)": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "Eligible patients were those who were scheduled for elective hepatectomy under general anesthesia.",
      "hits": 1
    },
    "source_pdf": "covidence_25_verified.pdf"
  },
  "Hou 2023": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "index monitor (BIS) were placed, general anesthesia was induced with IV sufentanil 0.3–0.5 μg kg\u0000 1 and propofol 0.2–0.3 mg kg\u0000 1.",
      "hits": 1
    },
    "source_pdf": "007_hou_2023.pdf"
  },
  "Huang 2017": {
    "arms": {
      "value": 4,
      "page": 1,
      "quote": "experience of TEAS or acupuncture were randomly assigned to four groups: control (con), 2/100, 2, and 100 Hz.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "and general anesthesia is beneficial in pneumonectomy [7, 8]. Transcutaneous electrical acupoint stimulation (TEAS), a noninvasive adjunctive intervention based on acupunc- ture, may reduce pulmonary inflammatory responses induced by one-lung ventilation, and therefore reduce the incidence of postop",
      "hits": 3
    },
    "source_pdf": "covidence_666_full_article.pdf"
  },
  "Huang 2024": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "All patients underwent surgery under general anesthesia.",
      "hits": 1
    },
    "source_pdf": "covidence_245_full_article.pdf"
  },
  "Huang 2025": {
    "source_pdf": "covidence_131_verified.pdf"
  },
  "Jiang 2026": {
    "source_pdf": "study_4_Jiang_2026.pdf"
  },
  "Jin 2023": {
    "randomised_n": {
      "value": 174,
      "page": 3,
      "quote": "The 174 patients were randomized to receive PCIA + 2-Hz EA (n=58), PCIA + 20/ 100−Hz EA (n=58), or PCIA + sham EA (n=58) treatment ( Figure 1 ).",
      "hits": 1
    },
    "source_pdf": "009_jin_2023.pdf"
  },
  "Lee 2011": {
    "randomised_n": {
      "value": 47,
      "page": 1,
      "quote": "on a double-blind, sham and di ﬀerent intervention controlled clinical experimental design, 47 women were randomly allocated to four di ﬀerent groups.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "1 received general anesthesia only.",
      "hits": 1
    },
    "source_pdf": "049_lee_2011.pdf"
  },
  "Li 2021": {
    "pulse_width": {
      "value": "0.6 ms / 0.2 ms",
      "page": 3,
      "quote": "The wave widths were 2 Hz for 0.6 ms and 100 Hz for 0.2 ms, and the waveform was complete symmetric biphasic pulse.",
      "hits": 2
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "Patients received general anesthesia intravenously, as determined by the chief anesthesiologist.",
      "hits": 2
    },
    "source_pdf": "covidence_437_full_article.pdf"
  },
  "Li 2022": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "frequently used for general anesthesia.1 However, experimental and clinical studies have reported a paradoxical phenomenon termed remifentanil-induced post-infusion hyperalgesia (RPH), in which pain sensitivity increases after the administration of high doses of remifentanil during surgery.2–4 The p",
      "hits": 1
    },
    "source_pdf": "getfile.php.pdf"
  },
  "Liang 2021": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "undergoing TURP under general anesthesia requiring intraoperative urinary catheterization were enrolled for the trial.",
      "hits": 2
    },
    "source_pdf": "014_liang_2021.pdf"
  },
  "Lin 2002": {
    "arms": {
      "value": 4,
      "page": 2,
      "quote": "hysterectomy were randomly divided into four groups of 25 each by a computer-generated randomization sequence: Group I received neither needle insertion nor electric stimu- lation (control); Group II received needle insertion but with- out electrical stimulation (sham-EA); Group III received needle ",
      "hits": 1
    },
    "source_pdf": "covidence_951_lin_2002.pdf"
  },
  "Liu 2015": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 7,
      "quote": "electroacupuncture with general anesthesia induced by sevoflurane in patients undergoing supratentorial craniotomy and improvements in their clinical recovery profile & blood enkephalin.",
      "hits": 1
    },
    "source_pdf": "covidence_681_full_article.pdf"
  },
  "Liu 2021": {
    "randomised_n": {
      "value": 100,
      "page": 4,
      "quote": "The remaining 100 patients were randomly divided into Group T and Group C (Figure 2). Patient Characteristics The patients included into this final cohort were all Han Chinese, the general characteristics of the entire patients included gender [female, 49 (49%)], age (70.24±5.143 years), BMI (24.78±",
      "hits": 1
    },
    "source_pdf": "getfile.php-2.pdf"
  },
  "Liu 2025": {
    "source_pdf": "pdf.pdf"
  },
  "Liu 2026 (ESD)": {
    "pulse_width": {
      "value": "0.6 ms / 0.2 ms",
      "page": 3,
      "quote": "the current frequency of 2/100 Hz (wave width: 2 Hz, 0.6 ms; 100 Hz, 0.2 ms), alternating frequency for 3 s, and stimulation intensity was set to the patient's maximum tolerance level.",
      "hits": 2
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 6,
      "quote": "undergoing gastroesophageal ESD under general anesthesia, pretreating with TEAS could effectively improve the early postoperative pain of patients, reduce the incidence of moderate-to-severe pain, and decrease the application of morphine after surgery.",
      "hits": 1
    },
    "source_pdf": "covidence_69_full_article.pdf"
  },
  "Liu 2026 (burn)": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "wound debridements, undergoing general anesthesia, thus providing comfortable analgesia for them while reducing the dosages of opioid will be a major challenge for anesthesiologists. It is supported that preemptive analgesia, which means reducing peripheral and central nerve sensitiza - tion caused ",
      "hits": 1
    },
    "source_pdf": "covidence_48_verified.pdf"
  },
  "Long 2025": {
    "source_pdf": "1-s2.0-S0020138325005200.pdf"
  },
  "Lu 2021": {
    "randomised_n": {
      "value": 576,
      "page": 3,
      "quote": "A total of 576 patients met the criteria and were randomly assigned into the sham-operated control (n = 188), single acupoint (n = 198), and combined acupoints (n = 190) groups (Fig.",
      "hits": 1
    },
    "anaesthesia": {
      "conflict": [
        "General anaesthesia",
        "Total intravenous anaesthesia"
      ],
      "note": "anaesthesia: the paper yielded more than one candidate; not resolved automatically"
    },
    "source_pdf": "covidence_414_full_article.pdf"
  },
  "Lu 2022": {
    "anaesthesia": {
      "conflict": [
        "Epidural anaesthesia",
        "General anaesthesia"
      ],
      "note": "anaesthesia: the paper yielded more than one candidate; not resolved automatically"
    },
    "source_pdf": "getfile.php-3.pdf"
  },
  "Luo 2026": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "frequent and distressing complication following general anesthesia, particularly in patients undergoing middle ear surgery [1].",
      "hits": 1
    },
    "source_pdf": "covidence_35_verified.pdf"
  },
  "Ma 2026": {
    "randomised_n": {
      "value": 35,
      "page": 5,
      "quote": "< 6 were assigned to the non-randomized control group (Group C), and 35 patients with PSQI ≥ 6 were randomly allocated (1:1) to the sleep disturbance group (Group S, n = 17) or the TEAS intervention group (Group T, n = 18).",
      "hits": 1
    },
    "source_pdf": "117210.pdf"
  },
  "Ng 2013": {
    "anaesthesia": {
      "value": "Epidural anaesthesia",
      "page": 2,
      "quote": "received epidural anesthesia or analgesia, those with a cardiac pacemaker, those who were allergic to acupuncture needles, and those who previously received acupuncture. Study Design Patients potentially eligible for the study were informed by the principal investigator about the study details the d",
      "hits": 1
    },
    "source_pdf": "covidence_1970_ng_2013.pdf"
  },
  "Ntritsou 2014": {
    "randomised_n": {
      "value": 75,
      "page": 1,
      "quote": "observer-blinded trial, 75 patients undergoing radical prostatectomy were randomly assigned to two groups: (1) EA (n=37; tramadol+ketamine +EA) and (2) control (n=38; tramadol+ketamine). EA (100 Hz frequency) was applied at LI4 bilaterally during the closure of the abdominal walls and EA (4 Hz) was ",
      "hits": 1
    },
    "arms": {
      "value": 2,
      "page": 1,
      "quote": "radical prostatectomy were randomly assigned to two groups: (1) EA (n=37; tramadol+ketamine +EA) and (2) control (n=38; tramadol+ketamine). EA (100 Hz frequency) was applied at LI4 bilaterally during the closure of the abdominal walls and EA (4 Hz) was applied at ST36 and LI4 bilaterally immediately",
      "hits": 2
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "General anaesthesia was conducted by one of a team of five anaesthetists not involved in patient post- operative assessments. All the patients underwent radical retropubic prosta- tectomy for prostate malignancy .",
      "hits": 2
    },
    "source_pdf": "covidence_729_full_article.pdf"
  },
  "Oztas 2019": {
    "arms": {
      "value": 3,
      "page": 8,
      "quote": "The patients were randomly divided into three groups. Contemporary Nurse 129",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 6,
      "quote": "All patients received general anesthesia with the same protocol.",
      "hits": 1
    },
    "source_pdf": "covidence_505_full_article.pdf"
  },
  "Pan 2023": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 10,
      "quote": "electro-acupuncture on the intratracheal extubation stress response in general anesthesia of patients with breast cancer undergoing modified radical mastectomy].",
      "hits": 1
    },
    "source_pdf": "getfile.php-4.pdf"
  },
  "Seevaunnamtum 2016": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "dard care was defined as general anaesthesia with intraop- erative analgesia of IV Morphine 0.1 mg/kg and postopera- tive patient-controlled analgesia Morphine (PCAM). Double blinding was ensured by starting EA after pa- tients were induced under general anaesthesia and the as- sessors did not know ",
      "hits": 3
    },
    "source_pdf": "covidence_596_verified.pdf"
  },
  "Sim 2002": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "General anaesthesia is the state in which, as a result of drug-induced narcosis, the patient neither perceives nor recalls noxious stimuli.",
      "hits": 2
    },
    "source_pdf": "covidence_952_full_article.pdf"
  },
  "Song 2020": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "surgery under general anesthesia.",
      "hits": 2
    },
    "source_pdf": "getfile.php-6.pdf"
  },
  "Sun 2017": {
    "pulse_width": {
      "value": "0.6 ms / 0.2 ms",
      "page": 2,
      "quote": "2 Hz (0.6 ms pulse width) stimulation is alternated with 100 Hz stimulation (0.2 ms pulse width) automatically in every 3 seconds, 9,13,18 at a maximum current tolerated but subnoxious to the patient.",
      "hits": 2
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "for laparoscopic surgery under general anesthesia were randomly assigned to receive sham TEAS (group SSS), preoperative TEAS (group TSS), preoperative TEAS combined with intraoperative TEAS (group TTS) or preoperative TEAS combined with post- operative TEAS (group TST) (n = 95 each group).",
      "hits": 1
    },
    "source_pdf": "sun2017-2.pdf"
  },
  "Szmit 2021": {
    "source_pdf": "pdf-3.pdf"
  },
  "Tu 2024": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "status classification of I or II, undergoing general anesthesia, no history of PONV or motion sickness, no use of antiemetics and analgesia 24 h before surgery, willingness to participate, no prior experience with TEAS and signed an informed consent form.",
      "hits": 1
    },
    "source_pdf": "study_244_Tu_2023.pdf"
  },
  "Wang 2023": {
    "source_pdf": "s40122-023-00493-2.pdf"
  },
  "Wang 2024": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "Standard general anesthesia was induced with propofol 1–2 mg kg−1, sufentanil 0.3–0.6 μg kg−1, and cis-atracurium 0.2–0.4 mg kg−1.",
      "hits": 1
    },
    "source_pdf": "covidence_212_full_article.pdf"
  },
  "Wong 2006": {
    "source_pdf": "covidence_912_wong_2006.pdf"
  },
  "Wu 2016": {
    "source_pdf": "wu2015.pdf"
  },
  "Wu 2022": {
    "anaesthesia": {
      "value": "Total intravenous anaesthesia",
      "page": 2,
      "quote": "total intravenous anesthesia (pTEAS group, n = 45). Inclusion criteria are as follows: (1) ASA I – II; (2) between 40 and 70 years of age; (3) diagnosed with lum - bar spinal stenosis or lumbar intervertebral disc hernia - tion based on imaging results; and (4) undergoing the operative procedures of",
      "hits": 1
    },
    "source_pdf": "s12871-022-01875-3.pdf"
  },
  "Wu 2025": {
    "randomised_n": {
      "value": 100,
      "page": 4,
      "quote": "Consequently, 100 eligible patients were selected and randomly assigned to two groups: 50 in the TEAS group and 50 in the control group.",
      "hits": 1
    },
    "arms": {
      "value": 2,
      "page": 4,
      "quote": "patients were selected and randomly assigned to two groups: 50 in the TEAS group and 50 in the control group.",
      "hits": 1
    },
    "anaesthesia": {
      "conflict": [
        "General anaesthesia",
        "Regional anaesthesia"
      ],
      "note": "anaesthesia: the paper yielded more than one candidate; not resolved automatically"
    },
    "source_pdf": "103940.pdf"
  },
  "Xie 2014": {
    "arms": {
      "value": 3,
      "page": 2,
      "quote": "patients were randomly divided into 3 groups by com- puter generated randomization number ( n=20 for each group): group A (control) receiving a general anesthesia only; group B (sham) given EA needles at PC4 (Ximen) and PC6 (Neiguan) but no stimulation; group C (EAS) electrically given EAS of the ip",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "The general anesthesia was induced by intravenous anesthesia with remifentanil and propofol by a target controlled infusion (TCI) system (CP600TCI, Slgo Technology Co.",
      "hits": 1
    },
    "source_pdf": "covidence_701_full_article.pdf"
  },
  "Xing 2022": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "were randomly divided into general anesthesia group (group G), TAPB group (group NG), and TEAS combined with TAPB group (group NTG). Patients in the NTG group received TEAS at PC6, LI4, and ST36 acupoints and TAPB.",
      "hits": 2
    },
    "source_pdf": "s40122-022-00429-2.pdf"
  },
  "Xiong 2021": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "who underwent elective LSG under general anesthesia be- tween May 2018 and February 2020.",
      "hits": 1
    },
    "source_pdf": "covidence_431_full_article.pdf"
  },
  "Yang 2020": {
    "randomised_n": {
      "value": 59,
      "page": 3,
      "quote": "The remaining 59 participants were randomized into e920648-3 Indexed in: [Current Contents/Clinical Medicine] [SCI Expanded] [ISI Alerting System] [ISI Journals Master List] [Index Medicus/MEDLINE] [EMBASE/Excerpta Medica] [Chemical Abstracts/CAS] Yang J.",
      "hits": 1
    },
    "source_pdf": "covidence_464_verified.pdf"
  },
  "Yang 2024": {
    "source_pdf": "covidence_1930_full_article.pdf"
  },
  "Yao 2015": {
    "randomised_n": {
      "value": 71,
      "page": 3,
      "quote": "A total of 71 patients randomizedtotreatmentallocationcompletedthestudyand theirdatawereincludedintheanalysis.Patientdemographic characteristics, type, and durations of procedures were sim- ilar with no statistically significant differences (𝑃>0.05 ) betweengroups( Table 1). PatientsintheTEASgroupha",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 2,
      "quote": "General anesthesia was induced (Hegu) LI4 (Neiguan) PC6 (Zusanli) ST36 (Sanyinjiao) SP6 Figure 1: Location of Hegu (LI4), Neiguan (PC6), Zusanli (ST36), and Sanyinjiao (SP6) acupoints. withIVsufentanil0.5𝜇g/kgandpropofol2.0mg/kg.Tracheal intubation was facilitated with cisatracurium 0.15mg/kg. After",
      "hits": 2
    },
    "source_pdf": "039_yao_2015.pdf"
  },
  "Yeh 2010": {
    "source_pdf": "covidence_828_full_article.pdf"
  },
  "Yeh 2011": {
    "pulse_width": {
      "value": "0.25 ms",
      "page": 3,
      "quote": "for 30 min, bilateral, pulse duration 0.25 ms) • Acupuncture (ipsilateral to the side of surgery, needles remained for 15 min and manually stimulated for 5 s per 5 min and just before needle removal) •PCA+TENS(2Hz) •PCA+TENS(100Hz) • PCA+TENS (altemating 2/100 Hz per 3 s) • True acupressure (no repo",
      "hits": 1
    },
    "source_pdf": "015_PainATHM-2.pdf"
  },
  "Yu 2020": {
    "source_pdf": "s13063-019-3892-4.pdf"
  },
  "Zhan 2020": {
    "source_pdf": "covidence_1389_full_article.pdf"
  },
  "Zhang 2014": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 8,
      "quote": "electroacupuncture with general anesthesia induced by sevo- flurane in patients undergoing supratentorial craniotomy and improvements in their clinical recovery profile & blood enkephalin.",
      "hits": 1
    },
    "source_pdf": "043_zhang_2014.pdf"
  },
  "Zhang 2018": {
    "source_pdf": "Needleless Transcutaneous Electrical Acustimulation_ A Pilot Study Evaluating Improvement in Post-Operative Recovery-2.pdf"
  },
  "Zhang 2023": {
    "source_pdf": "covidence_308_full_article.pdf"
  },
  "Zhang 2025": {
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 4,
      "quote": "General anesthesia was induced intravenously with sufentanil (0.4 μg/kg), propofol (2 mg/kg), and rocuronium (0.6 mg/kg).",
      "hits": 1
    },
    "source_pdf": "109551.pdf"
  },
  "Zheng 2025": {
    "randomised_n": {
      "value": 88,
      "page": 5,
      "quote": "The remaining 88 patients were randomly assigned to either the TEAS or the control group.",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 1,
      "quote": "scopic surgery under general anesthesia at a tertiary hospital in China between April and December 2022 were enrolled.",
      "hits": 3
    },
    "source_pdf": "109499.pdf"
  },
  "Zhou 2021": {
    "source_pdf": "getfile.php-5.pdf"
  },
  "Zhu 2022": {
    "randomised_n": {
      "value": 405,
      "page": 7,
      "quote": "POV incidence at 0–6 h and 6–24 h including all 405 patients who were randomized and did not convert to open surgery (Supplemental Table 1).",
      "hits": 1
    },
    "arms": {
      "value": 4,
      "page": 1,
      "quote": "Methods: A total of 413 patients undergoing elective laparoscopic gynecological surgery were randomly allocated into 4 groups receiving EA the day before surgery (Group Pre, n = 103), 30 min before (Group 30, n = 104) or both (Group Comb, n = 103), or usual care alone (Group Usual, n = 103).",
      "hits": 1
    },
    "anaesthesia": {
      "value": "General anaesthesia",
      "page": 3,
      "quote": "general anesthesia; female sex; age 18–60 years; non- smoking; body mass index 20–30 kg/m2; undergoing lapa- roscopic hysterectomy, myomectomy, oophorectomy, salpingoopherectomy or ovarian cystectomy.",
      "hits": 2
    },
    "source_pdf": "covidence_381_full_article.pdf"
  }
};
