// GENERATED by scripts/build_prior_evidence_comparison.py -- do not hand-edit.
// Source: TAN_2024_COVIDENCE_RECONCILIATION_AUDIT.md; dispositions re-derived from the locked workbook and
// 06_FINAL_ANALYSIS_V26/02_STATA/logs/01_opioid24_primary.log
window.PRIOR_EVIDENCE = {
  "generated_by": "scripts/build_prior_evidence_comparison.py",
  "source_document": "TAN_2024_COVIDENCE_RECONCILIATION_AUDIT.md",
  "audit_date": "2026-09-07",
  "prior": {
    "citation": "Tan SY, et al. Front Med (Lausanne). 2024;11:1302057.",
    "short": "Tan 2024",
    "scope": "76 RCTs of transcutaneous electrical acupoint stimulation. Needle-based electroacupuncture was excluded, and the search predates this review's 2024–2026 trials — so the two evidence bases overlap only partly.",
    "shared_outcome": "24-hour cumulative intravenous morphine-equivalent consumption"
  },
  "trials": [
    {
      "priority": "1",
      "study": "Chiu 1999",
      "tan_ref": "11",
      "population": "Hemorrhoidectomy (n=70)",
      "anaesthesia": "Perineal infiltration / Local anesthesia (30 mL 0.25% bupivacaine + epinephrine); NO general anesthesia",
      "opioid_reported": "IV PCA morphine 0-24 h: Acupoint 6.2 ± 1.3 mg (SEM) vs Control 11.6 ± 2.2 mg (SEM) [SD: 7.69 vs 13.01 mg]",
      "audit_judgment": "LEGITIMATE EXCLUSION. Violates two core protocol eligibility criteria: (1) Procedure performed under local block without general anesthesia; (2) Control group received active TENS stimulation rather than inactive sham. Tan inappropriately pooled an active control under local block.",
      "status": "excluded",
      "status_note": "Not eligible for this review."
    },
    {
      "priority": "2",
      "study": "Lan 2012",
      "tan_ref": "29",
      "population": "Total hip arthroplasty (THA) in elderly (n=60)",
      "anaesthesia": "Combined spinal-epidural anesthesia (CSEA) ; NO general anesthesia",
      "opioid_reported": "IV PCA fentanyl 0-24 h: TEAS 360 ± 117 µg vs Sham 572 ± 132 µg (converted: 36.0 vs 57.2 mg IV MME)",
      "audit_judgment": "LEGITIMATE EXCLUSION. Review protocol mandates general anesthesia. Neuraxial CSEA regional block violates inclusion criteria. Tan included this despite regional anesthesia.",
      "status": "excluded",
      "status_note": "Not eligible for this review."
    },
    {
      "priority": "3",
      "study": "Chen 2020",
      "tan_ref": "4",
      "population": "Minimally invasive thoracoscopic lobectomy (n=80)",
      "anaesthesia": "Standardized endotracheal General Anesthesia (propofol, sufentanil, rocuronium, cisatracurium)",
      "opioid_reported": "IV PCIA sufentanil 0-24 h: TEAS 72.43 ± 4.78 µg vs Sham 100.62 ± 10.20 µg (P < 0.001); converted: 7.243 vs 10.062 mg MME",
      "audit_judgment": "MATCHED — INCLUDED. Fully eligible for systematic review and strict primary 24-h opioid meta-analysis. Already included in our primary synthesis (opioid_24h_primary.csv).",
      "status": "in-primary",
      "status_note": "Contributes to this review's strict primary 0–24 h opioid synthesis."
    },
    {
      "priority": "4",
      "study": "Szmit 2021",
      "tan_ref": "46",
      "population": "Open Lichtenstein inguinal hernia repair (n=71)",
      "anaesthesia": "Standardized endotracheal General Anesthesia (fentanyl, propofol, rocuronium, sevoflurane)",
      "opioid_reported": "IV PCA morphine 0-24 h: TEAS 7.5 ± 3.8 mg vs Sham 15.2 ± 6.24 mg (P < 0.001); Median (IQR): 8 (5; 9) vs 15 (13; 18) mg",
      "audit_judgment": "QUESTIONABLE EXCLUSION / TOP ACTIONABLE POTENTIAL MISSED STUDY. Covidence exclusion reason Wrong outcomes is demonstrably erroneous. Study reports high-quality, directly reported 24-h IV PCA morphine under general anesthesia with sham control. Should be reconsidered immediately.",
      "status": "in-primary",
      "status_note": "Contributes to this review's strict primary 0–24 h opioid synthesis."
    },
    {
      "priority": "5",
      "study": "Yeh 2010",
      "tan_ref": "61",
      "population": "Non-traumatic lumbar spine injury/surgery (n=94)",
      "anaesthesia": "General Anesthesia",
      "opioid_reported": "24-h opiate dose: AES 18.6 ± 9.7 mg vs Sham 21.6 ± 13.1 mg vs Control 27.2 ± 12.5 mg; text states epidural PCA",
      "audit_judgment": "DUPLICATE / OVERLAPPING COHORT. Shares identical hospital, dates, authors, surgical indication, and identical sham control data (21.6 ± 13.1 mg) with Yeh 2011. Appropriately held from pooled meta-analysis.",
      "status": "included-held",
      "status_note": "Included in this review, but held from the strict primary synthesis."
    },
    {
      "priority": "6",
      "study": "Yeh 2011",
      "tan_ref": "60",
      "population": "Non-traumatic lumbar spine injury/surgery (n=90)",
      "anaesthesia": "General Anesthesia",
      "opioid_reported": "24-h opiate dose: AES 19.3 ± 9.7 mg vs Sham 21.6 ± 13.1 mg vs Control 28.0 ± 12.1 mg; text states IV PCA via central line",
      "audit_judgment": "DUPLICATE / OVERLAPPING COHORT. Tan 2024 erroneously double-counted Yeh 2010 and Yeh 2011 as independent trials. Our repository correctly recognized the duplicate sham group and held them from pooled primary synthesis.",
      "status": "included-held",
      "status_note": "Included in this review, but held from the strict primary synthesis."
    }
  ],
  "counts": {
    "in-primary": 2,
    "included-held": 2,
    "excluded": 2
  },
  "superseded_note": "The audit, dated 2026-09-07, recorded 1 of these 6 trials in the strict primary synthesis. 2 are in it now: the audit identified Szmit 2021 as wrongly excluded, and the review acted on that finding. This panel reports the current state, re-derived from the analysis itself; the figure in the audit document is superseded rather than corrected in place.",
  "our_primary": [
    "Chen 1998",
    "Chen 2020",
    "El-Rakshy 2009",
    "He 2026 (hepatectomy/JIS)",
    "Seevaunnamtum 2016",
    "Szmit 2021",
    "Yang 2024"
  ],
  "disclaimer": "Comparison with prior published evidence. The dispositions below are re-derived from this review's own locked dataset and Stata output, not copied from the audit document. Nothing here is a finding about the prior review's conduct; it records why the two evidence bases differ."
};
