// GENERATED by scripts/build_prisma_checklist.py -- do not hand-edit.
// Counts inside each item are re-derived from live files on every build.
window.PRISMA_CHECKLIST = {
  "generated_by": "scripts/build_prisma_checklist.py",
  "standard": "PRISMA 2020 (Page MJ, et al. BMJ 2021;372:n71)",
  "disclaimer": "Maps each PRISMA 2020 item to this review's own material. “Evidence-ready” means the material exists and is pinned to a location — not that the manuscript reports it yet, which is what PRISMA actually asks. Counts are re-derived on every build. Requirement wording is a paraphrase, not the checklist's own text.",
  "items": [
    {
      "item": "1",
      "section": "Title",
      "requirement": "Identify the report as a systematic review.",
      "status": "manuscript-only",
      "evidence": "Authorial. Nothing to derive.",
      "where": "Manuscript title page"
    },
    {
      "item": "2",
      "section": "Abstract",
      "requirement": "Structured abstract following the PRISMA 2020 for Abstracts checklist.",
      "status": "manuscript-only",
      "evidence": "Authorial, but the figures it must carry are all derived: 22 reported analyses with adopted certainty, and the PRISMA flow.",
      "where": "GRADE Summary of Findings; PRISMA flow"
    },
    {
      "item": "3",
      "section": "Introduction",
      "requirement": "Rationale for the review in the context of existing knowledge.",
      "status": "manuscript-only",
      "evidence": "Authorial. The comparison with Tan 2024 is assembled and can support it.",
      "where": "Comparison with prior evidence panel"
    },
    {
      "item": "4",
      "section": "Introduction",
      "requirement": "Explicit statement of objectives / questions addressed.",
      "status": "evidence-ready",
      "evidence": "Pre-specified in the locked protocol scope.",
      "where": "00_protocol/protocol_scope_locked.md"
    },
    {
      "item": "5",
      "section": "Methods",
      "requirement": "Inclusion and exclusion criteria, and how studies were grouped.",
      "status": "evidence-ready",
      "evidence": "Recorded in the locked protocol scope, with comparator and modality strata carried through every analysis.",
      "where": "00_protocol/protocol_scope_locked.md; per-analysis comparator strata"
    },
    {
      "item": "6",
      "section": "Methods",
      "requirement": "All information sources, with the date each was last searched.",
      "status": "evidence-ready",
      "evidence": "PubMed (2026-07-21, 1009 records); CENTRAL (2026-07-21, 1698 records); Embase (2026-07-22, 1928 records); CINAHL Ultimate (2026-07-23, 465 records)",
      "where": "Search strategies panel"
    },
    {
      "item": "7",
      "section": "Methods",
      "requirement": "Full verbatim search strategy for every source.",
      "status": "evidence-ready",
      "evidence": "4 of 4 databases have their full strategy stored verbatim.",
      "where": "Search strategies panel"
    },
    {
      "item": "8",
      "section": "Methods",
      "requirement": "Selection process: how many screened each record, and any automation.",
      "status": "attention",
      "evidence": "The screening records show Covidence dual screening with consensus, and 508 records marked ineligible by automation tools. The manuscript must state explicitly how many reviewers screened each record and how disagreements were resolved.",
      "where": "PRISMA flow; Covidence screening export"
    },
    {
      "item": "9",
      "section": "Methods",
      "requirement": "Data collection process: how many extractors, and any automation.",
      "status": "attention",
      "evidence": "Extraction provenance is recorded per study, but the number of independent extractors is a statement the manuscript must make and this pipeline cannot derive.",
      "where": "Study_Master reconciliation batches"
    },
    {
      "item": "10a",
      "section": "Methods",
      "requirement": "All outcomes sought, and which results were sought for each.",
      "status": "evidence-ready",
      "evidence": "Every outcome is registered with its window and eligibility; 45 analyses were computed in total.",
      "where": "Outcome data; derivability audit"
    },
    {
      "item": "10b",
      "section": "Methods",
      "requirement": "All other variables sought (participants, interventions, funding).",
      "status": "evidence-ready",
      "evidence": "Study characteristics are extracted per trial.",
      "where": "Study characteristics panel"
    },
    {
      "item": "11",
      "section": "Methods",
      "requirement": "Risk-of-bias assessment: tool, how many assessors, automation.",
      "status": "attention",
      "evidence": "36 result-specific RoB 2 assessments exist with all five domains. Independent dual assessment is in progress; the manuscript must state the final assessor process, so this cannot be closed yet.",
      "where": "Result-specific RoB 2 panel"
    },
    {
      "item": "12",
      "section": "Methods",
      "requirement": "Effect measures used for each outcome.",
      "status": "evidence-ready",
      "evidence": "Each analysis records its effect measure and estimator explicitly (mean difference, risk ratio, log risk ratio, standardized mean difference).",
      "where": "Per-analysis estimator and measure"
    },
    {
      "item": "13a",
      "section": "Methods",
      "requirement": "How studies were deemed eligible for each synthesis.",
      "status": "evidence-ready",
      "evidence": "The derivability audit records, contrast by contrast, why each is or is not poolable on the primary estimand.",
      "where": "Derivability audit (Tiers A–F)"
    },
    {
      "item": "13b",
      "section": "Methods",
      "requirement": "Data preparation: missing statistics, conversions.",
      "status": "evidence-ready",
      "evidence": "Unit conversions are recorded per contrast with source and status; median/IQR approximations and multi-arm combinations are named where used (Cochrane Handbook 6.5.2.5 and 6.5.2.10).",
      "where": "Opioid conversion audit; per-contrast combine notes"
    },
    {
      "item": "13c",
      "section": "Methods",
      "requirement": "How results were tabulated or visually displayed.",
      "status": "evidence-ready",
      "evidence": "Forest plots and per-analysis tables are generated from the Stata outputs.",
      "where": "Forest plots; Summary of Findings"
    },
    {
      "item": "13d",
      "section": "Methods",
      "requirement": "Synthesis method, model and software.",
      "status": "evidence-ready",
      "evidence": "REML random-effects with Hartung-Knapp intervals where k permits, StataNow 19.5; single-study rows are labelled as not pooled.",
      "where": "Per-analysis estimator; Stata do-files and logs"
    },
    {
      "item": "13e",
      "section": "Methods",
      "requirement": "How heterogeneity was explored (subgroups, meta-regression).",
      "status": "evidence-ready",
      "evidence": "I² and τ² reported per analysis; subgroup and meta-regression outputs exist. 12 analyses show considerable heterogeneity.",
      "where": "Heterogeneity statistics; subgroup / meta-regression log"
    },
    {
      "item": "13f",
      "section": "Methods",
      "requirement": "Sensitivity analyses used to assess robustness.",
      "status": "evidence-ready",
      "evidence": "21 of 45 computed analyses are sensitivity variants, including leave-one-out and the conversion-factor sensitivity.",
      "where": "Sensitivity analyses; “computed but not reported” panel"
    },
    {
      "item": "14",
      "section": "Methods",
      "requirement": "Methods to assess risk of bias due to missing results.",
      "status": "attention",
      "evidence": "Funnel-plot asymmetry testing is uninformative below about 10 studies and every analysis here is smaller, so no statistical assessment was possible. The manuscript must state this rather than omit the item.",
      "where": "Limitations — publication and reporting bias"
    },
    {
      "item": "15",
      "section": "Methods",
      "requirement": "Methods for assessing certainty in the body of evidence.",
      "status": "evidence-ready",
      "evidence": "GRADE applied by explicit rule; 10 model ratings are computed from the analysis inputs and disclose that they are rule-based, not an independent panel judgement.",
      "where": "GRADE Summary of Findings; the GRADE rule script"
    },
    {
      "item": "16a",
      "section": "Results",
      "requirement": "Numbers screened, assessed and included, ideally with a flow diagram.",
      "status": "evidence-ready",
      "evidence": "Full PRISMA flow: 5,100 references resolving to 5,088 studies, 2,160 removed, 2,928 screened, 224 sought, 210 assessed, 70 included.",
      "where": "PRISMA flow panel"
    },
    {
      "item": "16b",
      "section": "Results",
      "requirement": "Studies excluded at full text, with reasons.",
      "status": "evidence-ready",
      "evidence": "141 exclusions with reasons, itemised by category.",
      "where": "PRISMA flow panel"
    },
    {
      "item": "17",
      "section": "Results",
      "requirement": "Cite and describe the characteristics of each included study.",
      "status": "evidence-ready",
      "evidence": "All 70 included reports (69 trials) carry extracted characteristics and a citation.",
      "where": "Study characteristics panel"
    },
    {
      "item": "18",
      "section": "Results",
      "requirement": "Risk-of-bias assessments for each included study.",
      "status": "evidence-ready",
      "evidence": "36 result-specific assessments with all five domains and an overall judgement.",
      "where": "Result-specific RoB 2 panel"
    },
    {
      "item": "19",
      "section": "Results",
      "requirement": "For each study, summary statistics and effect estimates.",
      "status": "evidence-ready",
      "evidence": "Per-study arm data and effect estimates are stored for every contributing contrast.",
      "where": "Outcome data; forest plots"
    },
    {
      "item": "20a",
      "section": "Results",
      "requirement": "For each synthesis, characteristics and risk of bias of contributors.",
      "status": "evidence-ready",
      "evidence": "Each analysis records its contributing studies and their RoB composition.",
      "where": "Model rollup; per-analysis panels"
    },
    {
      "item": "20b",
      "section": "Results",
      "requirement": "For each synthesis, the summary estimate, precision and heterogeneity.",
      "status": "evidence-ready",
      "evidence": "22 reported analyses, each with estimate, confidence interval, I² and prediction interval where available.",
      "where": "Summary of Findings; forest plots"
    },
    {
      "item": "20c",
      "section": "Results",
      "requirement": "Results of heterogeneity investigations.",
      "status": "evidence-ready",
      "evidence": "Subgroup and meta-regression outputs are generated and logged.",
      "where": "Subgroup / meta-regression log"
    },
    {
      "item": "20d",
      "section": "Results",
      "requirement": "Results of sensitivity analyses.",
      "status": "evidence-ready",
      "evidence": "21 sensitivity analyses computed, with leave-one-out per analysis.",
      "where": "Sensitivity analyses"
    },
    {
      "item": "21",
      "section": "Results",
      "requirement": "Risk of bias due to missing results in the synthesis.",
      "status": "attention",
      "evidence": "Not assessable statistically at these k. What can be reported instead is documented: 7 analyses computed and not reported, each with its reason, and the open author-contact roster.",
      "where": "“Computed but not reported” panel; author outreach roster"
    },
    {
      "item": "22",
      "section": "Results",
      "requirement": "Certainty of evidence for each outcome assessed.",
      "status": "evidence-ready",
      "evidence": "All 22 reported analyses carry an adopted certainty rating; the exploratory Tier E rows are explicitly ungraded and labelled as such.",
      "where": "GRADE Summary of Findings"
    },
    {
      "item": "23a",
      "section": "Discussion",
      "requirement": "General interpretation of the results in context.",
      "status": "evidence-ready",
      "evidence": "Draft Results-safe and Discussion-safe wording exists for every analysis, with claim boundaries, plus a trial-by-trial comparison with the prior meta-analysis.",
      "where": "Manuscript Lens; comparison with prior evidence"
    },
    {
      "item": "23b",
      "section": "Discussion",
      "requirement": "Limitations of the evidence included.",
      "status": "evidence-ready",
      "evidence": "12 limitations assembled from the review's own outputs, each with the figures behind it.",
      "where": "Limitations panel"
    },
    {
      "item": "23c",
      "section": "Discussion",
      "requirement": "Limitations of the review processes used.",
      "status": "attention",
      "evidence": "Partly assembled. The risk-of-bias assessor process is deliberately deferred while independent dual assessment is in progress, and must be written once it concludes.",
      "where": "Limitations panel — deferred items"
    },
    {
      "item": "23d",
      "section": "Discussion",
      "requirement": "Implications for practice, policy and future research.",
      "status": "manuscript-only",
      "evidence": "Authorial. The discussion prompts on each analysis are drafting aids for it, not content.",
      "where": "Manuscript Lens — questions for manuscript discussion"
    },
    {
      "item": "24a",
      "section": "Other",
      "requirement": "Registration name and number, or a statement that it is unregistered.",
      "status": "evidence-ready",
      "evidence": "Registered on PROSPERO as CRD420251090635.",
      "where": "Protocol and registration"
    },
    {
      "item": "24b",
      "section": "Other",
      "requirement": "Where the protocol can be accessed, or that none was prepared.",
      "status": "evidence-ready",
      "evidence": "A locked protocol scope document is held in the repository.",
      "where": "00_protocol/protocol_scope_locked.md"
    },
    {
      "item": "24c",
      "section": "Other",
      "requirement": "Amendments to registration or protocol, with rationale.",
      "status": "evidence-ready",
      "evidence": "2 recorded amendment(s): 2026-08-14 primary outcome screening focus; 2026-08-20 english full text eligibility.",
      "where": "00_protocol/amendments/"
    },
    {
      "item": "25",
      "section": "Other",
      "requirement": "Sources of financial and non-financial support, and the funder's role.",
      "status": "manuscript-only",
      "evidence": "Authorial. Nothing in this repository records it.",
      "where": "Manuscript funding statement"
    },
    {
      "item": "26",
      "section": "Other",
      "requirement": "Competing interests of the review authors.",
      "status": "manuscript-only",
      "evidence": "Authorial. Nothing in this repository records it.",
      "where": "Manuscript competing-interests statement"
    },
    {
      "item": "27",
      "section": "Other",
      "requirement": "Availability of data, code, and other materials (extracted data, analytic code).",
      "status": "evidence-ready",
      "evidence": "The extraction dataset is SHA-256 pinned, the Stata do-files and logs are held with it, and every generated dashboard artefact names the script that produced it.",
      "where": "Repository and downloads; locked master workbook"
    }
  ],
  "counts": {
    "evidence-ready": 30,
    "manuscript-only": 6,
    "attention": 6
  },
  "total": 42
};
