// GENERATED by scripts/build_rob2_source_links.py -- do not hand-edit.
// Partial by construction -- see disclaimer field. Keyed "studyId::bucket".
window.ROB2_SOURCE_LINKS = {
  "generated_by": "scripts/build_rob2_source_links.py",
  "disclaimer": "Links each RoB 2 matrix cell to the specific per-domain, source-quoted rationale and source PDF it has in the review's RoB 2 registers, where that link can be established without guessing -- an explicit keyword/timepoint rule matching exactly one candidate result for that study, a hard numeric match against the dashboard's own stored denominator, or (a small, individually-documented set of cases) a match hand-verified by reading the source PDF directly, listed in MANUAL_OVERRIDES in this script with the exact evidence read. Coverage is partial by construction: a cell with no entry here has no ambiguity-free match, not a missing quote -- see the dashboard's own note on those cells. No page number is given because none exists in the source registers; the source PDF filename is the exact locator available.",
  "total_assessed_results": 74,
  "linked_count": 43,
  "coverage": 0.5811,
  "links": {
    "1879897477::pca_behavior": {
      "study": "Lin 2002",
      "matched_outcome": "Cumulative IV PCA morphine delivered during postoperative test period",
      "matched_timepoint": "Postoperative hour 1 through next 23 h (published as 24-h test-period value)",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "patients 'randomly divided into four groups of 25 each by a computer-generated randomization', with no concealment mechanism (e.g. sealed envelope) confirmed in the extracted text",
        "2": "'Subjects and electrical equipment were placed such that subjects were unable to see any specifics regarding the type of current administered, and technicians maintained a normal persona to ensure that patients remained unaware of their grouping category'",
        "3": "'All enrolled patients completed the study period with no withdrawals'",
        "5": "the extracted text confirms a sample-size/power calculation for detecting an inter-group difference but does not itself name PCA morphine consumption as a pre-specified primary/secondary outcome",
        "4": "a device-logged PCA record for a participant blinded via a genuine sham, handled by technicians instructed to conceal group assignment"
      },
      "flags": "PCA morphine consumption not confirmed as a named pre-specified outcome in the extracted text",
      "source_pdf": "covidence_951_lin_2002.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879897479::opioid_24h": {
      "study": "Sim 2002",
      "matched_outcome": "Postoperative IV PCA morphine in interval",
      "matched_timepoint": "18–24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "5": "this is a pre-2004 trial with no formal primary/secondary outcome declaration, but the measure is prospectively described in the Methods as part of the planned data collection, not introduced only in the Results",
        "1": "'The patients were randomised by the use of a table of random numbers', with no allocation-concealment mechanism described",
        "2": "'the acupuncturist and the anaesthetists involved in this study were aware of the group assignment', but 'Patients in Group I and II were blinded to the types of acupuncture administered' and 'An independent observer blinded to the group assignments carried out the postoperative assessment in this study'",
        "3": "no losses to follow-up or exclusions are reported; all 90 randomised patients (30 per group) appear in the results",
        "4": "PCA morphine consumption is an objective device record, collected as part of the blinded independent observer's postoperative assessment"
      },
      "flags": "",
      "source_pdf": "covidence_952_full_article.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879897479::intraop_remi": {
      "study": "Sim 2002",
      "matched_outcome": "Alfentanil requirement rate",
      "matched_timepoint": "Intraoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "5": "a 'Protocol for Alfentanil Administration' is described in the Methods; this is a pre-2004 trial with no formal primary/secondary outcome declaration, but the measure is prospectively described in the Methods as part of the planned data collection, not introduced only in the Results",
        "1": "'The patients were randomised by the use of a table of random numbers', with no allocation-concealment mechanism described",
        "2": "'the acupuncturist and the anaesthetists involved in this study were aware of the group assignment', but 'Patients in Group I and II were blinded to the types of acupuncture administered' and 'An independent observer blinded to the group assignments carried out the postoperative assessment in this study'",
        "3": "no losses to follow-up or exclusions are reported; all 90 randomised patients (30 per group) appear in the results",
        "4": "intraoperative alfentanil is titrated by the anaesthetist, who is explicitly stated to have been 'aware of the group assignment' -- the person controlling this dose was not blinded"
      },
      "flags": "unblinded anaesthetist is the outcome recorder for this intraoperative result",
      "source_pdf": "covidence_952_full_article.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879897414::opioid_72h": {
      "study": "Wong 2006",
      "matched_outcome": "IV PCA morphine consumption",
      "matched_timepoint": "First 3 postoperative days total",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "patients were 'randomized', but no sequence-generation or allocation-concealment method is described",
        "2": "'Both the patients and all surgeons in charge of postoperative patient care were blinded to the nature of the acupuncture'; the sham used 'a blunt-tip needle ... pressed to the same acupoints ... mimicking the pinprick sensation without actual skin piercing ... fixed with an opaque fixator to blind'",
        "3": "2 of 27 (7.4%) excluded post-randomisation for complications unrelated to acupuncture, documented",
        "5": "'The average visual analog scale pain scores and the cumulative PCA morphine usage were the primary outcome measures.'",
        "4": "both the participant and the surgeons responsible for postoperative care were blinded to allocation"
      },
      "flags": "",
      "source_pdf": "covidence_912_wong_2006.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879897195::flatus_time": {
      "study": "Ng 2013",
      "matched_outcome": "Time to first flatus",
      "matched_timepoint": "Postoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'A sealed nonopaque envelope ... was opened to determine the limb of entry' -- the report states explicitly that the concealment envelopes were not opaque",
        "2": "the compared arms are EA vs sham acupuncture, both blinded, and 'the outcome assessor were blinded to the treatment allocation'",
        "3": "'There was no withdrawal or dropout, and all recruited patients were available for analysis'",
        "5": "explicitly named among the secondary outcomes -- 'time of first passing flatus, time that the patients tolerated a solid diet, time to walk independently, duration of hospital stay, pain scores on visual analogue scale'",
        "4": "the outcome assessor was blinded, and both compared arms (EA and sham acupuncture) are equally blinded to the participant"
      },
      "flags": "",
      "source_pdf": "covidence_1970_ng_2013.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879897120::rescue_analgesia": {
      "study": "Ntritsou 2014",
      "matched_outcome": "Total rescue analgesia",
      "matched_timepoint": "First 24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'The randomisation was concealed by the director of the anaesthesiology department', who was not otherwise involved in the trial",
        "2": "'a sham-controlled participant- and observer-blinded trial'; patients were anaesthetised for the initial EA application and the second (postoperative) application was given under a sham protocol 'just after awakening from anaesthesia'",
        "3": "70 of 75 (93.3%) completed the study (3 control, 2 EA group excluded)",
        "5": "identical reasoning -- rescue analgesia total is not confirmed as a named pre-specified outcome in the extracted text",
        "4": "recorded by the blinded observer for a participant blinded via a credible sham protocol"
      },
      "flags": "rescue analgesia total not confirmed among the extracted named outcomes",
      "source_pdf": "covidence_729_full_article.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879897091::intraop_remi": {
      "study": "Zhang 2014",
      "matched_outcome": "Remifentanil consumption rate",
      "matched_timepoint": "Intraoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'a randomisation sequence based on a table of randomly generated numbers'; 'both the randomisation and allocation lists were concealed from the anaesthetists who gave the general anaesthetic to study patients'",
        "2": "'The patients were not informed of the allocation, and blinding was assured for other persons involved in the study by using placebo gel electrodes applied to the same acupressure p[oints]'; 'Recovery room nursing personnel were blinded to patient study groups'; the treating acupuncturist was not masked but 'none participated in data acquisition and analysis'",
        "3": "7 of 72 (9.7%) dropped out (3 declined TEAS, remainder met exclusion criteria), documented",
        "5": "explicitly named among the secondary endpoints -- 'the consumption of anaesthetics, the time to removal of the LMA, the time to reorientation and postoperative side-effects (incidence of respiratory dep[ression, nausea and vomiting])'",
        "4": "uniquely among this review's trials, 'both the randomisation and allocation lists were concealed from the anaesthetists who gave the general anaesthetic', so intraoperative dosing was set under genuinely blinded conditions"
      },
      "flags": "",
      "source_pdf": "043_zhang_2014.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879897004::opioid_24h": {
      "study": "Chen 2015",
      "matched_outcome": "Cumulative rescue IV morphine dose derived from fixed 2-mg rescue administrations",
      "matched_timepoint": "0-24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'assigned ... by a table of computer-generated random numbers', 1:1, 'sealed in sequentially numbered opaque envelopes'",
        "2": "'The patients, attending anesthesiologist, surgeons and data collector were blinded to group assignment'; placebo-controlled with a no-stimulation device",
        "3": "1 of 84 excluded for protocol breach (1.2%), 83 analysed",
        "5": "registered NCT02333747 with PONV named as the pre-specified secondary outcome; this derived morphine-dose figure (calculated from a fixed 2-mg-per-rescue assumption) is not itself the paper's own named outcome or reported figure",
        "4": "rescue administrations are a blinded-data-collector record for a blinded participant; the conversion itself introduces no additional measurement-blinding risk"
      },
      "flags": "underlying morphine-dose figure is a review-derived calculation, not a named pre-specified outcome",
      "source_pdf": "037_chen_2015_thyroidectomy_lund.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879897004::rescue_analgesia": {
      "study": "Chen 2015",
      "matched_outcome": "Cumulative rescue IV morphine dose derived from fixed 2-mg rescue administrations",
      "matched_timepoint": "0-24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'assigned ... by a table of computer-generated random numbers', 1:1, 'sealed in sequentially numbered opaque envelopes'",
        "2": "'The patients, attending anesthesiologist, surgeons and data collector were blinded to group assignment'; placebo-controlled with a no-stimulation device",
        "3": "1 of 84 excluded for protocol breach (1.2%), 83 analysed",
        "5": "registered NCT02333747 with PONV named as the pre-specified secondary outcome; this derived morphine-dose figure (calculated from a fixed 2-mg-per-rescue assumption) is not itself the paper's own named outcome or reported figure",
        "4": "rescue administrations are a blinded-data-collector record for a blinded participant; the conversion itself introduces no additional measurement-blinding risk"
      },
      "flags": "underlying morphine-dose figure is a review-derived calculation, not a named pre-specified outcome",
      "source_pdf": "037_chen_2015_thyroidectomy_lund.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879897029::opioid_24h": {
      "study": "Chen 2015 (Hyperalgesia)",
      "matched_outcome": "Derived cumulative sufentanil dose from fixed 0.05 µg/kg bolus",
      "matched_timepoint": "0-24 h",
      "match_method": "manual_source_verified",
      "domains": {
        "1": "computer-generated allocation list, sealed envelopes",
        "2": "'All study personnel including the patients, investigator, attending anesthetist, surgeons, recovery ward nurses, and the person who performed the statistical analysis were blinded to group assignments'",
        "3": "1 of 60 excluded for protocol breach",
        "5": "the underlying bolus count is a named secondary outcome, but this specific mass-dose figure is calculated by the review (bolus count x a fixed per-kg dose) rather than reported directly by the paper",
        "4": "the underlying bolus count feeding this calculation is a device-logged record under comprehensive blinding"
      },
      "flags": "mass-dose value is a review-derived calculation, not the paper's own reported figure",
      "source_pdf": "040_chen_2015_hyperalgesia_lund.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08",
      "match_evidence": "Two candidates share n=(29,30): a raw PCIA-bolus COUNT (the paper's own named secondary outcome per its D5 text) and a dose figure DERIVED from that count (bolus count × fixed per-bolus dose), whose own D5/flags text says so explicitly ('review-derived calculation, not the paper's own reported figure'). The bucket is a dose/mass measure ('Cumulative 24-h Opioid Consumption'), and the sibling study Chen 2015 (non-Hyperalgesia) resolves its own opioid_24h cell the same way -- to a dose derived from a fixed per-administration amount, not the raw administration count -- so this follows the review's own established convention for this exact situation rather than guessing between the two."
    },
    "1879897029::rescue_analgesia": {
      "study": "Chen 2015 (Hyperalgesia)",
      "matched_outcome": "Cumulative number of rescue sufentanil PCIA boluses",
      "matched_timepoint": "0-24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "computer-generated allocation list, sealed envelopes",
        "2": "'All study personnel including the patients, investigator, attending anesthetist, surgeons, recovery ward nurses, and the person who performed the statistical analysis were blinded to group assignments'",
        "3": "1 of 60 excluded for protocol breach",
        "5": "'cumulative number of rescue analgesia' is a named secondary outcome",
        "4": "PCIA bolus count is a device-logged record under this trial's comprehensive blinding"
      },
      "flags": "",
      "source_pdf": "040_chen_2015_hyperalgesia_lund.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879897026::rescue_analgesia": {
      "study": "Yao 2015",
      "matched_outcome": "Cumulative number of rescue analgesia administrations",
      "matched_timepoint": "0-24 h postoperative",
      "match_method": "manual_source_verified",
      "domains": {
        "1": "'Patients were assigned to either the TEAS group or the control group by a table of computer-generated random numbers'",
        "2": "'The patients, attending anesthesiologist, surgeons, recovery ward nurses, data collectors, and the person who performed the final statistical analysis were blinded to group assignment' in this double-blind, placebo-controlled trial",
        "3": "3 of 74 (4%) excluded, 71 analysed",
        "5": "'postoperative pain scores' is named generally; rescue-analgesia administration counts are not itself the specific reported metric",
        "4": "this trial achieved genuine participant blinding alongside comprehensive staff blinding, so even a subjective, self-reported component of this measure is not exposed to differential awareness of allocation"
      },
      "flags": "specific rescue-count metric not itself named among the outcomes",
      "source_pdf": "039_yao_2015.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08",
      "match_evidence": "Two candidates at n=(35,36): an administration COUNT and a TIME-TO-FIRST-administration. The dashboard's own outcome_name for this cell is 'Rescue sufentanil administration count' -- it names a count, not a time-to-event, and only one candidate is a count. The distinguishing-token tiebreak misses this because 'administration' (singular, target) and 'administrations' (plural, candidate) are different tokens under exact matching, not because the evidence is actually ambiguous."
    },
    "1879896692::rescue_analgesia": {
      "study": "Yu 2020",
      "matched_outcome": "Participants requiring rescue sufentanil",
      "matched_timepoint": "0-24 h postoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'random numbers generated by a computer'; 'Only the acupuncturist was informed by the nurse of the randomization allocation'",
        "2": "'Blinding of the patients was ensured by using gel electrodes in the same therapeutic setting, which has previously been proved to be a successful strategy'; 'None of the anesthesiologists, surgeons, physicians in the post-anesthesia care unit (PACU), or participants were aware of the allocation'",
        "3": "all 60 randomised patients (30/30) appear in the analysis",
        "5": "explicitly named among the secondary endpoint -- 'anesthesia-related side effects, including pain scores, the incidence of nausea and vomiting and use of postoperative pain medications and antiemetics'",
        "4": "'BN, who was blinded to grouping, conducted the data collection and administered the questionnaires' for this trial's outcomes"
      },
      "flags": "",
      "source_pdf": "s13063-019-3892-4.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896610::intraop_remi": {
      "study": "Liang 2021",
      "matched_outcome": "Remifentanil consumption",
      "matched_timepoint": "Intraoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'randomly distributed into two groups, with the help of a computer-generated table of random numbers by an independent statistician'; that statistician 'created identical sealed envelopes before surgery'",
        "2": "'An anesthesiologist (LDD), who was not aware of the allocation, performed general anesthesia and all intraoperative data recording, and another investigator (WL), in charge of all postoperative assessments, was also blinded to the group identity'",
        "3": "5 of 75 randomised lost (surgical procedure change n=3; blood-sample loss), 6.7%, with documented reasons unrelated to the outcome; CONSORT reports none excluded from analysis of those followed up",
        "4": "remifentanil was recorded intraoperatively by the anaesthesiologist who was explicitly 'not aware of the allocation'",
        "5": "the trial's stated outcomes centre on catheter-related bladder discomfort, MMSE, PONV, pain and QoR-40; intraoperative opioid consumption appears in Table 1 as an anaesthetic characteristic rather than as a named pre-specified outcome"
      },
      "flags": "result not among pre-specified outcomes",
      "source_pdf": "014_liang_2021.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896597::pain_rest_24h": {
      "study": "Liu 2021",
      "matched_outcome": "VAS at rest",
      "matched_timepoint": "24 h",
      "match_method": "tiebreak_distinguishing_token",
      "domains": {
        "1": "'The randomization was performed using an online randomization tool', with no allocation-concealment mechanism described",
        "2": "the only specific blinding statement in this report is 'The trained researchers who performed the MMSE score were blinded to the grouping of patients' -- blinding for the clinicians recording pain/opioid outcomes is not separately confirmed",
        "3": "the analysed 50/50 matches the 100 enrolled patients, with no reported losses",
        "5": "this trial's registered focus is postoperative cognitive dysfunction; pain and opioid-consumption measures are reported without being clearly named as pre-specified outcomes alongside POCD",
        "4": "no blinded-assessor statement specific to this measure is given (only MMSE administration is confirmed blinded), and it is self-reported or clinician-set without a stated safeguard"
      },
      "flags": "",
      "source_pdf": "getfile.php-2.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896597::pca_behavior": {
      "study": "Liu 2021",
      "matched_outcome": "PCA pump compressions",
      "matched_timepoint": "0-24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'The randomization was performed using an online randomization tool', with no allocation-concealment mechanism described",
        "2": "the only specific blinding statement in this report is 'The trained researchers who performed the MMSE score were blinded to the grouping of patients' -- blinding for the clinicians recording pain/opioid outcomes is not separately confirmed",
        "3": "the analysed 50/50 matches the 100 enrolled patients, with no reported losses",
        "5": "this trial's registered focus is postoperative cognitive dysfunction; pain and opioid-consumption measures are reported without being clearly named as pre-specified outcomes alongside POCD",
        "4": "a device-logged count, but the report does not confirm blinding for whoever set up or monitored the PCA regimen"
      },
      "flags": "",
      "source_pdf": "getfile.php-2.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896580::ponv_24h": {
      "study": "Lu 2021",
      "matched_outcome": "Any PONV",
      "matched_timepoint": "24 h",
      "match_method": "denominator_exact_match",
      "domains": {
        "1": "randomisation via 'a secured web-based system that was stratified according to permuted blocks'",
        "2": "'anesthesiologists, surgeons, and outcome assessors were blinded to the interventions', but 'The patients and investigators who participated in the intervention were not masked'",
        "3": "analysed in the intention-to-treat population, with a documented worst-case imputation approach for missing pain-status data",
        "5": "explicitly named among the secondary endpoints -- 'remifentanil consumption during general anesthesia, the time to the first verbal response and the time to endotracheal extubation, postoperative nausea and vomiting (PONV), respiratory depression, numeric rating scale (NRS) scores, and demand for rescue analgesics, patient satisfaction scores on analgesia by 24 h after surgery, and the incidence of chronic pain at 3 months after surgery'",
        "4": "PONV recorded by blinded outcome assessors"
      },
      "flags": "",
      "source_pdf": "covidence_414_full_article.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896580::intraop_remi": {
      "study": "Lu 2021",
      "matched_outcome": "Total remifentanil",
      "matched_timepoint": "Intraoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "randomised 1:1:1 'using a secured web-based system that was stratified according to permuted blocks' across six centres; baseline characteristics did not differ",
        "2": "'We performed all the analyses in an intention-to-treat population'; although 'The patients and investigators who participated in the intervention were not masked', 'The stimulator was placed in an opaque box to blind the surgical team and anesthesiologist', and protocol adherence was audited by an independent observer",
        "3": "this is an intraoperative measurement with no missing data — all 190/188 randomised patients contribute",
        "4": "remifentanil was administered and recorded by the anaesthesia team, who were blinded by the opaque-box arrangement",
        "5": "registered NCT02741726 with the protocol supplied; 'The secondary endpoints included remifentanil consumption during general anesthesia' — explicitly pre-specified"
      },
      "flags": "",
      "source_pdf": "covidence_414_full_article.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896608::ponv_48h": {
      "study": "Xiong 2021",
      "matched_outcome": "Clinically important PONV",
      "matched_timepoint": "Within 48 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'the patients were randomly assigned to the TEAS or control groups using a computerized random number generator'; 'Group assignment was exposed from a sealed envelope only by an acupuncturist'; 'The acupoint stimulation instrument was covered with an opaque box'",
        "2": "'The patients were blinded to the group assignment'; the intraoperative anaesthetist was not blind but 'was not involved in the postoperative assessment', which was instead performed by 'An anesthetic resident who was not involved in the anesthesia routine and who was blinded to the group assignments'",
        "3": "5 of 67 screened patients excluded before randomisation (documented reasons); all 62 randomised (31/31) completed",
        "5": "this trial's central focus is PONV prophylaxis; clinically important PONV is the core comparison reported throughout the Results",
        "4": "postoperative follow-up and data collection were performed by 'an anesthetic resident who was not involved in the anesthesia routine and who was blinded to the group assignments', for genuinely blinded participants"
      },
      "flags": "",
      "source_pdf": "covidence_431_full_article.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896611::opioid_24h": {
      "study": "Zhou 2021",
      "matched_outcome": "Any postoperative opioid use",
      "matched_timepoint": "Postoperative window not clearly defined as 0-24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'We randomized patients according to the order of the random number table generated by SPSS 21.0', with allocation performed by a single named research team member and no independent concealment mechanism described",
        "2": "'This was an unblinded randomized controlled trial' -- no blinding of participants, clinicians, or assessors was attempted",
        "3": "patients with Clavien-Dindo grade >2 'met the withdrawal criteria and were not included in the analysis', but no confirmed final completion count was found in the extracted text",
        "5": "'The primary outcomes were pain score and consumption of analgesics.'",
        "4": "recorded in an open-label trial with no blinding of the participant, treating clinicians, or outcome assessors at any stage"
      },
      "flags": "",
      "source_pdf": "getfile.php-5.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896426::flatus_time": {
      "study": "Lu 2022",
      "matched_outcome": "Time to first flatus",
      "matched_timepoint": "Postoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'randomly assigned ... in a ratio of 1:1 using a computer-generated random allocation sequence'; 'The randomization code for each patient was put in sealed envelope and not opened until allocation'; multicentre",
        "2": "participants were not blinded — 'For logistic reasons, blinding the patients was hard to perform' and 'The patient may tell the investigator who did the follow-up that he/she felt a stimuli'; the mITT population excludes 6 randomised patients, one of them 'due to rejection to TEAS', which is an exclusion related to a deviation from the intended intervention",
        "3": "6 of 100 (6%) excluded post-randomisation with documented reasons (5 conversions to open surgery, 1 refusal)",
        "5": "registered NCT02921529; 'The secondary outcomes included time to flatus, time to first defecation' — both explicitly pre-specified",
        "4": "first flatus is self-reported by unblinded participants; the authors themselves note that 'flatus is sometimes regarded as an insensitive index' and chose defecation instead precisely because it is more objective"
      },
      "flags": "",
      "source_pdf": "getfile.php-3.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896460::pain_rest_24h": {
      "study": "Xing 2022",
      "matched_outcome": "Rest pain VAS",
      "matched_timepoint": "24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'computer-generated random numbers'; 'Randomization codes were kept in a sealed envelope and relayed to an independent nurse'",
        "2": "'The allocation was blinded for all patients, surgeons, the leading anesthesiologist, physician in the post-anesthesia care unit, and follow-up observers until the end of the study'; 'The TEAS stimulator was obscured by an opaque cloth'",
        "3": "1 participant lost per arm (29/29 of 30/30)",
        "5": "registered ChiCTR2100042119 with QoR-15 as the primary outcome; this result is reported under 'Other secondary outcomes ... shown in Table 3' without being individually named in a pre-specified list",
        "4": "'The researchers who conducted data collection and performed the outcome assessment were blinded to group allocation', and participants were blinded by the opaque-cloth arrangement"
      },
      "flags": "",
      "source_pdf": "s40122-022-00429-2.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896460::ponv_48h": {
      "study": "Xing 2022",
      "matched_outcome": "PONV incidence",
      "matched_timepoint": "Postoperative",
      "match_method": "manual_source_verified",
      "domains": {
        "1": "'computer-generated random numbers'; 'Randomization codes were kept in a sealed envelope and relayed to an independent nurse'",
        "2": "'The allocation was blinded for all patients, surgeons, the leading anesthesiologist, physician in the post-anesthesia care unit, and follow-up observers until the end of the study'; 'The TEAS stimulator was obscured by an opaque cloth'",
        "3": "1 participant lost per arm (29/29 of 30/30)",
        "5": "registered ChiCTR2100042119 with QoR-15 as the primary outcome; this result is reported under 'Other secondary outcomes ... shown in Table 3' without being individually named in a pre-specified list",
        "4": "'The researchers who conducted data collection and performed the outcome assessment were blinded to group allocation', and participants were blinded by the opaque-cloth arrangement"
      },
      "flags": "",
      "source_pdf": "s40122-022-00429-2.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08",
      "match_evidence": "The only PONV row for this study carries timepoint 'Postoperative' with no hour figure, so the keyword+timepoint rule cannot place it in ponv_24h vs ponv_48h. Read the source PDF directly (s40122-022-00429-2.pdf) to settle it: 'The frequency of PONV was reported by 5 patients in the NTG group, 11 patients in the NG group, and 13 patients in the G group within 48 h after surgery' -- the paper's own text states the window is 48 h."
    },
    "1879896460::flatus_time": {
      "study": "Xing 2022",
      "matched_outcome": "Time to first flatus",
      "matched_timepoint": "Postoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'We randomized patients ... using computer-generated random numbers'; 'Randomization codes were kept in a sealed envelope and relayed to an independent nurse'",
        "2": "'The allocation was blinded for all patients, surgeons, the leading anesthesiologist, physician in the post-anesthesia care unit, and follow-up observers until the end of the study', and 'The TEAS stimulator was obscured by an opaque cloth throughout the experiment'; the comparator is sham TEAS with the same TAP block",
        "3": "1 participant lost to follow-up in each of the two relevant arms (29/29 of 30/30, 3.3%)",
        "5": "D5 remains Some concerns for the separate, unaffected reason that these outcomes are not individually pre-specified",
        "4": "first flatus is self-reported but participants were blinded by an active sham, and 'The researchers who conducted data collection and performed the outcome assessment were blinded to group allocation'"
      },
      "flags": "1:1:1 vs 1:1:1:1 allocation ratio wording; resolved 2026-09-09 as an apparent typo, not an unreported fourth arm",
      "source_pdf": "s40122-022-00429-2.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-09"
    },
    "1879896460::intraop_remi": {
      "study": "Xing 2022",
      "matched_outcome": "Total remifentanil consumption",
      "matched_timepoint": "Intraoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'We randomized patients ... using computer-generated random numbers'; 'Randomization codes were kept in a sealed envelope and relayed to an independent nurse'",
        "2": "'The allocation was blinded for all patients, surgeons, the leading anesthesiologist, physician in the post-anesthesia care unit, and follow-up observers until the end of the study', and 'The TEAS stimulator was obscured by an opaque cloth throughout the experiment'; the comparator is sham TEAS with the same TAP block",
        "3": "1 participant lost to follow-up in each of the two relevant arms (29/29 of 30/30, 3.3%)",
        "5": "D5 remains Some concerns for the separate, unaffected reason that these outcomes are not individually pre-specified",
        "4": "'Remifentanil and propofol consumption ... were recorded' by an anaesthesia team blinded by the opaque-cloth arrangement"
      },
      "flags": "1:1:1 vs 1:1:1:1 allocation ratio wording; resolved 2026-09-09 as an apparent typo, not an unreported fourth arm",
      "source_pdf": "s40122-022-00429-2.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-09"
    },
    "1879896335::intraop_remi": {
      "study": "Guo 2023",
      "matched_outcome": "Remifentanil consumption",
      "matched_timepoint": "Intraoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'A randomization sequence was generated by ... SPSS 25.0 ... and the allocation code was performed by an independent technician'; baseline well matched (Table 1)",
        "2": "'The patients, anesthesiologists, surgeons, and observers were blinded to group assignment'; 'a standardized anesthetic protocol was elaborated and performed throughout the surgery'",
        "3": "18 of 128 randomised (14%) dropped out and only completers (55/55) were analysed, even though intraoperative remifentanil would have been recorded for every randomised patient; mitigated by the reported finding of 'No significant difference in baseline characteristics ... between the dropped patients and the completed patients'",
        "4": "remifentanil was titrated to BIS 40-60 by a blinded anaesthetist and taken from records",
        "5": "intraoperative remifentanil is not among the registered primary outcome (POCD by MoCA) or the listed secondary outcomes (MMSE, NRS pain and sleep, EORTC-QLQ-C30, chronic pain); it is reported as a perioperative anaesthetic characteristic"
      },
      "flags": "result not among pre-specified outcomes",
      "source_pdf": "006_guo_2023.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896440::opioid_24h": {
      "study": "Jin 2023",
      "matched_outcome": "Published 'fentanyl consumption' / PCIA solution volume",
      "matched_timepoint": "24 h",
      "match_method": "denominator_exact_match",
      "domains": {
        "1": "'randomized to receive ... with a 1:1 [allocation ratio]', with no sequence-generation or concealment method confirmed in the extracted text",
        "2": "'Participants, outcome assessors, data analysts, and statisticians were blinded to treatment allocation, and acupuncturists were not'; the device had 'power indicator lights covered and the battery compartment sealed to assist in blinding'",
        "3": "16 of 174 (9.2%) dropped out, with documented reasons",
        "5": "'fentanyl consumption at 48 hours after surgery' is the paper's named secondary outcome; this 24h extraction is a different timepoint from what is explicitly reported",
        "4": "recorded under comprehensive blinding of participants, outcome assessors, data analysts and statisticians"
      },
      "flags": "extracted timepoint (24h) differs from the paper's own named 48h fentanyl-consumption outcome",
      "source_pdf": "009_jin_2023.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896396::intraop_remi": {
      "study": "Pan 2023",
      "matched_outcome": "Intraoperative remifentanil",
      "matched_timepoint": "Intraoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'Patients were assigned to TEAS group (Group T) and control group (Group C) using random number tables', with no allocation-concealment mechanism described",
        "2": "described as a 'double-blind randomized control-group clinical trial', but the comparator is a control group and the report does not describe a sham device, so successful participant blinding is not established",
        "3": "105 patients were randomised (52 / 53) and 105 were analysed; the 15 documented exclusions (6 non-protocol analgesics, 6 different surgical procedure, 2 PCIA use, 1 intraoperative bleeding) occur in the enrolment flow before randomisation",
        "5": "registered ChiCTR2100045173; QoR-40 at 24 h is the stated primary outcome and 'dosage of remifentanil, propofol, any vasoactive drugs' is listed among the secondary outcome measures",
        "4": "the report documents blinding for the PACU nurse who collected NRS scores but does not state that the anaesthetist who titrated and recorded intraoperative remifentanil was blinded"
      },
      "flags": "",
      "source_pdf": "getfile.php-4.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896394::flatus_time": {
      "study": "Wang 2023",
      "matched_outcome": "Time to first flatus",
      "matched_timepoint": "Postoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'Patients were assigned to either the TEAS group or the Sham group by a table of computer-generated random numbers'; 'Group assignments were sealed in sequentially numbered opaque envelopes'; two-step screening with randomisation at final enrolment",
        "2": "'Patients, attending surgeons, operating room nurses, data collectors and individuals who performed the final statistical analysis were blinded to group assignment'; multicentre double-blind with a no-current sham",
        "3": "5 of 88 randomised were excluded post-randomisation 'because of a protocol breach' and only the 83 completers were analysed; for this outcome 40/43 of the randomised 43/45 contribute, with no ITT or sensitivity analysis",
        "4": "first flatus is self-reported, but participants were blinded by a credible no-current sham and the data collectors were blinded",
        "5": "registered ChiCTR2100054971 with postoperative sleep quality as the primary outcome; the listed secondary outcomes are VAS scores, rescue analgesia, abdominal distension, dizziness and PONV — time to first flatus is reported among the postoperative recovery data without being individually named in the pre-specified outcome list"
      },
      "flags": "pre-specification of this outcome not clearly established",
      "source_pdf": "s40122-023-00493-2.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896412::opioid_48h": {
      "study": "Zhang 2023",
      "matched_outcome": "Postoperative IV morphine-equivalent consumption",
      "matched_timepoint": "Within 48 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'randomly assigned to the TEAS or sham group in a 1:1 ratio using block randomization'; 'The randomized numbers were enclosed in sequentially numbered, sealed, opaque envelopes'",
        "2": "'The participants, outcome assessors, staff responsible for the postoperative care and statisticians were blinded to the treatment allocation'",
        "3": "53 and 57 of the 975/973 randomised (5.6% overall) withdrew, leaving 1,838 analysed",
        "5": "explicitly named among the secondary outcomes -- 'postoperative urinary retention (POUR), voiding difficulty, oliguria, nocturia, postoperative pain, sleep quality, anxiety and depression, vomiting, early ambulation, length of hospital stay'",
        "4": "'postoperative pain' is a named secondary outcome domain in this trial, assessed under the same comprehensive blinding"
      },
      "flags": "",
      "source_pdf": "covidence_308_full_article.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896323::flatus_time": {
      "study": "Yang 2024",
      "matched_outcome": "Time to first flatus",
      "matched_timepoint": "Postoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'Patients were randomly assigned to either usual care (UC) or EA group by computer-generated codes and sequentially numbered, opaque envelopes'",
        "2": "open-label against usual care — 'Given the characteristic of EA, the acupuncturist and patients were aware of the treatment allocation' — though 'anesthetists, assessors, the data collector as well as statisticians were blinded' and 'We conducted our analyses using the intention-to-treat principles'",
        "3": "ITT with 90 per group; 3 documented withdrawals (declined further EA, no PVB, conversion to open surgery)",
        "5": "registered ChiCTR1900024840; 'Primary outcomes of this study were time to first flatus and first defecation' — both are the pre-specified co-primary outcomes",
        "4": "'Times to first flatus and defecation measured in hours were recorded by the patients and then reported to our research assistant' — the timing is self-reported by participants who knew their allocation, and the authors concede that 'Because sham EA was not used in this study, the inadvertent interaction between assessors and patient in the UC group may affect the results'. Blinding the downstream assessor does not remedy an unblinded self-report. Specific to flatus: this endpoint has no external corroboration at all — unlike defecation it leaves no observable trace for a nurse to confirm — and the authors acknowledge that 'time to first flatus is difficult to assess accurately'. The reported between-group difference is 1.6 h on a self-reported timing"
      },
      "flags": "",
      "source_pdf": "covidence_1930_full_article.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896090::pca_behavior": {
      "study": "Long 2025",
      "matched_outcome": "PCIA compression count",
      "matched_timepoint": "48 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'randomly assigned to Group C (n=26) and Group A (n=27) using a random number table', with no allocation-concealment mechanism described",
        "2": "described as a 'double-masked'/'double-blind' trial, but the comparator is a 'non-stimulated control group' with no sham intervention described, and the report never states which personnel (participants, assessors, or both) were actually blinded or by what mechanism -- unlike other trials in this review that describe a concrete active-sham or name specific blinded roles",
        "3": "7 of 60 (11.7%) did not complete follow-up (2 withdrew consent, 1 cancelled surgery, 4 lost to follow-up), with reasons documented",
        "5": "recorded among the trial's stated outcome measures -- 'Adverse cardiovascular events, extubation duration, recovery room stay, analgesia pump use, analgesia pump use, postoperative adverse responses, and hospitalization length were recorded', with complications further detailed as 'Postoperative nausea and vomiting (PONV), abdominal discomfort, diarrhea, and other digestive disturbances ... The cardiovascular system included postoperative [hypertension, hypotension, tachycardia/bradycardia]'",
        "4": "the report gives no blinding detail for any specific outcome -- no stated blinded assessor, and the underlying participant/personnel blinding claim itself is not methodologically supported for this no-sham comparator"
      },
      "flags": "",
      "source_pdf": "1-s2.0-S0020138325005200.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896014::intraop_remi": {
      "study": "Zheng 2025",
      "matched_outcome": "Total intraoperative remifentanil consumption",
      "matched_timepoint": "Intraoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "allocation was by thresholding a seeded uniform random number — 'A fixed seed number (eg, 12345) was preset to generate random numbers ranging between 0 and 1. Participants with a random number <=0.5 were assigned to the experimental group' — a method that cannot guarantee the stated 1:1 ratio, yet exactly 44 and 44 were allocated; the described method and the reported allocation are inconsistent. Concealment itself is adequate: 'concealed in sequentially numbered, opaque, sealed envelopes, which were opened only at the time of anesthesia induction'",
        "2": "single-blind by design — 'the anesthesiologists were unblinded due to the nature of the intervention', which the authors list as a limitation ('the single-blind design may introduce performance bias'); participants and outcome assessors were blinded and a mITT analysis was used",
        "3": "3 of 88 excluded under pre-specified withdrawal criteria (2 procedure change, 1 procedure exceeding 3 hours)",
        "4": "intraoperative remifentanil is titrated and recorded by the anaesthesiologist, and the anaesthesiologists are precisely the personnel the report states were NOT blinded — the outcome is set by an unblinded clinician's own dosing decisions. The blinding of 'outcome assessors and data analysts' does not reach an intraoperative dose determined by the unblinded treating clinician",
        "5": "the pre-specified primary outcome is PONV within 24 h and the named secondary outcomes are QoR-40, PSQI, NRS, PCIA usage, gastrointestinal function recovery, adverse events, time to first flatus and length of stay; intraoperative remifentanil consumption is not among them"
      },
      "flags": "result not among pre-specified outcomes; unblinded dose-setter is the outcome recorder",
      "source_pdf": "109499.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-09"
    },
    "1879896105::flatus_time": {
      "study": "Zhou 2025",
      "matched_outcome": "Time to first flatus",
      "matched_timepoint": "Postoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'randomization into either the TEAS or Sham group at a 1:1 ratio, utilizing a computer-generated randomization sequence'; 'Allocation was concealed using sequentially numbered, sealed, opaque envelopes'",
        "2": "'single-center, randomized, double-blinded, sham-controlled trial'; 'Patients, anesthesiologists, surgeons, and data collectors remained blinded to group allocation'; the acupuncturist could not be blinded but 'adhered to a standardized interaction protocol for both groups', with 'scripted explanations, identical application of electrodes and device operation, and neutral responses to inquiries'",
        "3": "97 of 100 randomised completed (3%), 48/49 analysed",
        "4": "participants were blinded by a credible sham and 'time to first flatus' was collected by blinded data collectors as one of the pre-defined recovery times",
        "5": "registered ChiCTR2200055338 on 7 January 2022; QoR-15 is the primary outcome and time to first flatus is explicitly listed under the secondary 'Recovery times'"
      },
      "flags": "",
      "source_pdf": "105119.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879896105::rescue_analgesia": {
      "study": "Zhou 2025",
      "matched_outcome": "Any rescue analgesia",
      "matched_timepoint": "POD1-POD3",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'a computer-generated randomization sequence'; 'Allocation was concealed using sequentially numbered, sealed, opaque envelopes'",
        "2": "'Patients, anesthesiologists, surgeons, and data collectors remained blinded to group allocation'; a credible sham with a standardized interaction protocol for the (necessarily unblinded) acupuncturist",
        "3": "3 of 100 (3%) did not complete the study, documented reasons",
        "5": "named among the secondary outcomes -- postoperative pain (VAS), PONV incidence and rescue antiemetics, and 'Recovery times' including recovery-related timings",
        "4": "participants were blinded by a credible sham and 'data collectors' recording this result were also blinded"
      },
      "flags": "",
      "source_pdf": "105119.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879895909::opioid_24h": {
      "study": "He 2026 (hepatectomy/JIS)",
      "matched_outcome": "PCA attempts",
      "matched_timepoint": "24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "allocation 1:1 'through a secure web-based randomization system'; sequence 'generated using permuted blocks, stratified by treatment center'; assignment revealed by 'an independent investigator (uninvolved in anesthesia administration or outcome assessment)'",
        "2": "'The patients, anesthesiologists, outcome assessors, and ward staff remained unaware of treatment assignments'; the stimulator was 'placed inside an opaque box'",
        "3": "2 of 161 excluded (one cancelled surgery, one withdrew consent); a per-protocol sensitivity analysis agreed with the mITT result",
        "5": "registered NCT05396716 with POCD (MoCA) as the pre-specified primary outcome and MMSE, NRS pain/sleep, EORTC-QLQ-C30 and chronic pain as the listed secondary outcomes; PCA attempts are not among them, matching this study's own precedent finding for intraoperative remifentanil",
        "4": "a device-logged measure recorded under comprehensive blinding of patients, anaesthesiologists, and ward staff"
      },
      "flags": "result not among pre-specified outcomes, consistent with this study's own remifentanil precedent",
      "source_pdf": "covidence_25_verified.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879895909::pca_behavior": {
      "study": "He 2026 (hepatectomy/JIS)",
      "matched_outcome": "PCA attempts",
      "matched_timepoint": "24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "allocation 1:1 'through a secure web-based randomization system'; sequence 'generated using permuted blocks, stratified by treatment center'; assignment revealed by 'an independent investigator (uninvolved in anesthesia administration or outcome assessment)'",
        "2": "'The patients, anesthesiologists, outcome assessors, and ward staff remained unaware of treatment assignments'; the stimulator was 'placed inside an opaque box'",
        "3": "2 of 161 excluded (one cancelled surgery, one withdrew consent); a per-protocol sensitivity analysis agreed with the mITT result",
        "5": "registered NCT05396716 with POCD (MoCA) as the pre-specified primary outcome and MMSE, NRS pain/sleep, EORTC-QLQ-C30 and chronic pain as the listed secondary outcomes; PCA attempts are not among them, matching this study's own precedent finding for intraoperative remifentanil",
        "4": "a device-logged measure recorded under comprehensive blinding of patients, anaesthesiologists, and ward staff"
      },
      "flags": "result not among pre-specified outcomes, consistent with this study's own remifentanil precedent",
      "source_pdf": "covidence_25_verified.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879895960::rescue_analgesia": {
      "study": "Liu 2026 (burn)",
      "matched_outcome": "Any rescue dezocine use",
      "matched_timepoint": "Through POD1",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "allocation via 'a computer-generated [sequence]'; 'Allocations were concealed in sequentially numbered, opaque, sealed envelopes prepared by independent study monitors'",
        "2": "'All other individuals involved in the study (patients, surgeons, anesthesiologists, data collectors, data analysts) were blinded to the randomization and the stimulation'",
        "3": "16 of 102 excluded before analysis, with documented reasons (9 declined, 5 surgical modification, 1 other cause), leaving the analysed 43/43",
        "5": "explicitly named among the secondary outcomes -- 'intraoperative propofol dosage, patients' resting facial-visual analogue scale (F-VAS) scores before stimulation (F1), after stimulation (F2), at 24 h after surgery (F3), and 48 h after surgery (F4), the incidence of opioid-related adverse reactions, and the use of rescue analgesics until the first postoperative day'",
        "4": "this trial's blinding covers patients, surgeons, anaesthesiologists, data collectors and data analysts alike"
      },
      "flags": "",
      "source_pdf": "covidence_48_verified.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879895960::intraop_remi": {
      "study": "Liu 2026 (burn)",
      "matched_outcome": "Remifentanil consumption",
      "matched_timepoint": "Intraoperative",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "allocation via 'a computer-generated [sequence]'; 'Allocations were concealed in sequentially numbered, opaque, sealed envelopes prepared by independent study monitors'",
        "2": "'All other individuals involved in the study (patients, surgeons, anesthesiologists, data collectors, data analysts) were blinded to the randomization and the stimulation'",
        "3": "16 of 102 excluded before analysis, with documented reasons (9 declined, 5 surgical modification, 1 other cause), leaving the analysed 43/43",
        "5": "'The primary outcome was the intraoperative remifentanil dosage.'",
        "4": "this trial's blinding covers patients, surgeons, anaesthesiologists, data collectors and data analysts alike"
      },
      "flags": "",
      "source_pdf": "covidence_48_verified.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879895932::opioid_24h": {
      "study": "Luo 2026",
      "matched_outcome": "Cumulative postoperative oxycodone consumption",
      "matched_timepoint": "0-24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'Eligible participants were randomized in a 1:1 ratio using a computer-generated randomization sequence'",
        "2": "'patients, postoperative [outcome assessors] ... blinded outcome assessment: while the attending anesthesiologists performing the intervention could not be blinded' -- an intraoperative-only exception that does not affect these postoperative results; the sham used 'identical electrode placement and procedures ... however, the stimulator was turned off, and no electrical current was delivered'",
        "3": "277 enrolled against a planned minimum of 264 (132/group), with the analysed 138/139 essentially matching plan",
        "5": "not itself named among the stated secondary endpoints",
        "4": "opioid administration is not itself confirmed as an outcome the blinded assessors specifically tracked"
      },
      "flags": "result not among the pre-specified endpoints",
      "source_pdf": "covidence_35_verified.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879895932::vomiting_48h": {
      "study": "Luo 2026",
      "matched_outcome": "Cumulative postoperative vomiting",
      "matched_timepoint": "0-48 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'Eligible participants were randomized in a 1:1 ratio using a computer-generated randomization sequence'",
        "2": "'patients, postoperative [outcome assessors] ... blinded outcome assessment: while the attending anesthesiologists performing the intervention could not be blinded' -- an intraoperative-only exception that does not affect these postoperative results; the sham used 'identical electrode placement and procedures ... however, the stimulator was turned off, and no electrical current was delivered'",
        "3": "277 enrolled against a planned minimum of 264 (132/group), with the analysed 138/139 essentially matching plan",
        "5": "explicitly named among the secondary endpoints -- 'the rate of complete response (CR), the severity of PONV, the requirement for rescue antiemetics, postoperative pain scores, and the incidence of other adverse events'",
        "4": "assessed by blinded postoperative outcome assessors, for a participant who was also blinded via a genuine current-off sham"
      },
      "flags": "",
      "source_pdf": "covidence_35_verified.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879895855::nausea_24h": {
      "study": "Ma 2026",
      "matched_outcome": "Nausea",
      "matched_timepoint": "24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'This was a partially randomized controlled trial' -- patients with PSQI < 6 were assigned to a non-randomised reference control group, though the TEAS-vs-sham contrast extracted here is the genuinely randomised comparison",
        "2": "the authors state plainly that 'Allocation concealment was not feasible due to the physical nature of the TEAS intervention' and 'participant blinding was not feasible given the physical nature of the intervention', though 'An outcome assessor blinded to group allocation performed all data collection'",
        "3": "1 patient lost from each arm, documented ('incomplete postoperative data')",
        "5": "PONV incidence is named among the assessor's tracked postoperative measures",
        "4": "'All postoperative assessments (NRS pain scores, AIS sleep scores, PONV incidence) were conducted by the same blinded assessor', but this measure has a subjective, internal-sensation component that only the unblinded participant can report in the first place"
      },
      "flags": "",
      "source_pdf": "117210.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    },
    "1879895855::vomiting_24h": {
      "study": "Ma 2026",
      "matched_outcome": "Vomiting",
      "matched_timepoint": "24 h",
      "match_method": "keyword_timepoint_unique",
      "domains": {
        "1": "'This was a partially randomized controlled trial' -- patients with PSQI < 6 were assigned to a non-randomised reference control group, though the TEAS-vs-sham contrast extracted here is the genuinely randomised comparison",
        "2": "the authors state plainly that 'Allocation concealment was not feasible due to the physical nature of the TEAS intervention' and 'participant blinding was not feasible given the physical nature of the intervention', though 'An outcome assessor blinded to group allocation performed all data collection'",
        "3": "1 patient lost from each arm, documented ('incomplete postoperative data')",
        "5": "PONV incidence is named among the assessor's tracked postoperative measures",
        "4": "unlike nausea, vomiting is objectively observable and does not depend solely on the unblinded participant's own account, and it was recorded by the same blinded assessor"
      },
      "flags": "",
      "source_pdf": "117210.pdf",
      "adopted_by": "John Ryan N. Mendoza (review lead)",
      "adopted_date": "2026-09-08"
    }
  }
};
