// GENERATED by scripts/build_stratum_compliant_diagnostic.py -- do not hand-edit.
// DIAGNOSTIC ONLY. Shows what the protocol-compliant strata would give; it is
// not a finding and does not replace any reported analysis.
window.STRATUM_COMPLIANT_DIAGNOSTIC = {
  "generated_by": "scripts/build_stratum_compliant_diagnostic.py",
  "source": "06_FINAL_ANALYSIS_V26/03_RESULTS/results_stratum_compliant_diagnostic.csv",
  "status": "DIAGNOSTIC - not a finding, not an alternative headline result",
  "analyses": [
    {
      "analysis_id": "AN-02-TARGET-A",
      "reported_k": 3,
      "compliant_strata": 2,
      "estimable_strata": 1,
      "largest_k": 2,
      "strata": [
        {
          "modality": "TEAS",
          "comparator": "Sham",
          "k": 2,
          "studies": [
            "Chen 2020",
            "Zhang 2023"
          ],
          "estimable": true,
          "fit": {
            "units": "mg IV MME",
            "k": 2,
            "estimate": -12.39535676151819,
            "ci_low": -128.6307461090355,
            "ci_high": 103.8400325859991,
            "p_value": 0.4047530578069054,
            "i2": 98.59271781072646,
            "tau2": 165.0283448355937
          }
        },
        {
          "modality": "EA",
          "comparator": "Usual care",
          "k": 1,
          "studies": [
            "An 2014"
          ],
          "estimable": false
        }
      ],
      "source_modality_notes": {}
    },
    {
      "analysis_id": "AN-06-TARGET-D-48",
      "reported_k": 2,
      "compliant_strata": 2,
      "estimable_strata": 0,
      "largest_k": 1,
      "strata": [
        {
          "modality": "TEAS",
          "comparator": "Sham",
          "k": 1,
          "studies": [
            "Xing 2022"
          ],
          "estimable": false
        },
        {
          "modality": "TEAS",
          "comparator": "UNCLASSIFIED (Dexamethasone + tropisetron)",
          "k": 1,
          "studies": [
            "Xiong 2021"
          ],
          "estimable": false
        }
      ],
      "source_modality_notes": {}
    },
    {
      "analysis_id": "AN-07-TARGET-E",
      "reported_k": 7,
      "compliant_strata": 4,
      "estimable_strata": 2,
      "largest_k": 3,
      "strata": [
        {
          "modality": "TEAS",
          "comparator": "Sham",
          "k": 3,
          "studies": [
            "Xing 2022",
            "Zhang 2018",
            "Zhou 2025"
          ],
          "estimable": true,
          "fit": {
            "units": "hours",
            "k": 3,
            "estimate": -10.90304727287917,
            "ci_low": -47.11503927165348,
            "ci_high": 25.30894472589509,
            "p_value": 0.3245245330803426,
            "i2": 98.41275083990872,
            "tau2": 194.5001942481303
          }
        },
        {
          "modality": "EA",
          "comparator": "Usual care",
          "k": 2,
          "studies": [
            "Yang 2020",
            "Yang 2024"
          ],
          "estimable": true,
          "fit": {
            "units": "hours",
            "k": 2,
            "estimate": -1.909817662410532,
            "ci_low": -10.24864016944941,
            "ci_high": 6.429004844628343,
            "p_value": 0.2107166448401046,
            "i2": 18.0484780547938,
            "tau2": 0.2608007419800547
          }
        },
        {
          "modality": "EA",
          "comparator": "Sham",
          "k": 1,
          "studies": [
            "Ng 2013"
          ],
          "estimable": false
        },
        {
          "modality": "TEAS",
          "comparator": "Usual care",
          "k": 1,
          "studies": [
            "Lu 2022"
          ],
          "estimable": false
        }
      ],
      "source_modality_notes": {
        "Zhang 2018": "Source-verified: “Needleless Transcutaneous Electrical Acustimulation”; TEA “is a newly developed method of EA by replacing needles with surface electrodes”, electrodes at bilateral ST36 and PC6. The v34 outcome register leaves this unfilled."
      }
    }
  ]
};
