// Generated by scripts/build_reference_data.py; do not edit.
window.STUDY_CHARACTERISTICS = {
  "Chen 1998": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Elective total abdominal hysterectomy or myomectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/chen_1998_covidence_969_full_data_extraction.md",
    "source_line": 88,
    "source_excerpt": "| Surgical procedures | **Elective total abdominal hysterectomy or myomectomy** |"
  },
  "Lin 2002": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Abdominal hysterectomy / lower abdominal surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/lin_2002_covidence_951_full_data_extraction.md",
    "source_line": 88,
    "source_excerpt": "| Surgery | **Abdominal hysterectomy / lower abdominal surgery** |"
  },
  "Sim 2002": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Women undergoing elective total abdominal hysterectomy with or without bilateral salpingo-oophorectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/sim_2002_covidence_952_full_data_extraction.md",
    "source_line": 86,
    "source_excerpt": "| Population | Women undergoing elective **total abdominal hysterectomy with or without bilateral salpingo-oophorectomy** |"
  },
  "Wong 2006": {
    "surgery_category": "Thoracic & Cardiac",
    "surgery_procedure": "Anatomic lung resection with curative intent through thoracotomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/wong_2006_covidence_912_full_data_extraction.md",
    "source_line": 95,
    "source_excerpt": "| Surgery | **Anatomic lung resection with curative intent through thoracotomy** |"
  },
  "El-Rakshy 2009": {
    "surgery_category": "Mixed specialties",
    "surgery_procedure": "Elective abdominal hysterectomy or laparoscopic cholecystectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/el_rakshy_2009_covidence_868_full_data_extraction.md",
    "source_line": 121,
    "source_excerpt": "| Surgeries | **Elective abdominal hysterectomy or laparoscopic cholecystectomy** |"
  },
  "Yeh 2010": {
    "surgery_category": "Orthopedic & Spine",
    "surgery_procedure": "Patients undergoing surgery for nontraumatic lumbar spine injury/disorders",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/yeh_2010_spinal_aes_full_data_extraction.md",
    "source_line": 97,
    "source_excerpt": "| Population | Patients undergoing surgery for **nontraumatic lumbar spine injury/disorders** |"
  },
  "Coura 2011": {
    "surgery_category": "Thoracic & Cardiac",
    "surgery_procedure": "Adults undergoing elective conventional cardiac surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/coura_2011_covidence_819_full_data_extraction.md",
    "source_line": 98,
    "source_excerpt": "| Population | Adults undergoing **elective conventional cardiac surgery** |"
  },
  "Lee 2011": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Women undergoing hysterectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/lee_2011_covidence_49_full_data_extraction.md",
    "source_line": 94,
    "source_excerpt": "| Population | Women undergoing **hysterectomy** |"
  },
  "Yeh 2011": {
    "surgery_category": "Orthopedic & Spine",
    "surgery_procedure": "Patients undergoing surgery for non-traumatic lumbar spine disorders",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/yeh_2011_covidence_828_full_data_extraction.md",
    "source_line": 94,
    "source_excerpt": "| Population | Patients undergoing surgery for **non-traumatic lumbar spine disorders** |"
  },
  "Ng 2013": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Adults undergoing elective laparoscopic resection of colonic or upper rectal cancer",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/ng_2013_covidence_1970_full_data_extraction.md",
    "source_line": 99,
    "source_excerpt": "| Population | Adults undergoing **elective laparoscopic resection of colonic or upper rectal cancer** |"
  },
  "An 2014": {
    "surgery_category": "Neurosurgery",
    "surgery_procedure": "Adults undergoing supratentorial tumor resection / supratentorial craniotomy under general anesthesia",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/covidence_study_698_full_data_extraction.md",
    "source_line": 67,
    "source_excerpt": "| Population | Adults undergoing **supratentorial tumor resection / supratentorial craniotomy** under general anesthesia |"
  },
  "Ntritsou 2014": {
    "surgery_category": "Urologic",
    "surgery_procedure": "Men undergoing radical retropubic prostatectomy for prostate malignancy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/ntritsou_2014_covidence_729_full_data_extraction.md",
    "source_line": 104,
    "source_excerpt": "| Population | Men undergoing **radical retropubic prostatectomy for prostate malignancy** |"
  },
  "Xie 2014": {
    "surgery_category": "Thoracic & Cardiac",
    "surgery_procedure": "Patients undergoing elective radical esophagectomy for cancer",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/xie_2014_covidence_701_full_data_extraction.md",
    "source_line": 94,
    "source_excerpt": "| Population | Patients undergoing **elective radical esophagectomy for cancer** |"
  },
  "Zhang 2014": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Women undergoing elective cosmetic breast surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/zhang_2014_breast_surgery_teas_full_data_extraction.md",
    "source_line": 106,
    "source_excerpt": "| Population | Women undergoing **elective cosmetic breast surgery** |"
  },
  "Chen 2015": {
    "surgery_category": "Head, Neck & ENT",
    "surgery_procedure": "Elective thyroidectomy",
    "source_file": "TEAS EA Verification/astra_audit/source_text/037_chen_2015_thyroidectomy_lund.txt",
    "source_line": 23,
    "source_excerpt": "or II patients undergoing thyroidectomy were randomly allocated to TEAS or control groups. The primary outcome"
  },
  "Chen 2015 (Hyperalgesia)": {
    "surgery_category": "Head, Neck & ENT",
    "surgery_procedure": "Elective thyroidectomy",
    "source_file": "TEAS EA Verification/astra_audit/source_text/040_chen_2015_hyperalgesia_lund.txt",
    "source_line": 8,
    "source_excerpt": "undergoing thyroidectomy: a randomized controlled trial"
  },
  "Yao 2015": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Ovarian cystectomy or myomectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/yao_2015_full_data_extraction.md",
    "source_line": 105,
    "source_excerpt": "| Procedures | **Ovarian cystectomy or myomectomy** |"
  },
  "Grech 2016": {
    "surgery_category": "Head, Neck & ENT",
    "surgery_procedure": "Thyroid or parathyroid surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/grech_2016_full_data_extraction.md",
    "source_line": 51,
    "source_excerpt": "| Surgery | Thyroid or parathyroid surgery |"
  },
  "Seevaunnamtum 2016": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Total abdominal hysterectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/seevaunnamtum_2016_covidence_596_full_data_extraction.md",
    "source_line": 135,
    "source_excerpt": "| Surgery | **Total abdominal hysterectomy** |"
  },
  "Huang 2017": {
    "surgery_category": "Thoracic & Cardiac",
    "surgery_procedure": "VATS lobectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/huang_2017_covidence_666_full_data_extraction.md",
    "source_line": 126,
    "source_excerpt": "| Surgery | **VATS lobectomy** |"
  },
  "Sun 2017": {
    "surgery_category": "Mixed specialties",
    "surgery_procedure": "Adults undergoing laparoscopic cholecystectomy or laparoscopic gynecological surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/sun_2017_covidence_632_full_data_extraction.md",
    "source_line": 145,
    "source_excerpt": "| Population | Adults undergoing **laparoscopic cholecystectomy or laparoscopic gynecological surgery** |"
  },
  "Gu 2019": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Laparoscopic radical gastrectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/gu_2019_covidence_1471_full_data_extraction.md",
    "source_line": 101,
    "source_excerpt": "| Surgery | **Laparoscopic radical gastrectomy** |"
  },
  "Chen 2020": {
    "surgery_category": "Thoracic & Cardiac",
    "surgery_procedure": "Video-assisted thoracoscopic surgery (VATS) pulmonary resection",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/chen_2020_full_data_extraction.md",
    "source_line": 103,
    "source_excerpt": "| Surgery | **Video-assisted thoracoscopic surgery (VATS) pulmonary resection** |"
  },
  "Yang 2020": {
    "surgery_category": "Thoracic & Cardiac",
    "surgery_procedure": "Adults undergoing VATS segmentectomy or lobectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/yang_2020_covidence_464_full_data_extraction.md",
    "source_line": 111,
    "source_excerpt": "| Population | Adults undergoing **VATS segmentectomy or lobectomy** |"
  },
  "Yu 2020": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Adults undergoing elective gynecological laparoscopic surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/yu_2020_gynecological_laparoscopy_teas_full_data_extraction.md",
    "source_line": 103,
    "source_excerpt": "| Population | Adults undergoing **elective gynecological laparoscopic surgery** |"
  },
  "Zhan 2020": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Total gastrectomy, partial gastrectomy, radical colectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/zhan_2020_covidence_1389_full_data_extraction.md",
    "source_line": 102,
    "source_excerpt": "| Procedures | **Total gastrectomy, partial gastrectomy, radical colectomy** |"
  },
  "Ao 2021": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Elective radical mastectomy for breast cancer",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/ao_2021_full_data_extraction.md",
    "source_line": 148,
    "source_excerpt": "| Surgery | **Elective radical mastectomy for breast cancer** |"
  },
  "Gao 2021": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Patients undergoing colorectal cancer surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/gao_2021_covidence_400_full_data_extraction.md",
    "source_line": 107,
    "source_excerpt": "| Population | Patients undergoing **colorectal cancer surgery** |"
  },
  "Li 2021": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Adults undergoing laparoscopic gastric, colon, or rectal tumor resection",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/li_2021_covidence_437_full_data_extraction.md",
    "source_line": 123,
    "source_excerpt": "| Population | Adults undergoing **laparoscopic gastric, colon, or rectal tumor resection** |"
  },
  "Liang 2021": {
    "surgery_category": "Urologic",
    "surgery_procedure": "Transurethral resection of the prostate (TURP)",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/liang_2021_covidence_14_full_data_extraction.md",
    "source_line": 130,
    "source_excerpt": "| Procedure | **Transurethral resection of the prostate (TURP)** |"
  },
  "Liu 2021": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Elderly patients undergoing laparoscopic radical resection of colon cancer",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/liu_2021_pocd_teas_full_data_extraction.md",
    "source_line": 99,
    "source_excerpt": "| Population | Elderly patients undergoing **laparoscopic radical resection of colon cancer** |"
  },
  "Lu 2021": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Elective radical mastectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/lu_2021_covidence_414_full_data_extraction.md",
    "source_line": 126,
    "source_excerpt": "| Surgery | **Elective radical mastectomy** |"
  },
  "Xiong 2021": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Laparoscopic sleeve gastrectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/xiong_2021_covidence_431_full_data_extraction.md",
    "source_line": 108,
    "source_excerpt": "| Surgery | **Laparoscopic sleeve gastrectomy** |"
  },
  "Zhou 2021": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Patients undergoing radical gastrectomy for gastric cancer",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/zhou_2021_gastric_cancer_teas_full_data_extraction.md",
    "source_line": 112,
    "source_excerpt": "| Population | Patients undergoing radical gastrectomy for gastric cancer |"
  },
  "Li 2022": {
    "surgery_category": "Head, Neck & ENT",
    "surgery_procedure": "Adults undergoing elective thyroidectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/li_2022_preoperative_ea_thyroidectomy_full_data_extraction.md",
    "source_line": 105,
    "source_excerpt": "| Population | Adults undergoing elective **thyroidectomy** |"
  },
  "Lu 2022": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Adults undergoing elective laparoscopic colon surgery under general anesthesia",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/lu_2022_colon_surgery_teas_full_data_extraction.md",
    "source_line": 112,
    "source_excerpt": "| Population | Adults undergoing **elective laparoscopic colon surgery under general anesthesia** |"
  },
  "Wu 2022": {
    "surgery_category": "Orthopedic & Spine",
    "surgery_procedure": "Posterior lumbar decompression + bone-graft fusion + internal fixation",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/wu_2022_spinal_surgery_pteas_full_data_extraction.md",
    "source_line": 106,
    "source_excerpt": "| Surgical procedures | Posterior lumbar decompression + bone-graft fusion + internal fixation |"
  },
  "Xing 2022": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Elderly adults undergoing elective laparoscopic gastric cancer surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/xing_2022_gastric_cancer_teas_tapb_full_data_extraction.md",
    "source_line": 137,
    "source_excerpt": "| Population | Elderly adults undergoing **elective laparoscopic gastric cancer surgery** |"
  },
  "Zhu 2022": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Laparoscopic hysterectomy, myomectomy, oophorectomy, salpingo-oophorectomy, ovarian cystectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/zhu_2022_covidence_381_full_data_extraction.md",
    "source_line": 121,
    "source_excerpt": "| Procedures | Laparoscopic hysterectomy, myomectomy, oophorectomy, salpingo-oophorectomy, ovarian cystectomy |"
  },
  "Guo 2023": {
    "surgery_category": "Thoracic & Cardiac",
    "surgery_procedure": "Older adults undergoing thoracoscopic pulmonary resection for suspected lung cancer",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/guo_2023_full_data_extraction.md",
    "source_line": 126,
    "source_excerpt": "| Population | Older adults undergoing **thoracoscopic pulmonary resection for suspected lung cancer** |"
  },
  "Hou 2023": {
    "surgery_category": "Urologic",
    "surgery_procedure": "Living kidney donors (LKDs) undergoing nephrectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/hou_2023_covidence_7_full_data_extraction.md",
    "source_line": 106,
    "source_excerpt": "| Population | **Living kidney donors (LKDs)** undergoing nephrectomy |"
  },
  "Jin 2023": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Primigravida women after cesarean delivery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/jin_2023_covidence_9_full_data_extraction.md",
    "source_line": 53,
    "source_excerpt": "| Population | Primigravida women after cesarean delivery |"
  },
  "Pan 2023": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Women undergoing laparoscopic myomectomy / hysteromyomectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/pan_2023_laparoscopic_myomectomy_teas_full_data_extraction.md",
    "source_line": 139,
    "source_excerpt": "| Population | Women undergoing **laparoscopic myomectomy / hysteromyomectomy** |"
  },
  "Wang 2023": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Laparoscopic radical gastrectomy for gastric cancer or laparoscopic radical colorectal cancer resection",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/wang_2023_gi_tumor_sleep_teas_full_data_extraction.md",
    "source_line": 110,
    "source_excerpt": "| Surgical procedures | **Laparoscopic radical gastrectomy for gastric cancer or laparoscopic radical colorectal cancer resection** |"
  },
  "Zhang 2023": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Elective laparoscopic cholecystectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/zhang_2023_covidence_308_full_data_extraction.md",
    "source_line": 78,
    "source_excerpt": "| Surgery | **Elective laparoscopic cholecystectomy** |"
  },
  "Huang 2024": {
    "surgery_category": "Orthopedic & Spine",
    "surgery_procedure": "Unilateral TKA",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/huang_2024_covidence_245_full_data_extraction.md",
    "source_line": 104,
    "source_excerpt": "| Surgery | **Unilateral TKA** |"
  },
  "Tu 2024": {
    "surgery_category": "Neurosurgery",
    "surgery_procedure": "Adults undergoing craniotomy requiring opening of the cranium and dura",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/tu_2024_covidence_244_full_data_extraction.md",
    "source_line": 125,
    "source_excerpt": "| Population | Adults undergoing **craniotomy requiring opening of the cranium and dura** |"
  },
  "Wang 2024": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Women undergoing unilateral breast cancer surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/wang_2024_covidence_212_full_data_extraction.md",
    "source_line": 135,
    "source_excerpt": "| Population | Women undergoing **unilateral breast cancer surgery** |"
  },
  "Yang 2024": {
    "surgery_category": "Thoracic & Cardiac",
    "surgery_procedure": "VATS lobectomy or segmentectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/yang_2024_covidence_1930_full_data_extraction.md",
    "source_line": 114,
    "source_excerpt": "| Surgical procedures | **VATS lobectomy or segmentectomy** |"
  },
  "Huang 2025": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Laparoscopic hysterectomy with or without salpingo-oophorectomy or salpingectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/huang_2025_covidence_131_full_data_extraction.md",
    "source_line": 127,
    "source_excerpt": "| Surgery | **Laparoscopic hysterectomy with or without salpingo-oophorectomy or salpingectomy** |"
  },
  "Liu 2025": {
    "surgery_category": "Thoracic & Cardiac",
    "surgery_procedure": "Adults undergoing single-port thoracoscopic lung cancer surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/liu_2025_thoracoscopic_ea_full_data_extraction.md",
    "source_line": 119,
    "source_excerpt": "| Population | Adults undergoing **single-port thoracoscopic lung cancer surgery** |"
  },
  "Long 2025": {
    "surgery_category": "Orthopedic & Spine",
    "surgery_procedure": "Surgical repair of hip fracture",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/long_2025_hip_fracture_teas_full_data_extraction.md",
    "source_line": 150,
    "source_excerpt": "| Surgery | Surgical repair of hip fracture |"
  },
  "Wu 2025": {
    "surgery_category": "Thoracic & Cardiac",
    "surgery_procedure": "VATS pulmonary wedge resection",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/wu_2025_day_lung_cancer_teas_full_data_extraction.md",
    "source_line": 116,
    "source_excerpt": "| Surgery | **VATS pulmonary wedge resection** |"
  },
  "Zhang 2025": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Patients undergoing elective laparoscopic hysterectomy",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/zhang_2025_laparoscopic_hysterectomy_teas_full_data_extraction.md",
    "source_line": 130,
    "source_excerpt": "| Population | Patients undergoing **elective laparoscopic hysterectomy** |"
  },
  "Zheng 2025": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Patients undergoing gynecological laparoscopic surgery under general anesthesia",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/zheng_2025_gynecological_laparoscopy_teas_full_data_extraction.md",
    "source_line": 116,
    "source_excerpt": "| Population | Patients undergoing **gynecological laparoscopic surgery under general anesthesia** |"
  },
  "#105119 - Zhou 2025": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Patients undergoing elective gynecological laparoscopic surgery under general anesthesia",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/zhou_2025_pacu_teas_gynecologic_laparoscopy_full_data_extraction.md",
    "source_line": 117,
    "source_excerpt": "| Population | Patients undergoing **elective gynecological laparoscopic surgery under general anesthesia** |"
  },
  "He 2026 (breast/WJCO)": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Adults undergoing elective breast cancer surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/he_2026_covidence_41_full_data_extraction.md",
    "source_line": 83,
    "source_excerpt": "| Population | Adults undergoing **elective breast cancer surgery** |"
  },
  "He 2026 (hepatectomy/JIS)": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Adults scheduled for elective hepatectomy under general anesthesia",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/he_2026_covidence_25_full_data_extraction_REVISED_with_supplements.md",
    "source_line": 114,
    "source_excerpt": "| Population | Adults scheduled for **elective hepatectomy under general anesthesia** |"
  },
  "Jiang 2026": {
    "surgery_category": "Mixed or unspecified surgery",
    "surgery_procedure": "Elective laparoscopic non-gastrointestinal surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/jiang_2026_covidence_4_full_data_extraction.md",
    "source_line": 127,
    "source_excerpt": "| Surgery | Elective **laparoscopic non-gastrointestinal surgery** |"
  },
  "Liu 2026 (burn)": {
    "surgery_category": "Burn & Reconstructive",
    "surgery_procedure": "Adult patients with moderate burn injury undergoing wound debridement under general anesthesia",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/liu_2026_burn_teas_covidence_48_full_data_extraction.md",
    "source_line": 117,
    "source_excerpt": "| Population | **Adult patients with moderate burn injury undergoing wound debridement under general anesthesia** |"
  },
  "Liu 2026 (ESD)": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Adults undergoing elective gastric or esophageal endoscopic submucosal dissection (ESD)",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/liu_2026_covidence_69_full_data_extraction.md",
    "source_line": 121,
    "source_excerpt": "| Population | Adults undergoing elective **gastric or esophageal endoscopic submucosal dissection (ESD)** |"
  },
  "Luo 2026": {
    "surgery_category": "Head, Neck & ENT",
    "surgery_procedure": "Adults undergoing tympanoplasty under general anesthesia",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/luo_2026_covidence_35_full_data_extraction.md",
    "source_line": 103,
    "source_excerpt": "| Population | Adults undergoing **tympanoplasty under general anesthesia** |"
  },
  "Ma 2026": {
    "surgery_category": "Gynecologic & Breast",
    "surgery_procedure": "Patients with histologically confirmed breast cancer undergoing elective surgery",
    "source_file": "TEAS EA Verification/ChatGPT Sol Extraction/ma_2026_breast_cancer_sleep_teas_full_data_extraction.md",
    "source_line": 144,
    "source_excerpt": "| Population | Patients with histologically confirmed **breast cancer** undergoing elective surgery |"
  },
  "Szmit 2021": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Elective inguinal hernia repair (source states both laparoscopic mesh repair and Lichtenstein tension-free technique; internally inconsistent, not adjudicated)",
    "source_file": "dashboard/data.js",
    "source_line": null,
    "source_excerpt": "Elective inguinal hernia repair (source states both laparoscopic mesh repair and Lichtenstein tension-free technique; internally inconsistent, not adjudicated)"
  },
  "Gao 2022": {
    "surgery_category": "Mixed or unspecified surgery",
    "surgery_procedure": "High-risk laparoscopic non-gastrointestinal surgery (12-center trial)",
    "source_file": "dashboard/data.js",
    "source_line": null,
    "source_excerpt": "High-risk laparoscopic non-gastrointestinal surgery (12-center trial)"
  },
  "Song 2020": {
    "surgery_category": "Thoracic & Cardiac",
    "surgery_procedure": "Elective video-assisted thoracoscopic surgery (VATS)",
    "source_file": "dashboard/data.js",
    "source_line": null,
    "source_excerpt": "Elective video-assisted thoracoscopic surgery (VATS)"
  },
  "Wu 2016": {
    "surgery_category": "Not documented",
    "surgery_procedure": "Surgical procedure not documented in the available characteristics record.",
    "source_file": "dashboard/data.js",
    "source_line": null,
    "source_excerpt": "Elective surgical procedure under general anesthesia (three-arm: no-TAES control, active nonacupoint electrical stimulation, true-acupoint TAES)"
  },
  "Liu 2015": {
    "surgery_category": "Neurosurgery",
    "surgery_procedure": "Supratentorial craniotomy",
    "source_file": "dashboard/data.js",
    "source_line": null,
    "source_excerpt": "Supratentorial craniotomy"
  },
  "Oztas 2019": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Elective abdominal surgery (three-arm: TAES, incision-periphery TENS, no-intervention control)",
    "source_file": "dashboard/data.js",
    "source_line": null,
    "source_excerpt": "Elective abdominal surgery (three-arm: TAES, incision-periphery TENS, no-intervention control)"
  },
  "Zhang 2018": {
    "surgery_category": "Abdominal & Gastrointestinal",
    "surgery_procedure": "Open abdominal GI-cancer surgery",
    "source_file": "dashboard/data.js",
    "source_line": null,
    "source_excerpt": "Open abdominal GI-cancer surgery"
  }
};
