// v34 ANALYTICAL LAYER — generated file, do not hand-edit.
// Regenerate with:  python3 scripts/build_v34_dashboard_data.py
//
// Master : TEAS_EA_RECONCILED_MASTER_DATA_v34_FINAL_LOCK_READY.xlsx
// SHA-256: 985dc26a943cf30e1bbdac552a5eb69a6fb2d73fd252d0bc194abbdb8538d6f3
// Studies: 70   Outcome rows: 757
// Models : 5 new + 8 independently reproduced
//
// Every estimate is read from 09_V34_ANALYSIS/03_RESULTS/v34_models.csv, fitted
// by StataNow 19.5. None is copied from an earlier dashboard file.
window.V34_DATA = {
  "generated_by": "scripts/build_v34_dashboard_data.py",
  "master": "TEAS_EA_RECONCILED_MASTER_DATA_v34_FINAL_LOCK_READY.xlsx",
  "master_sha256": "985dc26a943cf30e1bbdac552a5eb69a6fb2d73fd252d0bc194abbdb8538d6f3",
  "master_version": "v34",
  "canonical_studies": 70,
  "outcome_rows": 757,
  "strict_primary_k": 7,
  "models": [
    {
      "model_id": "gi_first_flatus_TEAS_Sham",
      "label": "Time to first flatus — TEAS vs sham",
      "role": "secondary",
      "rob_key": "flatus_time",
      "unit": "hours",
      "measure": "MD",
      "phase": "NEW",
      "k": 7,
      "estimate": -6.2615,
      "ci_low": -9.5055,
      "ci_high": -3.0175,
      "p_value": 0.00325,
      "tau2": 9.0944,
      "i2": 81.96,
      "estimator": "REML + Hartung-Knapp",
      "studies": "Gao 2021; Gu 2019; Lu 2022; Wang 2023; Xing 2022; Zheng 2025; Zhou 2025",
      "rob2_pending": 6
    },
    {
      "model_id": "gi_first_flatus_EA_Usual_care",
      "label": "Time to first flatus — EA vs usual care",
      "role": "secondary",
      "rob_key": "flatus_time",
      "unit": "hours",
      "measure": "MD",
      "phase": "NEW",
      "k": 2,
      "estimate": -3.3633,
      "ci_low": -7.426,
      "ci_high": 0.6994,
      "p_value": 0.10468,
      "tau2": 7.1401,
      "i2": 80.95,
      "estimator": "REML normal CI",
      "studies": "Huang 2025; Yang 2024",
      "rob2_pending": 1
    },
    {
      "model_id": "gi_first_bowel_sounds_TEAS_Sham",
      "label": "Time to first bowel sounds — TEAS vs sham",
      "role": "secondary",
      "rob_key": "flatus_time",
      "unit": "hours",
      "measure": "MD",
      "phase": "NEW",
      "k": 2,
      "estimate": -6.0864,
      "ci_low": -8.2825,
      "ci_high": -3.8903,
      "p_value": 0.0,
      "tau2": 0.0,
      "i2": 0.0,
      "estimator": "REML normal CI",
      "studies": "Gao 2021; Gu 2019",
      "rob2_pending": 2
    },
    {
      "model_id": "pain_vas_24h_TEAS_Sham",
      "label": "Pain VAS at 24 h — TEAS vs sham",
      "role": "secondary",
      "rob_key": "pain_rest_24h",
      "unit": "VAS 0–10",
      "measure": "MD",
      "phase": "NEW",
      "k": 2,
      "estimate": -1.506,
      "ci_low": -3.0345,
      "ci_high": 0.0225,
      "p_value": 0.05348,
      "tau2": 1.1833,
      "i2": 97.24,
      "estimator": "REML normal CI",
      "studies": "Gu 2019; Wu 2025",
      "rob2_pending": 1
    },
    {
      "model_id": "ponv_24h_TEAS_Sham",
      "label": "PONV incidence 0–24 h — TEAS vs sham",
      "role": "secondary",
      "rob_key": "ponv_24h",
      "unit": "risk ratio",
      "measure": "logRR",
      "phase": "NEW",
      "k": 3,
      "estimate": -0.6095,
      "ci_low": -1.8189,
      "ci_high": 0.5999,
      "p_value": 0.16239,
      "tau2": 0.1491,
      "i2": 57.44,
      "estimator": "REML + Hartung-Knapp",
      "studies": "Chen 2015; Chen 2015 (Hyperalgesia); He 2026 (hepatectomy/JIS)",
      "rob2_pending": 3,
      "rr": 0.5436,
      "rr_low": 0.1622,
      "rr_high": 1.8219
    },
    {
      "model_id": "v34_intraop_remifentanil_TEAS_Sham",
      "label": "Intraoperative remifentanil — TEAS vs sham",
      "role": "secondary",
      "rob_key": "intraop_remi",
      "unit": "µg",
      "measure": "MD",
      "phase": "REPRODUCED",
      "k": 6,
      "estimate": -117.7771,
      "ci_low": -242.5056,
      "ci_high": 6.9513,
      "p_value": 0.05958,
      "tau2": 10748.9226,
      "i2": 83.86,
      "estimator": "REML + Hartung-Knapp",
      "studies": "",
      "rob2_pending": null
    },
    {
      "model_id": "v34_intraop_sufentanil_TEAS_Sham",
      "label": "Intraoperative sufentanil — TEAS vs sham",
      "role": "secondary",
      "rob_key": "intraop_remi",
      "unit": "µg",
      "measure": "MD",
      "phase": "REPRODUCED",
      "k": 2,
      "estimate": -9.4356,
      "ci_low": -32.3953,
      "ci_high": 13.5242,
      "p_value": 0.42055,
      "tau2": 254.121,
      "i2": 92.03,
      "estimator": "REML normal CI",
      "studies": "",
      "rob2_pending": null
    },
    {
      "model_id": "v34_qor40_24h_TEAS_Sham",
      "label": "Global QoR-40 at 24 h — TEAS vs sham",
      "role": "secondary",
      "rob_key": "qor_24h",
      "unit": "QoR-40 points",
      "measure": "MD",
      "phase": "REPRODUCED",
      "k": 2,
      "estimate": 6.7163,
      "ci_low": -2.1609,
      "ci_high": 15.5935,
      "p_value": 0.13811,
      "tau2": 36.3767,
      "i2": 87.86,
      "estimator": "REML normal CI",
      "studies": "",
      "rob2_pending": null
    },
    {
      "model_id": "v34_gi_first_defecation_TEAS_Sham",
      "label": "Time to first defecation — TEAS vs sham",
      "role": "secondary",
      "rob_key": "flatus_time",
      "unit": "hours",
      "measure": "MD",
      "phase": "REPRODUCED",
      "k": 3,
      "estimate": -10.3982,
      "ci_low": -23.1249,
      "ci_high": 2.3285,
      "p_value": 0.07226,
      "tau2": 6.4464,
      "i2": 20.81,
      "estimator": "REML + Hartung-Knapp",
      "studies": "",
      "rob2_pending": null
    },
    {
      "model_id": "v34_gi_first_defecation_EA_Usual_care",
      "label": "Time to first defecation — EA vs usual care",
      "role": "secondary",
      "rob_key": "flatus_time",
      "unit": "hours",
      "measure": "MD",
      "phase": "REPRODUCED",
      "k": 3,
      "estimate": -4.0811,
      "ci_low": -6.0671,
      "ci_high": -2.095,
      "p_value": 0.01255,
      "tau2": 0.0,
      "i2": 0.0,
      "estimator": "REML + Hartung-Knapp",
      "studies": "",
      "rob2_pending": null
    },
    {
      "model_id": "v34_primary_24h_mme_TEAS_Sham",
      "label": "Primary 0–24 h opioid — TEAS vs sham",
      "role": "primary",
      "rob_key": "opioid_24h",
      "unit": "mg IV MME",
      "measure": "MD",
      "phase": "REPRODUCED",
      "k": 4,
      "estimate": -13.9953,
      "ci_low": -34.1808,
      "ci_high": 6.1903,
      "p_value": 0.11448,
      "tau2": 156.8823,
      "i2": 98.59,
      "estimator": "REML + Hartung-Knapp",
      "studies": "",
      "rob2_pending": null
    },
    {
      "model_id": "v34_primary_24h_mme_EA_Usual_care",
      "label": "Primary 0–24 h opioid — EA vs usual care",
      "role": "primary",
      "rob_key": "opioid_24h",
      "unit": "mg IV MME",
      "measure": "MD",
      "phase": "REPRODUCED",
      "k": 3,
      "estimate": -3.9358,
      "ci_low": -19.7732,
      "ci_high": 11.9016,
      "p_value": 0.39689,
      "tau2": 28.4713,
      "i2": 77.15,
      "estimator": "REML + Hartung-Knapp",
      "studies": "",
      "rob2_pending": null
    },
    {
      "model_id": "v34_primary_24h_mme_ALL_AUDIT",
      "label": "Primary 0–24 h opioid — combined audit synthesis",
      "role": "supporting",
      "rob_key": "opioid_24h",
      "unit": "mg IV MME",
      "measure": "MD",
      "phase": "REPRODUCED",
      "k": 7,
      "estimate": -9.907,
      "ci_low": -20.0794,
      "ci_high": 0.2654,
      "p_value": 0.05454,
      "tau2": 113.9105,
      "i2": 98.57,
      "estimator": "REML + Hartung-Knapp",
      "studies": "",
      "rob2_pending": null
    }
  ],
  "new_model_count": 5,
  "reproduced_model_count": 8,
  "withdrawn": [
    {
      "analysis_id": "V33_RESCUE_OPIOID_RR_24H",
      "label": "Binary rescue opioid use, 0–24 h / POD1",
      "previous": "k = 3, RR 0.519 (95% CI 0.370 to 0.727), p = 0.014",
      "reason": "Withdrawn as an exact-window model: the three trials did not share one time window. Tu 2024 measured 6–24 h, Liu 2026 (burn) through POD1, and only Yu 2020 reported exact 0–24 h incidence. Pooling them described no single estimand.",
      "now": "The exact 0–24 h set contains one trial (Yu 2020) and is not meta-analysed. The other two results remain available in their own windows.",
      "affects": "A secondary rescue endpoint. The strict primary opioid-dose model (k = 7) is unaffected."
    },
    {
      "analysis_id": "V33_QOR40_24H_MD",
      "label": "Global QoR-40 at ~24 h (previous mixed-window set)",
      "previous": "k = 3, MD +7.34 points (95% CI −4.60 to +19.28), p = 0.118",
      "reason": "The previous set mixed Yu 2020's POD1 assessment with exact 24-hour assessments, and pooled across comparator strata.",
      "now": "The exact 24-hour TEAS-vs-sham set is Yao 2015 and Liang 2021 (k = 2). Yu 2020's POD1 result is kept separately, and Pan 2023's usual-care result is a separate k = 1.",
      "affects": "Secondary quality-of-recovery endpoint."
    }
  ],
  "superseded": [
    {
      "old": "V33_INTRAOP_REMI_MD",
      "old_desc": "k = 8, MD −116.76 µg, pooled across modality and comparator",
      "new": "v34_intraop_remifentanil_TEAS_Sham",
      "reason": "Restratified to TEAS vs sham. EA and usual-care contrasts are reported separately and single-study strata are not pooled."
    },
    {
      "old": "V33_INTRAOP_SUF_MD",
      "old_desc": "k = 5, MD −0.12 µg, pooled across modality and comparator",
      "new": "v34_intraop_sufentanil_TEAS_Sham",
      "reason": "Restratified to TEAS vs sham. Wang 2024's SNVP and MNVP are strata within one trial and are never counted as two independent RCTs."
    },
    {
      "old": "V33_GI_DEFECATION_MD",
      "old_desc": "k = 7, MD −4.80 h, pooled across modality and comparator",
      "new": "v34_gi_first_defecation_TEAS_Sham",
      "reason": "Split into TEAS vs sham (k = 3) and EA vs usual care (k = 3). Ng 2013's EA-vs-sham contrast is a separate k = 1."
    }
  ],
  "eligibility_counts": {
    "INCLUDE": 464,
    "NARRATIVE ONLY": 99,
    "GRAPH ONLY": 63,
    "HOLD": 62,
    "NOT REPORTED": 55,
    "CONDITIONAL": 4,
    "EXCLUDE": 4,
    "DUPLICATE HOLD": 4,
    "SOURCE NOT ACCESSED": 2
  },
  "rob2_status_counts": {
    "ROB2_RESULT_SPECIFIC_PENDING": 668,
    "EXISTING_RESULT_SPECIFIC: Some concerns": 45,
    "EXISTING_RESULT_SPECIFIC: High": 37,
    "EXISTING_LOCKED_PRIMARY: Some concerns": 6,
    "EXISTING_LOCKED_PRIMARY: High": 1
  },
  "source_holds": {
    "unresolved_conflicts": 27,
    "conflict_records": 27,
    "conflicts": [
      {
        "study": "Liang 2021",
        "outcome": "CRBD",
        "timepoint": "48 h",
        "value_a": "4/35 vs 7/35",
        "location_a": "Abstract",
        "value_b": "4/35 vs 19/35",
        "location_b": "Table 2",
        "choice": "4/35 vs 19/35"
      },
      {
        "study": "Liang 2021",
        "outcome": "Randomized arm counts",
        "timepoint": "Allocation",
        "value_a": "38/37",
        "location_a": "v33 CRBD rows",
        "value_b": "37/38",
        "location_b": "Source Figure 2",
        "choice": "37/38"
      },
      {
        "study": "Liang 2021",
        "outcome": "Extra analgesia requirement",
        "timepoint": "Unclear",
        "value_a": "3.8 (1.9) vs 5.0 (2.9)",
        "location_a": "Table 4",
        "value_b": "Drug, unit, measurement, denominator and window undefined",
        "location_b": "Endpoint definition",
        "choice": "Raw values only"
      },
      {
        "study": "Liang 2021",
        "outcome": "PONV definition",
        "timepoint": "End of surgery/PACU/24h/48h",
        "value_a": "Row labelled PONV; printed event counts retained",
        "location_a": "Table 4",
        "value_b": "Nausea verbal scale described; composite event definition unclear",
        "location_b": "Methods",
        "choice": "Source label and counts retained; quantitative HOLD"
      },
      {
        "study": "Yu 2020",
        "outcome": "Resting VAS dispersion",
        "timepoint": "POD1",
        "value_a": "3.70±1.53 vs 4.73±1.53",
        "location_a": "Table 2",
        "value_b": "TEAS 3.70±1.41",
        "location_b": "Abstract",
        "choice": "3.70±1.53 vs 4.73±1.53"
      },
      {
        "study": "Yu 2020",
        "outcome": "Resting VAS dispersion",
        "timepoint": "POD2",
        "value_a": "1.83±0.98 vs 2.30±0.95",
        "location_a": "Table 2",
        "value_b": "TEAS 1.83±0.88",
        "location_b": "Abstract",
        "choice": "1.83±0.98 vs 2.30±0.95"
      },
      {
        "study": "Yu 2020",
        "outcome": "Pain significance",
        "timepoint": "POD2",
        "value_a": "P=0.26",
        "location_a": "Results prose",
        "value_b": "*P<0.05 / significant",
        "location_b": "Table 2 / abstract",
        "choice": "Both P versions"
      },
      {
        "study": "Yu 2020",
        "outcome": "MMSE direction",
        "timepoint": "POD1/POD2",
        "value_a": "TEAS numerically higher",
        "location_a": "Table 3",
        "value_b": "TEAS lower",
        "location_b": "Results prose",
        "choice": "Table values"
      },
      {
        "study": "Lu 2021",
        "outcome": "Rest NRS",
        "timepoint": "24 h",
        "value_a": "P=0.94",
        "location_a": "Table 3",
        "value_b": "P=0.12",
        "location_b": "Results prose",
        "choice": "Table values; both P versions"
      },
      {
        "study": "Lu 2021",
        "outcome": "Cough NRS",
        "timepoint": "24 h",
        "value_a": "P=0.89",
        "location_a": "Table 3",
        "value_b": "P=0.49",
        "location_b": "Results prose",
        "choice": "Table values; both P versions"
      },
      {
        "study": "Lu 2021",
        "outcome": "Rescue parecoxib",
        "timepoint": "24 h",
        "value_a": "P=0.35",
        "location_a": "Table 3",
        "value_b": "P=0.58",
        "location_b": "Results prose",
        "choice": "Table values; both P versions"
      },
      {
        "study": "Lu 2022",
        "outcome": "QoR-15",
        "timepoint": "24 h",
        "value_a": "Median 54.5 (range 15–92) vs 59 (27–136), P=0.01",
        "location_a": "Table 3",
        "value_b": "Median 50.5 (IQR 42.3–61.8) vs 44.5 (35–57), P=0.04",
        "location_b": "Results prose",
        "choice": "Table 3"
      },
      {
        "study": "Long 2025",
        "outcome": "VAS",
        "timepoint": "24 h",
        "value_a": "EA 2.78±0.97",
        "location_a": "Table 7",
        "value_b": "EA 2.65±0.94",
        "location_b": "Abstract",
        "choice": "Table 7"
      },
      {
        "study": "Long 2025",
        "outcome": "PND denominator",
        "timepoint": "POD1/POD3/POD7",
        "value_a": "EA 27 / C 26",
        "location_a": "Study flow",
        "value_b": "Imply EA 28 / C 25; POD7 1 (3.6%) vs 2 (8.0%)",
        "location_b": "Table 2 count/percentage pairs",
        "choice": "Printed events; no assumed result denominator"
      },
      {
        "study": "Zheng 2025",
        "outcome": "Pain significance",
        "timepoint": "24 h",
        "value_a": "P=0.042",
        "location_a": "Results prose",
        "value_b": "P=0.422",
        "location_b": "Table 4 footnote",
        "choice": "Both versions"
      },
      {
        "study": "Gu 2019",
        "outcome": "PCIA quantity",
        "timepoint": "24 h",
        "value_a": "Exact cumulative sufentanil",
        "location_a": "v33 label",
        "value_b": "Graph-only multimodal PCIA solution volume",
        "location_b": "Figure 4",
        "choice": "Graph-only mL solution"
      },
      {
        "study": "Gu 2019",
        "outcome": "Satisfaction",
        "timepoint": "Postoperative",
        "value_a": "Composite 67.3% vs 42.4%",
        "location_a": "Prose",
        "value_b": "Category counts: 32/9, 19/32, 7/16, 0/2",
        "location_b": "Table 4",
        "choice": "Four printed category contrasts"
      },
      {
        "study": "Zhu 2022",
        "outcome": "Randomized allocation",
        "timepoint": "Baseline",
        "value_a": "Pre103 / 30min104 / Comb103 / Usual103",
        "location_a": "Abstract",
        "value_b": "Pre103 / 30min103 / Comb103 / Usual104",
        "location_b": "CONSORT Figure 1",
        "choice": "CONSORT"
      },
      {
        "study": "Zhu 2022",
        "outcome": "Movement NRS",
        "timepoint": "6–24 h",
        "value_a": "Movement pain at 24 h",
        "location_a": "Methods",
        "value_b": "Pain at 6–24 h",
        "location_b": "Table 3",
        "choice": "6–24 h interval"
      },
      {
        "study": "Zhu 2022",
        "outcome": "QoR-15",
        "timepoint": "AMBIGUOUS",
        "value_a": "Printed QoR-15 means/SD",
        "location_a": "Table 3",
        "value_b": "Time not explicitly identified",
        "location_b": "Assessment label",
        "choice": "AMBIGUOUS"
      },
      {
        "study": "Jiang 2026",
        "outcome": "NRS",
        "timepoint": "AMBIGUOUS",
        "value_a": "3 (2–3) vs 3 (2–3.5)",
        "location_a": "Table 4",
        "value_b": "6,24,48 h planned; result not linked",
        "location_b": "Methods",
        "choice": "AMBIGUOUS"
      },
      {
        "study": "Jiang 2026",
        "outcome": "Printed effect direction/CI",
        "timepoint": "Defecation/cost",
        "value_a": "Raw estimates and CI retained in V34_Audit_Dispositions",
        "location_a": "Table 4 / Results",
        "value_b": "Effect direction/CI formatting inconsistent",
        "location_b": "Arm summaries",
        "choice": "Group summaries unchanged; no corrected effect asserted"
      },
      {
        "study": "Tu 2024",
        "outcome": "Vomiting P",
        "timepoint": "2–6 h",
        "value_a": "0.047",
        "location_a": "Table 3 / abstract",
        "value_b": "0.47",
        "location_b": "Results prose",
        "choice": "0.047"
      },
      {
        "study": "Tu 2024",
        "outcome": "Rescue tramadol window",
        "timepoint": "6–24 h",
        "value_a": "Within 24 h",
        "location_a": "v33 Outcome_Data",
        "value_b": "6–24 h",
        "location_b": "Audit Reconciliation_Status / Table 4",
        "choice": "6–24 h"
      },
      {
        "study": "Pan 2023",
        "outcome": "Participant flow",
        "timepoint": "Trial flow",
        "value_a": "120 women",
        "location_a": "Methods",
        "value_b": "105 final cohort, 52/53",
        "location_b": "Abstract / Results",
        "choice": "Analyzed 52/53; no inferred randomized allocation"
      },
      {
        "study": "Pan 2023",
        "outcome": "Mobile/PACU NRS statistic",
        "timepoint": "1h/24h/PACU",
        "value_a": "Parenthetical numbers, e.g. 2 (1.4) vs 3 (2.4)",
        "location_a": "Tables 6–7",
        "value_b": "Parenthetical statistic undefined",
        "location_b": "Statistic definition",
        "choice": "Raw values only"
      },
      {
        "study": "Huang 2025",
        "outcome": "QoR-40 direction",
        "timepoint": "Discharge",
        "value_a": "Median 196 vs 192",
        "location_a": "Table 4",
        "value_b": "Lower with EA",
        "location_b": "Results prose",
        "choice": "Table medians"
      }
    ],
    "supplement_access_gaps": [
      "Zhu 2022",
      "Lu 2022",
      "Gao 2021",
      "Jiang 2026",
      "Tu 2024",
      "Lu 2021",
      "Zheng 2025"
    ],
    "source_not_accessed_outcomes": [
      "Gao 2021 — total length of stay (Supplementary Table S4)",
      "Gao 2021 — 30-day complications (Supplementary Table S4)"
    ]
  },
  "poolable_scan": {
    "groups_examined": 602,
    "candidates": 7,
    "shared_arm_holds": 112,
    "single_study": 267
  },
  "certainty_note": "New and restratified v34 analyses carry result-specific risk-of-bias assessments that are still pending, so no GRADE certainty is presented for them. Previous GRADE ratings describe the earlier syntheses and are not carried across to a materially changed model."
};
