"""Generate table-bearing v37 handoff reports directly from canonical files (no hand-transcribed numbers)."""
import csv, json, pathlib, re, collections, datetime
ROOT = pathlib.Path(__file__).resolve().parents[2]; D = ROOT / '10_FINAL_ADJUDICATION'; R = D / '06_REPORTS'; R.mkdir(exist_ok=True)
load = lambda p: list(csv.DictReader(open(ROOT / p, encoding='utf-8-sig')))
results = {r['result_id']: r for r in load('10_FINAL_ADJUDICATION/03_CANONICAL/results.csv')}
studies = {s['report_id']: s for s in json.load(open(D / '03_CANONICAL/studies.json'))}
spec = json.load(open(D / '02_DECISIONS/model_specifications.json'))
out = {m['model_id']: m for m in json.load(open(D / '04_MODELS/model_outputs.json'))}
link = {r['result_id']: r for r in load('FINAL_RESULT_ROB2_LINKAGE.csv')}
grade = {r['model_id']: r for r in load('10_FINAL_ADJUDICATION/03_CANONICAL/grade.csv')}
trace = load('FINAL_PRIMARY_OUTCOME_TRACEABILITY.csv')
SUPPLEMENTS = json.load(open(D / '01_SOURCE_EVIDENCE/supplements/supplement_manifest.json'))
STAMP = 'Generated by `10_FINAL_ADJUDICATION/code/build_reports.py` from canonical v38 files. Do not edit by hand.'


def fmt(x, d=3):
    return '' if x in (None, '') else f'{float(x):.{d}f}'


def token(v):
    s = f'{float(v):g}'
    return s


def in_source(r):
    """Literal presence of arm statistics in extracted source text (normalizes whitespace, ±, unicode minus)."""
    t = open(ROOT / studies[r['study']]['source_text'], errors='ignore').read()
    for sup in SUPPLEMENTS:
        if sup['study'] == r['study']:
            t += '\n' + open(ROOT / sup['text_file'], errors='ignore').read()
    t = re.sub(r'\s+', ' ', t.replace('−', '-'))
    missing = []
    for k in ['mean_i', 'sd_i', 'mean_c', 'sd_c']:
        if r[k] in ('', None):
            continue
        tok = token(r[k])
        variants = {tok, f'{float(r[k]):.2f}', f'{float(r[k]):.1f}'}; variants |= {v.replace('.', ',') for v in variants}
        if not any(re.search(r'(?<![\d.])' + re.escape(v) + r'(?![\d])', t) for v in variants):
            missing.append(f'{k}={tok}')
    return 'ALL ARM MEANS/SDs FOUND IN SOURCE TEXT' if not missing else 'NOT FOUND AS PRINTED: ' + ', '.join(missing) + ' (figure/table extraction or supplement; see source_location)'


# 1. Primary evidence table.
prow = []
for t in trace:
    r = results[t['result_id']]
    models = [m for m in r['models'].split(';') if m]
    roles = sorted({out[m]['role'] for m in models})
    prow.append(dict(result_id=t['result_id'], study=t['study'], modality=t['modality'], comparator_class=r['comparator_class'],
                     outcome=t['outcome'], window=t['window'], unit=t['unit'], n_i=t['n_i'], n_c=t['n_c'], mean_i=t['mean_i'], sd_i=t['sd_i'],
                     mean_c=t['mean_c'], sd_c=t['sd_c'], systemic_capture=t['systemic_capture'], decision=r['decision'],
                     model_roles=';'.join(roles) or 'NOT MODELLED', models=';'.join(models), source_location=t['source_location'],
                     source_pdf=t['source_pdf'], source_sha256=t['source_sha256'], source_text=studies[t['study']]['source_text'],
                     literal_source_check=in_source(r), rob2=link[t['result_id']]['overall'], rob2_assessment=link[t['result_id']]['rob2_assessment_id'],
                     caveat=t['rationale']))
with open(R / 'primary_evidence_table.csv', 'w', newline='') as f:
    w = csv.DictWriter(f, list(prow[0])); w.writeheader(); w.writerows(prow)
L = ['# Source-backed primary evidence table (v37)', '', STAMP, '',
     'Registered construct: all delivered systemic postoperative opioid, end of surgery to 24 h, mg IV morphine equivalents. '
     'Rows are every 24-h opioid result considered for the primary construct (`FINAL_PRIMARY_OUTCOME_TRACEABILITY.csv`). '
     'Only rows whose model role is PRINCIPAL or SUPPORTIVE contribute to a primary-construct estimate; SENSITIVITY rows are diagnostics, not primary results. '
     'Full provenance columns (PDF path, SHA-256, extracted text path) are in `primary_evidence_table.csv`.', '',
     '## Primary-construct estimates', '',
     '| Body | Role | k | N | MD (95% CI), mg IV MME | Contributors | Status | GRADE (ASTRA recommendation) |', '|---|---|---:|---:|---|---|---|---|']
for mid in ['opioid24_TEAS_sham', 'opioid24_EA_sham', 'opioid24_TEAS_usual', 'opioid24_EA_usual']:
    m = out[mid]
    eff = f"{m['display_effect']:.2f} ({m['display_ci_low']:.2f} to {m['display_ci_high']:.2f})" if m['k'] else 'No eligible data'
    L.append(f"| {mid} | {m['role']} | {m['k']} | {m['N']} | {eff} | {m['studies'] or '—'} | {m['status']} | {grade[mid]['certainty']} |")
L += ['', 'k=1 rows are single-study contrasts with within-study normal CIs, not pooled random-effects estimates. '
      'Registered clinical threshold (≥10 mg sparing with paired ~24-h pain upper CI < +1) is not met by any body: no point estimate reaches −10 mg.', '',
      '## Result-level table', '',
      '| Result | Study | Mod. | Comparator | Outcome / window | n (I/C) | Mean±SD I | Mean±SD C | Unit | Systemic capture | Model roles | Source location | Literal check | RoB 2 |',
      '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|']
for p in prow:
    L.append(f"| {p['result_id']} | {p['study']} | {p['modality']} | {p['comparator_class']} | {p['outcome']} / {p['window']} | {fmt(p['n_i'],0)}/{fmt(p['n_c'],0)} | {p['mean_i']}±{p['sd_i']} | {p['mean_c']}±{p['sd_c']} | {p['unit']} | {p['systemic_capture']} | {p['model_roles']} | {p['source_location']} | {p['literal_source_check']} | {p['rob2']} |")
(R / 'PRIMARY_EVIDENCE_TABLE.md').write_text('\n'.join(L) + '\n')

# 2. Model membership and analysis manifest.
mrow = []
for s in spec:
    m = out[s['model_id']]
    members = s['result_ids']
    linked = [i for i in members if link[i]['rob2_assessment_id']]
    mrow.append(dict(model_id=s['model_id'], role=s['role'], construct=s['construct'], modality=s['modality'], comparator=s['comparator'], measure=s['measure'],
                     unit=s['unit'], k=m['k'], N=m['N'], studies=m['studies'], result_ids=';'.join(members), status=m['status'],
                     effect=fmt(m.get('display_effect')), ci_low=fmt(m.get('display_ci_low')), ci_high=fmt(m.get('display_ci_high')),
                     tau2=fmt(m.get('tau2'), 4), I2=fmt(m.get('I2'), 1), pi_low=fmt(m.get('pi_low')), pi_high=fmt(m.get('pi_high')),
                     rob2_linked_results=f'{len(linked)}/{len(members)}', grade=grade.get(s['model_id'], {}).get('certainty', 'NOT GRADED (sensitivity diagnostic)'),
                     note=s['note']))
with open(R / 'model_analysis_manifest.csv', 'w', newline='') as f:
    w = csv.DictWriter(f, list(mrow[0])); w.writeheader(); w.writerows(mrow)
L = ['# Model membership and analysis manifest (v37)', '', STAMP, '',
     'Policy: `10_FINAL_ADJUDICATION/02_DECISIONS/statistical_policy.md` (REML; safeguarded Hartung–Knapp with t(k−1) for k≥2; k=1 study contrast with normal CI; '
     'prediction intervals only for k≥5; RR 0.5 added to all four cells only when a cell is zero). TEAS and EA are never pooled; sham, usual care and active electrical are separate. '
     'RR effects and CIs are on the ratio scale; prediction-interval bounds are stored on the analysis (log) scale for RR. '
     'Per-result membership with rationale: `FINAL_MODEL_MEMBERSHIP_MATRIX.csv`; inputs: `04_MODELS/model_inputs.csv`.', '']
for role in ['PRINCIPAL', 'SUPPORTIVE', 'ADDITIONAL', 'SENSITIVITY']:
    L += [f'## {role}', '', '| Model | Construct | k | N | Effect (95% CI) | I² | Studies | RoB-linked results | GRADE |', '|---|---|---:|---:|---|---:|---|---|---|']
    for x in mrow:
        if x['role'] != role:
            continue
        eff = f"{x['effect']} ({x['ci_low']} to {x['ci_high']}) {x['unit']}" if x['k'] else 'No eligible data'
        L.append(f"| {x['model_id']} | {x['construct']} | {x['k']} | {x['N']} | {eff} | {x['I2']} | {x['studies'] or '—'} | {x['rob2_linked_results']} | {x['grade']} |")
    L.append('')
L += ['## Counts', '', f"- Defined estimands: {len(spec)}; fitted (k≥1): {sum(1 for m in out.values() if m['k'])}; pooled (k≥2): {sum(1 for m in out.values() if m['k'] > 1)}; empty (explicit absence): {sum(1 for m in out.values() if not m['k'])}.",
      f"- Roles: {dict(collections.Counter(s['role'] for s in spec))}.",
      f"- Reports contributing to at least one model: {len({results[i]['study'] for s in spec for i in s['result_ids']})} of {len(studies)}."]
(R / 'MODEL_MEMBERSHIP_ANALYSIS_MANIFEST.md').write_text('\n'.join(L) + '\n')

# 3. GRADE / RoB 2 reconciliation.
reg = {r['assessment_id']: r for r in load('10_FINAL_ADJUDICATION/02_DECISIONS/existing_rob2_assessments.csv')}
L = ['# GRADE and RoB 2 reconciliation (v37)', '', STAMP, '',
     'GRADE rows are ASTRA recommendations authored per evidence body (`code/grade_recommendations.py`), not human sign-off. '
     'RoB 2 ratings are existing assessments linked only when the exact result, window, contrast and population match; unlinked results are shown as UNLINKED and are never imputed as High or Low. '
     'The linker stores undocumented-signoff placeholders; these are not proof that no adoption records exist upstream. '
     'Historical v34 registers record lead adoption, but assessment vectors often conflict with the current selection. '
     'See `ROB2_PROVENANCE_RECONCILIATION_v37.md` and the v37 candidate ledger. No independent dual-assessor final sign-off is established by this export.', '',
     '| Body | Role | k | N | GRADE | RoB domain rationale | Linked results (rating) | Unlinked results |', '|---|---|---:|---:|---|---|---|---|']
for s in spec:
    if s['role'] == 'SENSITIVITY':
        continue
    m = out[s['model_id']]; g = grade[s['model_id']]
    lk = [f"{i} {results[i]['study']} ({link[i]['overall']})" for i in s['result_ids'] if link[i]['rob2_assessment_id']]
    ul = [f"{i} {results[i]['study']}" for i in s['result_ids'] if not link[i]['rob2_assessment_id']]
    L.append(f"| {s['model_id']} | {s['role']} | {m['k']} | {m['N']} | {g['certainty']} | {g['risk_of_bias']} | {'; '.join(lk) or '—'} | {'; '.join(ul) or '—'} |")
tot = [i for s in spec if s['role'] != 'SENSITIVITY' for i in s['result_ids']]
L += ['', f"Non-sensitivity model memberships: {len(tot)}; exact RoB 2 linked: {sum(1 for i in tot if link[i]['rob2_assessment_id'])}; unlinked: {sum(1 for i in tot if not link[i]['rob2_assessment_id'])}.",
      f"Canonical results with exact linkage overall: {sum(1 for l in link.values() if l['rob2_assessment_id'])} of {len(link)}."]
(R / 'GRADE_ROB2_RECONCILIATION.md').write_text('\n'.join(L) + '\n')
# Current provenance replaces the historical v37 pre-approval wording.
for name in ['PRIMARY_EVIDENCE_TABLE.md','MODEL_MEMBERSHIP_ANALYSIS_MANIFEST.md','GRADE_ROB2_RECONCILIATION.md']:
 p=R/name; txt=p.read_text().replace('(v37)','(v38)')
 if name=='GRADE_ROB2_RECONCILIATION.md':
  start=txt.index('GRADE rows are');end=txt.index('| Body |',start)
  txt=txt[:start]+'All 38 GRADE recommendations have been reviewed and adopted under user delegation. All non-sensitivity component results have fresh v38 result-specific RoB domain assessments, with source locators and unique IDs. Historical assessments remain available for comparison; their signatures are not transferred to new judgments. The user reports prior human review complete. New judgments are AI-conducted, not two independent human reviews. See `02_DECISIONS/v38/rob2_assessments.csv`.\n\n'+txt[end:]
 p.write_text(txt)
print('reports written:', sorted(p.name for p in R.iterdir()))
print('primary literal checks:', collections.Counter(p['literal_source_check'].split(':')[0] for p in prow))
