"""Authored delegated review; downgrade levels are judgments, not k/I²/P rules."""
import csv,json,pathlib,collections
ROOT=pathlib.Path(__file__).resolve().parents[2];D=ROOT/'10_FINAL_ADJUDICATION'
models=json.load(open(D/'04_MODELS/model_outputs.json')); J={}
def judge(ids,levels,rob,inc,imp,ind=None):
    for mid in ids.split('|'):J[mid]=(levels,[rob,inc,ind or 'Direct for the explicitly named outcome, window and comparator; not interchangeable with another construct or proof across all surgeries.',imp,'No separate downgrade: sparse evidence cannot rule out missing results, but specific evidence is insufficient to assert publication bias. Historical selection completeness is disclosed separately.'])
single='Not downgraded solely for one trial; consistency cannot be assessed.'
judge('opioid24_TEAS_sham|opioid24_TEAS_usual',(1,0,0,1,0),'Serious: Szmit exact assessments have prespecification concerns; usual-care arm additionally has possible co-intervention differences. No missing linkage remains.',single,'Serious: body-specific N=48 or N=47 and intervals cross registered 10mg benefit threshold. Crossing the supportive 8mg threshold is not a second independent reason to downgrade.')
judge('opioid24_EA_usual',(1,1,0,2,0),'Serious: El-Rakshy High for informative attrition/conflicting population descriptions; Seeva Some concerns.','Serious: divergent effects under different perioperative regimens; k=2 cannot establish stable magnitude.','Very serious: safeguarded HK interval allows very large benefit and harm; N=159.')
judge('ponv24_TEAS_sham',(1,1,0,0,0),'Serious: all components reviewed; variable sensory masking, exclusions and prespecification concerns remain. He primary PONV is Low risk.','Serious: variation across surgery/prophylaxis and prediction interval near/beyond null make a new-setting magnitude uncertain.','Not downgraded: N=3447, average RR CI 0.52–0.79 supports reduction; across-setting uncertainty counted above.')
judge('nausea24_TEAS_sham|vomiting24_TEAS_sham',(1,1,0,1,0),'Serious: result-specific missingness/prespecification concerns; nausea additionally vulnerable to sensory masking. Observable vomiting is not automatically High when patients know treatment.','Serious: effects and clinical contexts vary enough to undermine stable magnitude.','Serious: intervals allow substantial reductions and no benefit/increased risk.')
judge('nausea24_EA_usual|vomiting24_EA_usual',(1,0,0,2,0),'Serious: open-label reporting (especially nausea), co-intervention and prespecification concerns.','No separate inconsistency downgrade: two studies cannot distinguish heterogeneity from very imprecise estimates.','Very serious: safeguarded k=2 intervals allow very large benefit and harm.')
judge('nausea6to24_EA_usual|vomiting6to24_EA_usual',(1,0,0,0,0),'Serious: all three Zhu active arms assessed; sequence implementation/prespecification concerns and patient-report concerns for nausea. Vomiting measurement itself Low.',single,'Not downgraded: N=400 and intervals wholly support reduction. Single-trial status or no registered symptom MCID does not automatically imply imprecision; no minimum important benefit claimed.')
judge('persistent_nausea24_TEAS_sham',(1,0,0,1,0),'Serious: Gao incomplete patient masking and unverified result-level prospective analysis plan.',single,'Serious: relatively few persistent-nausea events despite N=1655; wide relative reduction range leaves uncertain absolute magnitude.')
judge('nausea48_TEAS_sham',(2,0,0,0,0),'Very serious: entire body is Luo; verified failed sensory masking and subjective nausea imply High measurement risk, compounded by unblinded care and uncertain prespecification.',single,'Not downgraded again: 77 nausea events (24/138 vs 53/139), RR CI 0.30–0.69 supports reduction. Not confused with the 36-event vomiting result; dominant uncertainty is bias.')
judge('vomiting48_TEAS_sham',(1,0,0,1,0),'Serious: Luo clinical-care/prespecification concerns. Observable vomiting measurement Low, not copied from nausea.',single,'Serious: 36 events in 277 participants and wide relative/absolute reduction range.')
judge('ponv48_TEAS_sham',(1,0,0,1,0),'Serious: Xiong concealment, clinical awareness, sensory masking and prespecification concerns. Five pre-randomization eligibility exclusions are not attrition.',single,'Serious, not very serious: N=62/37 events and RR CI 0.34–0.85; sparse information, but interval does not encompass major benefit AND harm.')
judge('ponv24_TEAS_active',(1,0,0,2,0),'Serious: Song result-level prespecification concerns; matched active-current sensory masking otherwise credible.',single,'Very serious: N=85 and sparse events; interval spans very large reduction through no benefit/slight increase.','Direct for active non-acupoint electrical control; not inert-sham efficacy. No penalty for answering its own labelled question.')
judge('vomiting24_TEAS_usual',(2,0,0,1,0),'Very serious: entire Pan body High for informative exclusions (external analgesia/PCIA) and internally conflicting flow counts; observed vomiting itself not High measurement risk.',single,'Serious: N=105/28 events; interval from large reduction to nearly no reduction.')
judge('pain24_rest_TEAS_sham|pain24_movement_TEAS_sham',(1,0,0,0,0),'Serious: exact pain results assessed; Liu masking/Xing sensory-unmasking and prospective-selection concerns. Prior blanket High assignments not sustained.','No downgrade: contrasts compatible with little average difference; movement body single trial.','Not downgraded for registered +1 pain-worsening decision: full CIs lie within −1 to +1. Standalone average-pain evidence is NOT paired opioid/pain proof or a formal noninferiority trial.')
judge('pain24_movement_EA_sham',(1,0,0,0,0),'Serious: both Huang arms assessed; missing-measurement handling and sensory masking concerns.',single,'Not downgraded for +1 worsening margin: CI −0.73 to +0.05 excludes important average worsening. Does not establish paired opioid reduction or broad analgesic benefit.')
judge('flatus_TEAS_sham',(1,2,0,0,0),'Serious: exact patient-report/missingness/prespecification concerns. Zheng continuous data excluded for source/construct uncertainty.','Very serious: clinically disparate magnitudes and prediction interval includes no improvement/delay; unstable expected benefit.','No extra downgrade: mean CI favours earlier passage; setting uncertainty counted under inconsistency.')
judge('flatus_EA_usual',(1,1,0,0,0),'Serious: open-label reporting including High measurement risk in Huang/Yang2024; all Zhu arms assessed.','Serious: magnitude varies by surgery, bowel care and baseline recovery.','No extra downgrade: average CI favours earlier flatus; no invented MCID or broad faster-recovery claim.')
judge('flatus_EA_sham',(1,0,0,2,0),'Serious: Ng nonopaque envelopes and incomplete prospective analysis-plan verification.',single,'Very serious: N=110, CI allows materially earlier flatus and no benefit/delay.')
judge('bowelsounds_TEAS_sham',(1,1,0,1,0),'Serious: Gu/Gao exact assessments now available; concealment/prespecification concerns. Zheng dispersion held out.','Serious: different recovery profiles/auscultation schedules undermine stable magnitude.','Serious: k=2 main MD −6.09h, CI −20.32 to +8.15; meaningful improvement and delay possible.')
judge('defecation_TEAS_sham|defecation_EA_usual',(1,1,0,1,0),'Serious: all exact assessments completed; missingness/prespecification and open-label reporting in EA usual-care.','Serious: varying surgery and bowel-management/laxative protocols.','Serious: intervals include important earlier defecation and no benefit/delay.')
judge('defecation_EA_sham',(1,0,0,1,0),'Serious: Ng concealment/prespecification concerns.',single,'Serious: N=110 and wide magnitude interval, about 6–37h earlier; sparse information despite excluding null.')
judge('opioid48_EA_usual_PCA|opioid72_EA_sham_PCA',(2,0,0,1,0),'Very serious: An/Wong entire bodies High for informative missingness; complications/reoperations can strongly affect opioid demand.',single,'Serious: small trials/wide magnitude intervals; 72h CI includes no reduction/increased dose.','Direct for labelled PCA-device exposure, not total systemic 24h opioid. No extra penalty merely for a different explicit question.')
judge('intraop_remifentanil_TEAS_sham',(1,1,0,0,0),'Serious: four retained trials have missingness/prespecification concerns. Zheng source uncertainty and Wu2025 pre-treatment dose excluded.','Serious: surgery duration, baseline dose and observed effects differ substantially.','No extra downgrade: average interval supports lower intraoperative dose; not postoperative opioid sparing/patient-important benefit.')
judge('intraop_remifentanil_TEAS_usual',(2,1,0,2,0),'Very serious: Pan High for informative exclusions/unblinded titration; Liang missingness concerns despite masked anaesthetist.','Serious: opposite observed directions in two small studies.','Very serious: k=2 interval spans very large decreases/increases.')
judge('intraop_remifentanil_EA_usual',(1,0,0,1,0),'Serious: Zhu sequence implementation/prespecification concerns; all arms assessed; masked anaesthesia supports Low measurement risk.',single,'Serious: N=400 but CI spans lower and increased dose; magnitude uncertain without registered dose MCID.')
judge('intraop_remifentanil_EA_sham',(2,0,0,2,0),'Very serious: Ntritsou unblinded clinician titration High, compounded by missingness/prespecification concerns.',single,'Very serious: N=70; interval spans very large decreases/increases.')
judge('pethidine24_TEAS_usual_rescue|pethidine24_TEAS_active_rescue',(2,0,0,2,0),'Very serious: Oztas rescue determined by unblinded clinical/patient decisions; both exact contrasts High. Active TENS does not establish assessor masking.',single,'Very serious: N=31 per contrast; intervals allow substantial reductions/increases; rescue component is not total systemic consumption.')
rows=[];lines=['# GRADE adjudication — v38','','All 38 non-sensitivity recommendations reviewed on 20 September 2026 by the AI assistant under user delegation. Prior human completion is user-reported; no independent human signatures invented. Five empty bodies are not rated. Diagnostic sensitivities have no independent efficacy grade.','','Randomized evidence starts High. Explicit downgrades below are authored judgments; k, I², P values and absent secondary MCIDs do not mechanically assign certainty. Risk-of-bias evidence is result-specific. Selection completeness remains a limitation, not a requirement to await reviewer approval.','','[Cochrane GRADE guidance](https://www.cochrane.org/authors/handbooks-and-manuals/handbook/current/chapter-14).','']
keys=['risk_of_bias','inconsistency','indirectness','imprecision','publication_bias']
for m in models:
    if m['role']=='SENSITIVITY':continue
    if m['k']:
        levels,reasons=J.pop(m['model_id']);certainty=['High','Moderate','Low','Very low'][min(3,sum(levels))]
    else:levels=(0,)*5;reasons=['No eligible quantitative evidence body.']*5;certainty='Not rated — insufficient evidence'
    r=dict(model_id=m['model_id'],label='V38 DELEGATED AI REVIEW COMPLETE',certainty=certainty,**dict(zip(keys,reasons)),**{k+'_downgrades':n for k,n in zip(keys,levels)},reviewer='AI assistant under user delegation',review_date='2026-09-20',decision_status='ADOPTED v38');rows.append(r)
    lines+=['## '+m['model_id'],'',f"**{certainty}**; k={m['k']}, N={m['N']}.",'']
    if m['k']:lines += [f"{m['measure']} {m['display_effect']:.3f} (95% CI {m['display_ci_low']:.3f} to {m['display_ci_high']:.3f}) {m['unit']}.",'']
    lines += [f'- {k.replace("_"," ").title()} (−{n}): {v}' for k,n,v in zip(keys,levels,reasons)]+['']
assert not J,J
assert len(rows)==38
with open(D/'03_CANONICAL/grade.csv','w',newline='') as f:w=csv.DictWriter(f,list(rows[0]));w.writeheader();w.writerows(rows)
(ROOT/'FINAL_GRADE_RECOMMENDATIONS.md').write_text('\n'.join(lines).replace('Five empty bodies','Four empty bodies').rstrip()+'\n')
print('v38 reviewed',len(rows),collections.Counter(r['certainty'] for r in rows))
