"""Current v38 status, policy, PRISMA and before/after reports."""
import csv,json,pathlib,collections,hashlib
ROOT=pathlib.Path(__file__).resolve().parents[2];D=ROOT/'10_FINAL_ADJUDICATION';R=D/'06_REPORTS';V=D/'05_REPRODUCTION/v38';B=V/'baseline'
def read(p):return list(csv.DictReader(open(p,encoding='utf-8-sig')))
def save(p,rows):
 with open(p,'w',newline='') as f:w=csv.DictWriter(f,list(rows[0]));w.writeheader();w.writerows(rows)
models=json.load(open(D/'04_MODELS/model_outputs.json')); by={m['model_id']:m for m in models}; old={m['model_id']:m for m in json.load(open(B/'10_FINAL_ADJUDICATION/04_MODELS/model_outputs.json'))}
g=read(D/'03_CANONICAL/grade.csv');gby={r['model_id']:r for r in g};og={r['model_id']:r for r in read(B/'10_FINAL_ADJUDICATION/03_CANONICAL/grade.csv')}
prisma=json.load(open(D/'02_DECISIONS/v38/prisma_counts.json'));rob=read(D/'02_DECISIONS/v38/rob2_assessments.csv');spec=json.load(open(D/'02_DECISIONS/model_specifications.json'))
active={i for s in spec if s['role']!='SENSITIVITY' for i in s['result_ids']};assert active<=set(r['result_id'] for r in rob)
policy=[
('Assignment effect and RoB','ADOPTED','Assess each exact outcome/window/arm/population for assignment effect. Awareness alone is not High D2; patient-reported nausea/pain differ from observable vomiting and recorded PCA dose. No invented independent human signatures.'),
('GRADE','ADOPTED','All 38 bodies independently considered: 34 rated, four empty. Explicit domain downgrades, not I²/P-value rules. No automatic single-trial downgrade; pain precision judged against registered +1 margin. No independent grades for diagnostics.'),
('IV-MME','ADOPTED','Central sufentanil factor 0.5mg IV morphine per microgram, with 0.25/1.0 sensitivities; uncertainty retained. Unknown oral/IV author-equivalent basis is diagnostic only.'),
('Systemic versus device exposure','ADOPTED','Admit delivered end-surgery–24h systemic totals, including quantified rescue. Chen1998/Yang2024/Lin2002 incomplete-rescue/window evidence stays sensitivity-only; never assume permitted rescue is zero.'),
('Chen2020 / He hepatectomy','ADOPTED HOLD','Chen basal-dose contradiction and He unknown MME basis remain flagged diagnostics; no fabricated unit or dose correction.'),
('El-Rakshy2009','ADOPTED','Retain outcome Table2 assignment in supportive EA/usual-care with High RoB and leave-out sensitivity. Do not silently swap arm labels or pretend flow contradiction resolved.'),
('Song2020','ADOPTED','Matched active non-acupoint electrical control remains separate from inert sham; broad-sham diagnostic retained.'),
('GI effect measure','ADOPTED','Use clinically interpretable hours MD within modality/control strata; SMD only diagnostic. Disclose posthoc choice; no effect-significance-based model selection.'),
('Zheng2025 continuous results','ADOPTED HOLD','Remove three unreconciled continuous results from main analyses. Dispersion/P inconsistencies and flatus/stool construct ambiguity remain unresolved; retain values unchanged only in with-Zheng-as-printed diagnostics. Binary PONV remains eligible.'),
('Wu2025 intraoperative dose','ADOPTED EXCLUSION FROM CAUSAL BODY','Randomization/treatment starts on PACU arrival after the intraoperative dose. Keep only pre-intervention negative-control diagnostic, not treatment efficacy.'),
('Other source holds','ADOPTED HOLD','Yeh probable family counted once and excluded from models; Jin2023 anaesthesia/concentration, Long2025 needle/patch ambiguity and He breast dispersion remain held/diagnostic. No author response presumed.'),
('Statistical inference','ADOPTED','REML with safeguarded Hartung–Knapp for k≥2; k=1 within-study normal interval, not pooled. Prediction intervals only k≥5. Combine compatible active arms with shared control once. Separate TEAS/EA and comparator classes.'),
('Moderators','ADOPTED','Do not carry forward historical mixed-modality k=7 regression. Registered minimum counts (≥10 per predictor, ≥4 per level, ≥20 multivariable) plus source-verified covariates govern; no new valid moderator model established.'),
('Clinical-importance criterion','ADOPTED','Keep ≥10mg opioid sparing plus paired ~24h pain upper CI <+1. Separate pain bodies cannot supply Szmit paired pain. 8mg/30% are sensitivity thresholds, not replacements.'),
('PRISMA','ADOPTED WITH PROVENANCE LIMIT','Wu2016 citation route user-confirmed. Reconcile exported record dispositions locally, not by editing Covidence. 12 import references remain unmapped; preserve aggregate provenance.'),
('Reviewer re-screening package','REMOVED FROM REQUESTED WORK','User withdrew this deliverable. Use requested outcome-exclusion label, retain raw reasons, and disclose completeness limitation without treating it as an outstanding approval workflow.'),
('External actions','NOT AUTHORIZED','Author queries remain UNSENT; local dashboard update only, no commit/push/public deployment.')]
pol=[dict(topic=a,status=b,decision=c,reviewer='AI assistant under user delegation',date='2026-09-20') for a,b,c in policy];save(D/'02_DECISIONS/v38/methodological_decisions.csv',pol)
(D/'02_DECISIONS/v38/methodological_decisions.json').write_text(json.dumps(pol,indent=2)+'\n')
lines=['# Methodological decisions — adopted v38','','Decisions made 20 September 2026 after results were known. No further reviewer approval is awaited under the user’s delegation. Source holds are settled conservative placement decisions, not a request to invent missing evidence.','']
for a,b,c in policy:lines+=['## '+a,'',b+': '+c,'']
(D/'02_DECISIONS/v38/METHODOLOGICAL_DECISIONS.md').write_text('\n'.join(lines))
P=['# PRISMA reconciliation — v38','','Wu 2016: citation search, user-confirmed 20 September 2026; no historical discovery date invented. Raw exports unchanged. Local adjudication does not imply that Covidence itself was edited.','','## Database branch','','- Raw RIS references: 5100 (Embase 1928, CENTRAL 1698, CINAHL 465, PubMed 1009).','- Historical imported records: 5088; **12-reference import difference unmapped**, not asserted as verified duplicate removal.','- Recorded upstream removals: 1651 automatic duplicates + 1 manual duplicate + 508 automation exclusions = 2160.','- 5088 − 2160 = 2928 screened; 2928 − 2704 title/abstract exclusions = 224 reports sought.','- Saved exports: 224 sought − 2 not retrieved = 222 retrieved records; six exact DOI/title duplicates removed late, leaving 216 distinct reports assessed.','- 216 distinct reports assessed − 147 excluded = 69 included database reports.','- Late duplicate removal: Chung, Tian, Tong, Tu, Wang and Yang (six records). Zhang’s distinct conference abstract remains an Abstract only exclusion.','','## Other-methods branch','','One citation report sought, retrieved, assessed and included: Wu 2016. Therefore 69 + 1 = **70 reports, 69 operational trial families** (Yeh probable overlap counted once; both held out of models).','','## Full-text exclusion reasons','','| Reason | Records |','|---|---:|']
P += [f'| {k} | {n} |' for k,n in prisma['exclusion_reasons'].items()]
P += ['','Six source-verified canonical reports formerly marked excluded are reinstated by this delegated adjudication: Gao2022, Liu2015, Oztas2019, Song2020, Szmit2021 and Zhang2018. The Zhang conference abstract is a distinct report (different DOI), excluded as Abstract only, not an exact duplicate publication. The original 161 exclusions reconcile as 6 reinstatements + 2 not retrieved + 6 exact duplicates + 147 substantive exclusions. The 122 original Wrong outcomes entries become 113 retained reason-labelled records after six reinstatements and three duplicate removals. Tu’s two exports disagree on the reason; the lowest-ID original reason is retained only as an administrative count convention, not a new validation of that clinical exclusion.','','The requested label **no perioperative analgesia outcome found** replaces the display wording, not the immutable original reason field. Re-screening is no longer a requested deliverable. The historical outcome-focused exclusion rule versus broader registered eligibility remains an evidence-completeness limitation; the label does not retrospectively validate every exclusion.','','Record-level ledger: `02_DECISIONS/v38/prisma_record_ledger.csv` (225 rows). Upstream deduplication numbers are historical aggregates; absent event logs prevent exact replay. The six late exact duplicates are fully mapped in `02_DECISIONS/v38/late_duplicate_register.csv`. The unrelated 12-reference import gap is not explained away by those six late discoveries.']
(R/'PRISMA_REPORT_TRIAL_ACCOUNTING.md').write_text('\n'.join(P)+'\n')
comparison=[]
for mid in sorted(set(old)|set(by)):
 a=old.get(mid,{});b=by.get(mid,{})
 comparison.append(dict(model_id=mid,status='NEW' if not a else 'SUPERSEDED DIAGNOSTIC' if not b else 'CURRENT',old_k=a.get('k',''),new_k=b.get('k',''),old_N=a.get('N',''),new_N=b.get('N',''),old_effect=a.get('display_effect',''),new_effect=b.get('display_effect',''),old_low=a.get('display_ci_low',''),new_low=b.get('display_ci_low',''),old_high=a.get('display_ci_high',''),new_high=b.get('display_ci_high',''),old_grade=og.get(mid,{}).get('certainty',''),new_grade=gby.get(mid,{}).get('certainty','')))
save(R/'model_comparison_v38.csv',comparison)
changes=[r for r in comparison if r['old_grade']!=r['new_grade'] and r['new_grade']];save(D/'02_DECISIONS/v38/grade_changes.csv',changes)
summary=['# Current state — adjudication v38','','20 September 2026 · PROSPERO CRD420261452908 · current analytical release adopted under user delegation. All decisions are posthoc with results known.','','## Completed','','- Wu2016 citation route recorded; all 225 full-text/citation records reconciled locally. 70 included reports / 69 operational families.','- 94 fresh exact-result RoB assessments across 40 reports, including all '+str(len(active))+' currently non-sensitivity component results. Unique v38 IDs and source locators; historical records preserved.','- All 38 GRADE recommendations reviewed: '+', '.join(f'{v} {k}' for k,v in collections.Counter(r['certainty'] for r in g).items())+'.','- Methodological choices adopted; no further reviewer approval awaited. Prior human completion is user-reported; new decisions are AI-conducted.','- Zheng continuous data held from main models; Wu2025 pre-intervention dose removed from causal synthesis and retained as diagnostic.','- Local dashboard now reads canonical v38 data; article-figure assets preserved. No publication/deployment authorized.','','## Primary conclusion unchanged','','| Body | k | N | MD mg IV MME (95% CI) | Certainty |','|---|---:|---:|---|---|']
for mid in ['opioid24_TEAS_sham','opioid24_EA_sham','opioid24_TEAS_usual','opioid24_EA_usual']:
 m=by[mid];e=f"{m['display_effect']:.2f} ({m['display_ci_low']:.2f}, {m['display_ci_high']:.2f})" if m['k'] else 'No eligible data';summary.append(f"| {mid} | {m['k']} | {m['N']} | {e} | {gby[mid]['certainty']} |")
summary += ['','No body establishes the registered joint criterion (≥10mg sparing with paired ~24h pain upper CI <+1). Szmit has discharge rather than eligible fixed-24h pain; separate pain studies do not provide the missing pairing.','','## What remains a limitation, not an approval queue','','The 12-reference import gap lacks record-level mapping; upstream deduplication can be reconciled arithmetically but not fully replayed. Historical outcome-focused exclusions leave review-wide completeness uncertain. The user withdrew re-screening; no screening package or reviewer approval is awaited. Source ambiguities remain explicit holds/diagnostics. These limitations prevent claiming that numerical reproducibility certifies source truth or exhaustive evidence selection.','','Author queries remain UNSENT. Covidence was not edited. No commit, push or public deployment performed. Any submission manuscript must disclose AI-assisted adjudication, posthoc choices, selection chronology and source holds.','','## Current files','','`10_FINAL_ADJUDICATION/03_CANONICAL`, `04_MODELS`, the root FINAL result/membership/participant tables, `02_DECISIONS/v38`, and dashboard/current_review data are authoritative. Earlier v26–v37 snapshots/reports remain historical. v38 baseline preserves pre-existing user dashboard/article-figure work.','','74 estimands defined; 69 fitted, 33 pooled, five empty (four non-sensitivity plus one sensitivity). 761 canonical results; 177 model inputs. 12,103 is an operational randomized count, not an analysed efficacy population. Analyzed N is model-specific.','','Numerical/integrity verification: `10_FINAL_ADJUDICATION/06_REPORTS/REPRODUCIBILITY_REPORT.md`. Full change comparison: `model_comparison_v38.csv`.']
coverage_file=D/'07_OUTCOME_COVERAGE/coverage_summary.json'
if coverage_file.exists():
 c=json.loads(coverage_file.read_text())
 summary += ['', '## Outcome-coverage addendum — 20 September 2026', '',
  f"The available-source coverage check covers all {c['reports_checked']} included report texts. It identifies {c['qor_reports']} QoR reports, {c['satisfaction_reports']} satisfaction/willingness reports, {c['quality_of_life_reports']} additional quality-of-life reports and {c['acceptability_reports']} additional acceptability reports. The {c['safety_records']} safety-relevant entries distinguish nonzero reactions, explicit zero statements, limited reporting and all-cause outcomes without established intervention attribution. No eligible opioid-use result beyond 30 days was located.", '',
  'See [outcome coverage report](10_FINAL_ADJUDICATION/07_OUTCOME_COVERAGE/OUTCOME_COVERAGE_REPORT.md). New QoR models and their exact-result RoB/GRADE are **not yet fitted or adopted**. The v38 74-model/38-GRADE analytical state above is unchanged. Its verification does not certify this new addendum; separate source/hash checks accompany the coverage report.']
qor_section=D/'08_QOR_ANALYSIS/CURRENT_STATE_SECTION.md'
if qor_section.exists():
 summary=[s.replace('New QoR models and their exact-result RoB/GRADE are **not yet fitted or adopted**.', 'The subsequent QoR analytical addendum below completes three approximately-24-hour bodies and their exact-result RoB/GRADE; the coverage report preserves its earlier audit status.') for s in summary]
 summary+=['',qor_section.read_text().strip()]
(ROOT/'FINAL_CURRENT_STATE_REPORT.md').write_text('\n'.join(summary)+'\n')
(R/'UNRESOLVED_HUMAN_DECISIONS.md').write_text('# Decision status — v38\n\nNo further reviewer approval is awaited: the user delegated RoB, all 38 GRADE bodies and methodological decisions, and reported prior human review complete. New decisions are AI-conducted. Re-screening package is withdrawn.\n\nResidual evidence limits, not undecided policies: 12-reference import mapping absent; historical exclusion completeness uncertain; publication/source ambiguities remain held or diagnostic. Author correspondence remains unsent; external database edits and public deployment were not performed. See current-state report and v38 decision register.\n')
(R/'CHANGELOG_v38.md').write_text('# v38 change record\n\n'+'\n'.join('- '+a+': '+c for a,b,c in policy)+'\n\nBaseline and hashes: `05_REPRODUCTION/v38`. All source values preserved. Primary four numerical estimates unchanged. Before/after models and GRADE: `model_comparison_v38.csv`.\n')
print('v38 reports; active component results',len(active),'GRADE changes',len(changes))
