#!/usr/bin/env python3
"""Restore display-only surgical characteristics from preserved extraction records.

These specialty groupings are for dashboard description, not new Stata covariates.
"""
import json
import re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def build():
    studies=json.JSONDecoder().raw_decode((ROOT/'dashboard/data.js').read_text().split('window.STUDIES_DATA = ',1)[1])[0]
    sources=ROOT/'TEAS EA Verification/ChatGPT Sol Extraction'
    aliases={
        'An 2014':'covidence_study_698_full_data_extraction.md',
        'He 2026 (breast/WJCO)':'he_2026_covidence_41_full_data_extraction.md',
        'He 2026 (hepatectomy/JIS)':'he_2026_covidence_25_full_data_extraction_REVISED_with_supplements.md',
        'Liu 2026 (burn)':'liu_2026_burn_teas_covidence_48_full_data_extraction.md',
        'Liu 2026 (ESD)':'liu_2026_covidence_69_full_data_extraction.md',
    }
    records={}
    for study in studies:
        name=study['key'];norm=re.sub(r'^#\d+\s*-\s*','',name).lower().replace('-','_').replace(' ','_')
        files=[sources/aliases[name]] if name in aliases else list(sources.glob(norm+'_*.md'))
        if len(files)>1:raise ValueError(f'Ambiguous source for {name}: {files}')
        if files:
            path=files[0];lines=path.read_text().splitlines();selected=None
            for label in ('surgery','surgical procedures','procedures','surgical population','population','surgeries','surgical procedure','procedure'):
                for i,line in enumerate(lines[:150],1):
                    cells=[c.strip() for c in line.split('|')]
                    if len(cells)>3 and cells[1].lower()==label:
                        selected=(i,line,cells[2]);break
                if selected:break
            if not selected:raise ValueError(f'Missing surgical population: {path}')
            line,excerpt,procedure=selected
            procedure=procedure.replace('**','').replace('*','')
            source=str(path.relative_to(ROOT))
        elif name.startswith('Chen 2015'):
            file='040_chen_2015_hyperalgesia_lund.txt' if 'Hyperalgesia' in name else '037_chen_2015_thyroidectomy_lund.txt'
            path=ROOT/'TEAS EA Verification/astra_audit/source_text'/file
            line,excerpt=next((i,t) for i,t in enumerate(path.read_text().splitlines(),1) if 'undergoing thyroidectomy' in t)
            source=str(path.relative_to(ROOT));procedure='Elective thyroidectomy'
        else:
            # Seven post-lock additions already have explicit source-direct
            # descriptions in the preserved browser record. Retain their caveats.
            assert name in {'Szmit 2021','Gao 2022','Song 2020','Wu 2016','Liu 2015','Oztas 2019','Zhang 2018'},name
            source='dashboard/data.js';line=None;excerpt=procedure=study['surgery_procedure']
        text=procedure.lower()
        categories=[]
        patterns={
            'Thoracic & Cardiac':r'thorac|lung|pulmonary|cardiac|esophagectomy|vats',
            'Gynecologic & Breast':r'hysterectomy|myomectomy|gynec|gynaec|breast|mastectomy|ovarian|cesarean',
            'Abdominal & Gastrointestinal':r'gastrectomy|gastric|gastrointestinal|colorectal|colon|colonic|rectal|cholecystectomy|hepatectomy|abdominal|hernia|esophageal.*dissection',
            'Orthopedic & Spine':r'spinal|spine|lumbar|knee|tka|hip fracture',
            'Neurosurgery':r'craniotomy|supratentorial',
            'Head, Neck & ENT':r'thyroid|parathyroid|tympanoplasty',
            'Urologic':r'prostate|nephrectomy|kidney donor',
            'Burn & Reconstructive':r'burn injury|wound debridement',
        }
        if 'non-gastrointestinal' in text: category='Mixed or unspecified surgery'
        elif name=='Wu 2016': category='Not documented';procedure='Surgical procedure not documented in the available characteristics record.'
        else:
            categories=[c for c,p in patterns.items() if re.search(p,text)]
            # "Abdominal hysterectomy" is gynecologic, not a mixed cohort.
            if 'Gynecologic & Breast' in categories and 'Abdominal & Gastrointestinal' in categories and not re.search(r'cholecystectomy|gastrectomy|colorectal',text):categories.remove('Abdominal & Gastrointestinal')
            category=categories[0] if len(categories)==1 else 'Mixed specialties' if len(categories)>1 else 'Other General Surgery'
        records[name]=dict(surgery_category=category,surgery_procedure=procedure,source_file=source,source_line=line,source_excerpt=excerpt)
    return records

if __name__=='__main__':
    records=build()
    (ROOT/'dashboard/study_characteristics.js').write_text('// Generated by scripts/build_study_characteristics.py. Display groupings only.\nwindow.STUDY_CHARACTERISTICS = '+json.dumps(records,ensure_ascii=False,indent=2)+';\n')
    print(f'Surgical characteristics: {len(records)} studies, {len({r["surgery_category"] for r in records.values()})} categories')
