#!/usr/bin/env python3
"""Generate browser reference data from preserved search and outreach sources."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def search_data():
    base = ROOT / '01_search_strategy'
    specs = [
        ('pubmed', 'PubMed', 'NCBI PubMed', '2026-07-21',
         'pubmed/pubmed_v0_2_multiline.txt', 'pubmed/pubmed_v0_2_explanation.md',
         r'Combined unique PubMed records: ([\d,]+)',
         'Cochrane sensitivity-maximizing RCT component; animal-only exclusion.',
         'v0.2 export; not labelled a formal search'),
        ('cochrane', 'CENTRAL', 'Cochrane Library Search Manager', '2026-07-21',
         'cochrane/2026-07-21/CENTRAL_search_strategy_2026-07-21.txt',
         'cochrane/2026-07-21/CENTRAL_search_log_2026-07-21.md',
         r'Exported: all ([\d,]+) CENTRAL',
         'CENTRAL Trials only; no additional trial, language, date or outcome filter.',
         'Strategy entered 2026-07-21; CENTRAL export completed 2026-07-22'),
        ('embase', 'Embase', 'Embase.com (Elsevier)', '2026-07-22',
         'embase/2026-07-22/EMBASE_search_strategy_2026-07-22.txt',
         'embase/2026-07-22/EMBASE_search_log_2026-07-22.md',
         r'Final result count: ([\d,]+)',
         'Randomized-trial component; see verbatim strategy for all exclusions.',
         'Revised executed search'),
        ('cinahl', 'CINAHL Ultimate', 'EBSCOhost', '2026-07-23',
         'cinahl/2026-07-23/CINAHL_search_strategy_2026-07-23.txt',
         'cinahl/2026-07-23/CINAHL_search_log_2026-07-23.md',
         r'F3 platform count: ([\d,]+)',
         'RCT component and animal-only exclusion; no interface limiters.',
         'CINAHL Ultimate substituted for Complete with user authorization'),
    ]
    result = []
    for ident, name, platform, date, strategy, log, pattern, filters, status in specs:
        count = re.search(pattern, (base / log).read_text())
        if not count:
            raise ValueError(f'Missing source count: {log}')
        result.append(dict(id=ident, name=name, database=name, platform=platform,
                           date=date, hits=int(count[1].replace(',', '')),
                           filters=filters, status=status,
                           source=str((base / strategy).relative_to(ROOT)),
                           count_source=str((base / log).relative_to(ROOT)),
                           strategy_text=(base / strategy).read_bytes().decode('utf-8')))
    return result


def main():
    data = (ROOT / 'dashboard/data.js').read_text().split('window.STUDIES_DATA = ', 1)[1]
    studies = json.JSONDecoder().raw_decode(data)[0]
    available = sorted({key for study in studies for key, value in study.get('outcomes', {}).items()
                        if isinstance(value, dict) and any(isinstance(value.get(k), (int, float))
                                                          for k in ('mean_diff', 'rr'))})
    payloads = {
        'author_inquiries': ('AUTHOR_INQUIRIES', json.loads((ROOT / 'dashboard/author_inquiries.json').read_text())),
        'search_strategies': ('SEARCH_STRATEGIES', search_data()),
        'meta_outcomes': ('META_OUTCOMES', available),
    }
    for filename, (variable, payload) in payloads.items():
        (ROOT / f'dashboard/{filename}.js').write_text(
            '// Generated by scripts/build_reference_data.py; do not edit.\n'
            f'window.{variable} = ' + json.dumps(payload, ensure_ascii=False, indent=2) + ';\n')
        print(f'{filename}: {len(payload)} records')


if __name__ == '__main__':
    main()
