// Regression checks for the interpretation layer -- the manuscript /
// peer-review overlay generated by
// 09_V34_ANALYSIS/05_INTERPRETATION/build_interpretation_layer.py.
//
// Scope, and the reason each check exists:
//
//   * The overlay must be OPT-IN and must never be mistaken for evidence, so
//     the default view is Evidence and every panel carries a draft label.
//   * Turning the lens on, and opening every panel, must leave every evidence
//     number on the page byte-identical. This is asserted by snapshotting the
//     rendered evidence values before and after, not by reading the source:
//     the separation is only worth anything if it survives the actual
//     rendering path.
//   * Reviewer questions must show the data condition that triggered them.
//     A panel that asserts criticism without showing why trains the team to
//     ignore it, and the brief rules out inventing criticism to fill the UI.
//   * A stale record must be shown behind a warning rather than presented as
//     current, because manuscript language describing a superseded result is
//     the specific failure the whole layer is built to prevent.
//
// These are presentation and provenance assertions. They never assert a
// scientific value, only that interpretation and evidence stay distinguishable
// and that the interpretation cannot move a number.
//
// Run: node scripts/check_interpretation_ui.cjs
const {chromium} = require('playwright');
const assert = require('assert');
const path = require('path');

const PORT = process.env.PORT;
const SITE = PORT ? `http://localhost:${PORT}/index.html`
                  : 'file://' + path.resolve(__dirname, '..', '_site', 'index.html');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
  const errors = [];
  page.on('pageerror', e => errors.push(String(e)));
  await page.goto(SITE);
  await page.waitForFunction(() => typeof window.switchTab === 'function');
  // Start from a known lens state; the toggle persists in localStorage.
  await page.evaluate(() => { try { localStorage.removeItem('teas-manuscript-lens'); } catch (e) {} });
  await page.reload();
  await page.waitForFunction(() => typeof window.switchTab === 'function');
  await page.evaluate(() => switchTab('primary'));
  await page.waitForTimeout(700);
  let checks = 0;

  // ── 1. the payload is present and declares itself non-evidence ──────────
  const L = await page.evaluate(() => window.INTERPRETATION_LAYER || null);
  assert.ok(L, 'the interpretation layer payload did not load');
  assert.strictEqual(L.is_evidence, false, 'payload does not declare is_evidence: false');
  assert.strictEqual(L.layer, 'INTERPRETATION', `payload layer is ${L.layer}`);
  assert.ok(L.records.length >= 10, `expected interpretation records, saw ${L.records.length}`);
  checks += 4;

  // ── 2. default view is Evidence; the overlay is opt-in ─────────────────
  const defaultState = await page.evaluate(() => ({
    pressed: document.getElementById('il-lens-btn').getAttribute('aria-pressed'),
    openPanels: [...document.querySelectorAll('.il-detail-row')].filter(r => !r.hidden).length,
  }));
  assert.strictEqual(defaultState.pressed, 'false', 'Manuscript Lens must default to off');
  assert.strictEqual(defaultState.openPanels, 0,
    'no interpretation panel should be open in the default Evidence view');
  checks += 2;

  // ── 3. THE SEPARATION: the overlay cannot move an evidence number ───────
  // Snapshot every rendered evidence value in the model table, plus the
  // evidence payloads themselves, then turn the lens on, open every panel,
  // and demand the snapshot is unchanged.
  const snapshot = () => page.evaluate(() => ({
    table: [...document.querySelectorAll('#v34-models tbody tr[data-analysis-id]')].map(tr => {
      const td = [...tr.children].map(c => c.innerText.trim());
      return {id: tr.dataset.analysisId, k: td[1], est: td[2], p: td[3], i2: td[4],
              estimator: td[5], certainty: td[6]};
    }),
    v34: JSON.stringify(window.V34_DATA.models),
    grades: JSON.stringify(window.V34_DATA.grade_new_models.ratings),
    rob2: JSON.stringify(window.V34_DATA.rob2_results.results),
    stata: JSON.stringify(window.STATA_MASTER_RESULTS),
    tiered: JSON.stringify(window.TIERED_V33.analysis_sets),
  }));

  const before = await snapshot();
  await page.evaluate(() => document.getElementById('il-lens-btn').click());
  await page.waitForTimeout(500);
  await page.evaluate(() => {
    document.querySelectorAll('.il-discuss-btn').forEach(b => b.click());
  });
  await page.waitForTimeout(400);
  const after = await snapshot();

  assert.deepStrictEqual(after.table, before.table,
    'an evidence value in the model table changed when the interpretation overlay was used');
  for (const key of ['v34', 'grades', 'rob2', 'stata', 'tiered']) {
    assert.strictEqual(after[key], before[key],
      `the interpretation overlay mutated the ${key} evidence structure`);
  }
  checks += 6;

  // ── 4. lens on actually reveals the overlay ────────────────────────────
  const lensOn = await page.evaluate(() => ({
    pressed: document.getElementById('il-lens-btn').getAttribute('aria-pressed'),
    panels: document.querySelectorAll('.il-detail-row').length,
  }));
  assert.strictEqual(lensOn.pressed, 'true', 'lens toggle did not turn on');
  assert.ok(lensOn.panels >= 10, `expected an interpretation panel per record, saw ${lensOn.panels}`);
  checks += 2;

  // ── 5. every panel separates Results-safe / Discussion-safe, and is
  //       labelled as a draft rather than as a finding ─────────────────────
  const panelAudit = await page.evaluate(() => {
    const out = [];
    for (const row of document.querySelectorAll('.il-detail-row')) {
      const t = row.innerText;
      out.push({
        id: row.id,
        resultsSafe: /Results-safe/.test(t),
        discussionSafe: /Discussion-safe/.test(t),
        claims: /Claim boundaries/.test(t),
        reviewer: /Reviewer lens/.test(t),
        draftLabel: /Draft interpretation — for team discussion/.test(t),
        fingerprint: /[0-9a-f]{16}/.test(t),
      });
    }
    return out;
  });
  assert.ok(panelAudit.length, 'no interpretation panels rendered');
  for (const p of panelAudit) {
    assert.ok(p.resultsSafe, `${p.id}: no Results-safe statement`);
    assert.ok(p.discussionSafe, `${p.id}: no Discussion-safe statement`);
    assert.ok(p.claims, `${p.id}: no claim boundaries`);
    assert.ok(p.reviewer, `${p.id}: no reviewer lens`);
    assert.ok(p.draftLabel, `${p.id}: panel is not labelled a draft interpretation`);
    assert.ok(p.fingerprint, `${p.id}: panel does not show its evidence fingerprint`);
  }
  checks += panelAudit.length;

  // ── 6. reviewer questions show the condition that fired them ───────────
  const qAudit = await page.evaluate(() =>
    (window.INTERPRETATION_LAYER.records || []).flatMap(r =>
      (r.reviewer_questions || []).map(q => ({
        id: r.analysis_id, q: q.question,
        hasTrigger: !!(q.trigger || '').trim(),
        hasPathway: !!(q.pathway || '').trim(),
      }))));
  assert.ok(qAudit.length, 'no reviewer questions were generated at all');
  for (const q of qAudit) {
    assert.ok(q.hasTrigger, `${q.id}: reviewer question with no data trigger: ${q.q}`);
    assert.ok(q.hasPathway, `${q.id}: reviewer question with no evidence pathway: ${q.q}`);
  }
  const triggerShown = await page.evaluate(() =>
    [...document.querySelectorAll('.il-detail-row')]
      .some(r => /fires because —/.test(r.innerText) && /evidence available —/.test(r.innerText)));
  assert.ok(triggerShown, 'the rendered reviewer lens hides the trigger / evidence pathway');
  checks += qAudit.length + 1;

  // ── 7. claim boundaries use the three-level vocabulary ─────────────────
  const claimLevels = await page.evaluate(() =>
    [...new Set((window.INTERPRETATION_LAYER.records || [])
      .flatMap(r => (r.claims || []).map(c => c.level)))].sort());
  for (const lvl of claimLevels) {
    assert.ok(['supported', 'qualified', 'unsupported'].includes(lvl),
      `unexpected claim level ${lvl}`);
  }
  assert.ok(claimLevels.includes('supported'), 'no supported claims generated');
  checks += 2;

  // ── 8. stale records are shown behind a warning, never as current ───────
  const staleAudit = await page.evaluate(() => {
    const recs = window.INTERPRETATION_LAYER.records || [];
    const stale = recs.filter(r => r.stale);
    return {
      count: stale.length,
      allWarned: stale.every(r => {
        const row = document.getElementById(`il-row-${r.analysis_id}`);
        return row && /Interpretation may be outdated/.test(row.innerText);
      }),
      bannerCount: document.querySelectorAll('.il-detail-row').length
        && [...document.querySelectorAll('.il-detail-row')]
             .filter(r => /Interpretation may be outdated/.test(r.innerText)).length,
    };
  });
  assert.strictEqual(staleAudit.bannerCount, staleAudit.count,
    `${staleAudit.bannerCount} stale warnings rendered for ${staleAudit.count} stale records`);
  if (staleAudit.count) {
    assert.ok(staleAudit.allWarned, 'a stale interpretation is presented without its warning');
  }
  checks += 1;

  // ── 9. the Manuscript Evidence Map renders one row per record ──────────
  const map = await page.evaluate(() => {
    document.querySelectorAll('#tab-primary details').forEach(d => { d.open = true; });
    const rows = document.querySelectorAll('#il-evidence-map tbody tr');
    return {
      rows: rows.length,
      subtitle: (document.getElementById('il-map-subtitle') || {}).textContent || '',
      disclaimer: (document.getElementById('il-evidence-map') || {}).innerText || '',
    };
  });
  assert.strictEqual(map.rows, L.records.length,
    `evidence map has ${map.rows} rows for ${L.records.length} records`);
  assert.ok(/not manuscript text/i.test(map.subtitle),
    'the evidence map does not disclose that it is not manuscript text');
  assert.ok(/Nothing in this table can change an extracted value/i.test(map.disclaimer),
    'the evidence map drops its "cannot change evidence" statement');
  checks += 3;

  assert.deepStrictEqual(errors, [], 'page errors: ' + errors.join(' | '));
  await browser.close();
  console.log(`PASS: ${checks} interpretation-layer checks — overlay is opt-in and declares ` +
    `itself non-evidence; using it left every evidence value and payload byte-identical; ` +
    `${panelAudit.length} panels separate Results-safe from Discussion-safe and are labelled ` +
    `drafts; ${qAudit.length} reviewer questions each show the data condition that fired them; ` +
    `${staleAudit.count} stale record(s) shown behind a warning; evidence map complete.`);
})().catch(e => { console.error('FAIL:', e.message); process.exit(1); });
